### ISSUE TITLE
Programs: Main programs screen

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1]
# Integrate programs UI into omSupply

Options to integrate:
- Create a new entry root for the omSupply programs, e.g. http://localhost/programs
- Use main login screen and link to programs/patients page, e.g. icon in the left bar?
- ~~Create an independent app? (programs should support dispensing in the future though)~~

## Customizable entry screen
Customization isn't a  priority but something we show in the mock ups. 

- [ ] [where to store customization data such as images, etc...?](https://github.com/openmsupply/remote-server/issues/1094)
![Image](https://user-images.githubusercontent.com/88299195/166851849-6c9ad259-043c-4484-97b0-7ee63a0f8c92.png)

## Patient list

![Image](https://user-images.githubusercontent.com/88299195/166852097-dbf01533-79e3-44b4-b286-17e3d49c467c.png)

## Register new patient
In the first prototype only the generate tab is important:

![Image](https://user-images.githubusercontent.com/88299195/166852313-588054f4-2617-4ad7-942d-6fba5abe1e9a.png)

**Comment by Chris-Petty** [comment]
I love that it's easy to change the colour theme for clients 😍

**Comment by clemens-msupply** [comment]
Already implemented
