### ISSUE TITLE
In electron discovery use ipv4 addresses

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1001]
Epic: https://github.com/openmsupply/open-msupply/issues/996

Comment: https://github.com/openmsupply/open-msupply/pull/802#discussion_r1024626286

 In electron app use ipv4 address, see TODO in electorn.ts

**Comment by mark-prins** [comment]
currently line 155 has `const ip = addresses[0];`
With the comment? before it:

`// TODO filter out ipv6 addresses and just get one ipv4 (it's usually the first one)`
I think we just need to filter the address array. These are plain strings, so we'll need to parse e.g.

```addresses: ["192.168.178.68","fe80::14fd:9446:1ec2:12ea","2406:e002:58c5:b01:c54:ca30:328c:ef16"]```
