### ISSUE TITLE
UI Improvements for Discovery

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1002]
Epic: https://github.com/openmsupply/open-msupply/issues/996

UI improvements:

* If discovered site is not initialised we just show `Initialise`, this could be better phrased
* The back link (back to discovery) was just hacked in the UI, further thought 

## Further thoughts ##

Ideally, when Android app starts for the first time, we should be able to pick from Server/Client. If `server` is picked, server is discoverable and we connect straight to localhost, if `client` is picked, server is not discoverable and we go to discovery. Still should be able to navigate back to `discovery` from login/initialise screen if `client` was picked. And maybe in Admin windows can change from client to server ¯\_(ツ)_/¯

I think if we we have lots of Android client/server on the same network, it would be hard to find the correct one (don't even think the list in discovery is scrollable)

**Comment by mark-prins** [comment]
We can also improve on the server display - the sync site name is probably more useful/readable/friendly for normal users than the IP and it would look better if we tidied that up e.g.

<img width="355" alt="Screenshot 2023-01-11 at 9 09 46 AM" src="https://user-images.githubusercontent.com/9192912/211651879-56228672-3cc8-4907-80b6-e55f80c4e80f.png">

or 

<img width="349" alt="Screenshot 2023-01-11 at 9 07 39 AM" src="https://user-images.githubusercontent.com/9192912/211651874-47032927-f759-4403-b7bb-c6f5fe7f6ade.png">
