### ISSUE TITLE
omsupply Server service is not starting after installation with Postgres

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1004]
## Issue Description
In Windows Server 2019 or latest, we've tried installing omsupply Server with Postgres, but the service does not start properly.
@raviSussol says this is because of the missing `libpq.dll` files during omsupply server installation.
**Note: Upgrading from v1.03 to the latest 1.05 does seem to work though!** 

## Steps
1. Get the latest omsupply server exe and install it.
2. Opt to check/tick the `Install Postgres` option and proceed.
3. Let the installation finish and launch omsupply server.
4. See error: the service won't start
![Screen Shot 2023-01-10 at 12 39 40](https://user-images.githubusercontent.com/59193490/211482109-9446007c-58b5-4ab8-a05c-34eed28a386c.png)
5. You can also try manually opening the exe. You'll see the alert:
![Screen Shot 2023-01-10 at 11 56 08](https://user-images.githubusercontent.com/59193490/211482421-93424653-4c64-46bc-96b0-5d05d888979b.png)

**Comment by nisha-dangol** [comment]
Tested in the latest v1.1.1 exe built by @raviSussol 

Opting to install the exe with Postgres now works fine and the service starts properly.

**Comment by nisha-dangol** [comment]
Another problem with openmsupply service in the latest v1.1.1-test3 exe built by @raviSussol
![Screen Shot 2023-01-17 at 17 19 58](https://user-images.githubusercontent.com/59193490/212891118-1c1f0a53-ea2b-4666-a823-03c471a3e7fe.png)

**Comment by raviSussol** [comment]
@nisha-dangol I tested on the windows machine that you'd found not working (i.e. win2019 server). It is working fine. I think you seemed to entered postgres password wrong while setting up the omsupply server in the installation wizard.
