### ISSUE TITLE
Compile error due to Autocomplete types

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#104]
If you do a full compile (without the "since HEAD") on `main` you get this error:

```
@openmsupply-client/inventory: ../common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx(110,7): error TS2322: Type 'boolean' is not assignable to type 'undefined'.
```

In Autocomplete.tsx:
![Screen Shot 2022-06-08 at 3 52 29 PM](https://user-images.githubusercontent.com/5456533/172527924-3901b6c3-186e-43bf-9751-59f2653da651.png)

Seems like an issue with Material-UI, but odd that it hasn't come up before.

**Comment by CarlosNZ** [comment]
This seems to have gone away since merging the f/e dependency updates #56 

👍

**Comment by CarlosNZ** [comment]
Aaaand, it's back (in feature branch)!

**Comment by andreievg** [comment]
@CarlosNZ do you think it's still an issue ?

**Comment by mark-prins** [comment]
not getting it in the feature branch now..
`lerna run --scope @openmsupply-client/* --parallel tsc`

**Comment by CarlosNZ** [comment]
Seems like it's sorted. For now...
