### ISSUE TITLE
Adding items stuck on `loading`

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1040]
Outbound shipment, add item, stuck on loading for Mobile. 
When running front end with `yarn start-local` get an error like this:
![Screenshot 2023-01-18 at 12 08 53 PM](https://user-images.githubusercontent.com/26194949/213032648-adb45a1c-d089-4a22-96d7-30db652f7a4a.png)

When running freshly built front end served from remote server also getting the loading.

There are two issue:
1 - Pagination for item on fe is set to 5000, but on backend is 1000
2 - Built app served from server doesn't show the error in toast (although other toasts are working, and the other toast are working in mobile or remote server served front end, can't see anything special in browser console, graphql response is erroneous but surprised to see what looks like polling request)

**Comment by mark-prins** [comment]
@roxy-dao has fixed the b/e limit for items in #1032
