### ISSUE TITLE
Add item performance

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1043]
Seen this while testing tl.

It was taking 1 - 3 second to get item list (for add items in outbound/inbound shipment). Running on samsung tablet with 3555 items and quite a fresh data file. 

Potential causes:
* Whole items stats, including AMC is being returned
* Too many fields being serialised

Possible fixes:
* Query for just the fields needed
* Only query for stock_on_hand (and make sure server only queries for stock on hand)
* Paginated virtualised list

Priority:

Most likely immediate since this is quite slow for a common operation on a clean data file. Would be very slow if data file is medium size, so very probable with high impact.

**Comment by CarlosNZ** [comment]
Shall we split this out into two issues. As far as I can tell, the solutions would be:

**Back-end**:
- Don't generate/return "Whole items stats, including AMC" or other fields we don't need for this

**Front-end**:
- Don't fetch the whole list, only the first 15-20 items, and then do search-as-you-type after that

Sound about right?

**Comment by andreievg** [comment]
@CarlosNZ yep sounds good, although I think for f/e changes it would be good to get UX help from Anisha (what is the ideal way to do this on mobile/desktop, also it sounds like mobile is more of a focus now). The reason for the UX `help` is mainly because if we do 15-20 items, scrolling through the list to find the item won't be possible, there are options of course  to make it work but would be great for Anisha to come up with something.

**Comment by CarlosNZ** [comment]
> @CarlosNZ @andreievg can we close this issue then? Is there any need to have 3 issues open?

Sounds good.
