### ISSUE TITLE
Prepare feature/programs branch for merging to develop

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1048]
Placeholder issue. Please make a list of the things that need to happen in order to facilitate this.

- [x] Store-based or system-wide preference to enable/disable Programs (can someone provide more detail of how this should work?)
- [x] Front-end to check this pref and render accordingly
- [x] Central sync (at least so far that it becomes easy to create/reset a test environment)
- [x] Remove initial data
- [ ] Go through program DB schemas and review them (to avoid later migrations)
  - [x]  Documents: rename owner -> owner_name_id?

**Comment by mark-prins** [comment]
I think that these are all completed. @clemens-msupply @CarlosNZ - any thoughts? Should we close and move on with the merge?

**Comment by clemens-msupply** [comment]
There might still be schema changes but since the patient program module is not used it should be trivial to write a migration...

**Comment by mark-prins** [comment]
We have #658 open as well, so I'll close this as we don't know what the schema changes might be yet. It's speculative to keep this issue open and delay the merge
