### ISSUE TITLE
Discussion: the Add item window for outbound shipments is causing some confusion

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1052]
Pauline and Damon found this very confusing during testing, as did Emily when she saw it later. 

I think a lot of the confusion comes from the fact that there's a mix of units used (units, and number of packs). I know this is a small UI issue, but if there is too much confusion it does add a lot of extra difficulty. 

<img width="903" alt="image" src="https://user-images.githubusercontent.com/29744386/213357349-82fc839f-fc71-4478-9be0-67e55ec2b333.png">

Would appreciate any thoughts on this!

**Comment by mark-prins** [comment]
@DhanyaHerath are you able to explain the confusion any further? I'm unsure what to change
Would the changes in #797 help do you think?

**Comment by DhanyaHerath** [comment]
Yes, was meaning to come back to this thanks! 
#797 would definitely help, and came up when Emily looked at this too. 

The main confusion was that they weren't sure whether the columns referred to packs or units, particularly the Available and In Store ones. 

One suggestion was shuffling the columns around so that the item details were all grouped together and anything that was with the `packs` unit were together. In addition, adding the units in brackets would be helpful! 


<img width="878" alt="image" src="https://user-images.githubusercontent.com/29744386/214202704-50d040e6-70c4-4169-885f-6e4273137c06.png">

**Comment by andreievg** [comment]
* Ask stakeholder if `pack of [ ] unit` needs to stay
* Something for columns to 
   * Clearly state if things are in packs of total quantity
   * Identify what is being issued and what is or will be in stock

**Comment by DhanyaHerath** [comment]
@craigdrown @richardmoizeau I think you two were the original designers for this - did we have a request for the dropdown list that swaps between `Any` and the specific units? It's causing a bit of confusion when in use, so wanted to check what the use case for it is. 

<img width="491" alt="image" src="https://user-images.githubusercontent.com/29744386/216183817-7bfabe32-7048-4d07-93e3-0030c2634eba.png">

**Comment by craigdrown** [comment]
@DhanyaHerath Richard and I are not sure we want to claim the "credit" of being the original designers ;-)
We think the use case is - say the pack size is 68 and the order quantity is 53 packs, we want the user to be able to choose the "68" pack size and type in "53" into the _issue_ field rather than getting their calculator out?

"Any" will do by FEFO > good. (The "coffee grinder magic button" ;-)  )

If there are a lot of batches present with various pack sizes, but you want to issue a specific pack size, again the ability to choose it from the DDL is nice.

If there is only 1 pack size present, that's the only choice in the DDL - "any" isn't an option. I suspect this is the most common scenario and not confusing....?

**Comment by DhanyaHerath** [comment]
@craigdrown Ok, thanks! I understood the use case - I suppose my real question was whether any customers have requested this?

**Comment by andreievg** [comment]
@mark-prins @DhanyaHerath @craigdrown @richardmoizeau I think we should have a meeting about this, I feel like this conversation has been conducted in smaller groups, and now there are questions from testers about how this should work and what should be tested, and we don't really know the answer.

Anyways my suggestion is we meet about this and discuss what the logic should be for different use cases/scenarios and consider this functionality as a whole (editing issue, editing #packs on each line, editing placeholder value, auto distribution etc..)

@craigdrown 
>  say the pack size is 68 and the order quantity is 53 packs, we want the user to be able to choose the "68" pack size and type in "53" into the issue field rather than getting their calculator out?

Probably best to answer in meeting, but wouldn't they just type 53 under `# Packs` on the line with 68 pack size ? not sure about calculator, do you mean if there are multiple batches with 68 packs size ? Also for this use case, the order is already picked ? Or was there a request from customer to send 53 packs of 68 packs size or did the customer actually say I want 3604 and warehouse realised best space efficiency for transportation is pack size of 68 ? (I definitely think it's best answered in person, I have a few other questions like this for the meeting)

@DhanyaHerath 
> I suppose my real question was whether any customers have requested this?

Ditto !

**Comment by richardmoizeau** [comment]
> One suggestion was shuffling the columns around so that the item details were all grouped together and anything that was with the `packs` unit were together. In addition, adding the units in brackets would be helpful!
> 
> <img alt="image" width="878" src="https://user-images.githubusercontent.com/29744386/214202704-50d040e6-70c4-4169-885f-6e4273137c06.png">

Not sure if we want to treat this as a separate issue. 

I'm a big supporter of a "reshuffle" of the columns especially with the idea of starting with the batch name and exp date. I remember that I mentioned to a developer (

![Screen Shot 2023-02-02 at 3 15 27 PM](https://user-images.githubusercontent.com/74992958/216214657-14e4ef47-b2bf-4c07-9580-98843697c992.png)

- batch number and batch attributes (exp date, location, pack size, pack sell price, on hold) are together
- Pack Size: (credit to @craigdrown), display the unit name next to to the pack size value ?
- Sell: change name to make it clear we are talking about the price of one pack ? Clearly show the currency with the three letters code ($ could refer to AUD, NZD, USD, etc...)
- having available (packs) next to "pack qty issued" is helpful (I know what available so I won't enter a value higher than what's available)
- Pack Qty Issued: don't know if it's a francophone thing, but # is usually used to express a quantity but rather a numbering ? 
- Unit Qty Issued: also display the unit name next to the quantity of units value.

**Comment by richardmoizeau** [comment]
> @craigdrown Ok, thanks! I understood the use case - I suppose my real question was whether any customers have requested this?

I think there was also a wish to combine what is done in mSupply Mobile with mSupply Desktop. In mSupply Mobile, you don't deal with pack size or even batch when adding an item to a customer invoice. You select an item, enter the quantity and the system will do the allocation itself. 

The `Any` option was an attempt to replicate what exists in Mobile, for users only dealing with quantity of units. 

So not a customer specifically, but on behalf of all our mobile customers ;-)

That being said, I agree we should have a meeting @andreievg.

**Comment by andreievg** [comment]
I was trying to figure out a bug in the issue for current sprint: https://github.com/openmsupply/open-msupply/issues/1119, and I got confused again and have these questions based on attached screencast (with times for the behaviour):

* (00:06) Placeholder, should this be updated when issue is set  ? (our existing requisition mechanism creates placeholder lines in outbound shipment, shouldn't that be somewhat `static`, only update when deliberately set)
* (00:17) What should be in drop down packs list ? I can select 1 or 30, but 1 is unavailable and there is also 15 and 10 available (they are expired but can be issue when Any is selected 00:30), also 1 disappears from the list (00:24)
* (00:25) Is it ok to `loose` issue quantity when packs don't add up to issue (lost the 70 that was entered)
* (00:35) Is it ok to reset previous issue allocation when packs are selected ?
* Is it ok to `loose` original placeholder/issue quantity before OK is pressed ?

https://user-images.githubusercontent.com/26194949/217391034-d6d7da3d-eb87-46f4-80d7-975ec2857a43.mov

**Comment by mark-prins** [comment]
> (00:06) Placeholder, should this be updated when issue is set ? (our existing requisition mechanism creates placeholder lines in outbound shipment, shouldn't that be somewhat static, only update when deliberately set)

Yes, it should be updated. The quantity in placeholder is the remainder when the amount issued is greater than the amount available

> (00:17) What should be in drop down packs list ? I can select 1 or 30, but 1 has not available stock and there is also 15 and 10 available (they are expired but can be issue when Any is selected 00:30), also 1 disappears from the list (00:24)

Only 30 should be in the list, as none of the batches for the other pack sizes have available quantity

> (00:25) Is it ok to lose issue quantity when packs don't add up to issue (lost the 70 that was entered)
> (00:35) Is it ok to reset previous issue allocation when packs are selected ?

Both are the same question aren't they? The issue quantity is updated when changing pack sizes, so that the user doesn't accidentally issue x packs when they intended x units. An alert dialog would be annoying to me, perhaps a snackbar / toast? or inline text alert? ( you had 70 units requested, changed to packs of 30. Rather than allowing you to have 70 packs of 30, the issue quantity is changed to 2, so that you have 60 units. If you had 3 packs of 30 available it would allocate 3 rather than 2. I think it should also add a placeholder of 10 units, so there's a bug there )

> Is it ok to lose original placeholder/issue quantity before OK is pressed ?

Is this the same question as the previous two? Or something else?

**Comment by mark-prins** [comment]
Other comments to be discussed:

- There is no warning when, due to pack sizes, the number of units supplied is more than requested
- Issue' and 'units' columns are unclear - it changes from 'packs of units' to 'units in packs' with no warning or reason why
- the 'available' column is not clear whether it is units or packs, and makes the quantity hard to calculate - for example, in the available column there may be 200 - but we do not know if it is packs or units

**Comment by andreievg** [comment]
I think this conversation should really be in person, i am probably not asking question with enough detail, like:

> Yes, it should be updated. The quantity in placeholder is the remainder when the amount issued is greater than the amount available

What is `amount available` in this case ? There is lots of stock available, but placeholder is being updated.

> Only 30 should be in the list, as none of the batches for the other pack sizes have available quantity

`none of the batches for the other pack sizes have available quantity` -> but they do (expired), In the same question I had `they are expired but can be issue when Any is selected 00:30` I couldn't understand logic for that. (Thinking through a use case where warehouse wants to issue a specific pack size, would mean it's quite likely they already selected that pack size and the box, so they already determined that they will issue regardless of expiry)

> Is this the same question as the previous two? Or something else?

I think you can see placeholder and issue at the start and end of the video

**Comment by andreievg** [comment]
Also I've just noticed something, sometimes `any` is default sometime it's something else (like the video), what should the logic be for `default` one ?

**Comment by DhanyaHerath** [comment]
### Meeting Notes

Attending: Anisha, Craig, Andrei, Mark, Dhanya

**Comment by anisha-msupply** [comment]
@mark-prins I forgot to mention yesterday - it would be good to have a small info icon (if there's enough space) next to certain column headers within this window, so users know which items they can hover over for additional details 

eg: 
![image](https://user-images.githubusercontent.com/117775597/217971744-2c08900a-99f2-41e4-b42d-426e8be41d5e.png)

**Comment by mark-prins** [comment]
to check: entering `0` in the placeholder zeroes out all inputs.
