### ISSUE TITLE
New program: Early Infant HIV Detection

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1058]
To save work for the data import, first:
-  [x] #1990

Use this information to create the following program

General: 
- [ ] Code: EID 
- [ ] Name: Early Infant HIV Detection

###  Enrolment Details:
- [ ] `Enrolment date`: date of enrolment (can be a date in the past!). Date picker. 
- [ ] ` Referred from: `: free text field (checking with PNG if this should be a dropdown)
###  Delivery Details:
- [ ] `Place of Delivery`: drop-down (Home; Facility)
- [ ] `Facility Name`: if `Place of Delivery` = `Facility`, then name of facility must be entered. Free text (checking with PNG if this should be a dropdown)
###  Family Details:
- [ ]  `Mother's HIV Program ID`: should be selected amongst existing HIV Care and Treatment program's patients
- [ ]  `Mother's Name`: Full name of the patient's mother (populated through the Mother Program ID ?)
- [ ] `Address`: Address of the mother (populated through the Mother Program ID ?)
- [ ] ` Phone Number`: phone number of the mother (populated through the Mother Program ID ?)
- [ ] `Mother's ARV start date`: drop-down (Before pregnancy; Early Ante-natal; Late Ante-natal; Post-Natal; Labour & Delivery; Never got ARVs; Unknown)
- [ ] `Mother's VL prior to delivery`: dropdown (Suppressed; Unsuppressed;  Not Done")
- [ ] `Risk of MTCT`: Mother To Child Transmission,  dropdown (High risk; Low risk)

 ###  Infant's Risk of MTCT:
- [ ] `Child's HIV exposure`: drop-down (Mother Known Positive; Clinical Suspicion)
- [ ] `Risk of MTCT`: dropdown (High risk; Low risk)

 ###  Infant's ARV Prophylaxis: 

- [ ] `ARV Prophylaxis Given`: drop-down (Not given; Given at labour ward; Given elsewhere)
- [ ] `ARV Regimen`: if `ARV Prophylaxis Given` = `Given ...` then specify which ARV. Drop-down (Nevirapine 6 weeks; Zidovuine 6 weeks and Nevirapine 12 weeks; other)
- [ ] `CTX at 6 weeks`: drop-down (Not given; Given)

##  **Encounter Form** 

The EID encounters seem to be following a pre-defined schedule (similar to what a Routine Immunisation Program would be @adamdewey). It seems that there is 5 visits in the schedule based on the infant's age: 

1. First Visit: 6 weeks
2. Follow-up Visit: 6 months
3. Follow-up Visit: 9 months
4. Follow-up visit: 12 months
5. Follow-up visit: 18 months

@clemens-msupply has already created a "Routine Immunisation Program" for demo purpose. And his idea was to create a different encounter form for each visit: 

![Screen Shot 2023-01-20 at 11 42 20 AM](https://user-images.githubusercontent.com/74992958/213578532-0851753c-77fd-4095-b73c-d6dabc278e7d.png)

We took the [NZ Immunisation Schedule](https://www.health.govt.nz/our-work/preventative-health-wellness/immunisation/new-zealand-immunisation-schedule) as a guide and as you can see, you won't have the same vaccines for each encounter so it would make sense to have a different encounter form for each of them. 

The other advantage would be for the system to automatically generate the next appointment based on the baby's age. 

### First Visit: 6 weeks - Early Infant Diagnosis at 6 weeks

- [ ] `DBS collected`:  dropdown (Yes; No) ** All fields below this are only enabled if `Yes` is selected` ** 
- [ ] `DBS number`: free text 
- [ ] `DBS collection date`: date picker, (can be a date in the past!)
- [ ] `DBS result received by patient`:  dropdown (Yes; No) ** All fields below this are only enabled if `Yes` is selected for this` ** 
- [ ] `Date DBS result given to patient`: date picker, can choose dates in the past 
- [ ] `DBS result`: dropdown (Negative; Positive)

### Follow up visits for 6 months, 9 months, and 12 months 
- [ ] `Date of visit`: date picker, (can be a date in the past!)
- [ ] `Baby feeding method`:  dropdown (BF - Exclusive breastfeeding; MF - mixed feeding ((other feeds + breast milk); NBF - other feeds without breast feeding)
- [ ] `Immunisations up to date?`: dropdown (Yes; No) 
- [ ] `Weight`: number field, allows decimals. I am assuming this is in grams 

### Follow up visits for 18 months 
The 18 month follow up has the same fields as the other ones above, PLUS: 
- [ ] `18mo Antibody Test Date`: date picker, (can be a date in the past!)
- [ ] `18mo Antibody Test result`: dropdown (Negative; Positive)

#### Post-Cessation of BF 
- [ ] `Post-BF DBS collected`: dropdown (Yes; No)
- [ ] `Date Post-BF DBS collected`: date picker, (can be a date in the past!)
- [ ] `Post-BF DBS result received by patient`: dropdown (Yes; No)
- [ ] `Date Post-BF DBS result received by patient`: date picker, (can be a date in the past!)
- [ ] `Post-BF DBS result`: dropdown (Negative; Positive)

#### Final Outcome 
- [ ] `Final outcome status`: dropdown (Death; Lost to follow-up; Discharged; on ART)

(nb. It feels like if they chose on ART, it should enrol them into the HIV Care program, but that can be for later)

**Comment by DhanyaHerath** [comment]
@richardmoizeau I have updated the encounters section as I saw them - would be great if you could cast a second eye over it and confirm whether we should go ahead! Thank you :)

**Comment by richardmoizeau** [comment]
Sure I will. Thanks Dhanya

**Comment by clemens-msupply** [comment]
Might make use of https://github.com/openmsupply/open-msupply/issues/2025

**Comment by richardmoizeau** [comment]
from @clemens-msupply (telegram): 

> Early infant detection program: split into multiple encounters? if yes, I think we need to rethink the UI a bit, e.g. how to make information from previous encounter quickly available to the user?

Instead of creating one specific form for each encounter we should have only one form with all sections in it, and user would have to enter data for relevant ones. There would be: 
- 1 section for the first visit
- 1 section for follow up visits (6, 9, 12 and 18 months) - ideally, section would start by a drop-down menu to select whether which follow up visit it is (eg. "6 months"). If "18 months" is selected, add the following properties (dependent field): 

 >18mo Antibody Test Date: date picker, (can be a date in the past!)
> 18mo Antibody Test result: dropdown (Negative; Positive)

- 1 section for the "Post-Cessation of BF & Final Outcome" which is in reality the 24 months encounter. When baby age is 2 years old, they decide whether to enrol the baby in the HIV Care Program or not based on final results. This could be the last section of the encounter form and should include the "Final Outcome Status" field.

**Comment by clemens-msupply** [comment]
Sounds good, but I still think we need a better way to show the progress to the user, e.g. which sections have been entered and what has been entered at previous encounters.

We could display data from a previous section as read only, e.g. display it in the same controls but greyed out and labelled as data from a previous encounter. (If we do that, do we need to have an option to redo the section? e.g. redo a vaccination?)
