### ISSUE TITLE
Revise context2 name

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1059]
From https://github.com/openmsupply/open-msupply/pull/1030
 

Mark: 

<blockquote>
context by itself is fine as a name, but context2 is taking it too far!
what are the context and context2 for? why are there two of them? why is one a ReportContext and one a String

the answers might come later.. but just reading the PR top to bottom I wonder if the column name could be more meaningful
</blockquote>

Clemens:

<blockquote>
Yes it would be good if we could find a better solution or term. Here is the problem maybe you have another idea?

Currently I need to print a patient report for a certain program (e.g. context="Patient" and context2="ABCProgram"). The patient report for a certain program should only be applicable for patient that are enrolled in this program. Currently, the report assumes that the patient is enrolled in the program and if not the report generation fails. However, it shouldn't be possible to print the report in the first place when you are not enrolled.

Additionally, you could have other Program reports, e.g. a store wide program report which shouldn't show up in the list of patient reports...

Further question, what if further nesting needed? e.g. context3?

We could hack something like having a context "Patient_ABCProgram" or "Store_ABCProgram" and the UI needs to know how to build these contexts. But not the nicest solution...
</blockquote>

Mark:

<blockquote>
tricky. So the contexts are hierarchical? and therefore context2 is a sub-context or refinement of the report context? The context2 could be named as a child / refinement / subcontext - or the original ReportContext could be an object with children under it?

Or the contexts are a set which all apply? in which case an array might make sense?
</blockquote>

**Comment by clemens-msupply** [comment]
@mark-prins 
Yes `sub_context` is a better name.

You mean using "old" mSupply context column as a `string | object`?

Another option would be having a `contextData` json column with a type depending on the context type, e.g. 
```json
{
  "context": "ProgramPatient", 
  "contextData": { "program": "ABCProgram" }
}
```

Think both a bit hacky? Maybe unlikely that we will need a `sub_sub_context` ? so tending to just calling it `sub_context`.

**Comment by mark-prins** [comment]
I think `sub_context` is fine - though now that I understand the intent, the name `sub_context` isn't very helpful. I see it more as a modifier than another context, perhaps that's just me.

```
{
  "context": "ProgramPatient", 
  "contextData": "ABCProgram"
}
```

which then relies on the server correctly interpreting the `contextData` for each type of context.

**Comment by clemens-msupply** [comment]
The main reason is to filter the reports and filtering by `contextData` is a bit odd(?).

I go for `sub_context` now and see how it goes, open for later changes!
