### ISSUE TITLE
Reports M1

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1063]
- [x] compose list of most important reports
  - [x] List of appointments
  - [x] Viral Load Eligibility List
  - [x] LTFU List
  - [ ] #1202 
- [ ] #1203

**Comment by mark-prins** [comment]
See also #705

**Comment by clemens-msupply** [comment]
Usually reports are for a specific program, e.g. visits for a specific program. It might be good to group them in the UI as well?

**Comment by clemens-msupply** [comment]
Remaining points are moved into their own issues
