### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1064]
The server is failing with 

```
2023-01-24 08:13:04.700940 INFO actix_web::middleware::logger - 127.0.0.1 "POST /graphql HTTP/1.1" 200 180 "http://localhost:3003/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 0.047792
zsh: segmentation fault  cargo run --features postgres,discovery
```

when run locally. Have had a few seg faults recently, will need investigating.

**Comment by DhanyaHerath** [comment]
Hasn't happened on production yet, but does happen on Mark's server - therefore leaving for now

**Comment by mark-prins** [comment]
Is happening more for me, and Roxy too. Bumping priority because it's annoying as well as worrying.

**Comment by andreievg** [comment]
Lately this was a frequent issue. Telegram post:

> When running in debug mode (pressing debug in main.rs), we can see call stack. Tried this with Roxy, and saw async-dnssd was playing up, after commenting discovery in lib.rs seems to stop ¯\_(ツ)_/¯, I think for bugs like this it's a good idea to see call stack (can potentially do this with cli option in cargo run, or with the debug way).

For now a quick fix would be to either discovery feature or configuration boolean.

More permanent fix should use a well supported library with good amount of activity, or at least one we can understand and fix ourselves

**Comment by andreievg** [comment]
@mark-prins @DhanyaHerath I am putting this issue in sprint as it's impeding development progress
