### ISSUE TITLE
Can try to create an outbound shipment from a customer requisition when finalised (+ UI is a little confusing)

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1078]
### What's happening 
On a finalised customer requisition, the `Create shipment` button stays enabled (image is of a different requisition). When you try to click it, it gives a small error saying `Outbound shipment not created` with no further explanation. 

![Screen Shot 2023-01-24 at 1 41 50 PM](https://user-images.githubusercontent.com/29744386/214187373-7cdcb0d8-55db-4208-a4d8-e6e2fbefc840.png)

### Expected behaviour 
Firstly, on a finalised requisition, I would expect the `Create shipment` button to be disabled. 
But also, this was found by Pauline and Damon, and they didn't have much idea of the previous workflow - so they thought the clear next step was finalising. they found it very confusing that it isn't. We should probably have at least a warning alert. 

@Chris-Petty also noted that mobile automatically creates an outbound shipment when the user finalises a customer requisition - this will also likely lead to confusion.

**Comment by mark-prins** [comment]
Disable the button on finalised requisitions and perhaps add a note as well.
