### ISSUE TITLE
Focus keeps jumping back to first input if no longer typing

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1081]
https://user-images.githubusercontent.com/61820074/214195741-b20082e0-0ff3-4575-b175-be560f1d206c.mov

**Comment by mark-prins** [comment]
Looks like the modal is re-rendering 🤔

**Comment by mark-prins** [comment]
ah. looking at this in #1116

**Comment by andreievg** [comment]
Duplicate
