### ISSUE TITLE
When store visibility is removed, it does not update correctly after syncing omSupply

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#1085]
## Describe the bug 😲

Currently if you remove visibility between two stores, in omSupply this change won't be reflected. E.g. a customer is removed from a store, it'll remain visible. If a supplier is removed from a store, it'll remain visible.

Adding supplier/customer visibility does work, though.

## To Reproduce ⬇️

You'll need access to the central sync server/primary

1. Initialise your omSupply site
2. Find a store that is visible to a store on your omSupply site
3. Remove visibility of that store 
4. Sync omSupply
5. Check if that store can still be used as a supplier or customer - it's still there!

## Expected behaviour 🤔

When store visibility is removed, the stores should no longer be able to use each other as customers or suppliers.

## Screenshots 📸

Where to edit store visibility:

![image](https://user-images.githubusercontent.com/7684221/214432211-f51cf901-c73d-46ab-9de4-15dd20231a30.png)

You can also do it via the _name_ record of the store.

## Versions (please complete the following information)
 - mSupply server: v7.0.5 interpreted mirror sync (would affect any earlier version anyway)
 - omSupply: debug, sqlite, mac, `develop` 3bd37669303668ba6907f49c21eae4b7ad7970a0

## Additional context

Figured out during very confused debugging here https://github.com/sussol/msupply/issues/12179 🤣😭 

I don't think this would affect patients or facilities, as for some reason we do delete those name_store_joins as far as I can tell in mSupply desktop code (haven't tested) 🤷‍♂️. If I'm right, then we're good. If not, then this is a related duplicate of these 2 issues:

- https://github.com/openmsupply/open-msupply/issues/988
- https://github.com/openmsupply/open-msupply/issues/940

## Agreed Solution 

Suggestion: 

https://github.com/openmsupply/open-msupply/blob/3bd37669303668ba6907f49c21eae4b7ad7970a0/server/service/src/sync/translations/name_store_join.rs#L11-L22

I believe the problem is that we don't have a boolean in omSupply like we do in mSupply desktop - I assume we opted for just whether or not the name_store_join record exists (I probably had a say towards this preference!). The problem lies in that mSupply never actually deletes these when it's between stores (but will do for regular ("facility") names or patients), it just sends updates toggling that boolean field. 

- Option 1: The translation layer checks the boolean field `"inactive"` and if it's **true**, deletes the join in the oms database. Should be fairly easy?
- Option 2: mSupply Desktop is adjusted to handle the store-store case the same as patient-store - just delete the join rather than updating the `inactive` boolean. Probably slightly less easy, ignoring that it opens Pandora's box of breaking other existing sync client apps.
- Option 3/illegal 😛: implement `inactive` in omSupply. This probably quite a refactor and the hardest option.

**Comment by Chris-Petty** [comment]
Hahaha foreshadowing:

https://github.com/openmsupply/open-msupply/blob/3bd37669303668ba6907f49c21eae4b7ad7970a0/server/service/src/sync/translations/name_store_join.rs#L83-L84

**Comment by andreievg** [comment]
Thanks @Chris-Petty good find, I suggest option 1.

> I assume we opted for just whether or not the name_store_join record exists (I probably had a say towards this preference!)

When I tested toggling name visibility in store, I didn't see `inactive` being toggled, so went with existing approach. 

I am still not sure where in mSupply UI `inactive` is set to true/false, could you please clarify (I tested with the `name` form

**Comment by andreievg** [comment]
As Chris pointed out in our chat, this is from `store` window, you can check in record browser:

`select name.name, store.name, inactive from name_store_join join name on name.id = name_store_join.name_id join store on store.id = name_store_join.store_id`

`inactive` is set vs record being deleted
