### ISSUE TITLE
Patient editing without program module

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1094]
Patient editing should work seamlessly no matter if the program module is disabled or enabled.

- [x] Currently the UI assumes a patient has be created with a patient document; make sure existing patients can be edited (with program config)
- [ ] If the programs module is disabled no central schema configuration should be required (e.g. bundled needed default patient schemas)
- [ ] ~Don't save a document when programs is disabled but only update the names table~

**Comment by andreievg** [comment]
My thoughts on this was, we have a generic `core` patient form, which is a simple form that doesn't have document or form schema (basic service etc..). And the `extra` data that a specific country needs can be captured in document/form schema, on the same page or separate tabs but not integrated to the core patient form.

This would remove the need to connect name and document or to maintain their alignment (this is especially tricky to do right in sync system).

A couple of things that may invalidate the simpler approach:
* There is a hard requirement in existing program work, for the core patient data to be in specific order or to have specific look/control that is different to what we want to do for general core patient data
* There is a definite need for other countries to customise how core patient data is entered

 @craigdrown @richardmoizeau, can you please confirm the above.

**Comment by clemens-msupply** [comment]
@roxy-dao brought up another good point about permissions. We don't want an extra config to view/edit/add a user. For this reason we thought about automatically giving user patient document permission if the user has the correct mSupply edit permissions.

**Comment by clemens-msupply** [comment]
Closing in favor of https://github.com/openmsupply/open-msupply/issues/2023

**Comment by nisha-dangol** [comment]
Moving this to Done since I see the `Patients` module in oms UI as long as the store is set as `Dispensary` type in mSupply (regardlless of programs module store pref), which looks like the correct behavior to me!

**Comment by roxy-dao** [comment]
> Moving this to Done since I see the `Patients` module in oms UI as long as the store is set as `Dispensary` type in mSupply (regardlless of programs module store pref), which looks like the correct behavior to me!

This is for something else Nisha (:
