### ISSUE TITLE
Logo queries (needed for reports)

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1095]
- [ ] figure out how the 4D Picture data is synced, e.g. which format
- [ ] add pull support to integrate the `store.logo` to mSupply (`service/src/sync/translations/store.rs`)
- [ ] add StoreNode method to return a new ImageNode in api (`graphql/types/src/types/store.rs`)

For example:
```rust
struct ImageNode {
  mimeType: string,
  /// base64 data
  data: string,
}
```
or just a return a string like `data:image/jpeg;base64`

**Comment by DhanyaHerath** [comment]
@anildahalsussol Hey Anil, nice to see you here in the omSupply repo 😄 Please remember to assign yourself if you're working on an issue - thanks!
