### ISSUE TITLE
Encounters for the wrong patient appearing

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1101]
This could be a just due to dodgy demo data, but worth looking into:

To reproduce (on feature branch, using demo data (the one with patient "Tina Ling" already created):

- Create and save new patient
- Go to the "Encounters" tab
- Notice the list of existing encounters for Tina Ling, not the newly created patient.

**Comment by CarlosNZ** [comment]
@clemens-msupply do you think this is just due to dodgy demo data (that wouldn't occur IRL), or an actual bug?

**Comment by clemens-msupply** [comment]
sounds like a bug...
