### ISSUE TITLE
When you add a new batch to a stocktake line, it gets added to the end (and is hard to notice)

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1117]
This is a small thing, but when I tried to add a new batch line to an item in a stocktake, the new line gets added to the bottom of the window, rather than the top. 

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/29744386/216179269-e78a5346-ba87-453a-9cb6-6221dafbc935.png">

This is ok when you can see it on the screen, but otherwise (if you are me...) you might keep clicking the button thinking it hasn't worked. I wonder if it would be helpful for the lines to get added at the top. 

_Example of someone being silly and constantly creating new lines_

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/29744386/216179729-f20f72c5-4e7d-466e-b1a6-50819e983b43.png">

**Comment by bijaySussol** [comment]
@DhanyaHerath @mark-prins : 

I have assigned to me.
But could you please let know where this issue stand?

thanks
