### ISSUE TITLE
Incorrect calculations when issuing stock on an outbound shipment created from a requisition 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1119]
### What is happening 

There are some odd calculations happening when issuing items in an outbound shipment created from a requisition. 

### To recreate

1. Create a customer requisition & make sure you have some items to supply with quantity > 0. 
2. Create an outbound shipment from the requisition 
3. Now select an item to issue to (ideally one with multiple packsizes) 
4. Write the amount you want to issue, and use the `unit` dropdown list to change units
5. Now try to manually allocate stock between lines of different packsizes 
6. Note that the placeholder line value still says a value, and the `Issue x units...` value is incorrect

<img width="943" alt="image" src="https://user-images.githubusercontent.com/29744386/216183361-bc971b1b-7a7e-40ef-a3a4-8689a0a69df7.png">

**Comment by andreievg** [comment]
I was just checking this and I think we need an agreement for this issue: https://github.com/openmsupply/open-msupply/issues/1052

Please see this comment (was trying to figure out what the logic should be but couldn't): https://github.com/openmsupply/open-msupply/issues/1052#issuecomment-1421641228

**Comment by andreievg** [comment]
It looks like this was fixed already ?

Can we close this ?

https://user-images.githubusercontent.com/26194949/217929799-45f7f8af-1093-492c-bc59-32e1ac1ac822.mov

**Comment by roxy-dao** [comment]
When manually allocating 🤔 
Uploading Screen Recording 2023-02-14 at 2.28.34 PM.mov…

**Comment by mark-prins** [comment]
Ok to close - it's working for me too. 
the retention of the placeholder value is ok - there is something odd when zeroing the placeholder though, which I'll pick up in #1052
