### ISSUE TITLE
User gets kicked out if they try to change status of Outbound Shipment before all lines have been allocated

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#1137]
User gets kicked out if they try to update Outbound Shipment status before all lines have been allocated: 

https://user-images.githubusercontent.com/19318937/217134446-01ab2683-b055-4d7c-aff2-894ef3fa1d39.mp4

Repro: 
1. Create a new OS
2. Add an item and issue a placeholder line
3. Attempt to change status of OS

Env: https://demo-open.msupply.org/
Version: 1.1.2

**Comment by roxy-dao** [comment]
Tested this on both dev env and on the demo... Not happening for me on either environments 🤔

**Comment by mark-prins** [comment]
I thought this should be fixed by #1084 

This is what I get when I try to repro:

https://user-images.githubusercontent.com/9192912/220004245-44ac8e33-7d00-4fac-8d7f-07b760cd18f9.mp4

Are you able to retry? The demo server has now been upgraded to v1.1.3 which will have the above fix in it.

**Comment by andreievg** [comment]
This seems to happen after auth timeout. i.e. on Auth timeout being taken to login screen, after logging, if we try to replicate it should work. I think we should be able to replicate this by settings timeouts to be quite short.

**Comment by mark-prins** [comment]
> This seems to happen after auth timeout. i.e. on Auth timeout being taken to login screen, after logging, if we try to replicate it should work. I think we should be able to replicate this by settings timeouts to be quite short.

🙏  Thanks - that did the trick!
