### ISSUE TITLE
Internal order -> Requisition workflow not working (for Kopu -> Opua)

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#1140]
Internal Orders from requesting Store are not arriving in the supplying Store as Requisitions: 

![telegram-cloud-photo-size-1-5120842692333513505-y](https://user-images.githubusercontent.com/19318937/217142430-31e99863-4830-4adc-ab60-05dc2d92e94e.jpg)

![telegram-cloud-photo-size-1-5120842692333513507-y](https://user-images.githubusercontent.com/19318937/217142471-dc0c42bf-c554-4a3a-8caf-1869f2bbd203.jpg)

Repro: 
1. Log into Kopu, raise an Internal Order to Opua
2. Log into Opua, check Requisitions
3. Do some random syncing in both stores just in case
4. Re-check Requisitions in Opua

Env: https://demo-open.msupply.org/
Version: 1.1.2

**Comment by andreievg** [comment]
There was a theory that processors stop working, judging by the code they should be able to resume from error, would be good to see replication.

It looks like processor is still running, there is however a problem with finding related records, not sure about the origin, but can potentially add a mechanism to skip these sorts of errors. Here is a log file and backup

[demo data and log.zip](https://github.com/openmsupply/open-msupply/files/10680473/demo.data.and.log.zip)

I initialise from the backup and tried requisition, seems to work correctly, I would assume there is something wrong with data of remote server in our demo instance. 

Would suggest closing this issue

**Comment by mark-prins** [comment]
It would be nice to know what exactly is wrong with the data - and perhaps add the data check to our internal database integrity checking code ( which needs to be added to the admin section.. )?

**Comment by andreievg** [comment]
> It would be nice to know what exactly is wrong with the data - and perhaps add the data check to our internal database integrity checking code ( which needs to be added to the admin section.. )?

Thanks for the idea, and for pushing further investigation.

## Further investigation

took one line from the log

```
2023-01-23 15:19:07.734941 ERROR service::processors - Error in shipment transfer processor (Problem getting upsert operation Error while fetching shipment operation ChangelogRow { cursor: 212, table_name: Invoice, record_id: "0f131c01-7e6c-470b-988d-588d6eaa5904", row_action: Upsert, name_id: Some("861102F624354F15ABEB48DC207A4C2D"), store_id: Some("1E31B3575A284B7DB27EE755102446FE") } Requisition not found "8539d413-4a6a-4c55-a873-0213846b2be4")  service\src\processors\mod.rs:83
```

* Checked central data, record exists
* Checked remote server data, record does not exists, it's not in change log either
* Checked sync_buffer, got this:

![Screenshot 2023-02-09 at 11 37 41 AM](https://user-images.githubusercontent.com/26194949/217667782-f9b9e21a-874c-43a0-a774-a37c49e87452.png)

record json is:
```
{"ID":"8539d413-4a6a-4c55-a873-0213846b2be4","authorisationStatus":"","colour":0,"comment":"","custom_data":null,"date_entered":"2022-06-16","date_order_received":"2022-06-16","date_required":"0000-00-00","date_stock_take":"0000-00-00","daysToSupply":90,"isRemoteOrder":false,"is_emergency":false,"lastModifiedAt":1655375863,"linked_purchase_order_ID":"","linked_requisition_id":"2fb40989-0488-457d-9306-425c5dbddd4e","name_ID":"861102F624354F15ABEB48DC207A4C2D","nsh_custInv_ID":"","om_colour":"","om_created_datetime":"2022-06-16T10:37:16.631124","om_expected_delivery_date":"2022-06-30","om_finalised_datetime":"","om_max_months_of_stock":3,"om_sent_datetime":"","om_status":"NEW","orderType":"","periodID":"","previous_csh_id":"","programID":"","requester_reference":"","requisition_category_ID":"","serial_number":3,"status":"cn","store_ID":"1E31B3575A284B7DB27EE755102446FE","thresholdMOS":1,"type":"response","user_ID":"0763E2E3053D4C478E1E6B6B03FEC207"}
```

At the erroneous column: `"om_finalised_datetime":""`, there was a fix to sync that fixed om nullable fields having empty string vs null in sync, this should have been fixed, but it looks like last sync was in November 2022.  

## Solution

Re-sync

## How to prevent in the future

We can be mindful of the error in sync, can see them in console, log file or sync_buffer. There are some know errors (in reports), it's only the extras that need a look.

Perhaps there should have been a migration to run through sync buffer and re-integrate erroneous records (after the fix to sync)

**Comment by mark-prins** [comment]
Have recreated the database on demo, synced and tested. All working fine.
