### ISSUE TITLE
Add spacer control to group control visually

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1154]
For example, similar to the right side of:

![Image](https://user-images.githubusercontent.com/88299195/217659906-fa596e4d-c15f-4baf-8993-242b7040a302.png)

From internal chat, make the following amendments compared to the mockup:
- have the line full width
- more space around the line
- just a plain line (no shadow)

**Comment by CarlosNZ** [comment]
Presumably takes a single parameter "height" in pixels, with a reasonable default value.

**Comment by CarlosNZ** [comment]
There's already a `<Divider/>` component available, just checking we're happy with how it looks out of the box:

![Screenshot 2023-02-10 at 11 42 04 AM](https://user-images.githubusercontent.com/5456533/217955793-bcfce7a3-a4dc-4663-862e-02c7109de3b8.png)

@anisha-msupply @clemens-msupply ?

**Comment by anisha-msupply** [comment]
Looks good to me - it's a clear enough separator, without making things too cluttered :)

**Comment by CarlosNZ** [comment]
Thanks @anisha-msupply  :)

**Comment by clemens-msupply** [comment]
Yes that look great!

**Comment by CarlosNZ** [comment]
Closed by #1163
