### ISSUE TITLE
Add programEnrolment node to the EncounterNode to be able to query the patient enrollment for an encounter

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1155]

**Comment by CarlosNZ** [comment]
Did you want to just add the "Patient" node too? Make everything we need available in one query?

**Comment by clemens-msupply** [comment]
> Did you want to just add the "Patient" node too? Make everything we need available in one query?
> 
> You'll see in #1159 that I had to do a separate Patient lookup for the Header details, so would make sense if this was all available in the same data structure.

There is already a `patient` node on the encounter or do you mean something else?

**Comment by CarlosNZ** [comment]
> There is already a `patient` node on the encounter or do you mean something else?

Ah okay, right. I thought it didn't have all the fields, but I can just more to the query.

Thanks, and never mind :)
