### ISSUE TITLE
Tetum language for user on central/remote

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1164]
Issue change just to make sure language exists for deployment. Should be available on central and remote server (can be set for user on central and shows as default for user in android app etc..)

Previous issue description:

From my understanding Language setting comes from browser app data (or cookie ?), it's set in `admin` menu and is valid for the browser. 

This means after initialisation of remote site (say mobile app), user with `admin` permissions would need to log in to that app instance and set the language for that app instance (this would need to be done on the clients too)

I think we should set language either globally for all omSupply sites or by user like we do in mSupply.

This seems like a high priority, since:
* Either all users would have to have admin permissions and set the language manually.
* Just one user has admin permissions but needs to log in for each app instance and set the language.

You can test this by switching to incognito mode or opening app in another browser after setting language in `admin` menu

**Comment by andreievg** [comment]
Ohh look like working as expected, langue set for user centrally seems to be used by default. We are missing language for tl from central and remote server

**Comment by Chris-Petty** [comment]
Aside, it'd be really better UX if users could just choose their language from the UI

**Comment by mark-prins** [comment]
> Aside, it'd be really better UX if users could just choose their language from the UI

during login like mobile? You can change the language already.. but only after you've logged in ( possibly with the site running under a strange language! ) and only if you have admin rights.

someone did mention login screen selection.. and I'd forgotten.

**Comment by Chris-Petty** [comment]
Sorry that was phrased vaguely! Login screen would be great, but I just meant moving it out of the admin window and readily accessible for any user. Wondering if we could possibly do a cookie for each user that stores their manually set language?

Under the admin cog ain't too hard to intuit I think. A thought for that is maybe making admin -> "Settings" and having navigable sub sections: "General" could be first and selected by default, showing language at top? General being available for all users. Then "Admin" and similar sections could be made available according to prefs.

When doing frontend dev I think it's nice having it handy after login too so I can flick the languages quickly to check layouts when making adjustments.

**Comment by mark-prins** [comment]
yes - the restriction of needing to be an administrator in order to change language does need to change!
Reading your comment, I'm wondering about a little 'change language' button somewhere, but I prefer your admin section approach for two reasons

- the language icons available aren't great and don't inform as much as a flag.. but the flag is problematic since language and country are different things
- I don't expect normal users to be switching up language that often, so we shouldn't use valuable screen real estate on the control ( though, this could be on the footer, where the site name and user name are.. 🤔 )

**Comment by Chris-Petty** [comment]
Agree that not often needed, but when you do and can't find it then it's a pain haha. On the footer is a cool idea, free real estate to use yet. I reckon it's worth trying on. My concerns against it is that right up against the store / username in my imagination looks a little ugly/crowded haha, but if on the other end (so bottom right of screen) it might be easy to miss... at least on my relatively large monitor anyway.

**Comment by mark-prins** [comment]
oki - will see if we can make something that looks ok and is easy to find. and if that doesn't work out, pop it into admin.
Still like the concept of levels of admin access in the settings section too. We should add that in as well.

**Comment by mark-prins** [comment]
Created central server issue https://github.com/sussol/msupply/issues/12353
