### ISSUE TITLE
Report builder fails to create PDF after Google Chrome updates to version 110.0.5481.77 (Official Build) (arm64) or higher

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/open-msupply#1184]
Report builder fails to create PDF after Google Chrome updates to version 110.0.5481.77 (Official Build) (arm64) or higher.

In the Course of three days PDF generation of my design print template for the stock window failed to work. After multiple trials and debugging with @anildahalsussol , we noticed that the `headless_chrome` feature failed to work once Google chrome got upgraded locally from 109.0.5414.119  to 110.0.5481.77.

This issue was discovered while working on PR :  https://github.com/openmsupply/open-msupply-reports/pull/4

The command no longer works :  

`cargo run -- print --report Stock_take_variance.json --config config.yaml --store-id A2B2F9D22BBA41EA8BB7D00EE75A7503 --data-id 5bf72bef-8558-45b0-87f5-ae4f5ddabb14 --output report_pdf_name.pdf  `

The error : 

```
> Send report print request 
Error: Failed to fetch report data: Failed to print report: status=200  GraphQlResponse {
    data: Null,
    errors: Some(
        Array([
            Object({
                "extensions": Object({
                    "details": String(
                        "HTMLToPDFError(\n    \"The event waited for never came\",\n)",
                    ),
                }),
                "locations": Array([
                    Object({
                        "column": Number(
                            3,
                        ),
                        "line": Number(
                            3,
                        ),
                    }),
                ]),
                "message": String(
                    "Internal error",
                ),
                "path": Array([
                    String(
                        "printReportDefinition",
                    ),
                ]),
            }),
        ]),
    ),
}

```

This is rather annoying. I think we should rely on local binary or exe work for this type of task.

**Comment by ujwalSussol** [comment]
@clemens-msupply   and  @andreievg  the latest Google Chrome has stopped me from viewing my designed reports.  Can this be improve ?

**Comment by clemens-msupply** [comment]
There is a fix but no release yet:
https://github.com/atroche/rust-headless-chrome/issues/367

You could use this fix temporarily by "patching" the dependency through your cargo.toml:
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

**Comment by clemens-msupply** [comment]
Could you please check if this fixes it?

https://github.com/atroche/rust-headless-chrome/releases/tag/v1.0.5

This release includes:
https://github.com/atroche/rust-headless-chrome/pull/368
