### ISSUE TITLE
Can't enter `BP in mmHg` with the correct format in the HIV Care and Treatment Encounter form

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1187]
Physical Exam Section: 

Unable to enter `BP in mmHg:` as per data validation rule: 

![Screen Shot 2023-02-15 at 11 45 03 AM](https://user-images.githubusercontent.com/74992958/218880240-21988590-b1fa-4400-997c-4c141d943737.png)

**Comment by DhanyaHerath** [comment]
I think this one https://github.com/openmsupply/open-msupply/issues/828 might be the duplicate @clemens-msupply

**Comment by clemens-msupply** [comment]
Yes #828 should fix it
