### ISSUE TITLE
Navigate to login on status change error

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1209]
## What went wrong? 😲

Was taken to login

## Expected behaviour 🤔

Stay on outbound shipment page

## How to Reproduce 🔨

In outbound shipment create a placeholder line

Try to go to allocated status

An error appears and being taken to login page

## Your environment 🌱
- Development environment on current develop branch

**Comment by roxy-dao** [comment]
Duplicate #1137

**Comment by andreievg** [comment]
thanks @roxy-dao, closing
