### ISSUE TITLE
After initialisation restarting server goes to bootstrap unless we can reach central

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#122]
After initialisation, stop central. Restart server, and it goes back to initialisation.

Expected behaviour is it stays initialised. I don't think we should hot patch it, but re-write as per second comment: https://github.com/openmsupply/open-msupply/issues/66

**Comment by mark-prins** [comment]
I'm not sure what you mean by 'hot patch' sorry!

But I think we should put something in place to stop this issue, before doing a full re-write. We've already had this issue in production and it doesn't seem like a big thing to work around. Just need to allow the server to start when in production mode, when the central server is unreachable.

**Comment by mark-prins** [comment]
@roxy-dao - wondering if you could help with this one?

**Comment by roxy-dao** [comment]
> @roxy-dao - wondering if you could help with this one?

I can try re-produce the error first since it hasn't happened to me yet I think 🤔

**Comment by andreievg** [comment]
`hot patch` was not very descriptive, i just meant `patch` vs re-write. Existing logic is quite convoluted and I think `hot patch` would be hacky, but yeah, let's patch it. @roxy-dao you'll have to add a condition somewhere in this file: https://github.com/openmsupply/open-msupply/blob/develop/server/server/src/lib.rs

**Comment by roxy-dao** [comment]
Can't seem to re-produce this 🤔  My dev environment stays initialised even after disconnecting from central and doesn't go back to the initialisation page

**Comment by andreievg** [comment]
@roxy-dao can you try this please:

* start front end with `yarn start-local`
* before starting back end make sure that all of the configuration tomls have sync commented out entirely
* start 4d 
* start back end and initialise by entering credentials via front end
* after initialised
* quit 4d
* restart back end
* refresh front end

**Comment by mark-prins** [comment]
@roxy-dao you need to run in release mode.
I get this when I run with `--release`

```
[2022-08-12T04:01:13Z WARN  server] Falling back to bootstrap mode
[2022-08-12T04:01:13Z WARN  server] Starting server in bootstrap mode. Please use API to configure the server.
```

even though my database is initialised
