### ISSUE TITLE
Ledger problem

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#1238]
## What went wrong? 😲

Stock discrepancies, ending up creating ledger problems.

## Expected behaviour 🤔

No Ledger problem

## How to Reproduce 🔨

Steps to reproduce the behaviour:

- Select the item that does not have a ledger problem
- Setup remote server with client and the central server
- From remote client > Create the outbound against that item
- `Confirm shipped` outbound invoice
- From central server > Lock that stock line
- Sync it from remote client
- Check the ledger
   - Will have a ledger problem

## Your environment 🌱
 - Version [1.2.3, current develop]
 - Platform [browser, windows desktop, server]
 - Central server [ 702 - Beta 15 ]

**Comment by andreievg** [comment]
@bijaySussol what do you y `lock stock line` ? Is it possible through UI ?

Are you testing on a build with this change https://github.com/sussol/msupply/pull/12340 ? If so then next sync should update stock line (even if it doesn't touch stock line)

**Comment by bijaySussol** [comment]
> @bijaySussol what do you y `lock stock line` ? Is it possible through UI ?
> 
> Are you testing on a build with this change [sussol/msupply#12340](https://github.com/sussol/msupply/pull/12340) ? If so then next sync should update stock line (even if it doesn't touch stock line)

Thanks @andreievg 
It does on next sync.
Can be closed.
