### ISSUE TITLE
Inbound invoice: Updating service tax amount > Error

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#1240]
## What went wrong? 😲

Updating service tax amount in Inbound shipment > Gives error.

![Inbound error](https://user-images.githubusercontent.com/13144882/221427598-99b44240-d7d2-4de9-a874-d6e266ddf6dd.PNG)

## Expected behaviour 🤔

Must be handled

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Any Inbound shipment, Any status not `Confirm Verified`
2. Click on 'More'
3. Service charges section
4. Click on Tax 'pen' icon
5. Set the tax amount
6. Click OK
7. See error

## Your environment 🌱
 - Version [1.2.3, current develop]
 - Platform [browser, windows desktop, server]

**Comment by CarlosNZ** [comment]
I can't reproduce this as per the steps described here. Anyone else?

**Comment by bijaySussol** [comment]
Sorry @CarlosNZ probably steps ain't so good.
but, I can recreate every-time.
Anyways, I will assign to myself.

**Comment by andreievg** [comment]
> but, I can recreate every-time.
> Anyways, I will assign to myself.

When we test the fix we would need to know how to reproduce

**Comment by bijaySussol** [comment]
@CarlosNZ @andreievg : 
Updated the test cases
Thanks
