### ISSUE TITLE
Setup server for field test

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1246]
- [x] windows server for central server
- [x] linux server for remote server
- [x] add dns entry, e.g. `png-field-test.msupply.org`

**Comment by mark-prins** [comment]
Is the intention something like this?

- Create a new virtual server on openstack ( linux? which distro? )
- Create / copy / configure a datafile to use which showcases the programs work
- Install mSupply ( where though, if linux VM? use an existing mSupply instance? )
- Install postgreSQL? use SQLite?
- Add entry to DNS. URL would be?
- Add / configure reports? Patient data?
- Restrict access? 
- Create user accounts?
- Refresh data?
- Update process?
