### ISSUE TITLE
Make specific Patient (and other program) modals bookmarkable

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#125]
Just putting this here to remember to do it after Patient form is properly implemented -- it should be fairly straightforward after that.

Suggest url schema `/patients?id=<documentName>`

**Comment by DhanyaHerath** [comment]
Hey @CarlosNZ currently it's just https://demo-programs.msupply.org/dispensary/patients/e924e3ec-71e7-4d02-acdb-8fd51720d50b (for example) - does it need to be extended further?

**Comment by CarlosNZ** [comment]
> Hey @CarlosNZ currently it's just https://demo-programs.msupply.org/dispensary/patients/e924e3ec-71e7-4d02-acdb-8fd51720d50b (for example) - does it need to be extended further?

Sorry, forgot to reply to this. 🤦‍♂️

Yes, this is fine now I think. Will close :)
