### ISSUE TITLE
JSON Forms -- component width inconsistency

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1255]
## What went wrong? 😲

There is still some width inconsistency with some of the JSON form components' widths:

![Screenshot 2023-03-01 at 11 42 32 AM](https://user-images.githubusercontent.com/5456533/221998832-49039e7a-5f9f-4ab5-b4fb-909d6a7296b8.png)

I think the best solution is to make sure they're all wrapped in a `DetailInputWithLabelRow` component, making them consistent with what @mark-prins did in #1251. (Some of them already are, and there might be one or two that this doesn't work for, so needs some investigation)

**Comment by clemens-msupply** [comment]
I fixed some of these issues yesterday in a PR where I defined a style constant so that they all use the same base style.

But the TEXT component is still too short and some vertical gap seem to be off as well...

**Comment by roxy-dao** [comment]
- Adding more screenshots where the components are inconsistent.

![Screen Shot 2023-03-16 at 11 14 49 AM](https://user-images.githubusercontent.com/61820074/225455618-58652570-6839-41bd-b34f-c1852ab01b6e.png)
![Screen Shot 2023-03-16 at 11 15 32 AM](https://user-images.githubusercontent.com/61820074/225455686-d5664276-2573-4273-8149-da6a6c071470.png)
![Screen Shot 2023-03-16 at 11 15 17 AM](https://user-images.githubusercontent.com/61820074/225455698-17fef631-8e12-4b42-893a-7baaf93be399.png)

**Comment by CarlosNZ** [comment]
Closed by #1557
