### ISSUE TITLE
Change New Encounter modal to use JSONForms

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1264]
As per the newly changed "Create Patient" modal.

**Comment by CarlosNZ** [comment]
As discussed in stand-up, getting this Modal to use JSONForms is not straightforward for the following reasons:

- the "Clinician" selector needs a dynamic lookup to get the list of options, which we currently can't do with our JSONForms components
- We don't currently have a "time only" component for the end time (currently only have Date and DateTime inputs)
- Mixing and matching JSONForms components with standard form elements is a bit of UI nightmare. This is not insurmountable, but is probably a lot more work than it's worth at this point.

So suggestion now is just to keep the existing form, but add some additional validation and checks:
- All fields (except "End time") are compulsory
- Dates must be valid (and show appropriate invalid state when not)

**Comment by CarlosNZ** [comment]
Currently most of the places using the Date and Time pickers are doing their own checks for valid dates as part of their `onChange` method. I'd like to move this into the pickers themselves so we can show consistent validity states on the date/time inputs and avoid code duplication in every implementation.

Sound reasonable, @mark-prins @clemens-msupply ?

(We'll still be able to add additional restrictions in the implementations, such as "can't be in the past" or a specific range restriction if we want to)

**Comment by clemens-msupply** [comment]
sounds good to me!

**Comment by CarlosNZ** [comment]
Closed by #1301
