### ISSUE TITLE
If Regimen Status = Start ARV or Changes to ARV Regimen, it has to be different from Current ARV Regimen (data validation)

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1265]
- [ ] If Regimen Status = Start ARV or Changes to ARV Regimen, it has to be different from Current ARV Regimen (data validation)

@richardmoizeau its possible but more tricky so wonder how important it is?

**Comment by clemens-msupply** [comment]
@richardmoizeau can I close this one?

**Comment by richardmoizeau** [comment]
> @richardmoizeau can I close this one?

Yes !
