### ISSUE TITLE
Error changes size of component

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1268]
## What went wrong? 😲
Width of component changes if there is an error
![Screen Shot 2023-03-03 at 11 53 00 AM](https://user-images.githubusercontent.com/61820074/222578330-09f66468-993b-4d84-9742-4e3137cda575.png)

## Expected behaviour 🤔
Probably should stay the same width...

**Comment by CarlosNZ** [comment]
It's expanding to allow for the error text, isn't it? In which case, we should probably make the minimum width enough to show the error text in a single line. (Or, how does it look if the error text wraps onto another line?)

**Comment by roxy-dao** [comment]
Doesn't seem like the other component is expanding to allow for the error text..

![Screen Shot 2023-03-03 at 12 01 36 PM](https://user-images.githubusercontent.com/61820074/222579625-e1b47816-f405-4f1b-9ce3-6c9619f556f6.png)

**Comment by clemens-msupply** [comment]
maybe control stays the same width but error uses full width
