### ISSUE TITLE
Revise programStatus and enrolmentStatus

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1270]
Currently program enrollments and and encounters use a `programStatus` and `encounterStatus` event type to show "LTFU" or "VL Result Pending" messages.

However, in general one can think of multiple statues that can coexist. In this case independent statues would overwrite each other.

Possible solution:
1) use a limited set of statues, e.g. `programStatus1`, `programStatus2`
2) use a prefix, e.g. `status{MyStatusDetails}` and all program events with this prefix will get displayed
3) add an event `group` property which can be used to group events, e.g. type = "LTFUStatus", group="programStatus"
4) be able to configure the UI for which events should be displayed (this can also include how the event will be displayed)

Option 4) seems very nice but we would need a way to configure the UI for a site which would need some further discussion. Option 2) could be an intermediate workaround.

**Comment by roxy-dao** [comment]
The program events should be displayed in the `Additional Infomation` column. 

Possible UI implementations could be a text box with helper text at the top? (The helper text being the type and text field data?) 
![Screen Shot 2023-03-24 at 11 04 38 AM](https://user-images.githubusercontent.com/61820074/227375146-a8bcde55-8c4a-4355-b2bb-2e7dcf0dc6fd.png)

Though we would have to figure out which type needs to be loaded with which program..

**Comment by clemens-msupply** [comment]
@mark-prins do you have an opinion / idea? e.g. is there already a place to store this kind of config? (Note, there are other UI configs that might need to be configured, e.g `Gender` vs `Sex` or other labels (?))

Otherwise, I would go with the prefix convention for now. If we want something more sophisticated we can still a config for it at a later point.

**Comment by clemens-msupply** [comment]
Yes the event data displayed in the "Additional Info" column is depending on the customer. For example, the same encounter type could have multiple statues like:
- `statusViralLoad`
- `statusNeedsFollowup`
- `statusMedicationPrescripted`
- ...

But an encounter could also have other custom events that shouldn't be displayed in this column. So we need a way to configure which events should be displayed in this column.

Same for program enrolments, you could have statues like:
- `statusLostToFollowUp`
- `statusSpecialMedicalCondition`
- `statusWarningViolentPatient`
- ...

In this example I just prefixed all events that should be displayed.

**Comment by clemens-msupply** [comment]
If there are no other suggestions I will go with the `status` prefix. Currently, all encounter events show up in the encounter list view so we need to filter unwanted events out...
