### ISSUE TITLE
When creating a patient, you cannot click create

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1285]
## What went wrong? 😲
 
After entering patient details, and searching, I'm presented with a patient entry form. I want to create the patient, but the button is disabled:

<img width="299" alt="Screenshot 2023-03-07 at 9 18 19 AM" src="https://user-images.githubusercontent.com/9192912/223223506-c281a679-cf09-460d-a8ea-72f181a5f988.png">

## Expected behaviour 🤔
A message explaining which fields need to be filled in, if there are any, or
the button should be enabled if there isn't anything to be entered

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary > Patients
2. Click on `New Patient`
3. Enter some details
4. Click `OK & Next`
5. Click `Create`
6. Note the state of the button. Entering anything in the fields will trigger the `isDirty` check and enable the button

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by CarlosNZ** [comment]
Hmm, also -- when the full Patient form loads, not all the fields entered into the previous Modal are pre-filled. Probably connected somehow...

**Comment by CarlosNZ** [comment]
There's also an infinite re-render going on on the initial Patient modal now too, which probably has something to do with both the above problems, so will need a fairly urgent fix.

**Comment by CarlosNZ** [comment]
Closed by #1290
