### ISSUE TITLE
Change number input pattern to max number in schema

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1288]
## Is your feature request related to a problem? Please describe 👀
Currently, the number input isn't matching the pattern provided in the schema, so users aren't alerted that their input is incorrect

## Describe the solution you'd like 🎁
- Limit the number input for blood pressure to 999

### Describe alternatives you've considered 💭
🤷🏻

**Comment by CarlosNZ** [comment]
Aren't (JSONForms / AJV) validation patterns just for strings? I thought you could only do `min` and `max` values (and maybe a couple of others) for number inputs.

It doesn't really make sense for a number to conform to a character pattern, does it?

Can you give an example of what you mean?

**Comment by CarlosNZ** [comment]
Oh yeah, I see @clemens-msupply made this point yesterday, too: https://github.com/openmsupply/open-msupply/pull/1267#discussion_r1123930807
