### ISSUE TITLE
Patient creation improvements

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1291]
- [ ] The patient creation modal finishes with a "Create" button but the patient is not saved at this point. Rename "Create" to "Ok & Next" as previous button
- [ ] When creating a new patient the save button is disabled but should be enabled

**Comment by CarlosNZ** [comment]
> * When creating a new patient the save button is disabled but should be enabled

Should be fixed by #1290 isn't it?
