### ISSUE TITLE
Error on android tablets when re-opening the app 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1295]
## What went wrong? 😲
 

Nick Pendergrast, [8/03/23 12:32 PM]
Hi team,
I've installed 1.1.4-rc1 apk on 4 tablets this morning.
All synced to sites ok.

On one of the tablets I am getting this error now when opening the app. Have tried to force stop, as well as clearing the cache. Can't get past this error

Nick Pendergrast, [8/03/23 12:35 PM]
Just got the error on a second tablet.
Logged into the store with user credentials, then closed the app through the task manager. When opening the app again I get the error

![image](https://user-images.githubusercontent.com/29744386/223585594-b6d297d3-88dc-4aa6-a19d-00180f2a62c7.png)

## Expected behaviour 🤔
No error 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [1.1.4]
 - Platform : tablet

**Comment by mark-prins** [comment]
<img width="855" alt="Screenshot 2023-03-08 at 4 36 47 PM" src="https://user-images.githubusercontent.com/9192912/223613338-a00540a7-1a0c-44b4-8b8f-36a763b72d93.png">

**Comment by mark-prins** [comment]
yes, rc version.
