### ISSUE TITLE
Uncounted stocktake lines should be pruned on finalise

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1302]
## What went wrong? 😲
 
When you finalise a stocktake, it saves all the lines added to the stocktake, including ones where the counted quantity and the snapshot quantity remain the same. These should be removed on finalise ideally, or otherwise it's a quick way to increase the size of your database?

## Expected behaviour 🤔
Should remove uncounted lines on finalise 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a stocktake (easiest if you do it from a masterlist)
2. Click finalise 
3. Notice that all lines remain 

## Your environment 🌱
 - Version 1.1.4
 - Platform tablet, but probably all

**Comment by roxy-dao** [comment]
I remember having this conversation with @mark-prins a while back 🤔 
I can't remember the exact conversation anymore... but it was something to the lines of don't prune...

**Comment by DhanyaHerath** [comment]
@roxy-dao Oh interesting - would be good to know why! Maybe that was before we started having the option to create them from masterlists?
