### ISSUE TITLE
The cross icon doesn't match the other icons in style (and is uncentred)

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1310]
## What went wrong? 😲
 
The cross icon doesn't match the other icons in style. More importantly, it isn't horizontally centred!

<img width="169" alt="Screenshot 2023-03-09 at 3 25 56 PM" src="https://user-images.githubusercontent.com/9192912/223900164-df77de15-7d7c-48fb-856b-70b5e0b07072.png">

## Expected behaviour 🤔
The icon should fit, and look pretty.

**Comment by DhanyaHerath** [comment]
oh no, unusable!
