### ISSUE TITLE
AV: Unable to issue stock

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1315]
## What went wrong? 😲
 
The default pagination limit strikes again!!

The issue as reported is this:
We have Ondansetron in stock, as shown by the item view: (I've confirmed this by checking stock lines)
![image](https://user-images.githubusercontent.com/9192912/224166393-343009fc-8400-4622-8c21-0d16c384d45e.png)

But, if we try to issue stock, we are unable to - it says that there is no stock available:
![image](https://user-images.githubusercontent.com/9192912/224166340-b9f45e28-93d0-4047-a94c-4735e9c17151.png)

![image](https://user-images.githubusercontent.com/9192912/224166359-10201712-62a4-4eaf-ac00-43aaf1324935.png)

The problem, I think, is that the query to fetch the stock lines to show in the outbound shipment, is hitting the default pagination limit. Checking the response of the `itemsById` query, there are exactly 100 stock lines returned. The database shows 134 stock lines.

<details>
<summary>Query</summary>

```
query itemById($storeId: String!, $itemId: String!) {
  items(storeId: $storeId, filter: {id: {equalTo: $itemId}}) {
    ... on ItemConnector {
      __typename
      nodes {
        __typename
        ...Item
        stats(storeId: $storeId) {
          __typename
          averageMonthlyConsumption
          availableStockOnHand
          availableMonthsOfStockOnHand
        }
        availableBatches(storeId: $storeId) {
          totalCount
          nodes {
            ...StockLine
          }
        }
      }
      totalCount
    }
  }
}

fragment Item on ItemNode {
  __typename
  id
  code
  name
  atcCategory
  ddd
  defaultPackSize
  doses
  isVaccine
  isVisible
  margin
  msupplyUniversalCode
  msupplyUniversalName
  outerPackSize
  strength
  type
  unitName
  volumePerOuterPack
  volumePerPack
  weight
  availableBatches(storeId: $storeId) {
    __typename
    totalCount
    nodes {
      __typename
      ...StockLine
    }
  }
  stats(storeId: $storeId) {
    __typename
    averageMonthlyConsumption
    availableStockOnHand
    availableMonthsOfStockOnHand
  }
}

fragment StockLine on StockLineNode {
  availableNumberOfPacks
  batch
  costPricePerPack
  expiryDate
  id
  itemId
  location {
    code
    id
    name
    onHold
  }
  note
  onHold
  packSize
  sellPricePerPack
  storeId
  totalNumberOfPacks
}
```
</details>

<details>
<summary>Variables</summary>

```
{
  "storeId": "F83210610D26F449BE658007114BD9FC",
  "itemId": "F2B44314EBB9D146978F96B66B5B506A"
}
```
</details>

## Expected behaviour 🤔
Should be able to see all stock lines in the OS add item modal.
Perhaps though, we should be pruning the old ones? Not displaying them?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. You will need a lot of stock lines for an item
2. Have 100 stock lines with 0 available stock, then add some with stock.
3. Try to issue this item

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by Chris-Petty** [comment]
For what it's worth, when mSupply Desktop displays the item issuing window for a CI it simply filters stock for having `>0` stock:

![image](https://user-images.githubusercontent.com/7684221/224172067-f41c39a6-ca46-4583-9b9c-1ade60f67a25.png)

https://github.com/sussol/msupply/blob/0bcf18c5d4c5df81baee6e6cc067b31e62709bf0/Project/Sources/Methods/pm_il_array.4dm#L167-L178

**Comment by mark-prins** [comment]
actually, omSupply does too. We'll need to upgrade the client to resolve, so closing this issue.
