### ISSUE TITLE
Printing: Extend the default query to have a store information

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#1319]
## What went wrong? 😲

As issue title.
For now we have a default query for invoices and others, which serves it well, It would be much better if we can extend the current default queries to give us information regarding store which probably or will be exposed most of the time in print form, Instance: Store Logo, store name etc 

## Expected behaviour 🤔

Default queries to return the information

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [1.1.4]

**Comment by bijaySussol** [comment]
@clemens-msupply : 

Created a issue as per our quick discussion.

Have anything to add in here? @clemens-msupply @mark-prins @andreievg .

**Comment by DhanyaHerath** [comment]
@andreievg @clemens-msupply to confirm whether this has been done
