### ISSUE TITLE
Open mSupply 1.1.5 : language selected is not saved when logging out and logging in again

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#1332]
## What went wrong? 😲

If I select a language different than English and then I log out of Open mSupply. When I log in again, we're back to English. This can be tricky for non English speaking users.

## Expected behaviour 🤔

For a user/site, when a language is selected within Settings in the Open mSupply interface, it should be saved until user chooses another language. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Log in to Open mSupply - the interface should be in English
2. Go to the bottom horizontal bar with the login info
3. Click on '和A - English'
4. Click on "Tetum' - The interface will shift to Tetum
5. Click on "Sai" to logout
6. Log in into Open mSupply - same store, same user
7. See error - The interface is back in English

## Your environment 🌱
 - Version 1.1.5
 - tablet and Desktop (demo website)

**Comment by mark-prins** [comment]
The language is set in mSupply - for them to be retained you have to edit the user in mSupply and set the language there.
The language switch in omSupply is temporary, and lasts for the current session only. When you login, the preferred language is taken from the mSupply user.

**Comment by Pauline-mSupply** [comment]
Ohh I see. We'll make sure to do the changes on the server then. 
However, it could be confusing for users if the settings are not configured on the server and they still have access to the settings on the interface. In all cases, this is not an urgent topic, I'll let you decide what you want to do with this issue.

**Comment by CarlosNZ** [comment]
I agree that it's confusing to have the language revert on logout. It's exacerbated by the fact that the login screen stays in the chosen language and then changes _after_ logging in again.

I would think that it wouldn't be too hard to do one of the following:
1. Prioritise the language specified in local storage over the language specified from the server's user data (and just use the server value as a default when it hasn't been specified yet) (simplest option)
2. Actually update the "language" value in the user account record when switching language.

But yes, not super high-priority :)

**Comment by andreievg** [comment]
2 would need new API, but i agree with 1. I think it would add extra support if language keeps reverting, it's probably easy to forget to configure it centrally, and then it would keep on switching and questions will be raised with support. I vote for 1

**Comment by mark-prins** [comment]
there was concern about the longevity of local storage; I agree that it's better than nothing though. 
Agree that we go ahead with (1)
