### ISSUE TITLE
omSupply doesn't send the exact version to cloud server desktop

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1339]
## What went wrong? 😲
 
If I install version 1.1.4 or 1.1.5 the version I see only the major version number 1.0 instead of the exact version (minor and patch) in the "App version" field of the sync settings window. 

omSupply
![image](https://user-images.githubusercontent.com/11624516/224837088-56861423-05c8-43a5-b7c5-132a9f2e9ba3.png)

mSupply
![image](https://user-images.githubusercontent.com/11624516/224828942-3bbe4a4b-b67d-4d95-9104-33b1e2d28d38.png)

The problem might be on the desktop side but put that issue here first to make sure that omSupply send back the right version

## Expected behaviour 🤔

Should probably for our sake what is the major, minor, patch versioning 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install omSupply 1.1.5
2. Put the site credentials and initialise
3. Go back to the cloud and in Special > Sync > your site, check the app version. See error 

## Your environment 🌱
 - Version [e.g. 1.1.4, 1.1.5]
 - Platform [e.g. tablet, desktop for the cloud server]

**Comment by andreievg** [comment]
Thanks Alain, that should be fixed with: https://github.com/openmsupply/open-msupply/pull/1305, I snuck it in there
