### ISSUE TITLE
Programs: when creating encounter from the patient view (encounters tab), you should be redirected to this view when closing the encounter view

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1342]
## What went wrong? 😲

When creating an encounter from the Patient detailed view > Encounters tab, when closing the encounter, I'm expecting to be back on the patient detailed view > Encounters tab. 

Currently, the system is redirecting you to the Encounters list menu. 

https://user-images.githubusercontent.com/74992958/224851920-f3ad8959-1450-4969-afd7-2c345336a55e.mov

## Expected behaviour 🤔

When creating an encounter from the patient detailed view's encounter tab, I should be redirected to the same page when closing the encounter detailed view and not be directed to the encounters list view. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

https://demo-open.msupply.org:88/dispensary/patients?sort=code

Dispensary > Patients > `Marla Johnson` or any other patients > Add Encounter button > Add a value and click save > click on Encounters to go back to the patient detailed view

## Your environment 🌱
 - Version 1.1.4
 - https://demo-open.msupply.org:88/dispensary/patients?sort=code

**Comment by mark-prins** [comment]
Perhaps link the patient name which is shown in the toolbar, in addition to some sort of 'back to patient' or 'save and close' button

**Comment by clemens-msupply** [comment]
This has been implemented
