### ISSUE TITLE
Placeholders lines are received in omSupply as normal shipped lines

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1347]
## What went wrong? 😲
 
In stock transfer, if the customer invoice in mSupply has placeholder lines, they are considered in omSupply as normal shipped lines.

In the example below, the supplier store has created a customer invoice for the lines requested. There was no stock on hand for one of the line so it stayed as placeholder line to be sent later.  

This is what is on the customer invoice of the supplier store
![image](https://user-images.githubusercontent.com/11624516/224864606-4791b2fd-1aef-40ff-a835-c4d3aa4661aa.png)

This is what you would see on the invoice. The place holder line is considered as not shipped.
![image](https://user-images.githubusercontent.com/11624516/224858800-b8be9792-3bb3-4141-b3a4-d5ca38628188.png)

 This is what you see on the inbound shipment
![image](https://user-images.githubusercontent.com/11624516/224859642-88a24774-8193-410b-91ba-d22bec81749c.png)

## Expected behaviour 🤔

Should probably be identified as not having been shipped in some way like colored in red and/or having the quantity set to 0 or something else

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. from omSupply create an internal order and have at least one item you know the supplier will not be to supply
2. From the supplier store fill the response requisition and create the customer invoice.
3. in the customer invoice provide the quantity requested except for the item you have no stock for. Keep the placeholder line
4. Confirm the invoice and click OK and Finalise when asked.
5. Go back and check in the omSupply your supplier invoice in Replenishment > inbound shipment. See error the line is not different for any other lines which makes you think that it will be delivered to you.

## Your environment 🌱
 - Version [e.g. 1.1.5 and 7.3.1 on Desktop]
 - Platform [e.g. tablet]

**Comment by andreievg** [comment]
Nice catch @alainsussol, thank you

**Comment by roxy-dao** [comment]
Issue has been merged
