### ISSUE TITLE
Hide doesn't clear data in documents

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1357]
## What went wrong? 😲
Hide condition doesn't clear data in documents

## Expected behaviour 🤔
Clear data if component is hidden on save... don't know if we want to clear it straight away since the user might have mistakenly pressed something

## How to Reproduce 🔨
Made a patient deceased and added the `Date of Death`, save. Then go back to patient... toggle the select off, save... then go back and toggle deceased on again. See `Date of Death` is still there.

https://user-images.githubusercontent.com/61820074/225175915-13ff2a1c-4a9e-44e4-9c84-4ff52a6face3.mov

**Comment by CarlosNZ** [comment]
Yeah, I just commented earlier on this problem to @clemens-msupply. I think it's actually a design flaw in JSON Forms. I was going to post on their discussion forum and see what their thinking is behind it, and maybe they might change it or add it as an option.

Failing that, I guess we could add some logic to our `useJsonForms` hook to do this kind of "mopping up" on each change.

**Comment by CarlosNZ** [comment]
Here: https://github.com/eclipsesource/jsonforms/issues/2118

Let's see what happens :)

**Comment by CarlosNZ** [comment]
Here -- see the response: https://github.com/eclipsesource/jsonforms/issues/2118

Makes sense I think.

If we think clearing out invisible data is important, we should probably have a discussion as to how best to approach it. I think doing some "clean-up" on submission is probably the way to go.

**Comment by CarlosNZ** [comment]
>  I think doing some "clean-up" on submission is probably the way to go.

The tricky thing is being able to access the UI state of all the elements from the top level. Does anyone know if this is already available somehow?

**Comment by roxy-dao** [comment]
> The tricky thing is being able to access the UI state of all the elements from the top level. Does anyone know if this is already available somehow?

Not that I'm aware

**Comment by clemens-msupply** [comment]
No don't know about retrieving the whole UI state...

The points from the JSONForms issue makes sense to me. Maybe we should just avoid to HIDE a control or be very careful when doing so.

Btw. another thing that could happen when hiding a control is that the whole form could indirectly becomes invalid because of the hidden control and the user has no obvious way to fix it.

**Comment by clemens-msupply** [comment]
Had another think about it, clearing the hidden data might actually be something we don't want to do. For example, if the user accidentally unchecks the "is deceased" box the "date of death" data will be lost. This might go unnoticed and just ticking the checkbox again doesn't result into the previous state.

Somewhat related, when removing an array element or clearing a select control we should actually have an undo option...

**Comment by mark-prins** [comment]
yes, agree - clearing could cause more problems than it resolves

**Comment by clemens-msupply** [comment]
I am closing the issue for now. Thanks for reporting though! I think its important that we are aware of the issue when designing the schema and UI!
