### ISSUE TITLE
Programs document endpoint

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#136]
Add endpoint that give hierarchical access to patient / program documents, e.g.

```graphql
patient {
   programs {
      encounters {
        ...
      }
   }
}
```

**Comment by andreievg** [comment]
I was thinking about this and got this far:

If we think of 'normal' patient edit for as 'General' program, I think it has some benefits for UI (but possibly too generic when adding new patient):

- unified entrypoint for all patient documents
- unified permissions for all patient documents (existing mSupply view/edit patient permissions can translate to user having 'general' program permission)

I think there are 3 operations:

1. View existing documents for patient
2. Edit existing documents for patient
3. Add an encounter type document to existing patient
4. Add a new patient (through document not linked to patient)

## 1. View existing documents for patient

For user with just general program permission in store:

```JSON
{
    "typename": "PatientNode",
    "id": "ABC",
    "name": "John Adams",
    "programs": [
        {
            "typename": "ProgramNode",
            "name": "General",
            "layout": "// if we want to display all forms/documents on one page, if forms are tabbed even within program, this is not needed",
            "documents": [
                {
                    "typename": "SimpleDocumentNode",
                    "document": "// JSON data for latest document: id, parent_id, timestamp, json, etc..",
                    "jsonSchema": "// This is the latest form schema for document type",
                    "//": "name is just to show above the form",
                    "formName": "General Patient Information",
                    "formSchema": "// This is the latest form schema for document type"
                }
            ]
        }
    ]
}
```

For user with General and Program 1 permission

```JSON
{
    "typename": "PatientNode",
    "id": "ABC",
    "name": "John Adams",
    "programs": [
        {
            "typename": "ProgramNode",
            "name": "General",
            "layout": "// if we want to display all forms/documents on one page, if forms are tabbed even within program, this is not needed",
            "documents": [
                {
                    "typename": "SimpleDocumentNode",
                    "document": "// optional (some program documents may not exist yet) JSON data for latest document: id, timestamp, json, etc..",
                    "jsonSchema": "// This is the latest form schema for document type",
                    "//": "name is just to show above the form",
                    "formName": "General Patient Information",
                    "documentType": "// named type of document, similar to form name",
                    "formSchema": "// This is the latest form schema for document type"
                }
            ]
        },
        {
            "typename": "ProgramNode",
            "name": "Program 1",
            "layout": "...",
            "documents": [
                {
                    "typename": "SimpleDocumentNode",
                    "document": "// optional (some program documents may not exist) JSON data for latest document: id, timestamp, json, etc..",
                    "jsonSchema": "// This is the latest form schema for document type",
                    "formName": "HIV patient information",
                    "documentType": "// named type of document, similar to form name",
                    "formSchema": "// This is the latest form schema for document type"
                },
                {
                    "typename": "EncounterDocumentNode",
                    "//": "Notice, encounter/tracked node has array of documents",
                    "documents":[
                        { "//": "JSON data for latest document: id, timestamp, json, etc.." },
                        { "//": "JSON data for latest document: id, timestamp, json, etc.." }
                        { "//": "When encounters are edited, should use existing schema/form linked to the encounter instance" }
                    ],
                    "jsonSchema": "// This is the latest form schema for document type, used for adding new document",
                    "formName": "HIV Patient Encounter",
                    "formSchema": "// This is the latest form schema for document type, used for adding new document"
                }
            ]
        }
    ]
}
```

## 2. Edit existing documents for patient
## 3. Add an encounter type document to existing patient

After getting data from `1. View existing documents for patient`. Can update with this mutation

`insertNewDocumentVersion`:

**input**

```JSON
{
    "patientId": "// optional (if adding new document patient)  id of patient",
    "document": {
        "parentId": " optional (if adding new document) id of existing document",
        "schemaId": "schemaId from existing document",
        "formSchemaId": "formSchemaId from existing document",
        "data": "JSON blob for new document version"
    }
}
```

patientID must be present unless parentID is not present and this document type can create patient

4. Add a new patient (through document not linked to patient)

Above mutation can be used, but we need to query for 'new patient document'

`newPatientDocument`:

```JSON
{
    "typename": "SimpleDocumentNode",
    "document": "// optional (some program documents may not exist yet) JSON data for latest document: id, timestamp, json, etc..",
    "jsonSchema": "// This is the latest form schema for document type",
    "//": "name is just to show above the form",
    "formName": "General Patient Information",
    "documentType": "// named type of document, similar to form name",
    "formSchema": "// This is the latest form schema for document type"
}
```

**Comment by clemens-msupply** [comment]
Thanks

There is already an `update_document` endpoint for inserting/updating a document. I think what is missing is a "update_patient_document" endpoint which has some business logic checks, e.g. that there are not two of the same programs for the same patient. This endpoint can also have the trigger logic for special documents like Patient or Encounters. (update_document endpoint could probably removed though)

For `formName` we need to add a field to the form_schema table. Alternatively we could use the title from the json schema but this might lead to translation issues...

Could you explain a bit more about `layout`?  The document layout can be encoded in the JsonForms ui schema. Or do you mean the overall layout? (didn't plan to make this customizable)

**Comment by andreievg** [comment]
> Could you explain a bit more about layout?

Just in case we need to control how forms are position (I don't really know how multiple document types for a program will be displayed), probably wont' end up using it if f/e has generic way to lay things out with like tabs if there are multiple encounters available.

> For formName we need to add a field to the form_schema table. Alternatively we could use the title from the json schema but this might lead to translation issues...

Sure, just thought to mention, the comment was mainly to try and see what types of queries/mutations we would need and where they should be fitted in existing schema (for ease of consumption)

>  that there are not two of the same programs for the same patient

If you mean having two documents for the same document_type with no parent_ids for the same patient, I don't really see this being a problem (and it's something that we can't really avoid with sync), but yeah adding an extra guard would probably help to protect against erroneous front end operations.

> This endpoint can also have the trigger logic for special documents like Patient or Encounters. (update_document endpoint could probably removed though)

What special logic would encounters have ?

> There is already an update_document endpoint for inserting/updating a document. I think what is missing is a "update_patient_document" endpoint which has some business logic checks, e.g. that there are not two of the same

I want to back track on my comment, and explicitly seperate `insert` and `update` document (rather than optionals determining if it's an insert or update).

And also having `insertPatient` as a seperate end point would be great.

I think at the end the following (btw i am using :

query `newPatientDocument` -> to get the schemas to use for new patient
mutation `insertPatient` -> only document mutation where patientId is not present
mutation `updateDocument` -> no optionals (parentId and patientId must be present)
mutation `insertDocument` -> does not pave parentId (used for new encounter or new program documents)
query `patient` -> to get existing status of all patient documents

**Comment by clemens-msupply** [comment]
Main point of this issues have been addressed
