### ISSUE TITLE
Encounter status changes

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1360]
Encounter statues are not really handled right now and need to be updated in the data model as well as in the UI.

### Data model

- [x] Update the possible encounter statuses to:

- `Pending`
- `Canceled`
- `Visited`

- [x] An encounter always has to have a status set and the default status is `Pending`

From this statuses we can derive a "dynamic" status value as following:
- [ ] if the status is `Pending` and the encounter start datetime is in the past the dynamic display status is `Missed`
- [ ] if the status is `Pending` and the encounter start datetime is in the future (or close to `now`) the dynamic display status is `Scheduled`
- [x] Canceled just mean Canceled

### Encounter UI

A user must be able to change the encounter status in the UI

- [ ] add a dropdown in the header to update the status in the header

Use the same `Missed` and `Schedule` logic to change the status to pending depending on if the encounter is in the past or in the future:

- [ ] if the encounter is in the past and has status `Canceled` or `Visited` the user can select `Missed` to internally change the status to `Pending`
- [ ] if the encounter is in the future and has status `Canceled` or `Visited` the user can select `Scheduled` to change the status to `Pending`
- [ ] Prevent users to change status to `Visited` when the encounter is in the future (?)

- [ ] If the Encounter is in the past show a warning show to the user (?)

### Encounter Report Arguments
- [x] update report arguments to work with the new statues (might need a specialized control)

**Comment by richardmoizeau** [comment]
just tagging @roxy-dao, @CarlosNZ, @mark-prins and @andreievg to have a bigger crowd on this topic. 

What Clemens and I are trying to do in just a few words (sorry @clemens-msupply if I repeat what you already said!)

In their current solution, our customer has one transaction for medical visits (encounters) and another to create appointments. Appointments and visits are 2 separate things. We would like to have only one transactions on the following simple logic: an encounter with a date in the future is an appointment, anything else is a "visited" encounter

Now regarding statuses for encounters, the idea was to make something simple, 2 statuses to indicate if the encounters is an **appointment** or an already done/visited/completed **visit**.  Something like: `Scheduled` > `Visited` (and `Cancelled` when an appointment is cancelled). 

So technically, user has 2 options when creating an encounter: 

1. Create an appointment (a scheduled encounter).  

- [ ] In contrast to an ad hoc visit, the user only wants to enter the header data for an appointment. It is therefore not necessary to open the encounter window. This means that user must indicate in the new encounter modal that this is an appointment. An `Appointment ?` check box ?
- [ ] An appointment could be a read-only document until the encounter is confirmed as `Visited` (similar to the inbound shipment before it is confirmed as `Delivered`)
- [ ] when the patient arrives for an appointment, the user must be able to confirm that the visit has started or that it has taken place (currently, the data is entered by a data clerk after the visits are completed). We thought of adding a dropdown in the headers but we could do the same as what we've done for shipments. 
- [ ] an appointment with a date in the past should be flagged as late, missed, overdue (show it in red ? show the word "missed" in red the encounter status column ? 
- [ ] you can cancel an appointment. Same as for the "missed" flag ? (see the below beautiful 1st mockup) or we could use a check box at the bottom left corner (similar to Outbound Shipment, 2nd screenshot)

![Screen Shot 2023-03-16 at 10 51 46 AM](https://user-images.githubusercontent.com/74992958/225452838-1829cbb3-3447-41b2-b95d-8664f9b3a850.png)

![Screen Shot 2023-03-16 at 11 02 02 AM](https://user-images.githubusercontent.com/74992958/225453734-84c56315-1dfa-462d-9bca-82a588744844.png)


2. Create an ad hoc visit (that already happened or is about to start)

- [ ] unlike when creating an appointment, the user wants to enter the encounter data right away. So the window should open when the encounter is created.
- [ ] Status should be `Visited` by default. Cannot be cancelled.

**Comment by richardmoizeau** [comment]
on another note, we need to find the right words:

- status for an appointment: scheduled / planned / pending / not visited / ???
- status for a completed encounter: done / completed / visited / finalised / ???

**Comment by richardmoizeau** [comment]
@adamdewey, you may want to have a look at this, since this would potentially be the same for an electronic immunisation registry.

**Comment by mark-prins** [comment]
Sounds good - thanks @richardmoizeau 
I think it sensible to have a single encounter item, which has the status updated rather than using two distinct 'things'

> you can cancel an appointment: could use the bottom left corner checkbox

or add an action button, bottom right ( makes more sense to me ) or a button top right.
The checkbox is used for changing the state of the current item; as we cannot un-cancel I don't think it is appropriate here.

> on another note, we need to find the right words:

My 2 cents:

- appointments: scheduled
- encounter: completed
- cancelled

**Comment by adamdewey** [comment]
Just to play devil's advocate... 

Is there an advantage in having both a change in name _and_ status? 

E.g. would the following be simpler?

- encounter: scheduled
- encounter: completed
- encounter: cancelled

I guess the point of confusion would be if the patient is ever interacting with the system as the lay terminology would likely be 'appointment' but if the internal user is aware that 'encounter: scheduled' is equivalent to 'appointment' then it might not be necessary to have both terms in the system?

**Comment by clemens-msupply** [comment]
Yes it should IMHO be one name, e.g. encounter. Similarly, the idea is to have one "Pending" status instead of "Scheduled" and "Missed". The reason is that if you have these additional statues you have to set them somehow, e.g. manually or automatically. Just having "Pending" solves this, you just have to interpret it based on some heuristic, i.e. if the encounter is in the past ("Missed") or in the future ("Scheduled").

**Comment by clemens-msupply** [comment]
The core encounter changes have been implemented. Further required UI changes regarding the "logical" encounter status are listed #1575
