### ISSUE TITLE
Programs: wrong label / name for the programs

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1367]
## What went wrong? 😲
 

encounter list: 
![Screen Shot 2023-03-16 at 1 10 36 PM](https://user-images.githubusercontent.com/74992958/225475510-d0d2513c-6753-4822-8867-a5ca48d56b70.png)

encounter detailed view's headers: 
![Screen Shot 2023-03-16 at 1 10 05 PM](https://user-images.githubusercontent.com/74992958/225475412-4898584b-c1b1-4ded-852b-bd96a61ee8fd.png)

## Expected behaviour 🤔

correct label for programs should be:

`HIV Care & Treatment` instead of `HIVCareProgram`
`HIV Testing & Counselling` instead of `HIVTestingProgram`

**Comment by roxy-dao** [comment]
Reopen https://github.com/openmsupply/open-msupply/pull/1406#issuecomment-1482001365
