### ISSUE TITLE
When filtering an item in internal order, the leading 0 are removed.

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1368]
## What went wrong? 😲
 
When trying to filter items showing in the internal order, the leading 0 are removed automatically from your filter. It is not a big thing but would be useful for refining search

https://drive.google.com/file/d/1ajrp7CuBo0QcjK8qEADGuP9pxsTOOQ9F/view?usp=share_link

## Expected behaviour 🤔
I think we should keep the leading 0 to refine search. Also when adding an item to an internal order the leading 0 is kept when filtering.

It is keeping leading 0 when filtering to add an item.
https://drive.google.com/file/d/1zHd-o75-coD2m03enjmicKfkHcA2BUFU/view?usp=sharing

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an internal order
2. Click on 'add from master_list'
3. Go the filter field and type 06
4. See error. The 0 is removed from the filter and you see only '6'.

## Your environment 🌱
 - Version [e.g. 1.1.5]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by CarlosNZ** [comment]
Ah, I think this is a problem with the `useUrlQuery` hook in that it converts the value to a number if it can. Just need to add the `skipParse` prop to the hook call, I think. Should be an easy fix.
