### ISSUE TITLE
Programs > Encounters list: change the name of the Encounter Status column to Additional Info

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1377]
Change the name of the column `Encounter Status` to `Additional Info`

<img width="1339" alt="Screen Shot 2023-03-17 at 2 29 27 PM" src="https://user-images.githubusercontent.com/74992958/225789220-53cadfc9-a5bb-4cd3-bdae-d41e954ff694.png">

**Comment by roxy-dao** [comment]
Duplicate of #1378
