### ISSUE TITLE
Location modal looks a bit weird

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1382]
## What went wrong? 😲

<img width="623" alt="Screen Shot 2023-03-20 at 11 31 54 AM" src="https://user-images.githubusercontent.com/74992958/226213934-a30cef68-503c-4c5f-9137-45b0d2d0753d.png">

## Expected behaviour 🤔

<img width="632" alt="Screen Shot 2023-03-20 at 11 34 41 AM" src="https://user-images.githubusercontent.com/74992958/226213996-4705ea48-b965-4b49-abea-c9b44f9ba248.png">

**Comment by mark-prins** [comment]
oops! that's likely the JSON forms alignment changes

**Comment by mark-prins** [comment]
much better!
Could the input fields be full width? would that look ok?

**Comment by bijaySussol** [comment]
> much better! Could the input fields be full width? would that look ok?
This is how it looking @mark-prins @richardmoizeau 

<img width="499" alt="Screen Shot 2023-04-19 at 12 28 55 PM" src="https://user-images.githubusercontent.com/13144882/232991104-0df98c1c-2f9a-4b95-83c3-b335103973da.png">
