### ISSUE TITLE
data in the requisition modal are not making sense

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1386]
## What went wrong? 😲

On the requisition line, I can see that I suggested quantity = 28
![226216221-0eef534e-ee6e-4a97-94f5-62768dbe29fd](https://user-images.githubusercontent.com/26194949/231039769-aac69918-21a4-4ccc-bfa0-2e7493bea8d8.png)

However when opening the modal, suggested qty = 0 and the charts is not making sense: 

![226216257-d683dd0b-2933-4525-b33a-fa443de50b35](https://user-images.githubusercontent.com/26194949/231039795-2d386364-80a3-43a6-90ba-a6274ab40ac6.png)

## Expected behaviour 🤔

I should see the correct data in the in modal and charts should behave correctly. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version 1.1.4
 - [Platform](https://demo-open.msupply.org/dashboard)

**Comment by richardmoizeau** [comment]
suggested quantity and modal was correct until I changed the Max MOS

**Comment by roxy-dao** [comment]
Suggested quantity only shows above 0 if you use more than what you currently have 🤔 
Don't think this is a bug....
What do you think? @mark-prins

**Comment by DhanyaHerath** [comment]
@roxy-dao Oh, not sure what you mean - shouldn't it match what is shown in the listbox?
