### ISSUE TITLE
2 item_lines for the same product created on omSupply or cloud server for only one received 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1401]
## What went wrong? 😲
 
Created an internal order for 50 TB Clofazimine 100mg tabs to a supplier store on mobile (8.0.8).
Mobile received the order and supply 50 TB Clofazimine 100mg tabs from a stock line which the GlobalFund as donor
omSupply received the shipment and verified it without making any changes. Checking the stock I find 2 stock_lines similar except that one has the donor (not related to any invoice) and the other does not have the donor but is related to the right invoice.

Ledger on cloud for the item on omSupply store 
![image](https://user-images.githubusercontent.com/11624516/226793469-655f88b0-a088-4d31-8624-21851813e245.png)

Stock_line for the same item on that store. There should be only one
![image](https://user-images.githubusercontent.com/11624516/226793847-b07a89f7-b075-49f9-a2cb-ebbc06d344fd.png)

the first item line is not related to any invoice 
![image](https://user-images.githubusercontent.com/11624516/226794398-02dd9754-4770-484b-bcb3-ba587f9ec5cc.png)

but the second one is
![image](https://user-images.githubusercontent.com/11624516/226794813-dd6dc0ab-e3c9-4990-8b93-afc2df840dc3.png)

Supplier store ledger on cloud. Send transfer of 50 packs to the omSupply store.
![image](https://user-images.githubusercontent.com/11624516/226799510-f47f2b17-683c-4541-b7d0-99f19854e11b.png)

customer invoice of the supplier store on mobile
![image](https://user-images.githubusercontent.com/11624516/226800091-eca3a025-d6db-4e95-84b0-555977bc0ec1.png)

Shipment received on omSupply
![image](https://user-images.githubusercontent.com/11624516/226800931-46e0684b-6de0-4cfb-ba7c-ae5155cb9ba9.png)

Stock on hand on omSupply. there should be only one line
![image](https://user-images.githubusercontent.com/11624516/226800636-a37f423f-b587-485d-9b8b-0ab0edb30e2f.png)

I made another try for the same item with the same stores and this time only one item was created. So it might be a fluke but I wanted to put out it there...
Might try again tomorrow

## Expected behaviour 🤔
I would assume that only one stock_line

## How to Reproduce 🔨

Steps to reproduce the behaviour:
I am not sure yet

## Your environment 🌱
 - Version [e.g. 1.1.6]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by roxy-dao** [comment]
Can't seem to reproduce this with omSupply internal order to central store, then central store sends invoice to omSupply store -> verified invoice

![photo_2023-04-21 13 55 14](https://user-images.githubusercontent.com/61820074/233522404-cd01755b-1bac-4439-8da6-0dc639644911.jpeg)
<img width="1181" alt="Screenshot 2023-04-21 at 1 56 24 PM" src="https://user-images.githubusercontent.com/61820074/233522511-01fcdf7d-c7e9-44ed-96bd-10327e972522.png">

**Comment by alainsussol** [comment]
Thanks @roxy-dao

I was not able to reproduced myself. Should I close this for now ?

**Comment by mark-prins** [comment]
I was trying also - and haven't reproduced 🤷

**Comment by roxy-dao** [comment]
> Thanks @roxy-dao
> 
> I was not able to reproduced myself. Should I close this for now ?

We can close for now and reopen if it does happen again...
