### ISSUE TITLE
Disable buttons on patient creation

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1405]
## Is your feature request related to a problem? Please describe 👀
If a user tries to click `Add Program` or `History` while creating a patient it might result in an error or incorrect information

## Describe the solution you'd like 🎁
Disable buttons except for `Cancel` and `Create` when creating a patient

### Moneyworks Jobcode 🧰
PG23THDVD

**Comment by sanijcreates** [comment]
Hello, I am a first-time contributor and would like to work on this issue!

**Comment by mark-prins** [comment]
Welcome @sanijcreates! Great that you're interested - and sorry it's taken some time to get back to you 😱 

For some general guidelines, check out our [contributing](https://github.com/openmsupply/open-msupply/blob/main/CONTRIBUTING.md) doc.

To get started with this issue, you'll need to be working with the react app. After cloning the repo, head over to the [client readme](https://github.com/openmsupply/open-msupply/blob/main/client/README.md) which walks you through getting set up. Let me know if you need some help!

**Comment by clemens-msupply** [comment]
Sorry @sanijcreates hope you haven't worked on it too much yet. I independently ran into it and quickly fixed it...
