### ISSUE TITLE
Outbound shipment created for the wrong supplier

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1412]
## What went wrong? 😲
 
As title. Received customer requisition from store "Alain Remote mobile store" but the shipment was created for Activestoreforsite1
I have added an extra item on the shipment. 

Here is the customer requisition

![image](https://user-images.githubusercontent.com/11624516/227096214-9e3bfd1c-fa66-4ee2-9020-336871a72b30.png)

the outbound shipment
![image](https://user-images.githubusercontent.com/11624516/227097079-aef2c9bf-e4a8-44ce-a89d-4907f4338ba2.png)

All the other tests I did worked fine. I will do more investigation on Monday.

## Expected behaviour 🤔

Should probably have the same customer between the requisition and the outbound shipment
## How to Reproduce 🔨

Steps to reproduce the behaviour:
I am not sure
1. Create an internal order for the omSupply store
2. on omSupply store, supply the items quantity requested 
3. Create a shipment for that requisition and add an extra item
4. Send the shipment. See error that the supplier invoice was not created in the store of the requisition customer
5. in omSupply, look back at the supplier of the shipment and you will see that it is not the same as the one in the requisition

## Your environment 🌱
 - Version [e.g. 1.1.6]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by DhanyaHerath** [comment]
@alainsussol this was testing on a tablet, right?

**Comment by alainsussol** [comment]
@DhanyaHerath Yes

**Comment by alainsussol** [comment]
@DhanyaHerath Did somebody was able to replicate? I didn't had time to investigate yet.

**Comment by mark-prins** [comment]
I've been trying today and cannot replicate.
Will close for now and reopen if it surfaces again.
