### ISSUE TITLE
Not error message for empty note

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1420]
When adding a new note to a patient but not entering any text the save button stays disabled, e.g.:
1) create note
2) `tab` to the next control
3) no error indication is shown

![Image](https://user-images.githubusercontent.com/88299195/227800075-7d936890-d7d8-4bf3-b122-0bc67db65d51.png)

**Comment by CarlosNZ** [comment]
> When adding a new note to a patient but not entering any text the save button stays disabled

What do you think the behaviour should be?

If you make an empty note, nothing is changed in the `data` object, so it doesn't register as a change. This seems reasonable to me -- why would we want empty notes to be saved?

We could possibly show an error state if you lose focus on a note with nothing in it, but that would just be internal to the component -- I'd be reluctant to actually change anything in the overall `data` (and affect the state of the Save button)

**Comment by clemens-msupply** [comment]
In this particular case we added notes and drug allergies and then the save button was disabled. We couldn't figure out why but fixed it by removing all entries again...

Not saving an empty note makes sense to me as well. So not adding the note to the data if it is empty would fixes it. Only drawback is that we would have to remember if the note is new or if we are editing an existing note.

Alternative would be to highlight the empty note.

**Comment by CarlosNZ** [comment]
> In this particular case we added notes and drug allergies and then the save button was disabled. We couldn't figure out why but fixed it by removing all entries again...

Oh I see the bug -- after leaving an empty note then changing *anything* else won't enable the "Save" button until you remove the empty note!

Okay, that definitely needs a fix.

**Comment by CarlosNZ** [comment]
> Not saving an empty note makes sense to me as well.

This is tricky, for the same kind of reason as [this issue](https://github.com/openmsupply/open-msupply/issues/1110) -- the parent array wrapper inserts an empty object in the data array when first creating the note, and the child note has no way to tell the parent not to consider this as part of its data (it can't, as it's the data array that is mapped over to show the notes!)

A possible solution would be to change the "addItem" method for Array wrappers to not actually insert an item into the data array, but create a temporary "unsaved" item that we insert into the mapped data for display only (i.e. we show `[...data.map((child)=>{renderChild}, tempItem]` and only *really* "add" the item once it's valid).

But that seems quite complicated and quite a lot of work to make it work elegantly.

> Alternative would be to highlight the empty note.

@clemens-msupply do you think a red border is enough of an indication of an empty note?
![Screenshot 2023-03-29 at 11 13 30 AM](https://user-images.githubusercontent.com/5456533/228378377-629420bf-ed85-402f-a041-e7289140d7a0.png)

**Comment by clemens-msupply** [comment]
Yes think that would definitely help!

**Comment by CarlosNZ** [comment]
Closed by #1477
