### ISSUE TITLE
Dependency update f/e

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1442]
## Is your feature request related to a problem? Please describe 👀

The ongoing saga of deps. The upgrade has just finished and the next round are ready to be upgraded. 
I'd like to have this as a more regular task to constrain the scope of the job. Hopefully we'll only have one major issue per upgrade if we keep on top of it.

## Describe the solution you'd like 🎁

# Major
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @mui/x-date-pickers | 5.0.20 | 5.0.20 | 6.0.3 | openmsupply-client | dependencies | https://mui.com/x/react-date-pickers/ |  |

# Minor
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @electron-forge/cli | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-deb | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-rpm | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-squirrel | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-zip | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/plugin-webpack | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @testing-library/dom | 9.0.1 | 9.2.0 | 9.2.0 | openmsupply-client | devDependencies | https://github.com/testing-library/dom-testing-library#readme |  |
| @typescript-eslint/eslint-plugin | 5.55.0 | 5.57.0 | 5.57.0 | openmsupply-client | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/eslint-plugin | 5.55.0 | 5.57.0 | 5.57.0 | @openmsupply-client/electron | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/parser | 5.55.0 | 5.57.0 | 5.57.0 | openmsupply-client | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/parser | 5.55.0 | 5.57.0 | 5.57.0 | @openmsupply-client/electron | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| electron | 23.1.4 | 23.2.0 | 23.2.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/electron#readme |  |
| eslint | 8.36.0 | 8.37.0 | 8.37.0 | openmsupply-client | devDependencies | https://eslint.org |  |
| eslint | 8.36.0 | 8.37.0 | 8.37.0 | @openmsupply-client/electron | devDependencies | https://eslint.org |  |
| lerna | 6.5.1 | 6.6.1 | 6.6.1 | openmsupply-client | dependencies | https://lerna.js.org |  |
| msw | 1.1.0 | 1.1.0 | 1.2.1 | openmsupply-client | dependencies | https://mswjs.io |  |
| webpack-dev-server | 4.12.0 | 4.13.1 | 4.13.1 | @openmsupply-client/host | devDependencies | https://github.com/webpack/webpack-dev-server#readme |  |

# Patch
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @graphql-codegen/typescript-graphql-request | 4.5.8 | 4.5.9 | 4.5.9 | openmsupply-client | devDependencies | https://github.com/dotansimha/graphql-code-generator-community#readme |  |
| @mui/material | 5.11.13 | 5.11.15 | 5.11.15 | @openmsupply-client/common | dependencies | https://mui.com/material-ui/getting-started/overview/ |  |
| @swc/core | 1.3.40 | 1.3.42 | 1.3.42 | openmsupply-client | devDependencies | https://swc.rs |  |
| @types/lodash | 4.14.191 | 4.14.192 | 4.14.192 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash |  |
| @types/node | 18.15.3 | 18.15.11 | 18.15.11 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node |  |
| @types/react | 18.0.28 | 18.0.31 | 18.0.31 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react |  |
| i18next | 22.4.11 | 22.4.13 | 22.4.13 | @openmsupply-client/common | dependencies | https://www.i18next.com |  |
| papaparse | 5.4.0 | 5.4.1 | 5.4.1 | openmsupply-client | dependencies | http://papaparse.com |  |
| prettier | 2.8.6 | 2.8.7 | 2.8.7 | openmsupply-client | devDependencies | https://prettier.io |  |
| webpack | 5.76.2 | 5.76.3 | 5.76.3 | openmsupply-client | devDependencies | https://github.com/webpack/webpack |  |
| webpack | 5.76.2 | 5.76.3 | 5.76.3 | @openmsupply-client/host | devDependencies | https://github.com/webpack/webpack |  |

**Comment by mark-prins** [comment]
I wasn't going to do the date pickers! 😆 I thought we could do mui and the date pickers at the same time.. just not right now.

Have done the minor and patch, and then stopped on storybook & electron, to sort out some issues with them.

**Comment by CarlosNZ** [comment]
> I thought we could do mui and the date pickers at the same time.

Is that because the date pickers are now part of the main package and no longer "experimental"?

**Comment by mark-prins** [comment]
yeah - we can drop the experimental package! 😁
