### ISSUE TITLE
Repack - UI

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1443]
This issue may need to be done in parts, there is rough design for this in Epic: https://github.com/openmsupply/open-msupply/issues/694, would require Priority 1 API

Add new tab to stock info, `Repack`

New tab will have a new entry for repack with the following enterable fields:

Number of Packs to Repack 
New Pack Size
New Location 

And the following info fields:

Pack Size
Location (original)
New Number of Packs
Number of Packs (total number of packs now).

There should be a button to save this and validation:
* Resulting pack is not `whole` pack (this is both for consolidation and for split, when result is a fraction of original or new pack)
* Other validation can be enforced in data entry ? (like new number of packs > number of packs), negative values etc..

### Job code 
OMS:REPAC

**Comment by roxy-dao** [comment]
Mock up 2

![image](https://github.com/openmsupply/open-msupply/assets/61820074/75f1e77b-de59-47d3-a267-899aa1cb0bc9)

**Comment by roxy-dao** [comment]
> Mock up 2 (Two options)
> 
> ![image](https://user-images.githubusercontent.com/61820074/241075830-75f1e77b-de59-47d3-a267-899aa1cb0bc9.png)

Option 3 from Mark: 
1. remove the current onclick from the table rows which opens the modal
2. add a 'select' state to the table, when you click a row, it is selected
3. have two buttons up in the appbar area for 'edit' and 'repack'
