### ISSUE TITLE
Patient Encounters View: Program and Program Status does not update on first load

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1454]
## Is your feature request related to a problem? Please describe 👀
- Program name doesn't update in patient encounter's view on load, but does update if you switch tabs and switch back. 
- Same goes for program status
- Noted in https://github.com/openmsupply/open-msupply/pull/1438#pullrequestreview-1361911790

## Describe the solution you'd like 🎁
Should update straight away

### Moneyworks Jobcode 🧰
PG23THDVD

**Comment by roxy-dao** [comment]
Seems to work now. Can someone else check and have this close if it is working?

**Comment by CarlosNZ** [comment]
Yeah, looks okay to me 👍

**Comment by mark-prins** [comment]
working fine for me too!
