### ISSUE TITLE
Update Note data structure and controls

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1463]
While importing data it became apparent that some of the required note fields are not available. Thus only make the Note text required.

**Comment by CarlosNZ** [comment]
Do you just mean in the schema? If so, can I do this as part of #1420 as that will make it easier if this is already in place.

I'll update the schema as part of #1420 anyway, so please close this issue or assign me, unless of course the scope is wider than just changing the schema?

**Comment by clemens-msupply** [comment]
Ok suspected it would require some changes in the controls, e.g. in my local branch I made the creation date optional because it is unknown when the note has been written for imported data... I will leave it open for now and try to merge in your schema changes!

**Comment by CarlosNZ** [comment]
Just FYI -- I didn't end up changing anything related to this in #1420.
