### ISSUE TITLE
Can create Encounter for a program which the patient isn't enrolled in

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1467]
## Is your feature request related to a problem? Please describe 👀
User may still want to create new encounters for programs that are no longer active. 

## Describe the solution you'd like 🎁
Display a message to let the user know that the patient isn't enrolled in any programs.

### Describe alternatives you've considered 💭
Leave as is 🤷🏻

**Comment by mark-prins** [comment]
I enrolled a patient in a program. 
Can then create an an encounter.

Edit the program enrolment - change status to 'opted out'
Try to create an encounter: 

<img width="751" alt="image" src="https://user-images.githubusercontent.com/9192912/229397928-3afc81bf-782f-40ec-9103-415c475c146d.png">

Question is - should the encounter button be active in this case? Should check the status of program enrolments when determining if the button is enabled

**Comment by roxy-dao** [comment]
Will need to change that too... 
Use case: Patient isn't actively enrolled in a program but user still wishes to create a new encounter for them (maybe a past encounter that has yet to be entered?)
Think having a message displayed if a patient isn't enrolled in any programs at all would be the way to go 🤔
