### ISSUE TITLE
Sync badge shouldn't show if there are no records to sync

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1469]
## What went wrong? 😲
![Screen Shot 2023-03-31 at 12 27 42 PM](https://user-images.githubusercontent.com/61820074/228994836-7221ec7f-aca7-4bd5-8a72-ab2489cf7cc2.png)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by mark-prins** [comment]
thanks! I spotted this one too.. and was going to raise an issue 😉

**Comment by roxy-dao** [comment]
Reopening since I'm still getting this on the current develop branch...

**Comment by mark-prins** [comment]
unable to replicate - spent a while looking and cannot get it to happen.
adding 'blocked' until it can be reproduced

**Comment by roxy-dao** [comment]
Strange... cleared cache, used chrome and firefox to test and it still shows up with 0 on the badge 👀

**Comment by CarlosNZ** [comment]
> Strange... cleared cache, used chrome and firefox to test and it still shows up with 0 on the badge 👀

Can you save a snapshot of your database to see if anyone else can replicate?
