### ISSUE TITLE
Unable to enrol into testing program

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1470]
Can't enroll a patient into the testing program (most likely because there is no control for the now require program status).

Possible solution: make the program status optional and interpret a missing status as 'Active'?  (to be discussed in next catchup)

**Comment by richardmoizeau** [comment]
could we remove the Patient ID field from the enrolment form for the HIV Testing & Counselling workflow ?

**Comment by roxy-dao** [comment]
Make this field default (Active) for all enrolments (still a required field) and allow the user to change the status
