### ISSUE TITLE
Programs: add a column "Additional Info" to the Patients/Programs view

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1473]
## Describe the solution you'd like 🎁

Patients > Programs tab > list of programs of the patient

<img width="1350" alt="Screen Shot 2023-03-31 at 4 39 21 PM" src="https://user-images.githubusercontent.com/74992958/229017082-a5204732-186d-47ab-96bb-d023fea58929.png">

Add the following flags, automatically calculated based on when the patient runs out of ARV (@clemens-msupply)
- Missed Appointment (once patient has run out of medicines)
- Early LTFU (once patient has run out of medicines + 28 days)
- LTFU (once patient has run out of medicines + 90 days)

### Moneyworks Jobcode 🧰

PG23THDVD

**Comment by richardmoizeau** [comment]
@Clemens, for "Missed Appointment", during our meeting you said that you were already calculating this label as describe above ? If not I can create an issue but basically the idea is when patient runs out of medicines, patient = Missed Appointment

**Comment by roxy-dao** [comment]
> * LTFU (once patient has run out of medicines + 90 days)

Missed appointment is currently calculated by current date > appointment time.

**Comment by clemens-msupply** [comment]
> > * LTFU (once patient has run out of medicines + 90 days)
> 
> Missed appointment is currently calculated by current date > appointment time.

This is a different Missed :) Richard and I already briefly talked about it that this might be confusing...
