### ISSUE TITLE
Programs: remove Program status column from Encounters list view

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1474]
Sorry about the confusion (my bad) but could you remove the "Program Status" column ? 

Dispensary > Encounters > list of encounters

<img width="1431" alt="Screen Shot 2023-03-31 at 4 49 10 PM" src="https://user-images.githubusercontent.com/74992958/229018117-56328e33-5f72-48cd-8f8a-9906e2840dc8.png">

**Comment by CarlosNZ** [comment]
Closed by #1490
