### ISSUE TITLE
Drop down for `Clinic Transferred From` in HCT Enrolment 

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1479]
## Is your feature request related to a problem? Please describe 👀

Clinic Transferred From: should be a drop-down

## Describe the solution you'd like 🎁
- Change this from a text field to autocomplete

### Additional context 💌
Needs to be discussed with client since they have not provided us with a list of the options yet

### Moneyworks Jobcode 🧰
PG23THDVD

**Comment by DhanyaHerath** [comment]
@clemens-msupply to check with Richard

**Comment by clemens-msupply** [comment]
Just checked the field is a text input in the client software. So it's ok to leave it as it.
