### ISSUE TITLE
Error while accessing Stocktakes in oms/programs

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1492]
## What went wrong? 😲
This is happening ONLY in `oms/programs` branch. Click stocktakes, you'll see the error below

## Expected behaviour 🤔
I wouldn't expect such random errors out of nowhere!

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get local oms-setup from `oms/programs` feature branch
2. Click Inventory>>Stocktakes
3. See error:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/59193490/229700866-1131b0aa-3ce8-417e-819f-ad7a921b0df8.png">

## Your environment 🌱
 - Version: mSupply Server on v7-04-00-beta20 with a remote-server in`oms/programs` feature branch
 - Platform: Error is on browser

**Comment by mark-prins** [comment]
checked on `feature/programs` and is still an issue
