### ISSUE TITLE
Remove `event` from Activity Log and add a `from` and `to` field for better translatability

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1493]
## Is your feature request related to a problem? Please describe 👀
The events for stock activity logs are currently hard coded in English in the backend.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/9192912/234727847-8f4e1b9a-2145-4dd7-adbf-e0b4d5ec2aa1.png">

We would also like to log sensor location changes from `location a` to `location b` and there will probably be more use cases for this in the future too, so nice to have it done now.

## Describe the solution you'd like 🎁
- [ ] Add a `from` and `to ` field to `activity_log`.
- [ ] Migrate current `events` column data to new `from` field. 
- [ ] Remove `events` column from `activity_log`
- [ ] Rename `activity_log_stock_entry` to be more generic and refactor.
- [ ] Refactor frontend to apply above changes

### Describe alternatives you've considered 💭
Using emojis 🍡

**Comment by Chris-Petty** [comment]
Not familiar if there is an ongoing logging story in omSupply but want to write somewhere that directus has a pretty good and comprehensive structure to logging.

They have a revision table which records which table (`collection`) and record (`item`) by ID, along with the new version of the record. `Data` is the new version I believe, `delta` is the fields that were changed (could be old version and delta new values, not sure. Same same.). It's linked to a user via `activity`. `parent` is naturally a link to the last revision (I think):
![image](https://github.com/openmsupply/open-msupply/assets/7684221/765698ce-2f48-4205-ae93-68767132dcf6)

`activity` table records what user did the revision, and meta data about the interaction. Including the table and record ID again.
![image](https://github.com/openmsupply/open-msupply/assets/7684221/282c3a41-bfbb-4925-aba2-ee68a2476806)

On a record is an "activity" list:
![image](https://github.com/openmsupply/open-msupply/assets/7684221/0386fe4b-7704-4b6b-a0b3-e3a16b670519)

And detail of a revision by clicking any element in that list:

![image](https://github.com/openmsupply/open-msupply/assets/7684221/955feb71-2eef-4191-a45b-436176ae09ce)

I think this gives really clear accountability (and a lot of it more relevant to a webservice than a local server). Tempted to propose something similar for HSH as the auditability is especially important there. Downside with this is that it's very very data heave, essentially the full history of all data is duplicated! 1 record edited 100 times has 100 revisions and 100 activities recorded...

**Comment by nisha-dangol** [comment]
Looks good in v2.1, except noticed one minor issue: #4449
