### ISSUE TITLE
cannot type the date of birth manually in the "New Patient" modal

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1494]
## What went wrong? 😲

Can't type the Date of Birth manually in the `New Patient` modal. Sounds like there's something wrong when you have to type the "year"

![Apr-05-2023 12-31-31](https://user-images.githubusercontent.com/74992958/229951762-51461a3a-1773-40b8-9cf0-c0e19d900191.gif)

Ok when you use the date picker though. 

## Expected behaviour 🤔

You should be able to type the date manually as an alternative to the date picker. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Dispensary > Patients > New Patient button > New Patient Modal > Date of Birth field

## Your environment 🌱

https://demo-open.msupply.org:88/dashboard
Version 1.1.10

**Comment by CarlosNZ** [comment]
Fixed by #1496
