### ISSUE TITLE
Focus stays on "OK & Next" in stocktake item input modal

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#1498]
## What went wrong? 😲

When I press OK & Next while editing items in a stock take, the focus remains on OK & Next. I have to tab a whole lot to get back to 
![image](https://user-images.githubusercontent.com/7684221/230012073-1569d451-7f54-41fb-aaa9-8a51064254ab.png)

## Expected behaviour 🤔

The focus should move to the top left most editable field of the list of lines. I expect this affects many input modals, if the fix needs too much work to get them all, make more issues/PRs I think.

THAT SAID, maybe someone likes this way. Makes it easier when just checking through many items. I'd argue that you can do that using the mouse. When doing data entry, it's nice to not have to leave the keyboard and that's the workflow that should be optimised in my opinion.

## How to Reproduce 🔨

1. Create stocktake with master list
2. Click on first row
3. Enter values pressing tab to cycle through cells
4. tab to OK & Next
5. Press enter
6. Focus stays on OK & Next

## Your environment 🌱
 - Version develop 1.1.10
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### Tangent

![image](https://user-images.githubusercontent.com/7684221/230012316-1c52326a-5409-42e6-8c68-4015c2ad12d6.png)

I tried cmd+K to see if there were any handy shortcuts for OK & Next, but it's behind the dialog. Way out of scope of this bug report though. I'd like there to be a short cut for each of the dialog buttons and to be able to cmd+K.

**Comment by CarlosNZ** [comment]
The problem is the data entry rows in this case are part the `DataTable` component, and there's no straightforward way to set an `autofocus` on one of the cell inputs like there is with normal text inputs. So this would involve some significant manipulation of the core Material-ui "TableCell" components. 

Unless @mark-prins can think of a straightfoward way?

**Comment by mark-prins** [comment]
> Unless @mark-prins can think of a straightfoward way?

Yes! I can 😁  #1887 1887

Turns out that we've been here before.. but the stocktake edit modal is a special case.

**Comment by nisha-dangol** [comment]
## Testing
Tested in apk v1.1.16

### Tests
- [x] Add a stocktake which has multiple lines:
    - [x] On clicking on the first line, the batch input of the first row should have focus.
    - [x] On clicking OK & Next, the batch input of the first row should have focus.
