### ISSUE TITLE
East Timor : Complaining that a reason can't be assigned when a stock take is zeroed

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/open-msupply#1500]
## What went wrong? 😲
East Timor : Complaining that a reason can't be assigned when a stock take is zeroed

![et-reason-1](https://user-images.githubusercontent.com/6764266/230092283-5cb12614-b1d5-4a11-be2f-7c199e28d077.jpg)

![et_reason](https://user-images.githubusercontent.com/6764266/230092318-4faf5992-cf4d-45c7-bbb3-84b833895df8.jpg)

## Expected behaviour 🤔

Think the reason should be available.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run openmSupply on any data, use East Timor one if possible.
2. See when the reason is available.

## Your environment 🌱
 - Version [lastest]
 - Platform [tablet, browser]
 
## First task

@nisha-dangol ,  @santoshkhanal12  @AnushaUp :  Can one of you test this. I think it needs to be reviewed before a developer work on this issue.

**Comment by mark-prins** [comment]
@ujwalSussol this one is fixed (hopefully!) in #1465 - which is included in [v1.1.9](https://github.com/openmsupply/open-msupply/releases/tag/v1.1.9)

**Comment by ujwalSussol** [comment]
> @ujwalSussol this one is fixed (hopefully!) in #1465 - which is included in [v1.1.9](https://github.com/openmsupply/open-msupply/releases/tag/v1.1.9)

Thanks, @npendergrast  also said the same thing...  so closing this.

false alarm @openmsupply/testers ... sorry.
