### ISSUE TITLE
Program Requisitions - Restrict program requisition editability

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1507]
From epic: #1451 

Program requisition = having program_id (or programName in API).

This issue is for both front end and back end.

## Request Requisitions

Disable changes to supplier, maxMOS, thresholdMOS, period, order type, program, item addition/deletion

## Response Requisition

Disable addition/deletion of items

## Other notes

I think for back end it's safe to standard error (bad user input) since front end should already restrict user actions (and maybe show why theses actions are restricted)

**Comment by roxy-dao** [comment]
mSupply uses tags for this... are we allowing users to create Program Requisitions as long as they have access to the master list with the program in it?
