### ISSUE TITLE
Rename 'Spanish (Colombia)' to 'Spanish' in translations

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#1513]
## Is your feature request related to a problem? Please describe 👀

@yeisonportela has translated a large portion of 'Spanish (Colombia)' and has used formal Spanish throughout. 

So it would be good to use this as the master translation for the Spanish language. 

I was thinking the easiest way would probably be to just swap the names between the two Spanish translations - although I'm sure there will be a catch...

![image](https://user-images.githubusercontent.com/19318937/231314118-ff13b3e6-1623-4fc5-ab56-304a426ca242.png)

**Comment by mark-prins** [comment]
Checked that [fallback](https://www.i18next.com/principles/fallback) does work as I'd hoped. 
Will update `es` & `es-CO`
