### ISSUE TITLE
Remove fine grain access control for document types

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1516]
Currently document access is restricted by document type. However, it's enough to restrict document access by program.

- [x] redefine dynamic document permission to only include program types as context
- [x] update permission setup in init scripts (remove non-program document types)
- [ ] ~Calculate the allowed docs list from the `document_registry` from the list of program names from the program permissions~
- [x] rename `CapabilityTag::DocumentType` ...
- [x] handle access for patient documents since they are not belonging to a special program

**Comment by nisha-dangol** [comment]
Moving this to Done as I can initialise the data after running the 4Dinit script and running it as FC code on mSupply Server in respect to [the test case](https://github.com/openmsupply/open-msupply/pull/1928#issue-1770381875)
