### ISSUE TITLE
HIV Testing enrolment/encounter updates

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1525]
Enrolment:
- [x] don't show the patient id in the testing enrolment (remove "Enrolment Patient Id")

Encounter
- [x] Clinician input: disallow text input and make it dropdown only (bonus if easy to do)
- [x] Simplify start time entry (no time)
- [x] Remove HIV Testing remove date input
- [x] Testing type: reverse order and fix naming
- [x] Spelling of questions, e.g. remove ":" for questions
- [x] Risk group section: add separator after main risk group section

**Comment by CarlosNZ** [comment]
> * don't show the patient id in the testing enrolment

What do you mean by this?

**Comment by clemens-msupply** [comment]
> > * don't show the patient id in the testing enrolment
> 
> What do you mean by this?

Remove the "Enrolment Patient Id"

![image](https://user-images.githubusercontent.com/88299195/232344284-91468bff-9115-437f-97d8-2337174209cb.png)

**Comment by CarlosNZ** [comment]
Closed by #1550
