### ISSUE TITLE
Show patient link in encounters breadcrumb

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1526]
- [ ] add link to patient page either in the breadcrumb 
- [ ] or for the patient name (or both)

Possible duplicate of #1342

![Image](https://user-images.githubusercontent.com/88299195/231610491-937f6fce-69e2-4220-a126-eca6854b5d8c.png)

**Comment by CarlosNZ** [comment]
> * add link to patient page in the breadcrumb

Just noting that this is not straightforward with the way the `useBreadcrumbs` hook currently works. The main part of the breadcrumb trail is derived directly from the URL, and we can add a custom "suffix", but that's only a simple string.

As far as I can tell, there are a few different ways we could do this:

1. Return `setUrlParts` from `useBreadcrumbs` and override them manually from the Encounter page, so they don't correspond exactly to the URL.
2. Allow `setSuffix` to take a complex structure similar to the `urlParts` shape, so we can specify multiple elements and links for them (which is essentially doing the same as "1"
3. Add a new method to `useBreadcrumbs` --  `setBreadcrumbs`, which does what 1 and 2 do, but would take precedence if set (but leave the current functionality of `setUrlParts` and `setSuffix` unchanged
4. Change the actual URL structure and insert the patient name into it.

Each of these comes with their own complexities and compromises. I think I prefer option 3 best, but won't know for sure until I try it. Option 4 is also a reasonable one, but I'm not sure how much that will affect other things.

Any thoughts @mark-prins , @clemens-msupply, @roxy-dao ?

**Comment by CarlosNZ** [comment]
Closed by #1563
