### ISSUE TITLE
Json Forms (7) -- User permissions and form editability

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#153]
Part of Epic #81 

Not sure where we're getting permissions from, but we need to check whether current user is allowed to edit the document/form being requested, and form elements should appear in "display-only" form if not.

Can use "readonly" property of JsonForms to set whole form non-editable at once: https://jsonforms.io/docs/readonly

**Comment by clemens-msupply** [comment]
This is already handled through permissions, e.g. the user can't see or load document without permissions.
