### ISSUE TITLE
Program Enrolment ID not showing up for HIV Testing & Counselling

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1534]
![Screenshot 2023-04-14 at 10 06 07 AM](https://user-images.githubusercontent.com/5456533/231893917-f0500c5a-522e-4c2c-b148-e7a67f5b6ba1.png)

As seen in this screenshot "Enrolment Patient ID" is not showing up for HIV Testing & Counselling, but it is definitely there when you open the enrolment form.

**Comment by DhanyaHerath** [comment]
@richardmoizeau says that it doesn't need to show - @clemens-msupply to check and confirm that this can be closed.

**Comment by clemens-msupply** [comment]
The "Enrolment Patient ID" is now removed from the testing enrolment..
