### ISSUE TITLE
Outbound shipment: Expose line number and need handler

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#157]
On Outbound and Inbound shipment invoices, The lines on both types are missing the line number, `[trans_line]line_number`.
Not having line number on Central server, That sort of lines are not counted upon Maths, which then creates a Ledger problem on all the items coming from remote to central server

### Steps to Reproduce

- Setup mono repo with Central server
- Make sure they understand each other
- From Frontend > Create a Outbound shipment with at-least 1 line
- Minimum status to keep is: Confirm
- Once created, wait for sync to happen so that this lines is pushed to Central server store
- Once synced, Do a ledger check from Diagnostic window
- You will a ledger problem against the item

### Side areas:

- Line number is missing on Inbound invoices
- Line number missing on requisition (All type)
- Probably more........

Probably, We also need to expose `[trans_line]line_number` in a GraphQL query? @andreievg @clemens-msupply @mark-prins 
Can see a `node` saying `Lines` but i think the use case for that node is different ...

**Comment by clemens-msupply** [comment]
There is currently no line_number in omSupply, could you please explain how it is used?, e.g. how it causes ledger problems?

**Comment by andreievg** [comment]
Bijay mentioned that logic in mSupply ledge calculation would consider line invalid unless it has line_number.

**Comment by bijaySussol** [comment]
Folks, I will need to re-visit on this one.
For now, Closing this, But will get back, on my recent testing session, This does not seems to be the culprit

Thanks
