### ISSUE TITLE
Response line to show the requested quantity in model is overlapping

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#1572]
## What went wrong? 😲

The response line details which shows how much is requester have requested that model Label and the quantity requested is overlapping.

![photo_2023-04-19_10-30-18](https://user-images.githubusercontent.com/13144882/232969425-3c5630f9-88d8-4cff-95d0-16bae15194c6.jpg)

## Expected behaviour 🤔

Need a extra space but @mark-prins want to look at it personally, so hold off the breath.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Need a response lines
2. Click on any 'line'

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by bijaySussol** [comment]
@mark-prins @roxy-dao :  Any thought?

**Comment by mark-prins** [comment]
not sure that I'll have time to look at this soon.. if you want to take it @bijaySussol that'd be awesome

**Comment by mark-prins** [comment]
see also @alainsussol's version in French from https://github.com/openmsupply/open-msupply/issues/1724#issuecomment-1540394020

![image](https://github.com/openmsupply/open-msupply/assets/9192912/59ecce65-9083-47ec-9906-0f6061236829)

**Comment by bijaySussol** [comment]
@mark-prins : 

Wondering if this much would be enough, since the details is shown upon hove and we just show that 2 different color indicator are?

![This](https://github.com/openmsupply/open-msupply/assets/13144882/9ca48633-4258-4197-8c04-41a17e04879b)

**Comment by mark-prins** [comment]
I thought that we'd be able to set a minimum on the width and have it display all of the text
