### ISSUE TITLE
Fix patient program migrations (which edit migration from develop)

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1578]
In the features/program branch some migrations have been modified that belonged to develop. (Dev was started before 1.0 and than it has been forgotten to fixes these)

To find diffs run this command from the feature branch:
```bash
git difftool -d develop server/repository/migrations/
```
This would give something like:

![Image](https://user-images.githubusercontent.com/88299195/233215703-a6c48d4b-6a69-48bd-b0e5-91c909e695e8.png)

For both DBs there there shouldn't be any file merges in the diff.

- [ ] For these merged migrations, revert changes made compared to develop
- [ ] Add equivalent 'alter' migrations in new diesel migration files

**Comment by CarlosNZ** [comment]
Closed by #1602
