### ISSUE TITLE
Program Requisitions: Program Settings upsert/deletes

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1584]
Continuation of #1481 

Currently, central server allows master lists to be deleted if the master list is not linked to any stores. i.e., If a user removes the master list from all stores, then it can result in the following error (along with some others): 
<img width="423" alt="Screenshot 2023-04-20 at 2 51 16 PM" src="https://user-images.githubusercontent.com/61820074/233245842-f6dd40d2-b284-452f-8d98-39f42d830086.png"> <img width="170" alt="Screenshot 2023-04-20 at 2 58 24 PM" src="https://user-images.githubusercontent.com/61820074/233246956-080e14cd-60bd-40be-9a82-a1e1c6ef19a0.png">

### Central Changes
- Master lists shouldn't be deleted from central as program uses master list as a FK, and it will cause errors if a master list with a program is deleted
- Have a boolean to toggle if the master list is active or not instead of deleting

### Program
- Add `is_active` field to program table 

### Program Requisition Settings
Program Requisition Settings cannot be edited but they can be deleted. The `id` for this table is generated on omSupply which makes it hard to delete existing program requisition setting based on id. 
- [x] Delete all program requisition settings before generating program requisition data in translation. 

### Program Requisition Order Type
Order types can be edited and deleted. 
- [x] Delete all order types before generating program requisition data in translation.

### General Master List Changes (can be moved to another issue)
- [x] Remove `try_translate_pull_delete` from `translations/master_list`
- Add `is_active` field to master list and filter by this field wherever applicable

**Comment by andreievg** [comment]
> Delete all program requisition settings before generating program requisition data in translation.

👍 

> Delete all order types before generating program requisition data in translation.

👍 

> Add is_active field to program table

👍 (although it's not required until we start soft deleting master lists)

> Remove try_translate_pull_delete from translations/master_list

👍 

> Add is_active field to master list and filter by this field wherever applicable

👍 (although it's not required until we start soft deleting master lists)

I think we would want a separate issue on mSupply and omSupply for soft deletion of master lists
