### ISSUE TITLE
Outbound Shipments to supplier should be counted for AMC calculation

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1586]
## What went wrong? 😲

Was not sure if it is a bug or a feature request but here is the issue:

version 1.1.11 does not support "return to supplier" but there is a workaround as you can create an Outbound Shipment to your supplier (also setup as your customer). Then why am I complaining you're gonna ask ? 

Because if I create a new outbound shipment this way, the quantity issued will be counted to calculate the AMC... and we don't want that.   

## Expected behaviour 🤔

- [ ] Option 1: we should enable "return to supplier" in Open mSupply
- [ ] Option 2: we could "flag" the O/S as being a return and then, would be excluded from consumption data (?) 

## Your environment 🌱
 - Version 1.1.11
 - Platform : macOS desktop

**Comment by DhanyaHerath** [comment]
We should wait for the supplier credit functionality rather than doing this - and should make the suppliers not customers in mSUpply for Djibouti
