### ISSUE TITLE
Should "Replenishment" menu be before "Distribution" ?

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1590]
IMHO, first you get stuff (replenishment) and then you distribute (distribution)

![Screen Shot 2023-04-20 at 5 54 33 PM](https://user-images.githubusercontent.com/74992958/233270794-b235e443-a001-4573-8a4d-ec6fe69caf2f.png)

**Comment by DhanyaHerath** [comment]
But...do you distribute more often than you replenish? 🤔

**Comment by richardmoizeau** [comment]
> But...do you distribute more often than you replenish? 🤔

Good point.
