### ISSUE TITLE
You can Create Blank Locations

### ISSUE THREAD

**Issue by santoshkhanal12** [openmsupply/open-msupply#1605]
## What went wrong? 😲

You can Create Blank Locations

## Expected behaviour 🤔

The creation of blank Location should be restricted.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Login Via website
2. Click on Inventory DDL in left side of the window
3. Click On Locations
4. Now in top right button, Click on "New Location"
5. But the Name and Code of the location just bunch of spaces
6. Now Click on OK, The blank location is created (BUG)

## Your environment 🌱
 - Version [e.g. 1.1.9]
 - Platform [browser, ]

**Comment by bijaySussol** [comment]
Technically, It is not a blank location considering the issue `How to Reproduce` section, Those location ain't empty rather filled with empty spaces.
Would be good to fix, so far I have not seen user doing such in desktop.
