### ISSUE TITLE
Store the current `store` when creating an encounter

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1612]
Beside being useful to explicitly storing where an encounter happened, this is needed for the central report.

**Comment by CarlosNZ** [comment]
Just include it in the JSON document, or are we creating a new field in the encounter table?

**Comment by clemens-msupply** [comment]
> Just include it in the JSON document, or are we creating a new field in the encounter table?

Good question, might be useful to query it at some point, e.g. for a site with multiple stores. It's not needed right now but think I will add it anyway...
