### ISSUE TITLE
Input with Labels causing components to overlap/go off screen

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1619]
## What went wrong? 😲
**Needs to be done in develop**
![Screenshot 2023-04-27 at 11 39 12 AM](https://user-images.githubusercontent.com/61820074/234725055-2990f548-5ccf-471f-939d-b1c96ed1131d.png)

See https://github.com/openmsupply/open-msupply/pull/1613#issuecomment-1524100784. Components are overlapping in the encounter header and the widths for the components are all different.
![234707376-5015847d-3f7a-44ad-946b-742579418f8d](https://user-images.githubusercontent.com/61820074/234713470-4a458674-aa52-4dcf-abac-ec76423d0885.png)

**Comment by CarlosNZ** [comment]
Does it look okay when the screen is wider?

**Comment by roxy-dao** [comment]
> Does it look okay when the screen is wider?

That screenshot is without changing the screen size.. now if I change it...

![Screenshot 2023-04-27 at 10 15 02 AM](https://user-images.githubusercontent.com/61820074/234714798-edad3d81-150f-4d0f-8bc8-1cd181cf875f.png)

**Comment by CarlosNZ** [comment]
I'm just wondering if this is something that has happened recently, or if it's always been like this. If it's a new problem, we should trying and figure out exactly what changed to cause it.

**Comment by roxy-dao** [comment]
Recent change from develop [ac4cd47](https://github.com/openmsupply/open-msupply/pull/1598/commits/ac4cd470b7ea6d01f98c19620e43c9115acfa8f8)

**Comment by roxy-dao** [comment]
Will have to do in develop since it's messing other components that use InputWithLabelRow
