### ISSUE TITLE
Input loses focus if hovering over chart

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1621]
## What went wrong? 😲
https://user-images.githubusercontent.com/61820074/234733850-94b91d19-962d-4a56-a816-99d6fe07a498.mov

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by CarlosNZ** [comment]
Hey, @roxy-dao  I can't reproduce this in the current `develop` branch -- I can still type in the input field while hovering over the charts.

Can you confirm if it's still a problem, and if so, can you show me?

**Comment by roxy-dao** [comment]
Just checked. Not an issue anymore in develop (:

**Comment by CarlosNZ** [comment]
> Just checked. Not an issue anymore in develop (:

Right, thanks. Will close :)
