### ISSUE TITLE
Menu: Sync: Last sync is showing the last attempt to sync but the last "successful" sync

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1624]
## What went wrong? 😲
 

Last sync is showing the last attempt to sync not the last "successful" sync

![Screen Shot 2023-04-27 at 1 38 34 PM](https://user-images.githubusercontent.com/74992958/234737951-743c37b0-a741-4e94-83a6-aebf99c0f48a.png)

![Screen Shot 2023-04-27 at 1 38 48 PM](https://user-images.githubusercontent.com/74992958/234737969-67a7fdea-9aa4-4423-8802-08873c1cd44a.png)

## Expected behaviour 🤔

should show the last time sync has been successful

## How to Reproduce 🔨

Steps to reproduce the behaviour:

you should be "unable to connect to server"

### Agreed solution 

Update to have two statuses: Last successful sync, and last attempt to sync

## Your environment 🌱
 - Version 1111
 - Platform windows desktop

**Comment by nisha-dangol** [comment]
Tested in v1.3.0 exe

I do see the new `Last succesful sync` in case of sync-break, which looks good, so PASS!
<img width="936" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/307198a6-905b-473b-b9de-589eecde89a3">
