### ISSUE TITLE
Supplier/Customer modal components are not aligned

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1632]
## Is your feature request related to a problem? Please describe 👀
![Screenshot 2023-04-28 at 10 45 13 AM](https://user-images.githubusercontent.com/61820074/235008123-e72ba2ff-f6ca-4cb3-82dc-1689f1c41ea4.png)

## Describe the solution you'd like 🎁
Align all components so they look pretty 

### Describe alternatives you've considered 💭
Just leaving it 🤷🏻

**Comment by DhanyaHerath** [comment]
@roxy-dao Looks fixed?
<img width="1093" alt="image" src="https://github.com/openmsupply/open-msupply/assets/29744386/7bcd244e-1bab-4289-994c-cca9608d5c69">

**Comment by roxy-dao** [comment]
> @roxy-dao Looks fixed? <img alt="image" width="1093" src="https://user-images.githubusercontent.com/29744386/253847922-7bcd244e-1bab-4289-994c-cca9608d5c69.png">

Much better ❤️

**Comment by kahn-msupply** [comment]
🧪 Testing - PASSED

- [x] As per the issue - create an outbound with a placeholder row. Allocate in the modal - if all of the placeholder quantity is allocated, the placeholder row should be removed.

LGTM... However.. If you look close enough, the text on left hand side compare to the right hand side doesn't line up. Probably not crucial.

![image](https://github.com/openmsupply/open-msupply/assets/132425100/030ce383-d96c-490a-8428-797960fd403c)
