### ISSUE TITLE
Internal Orders (both program and general): add the item's unit to the table

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1646]
- [x] Add the item's unit to the table: 

![Screen Shot 2023-05-01 at 12 30 46 PM](https://user-images.githubusercontent.com/74992958/235383581-a2f83abe-1052-46f1-8b0e-c44eeb5d19e9.png)

Addition: 

- [x] Can we also add the `default pack size` of the item please in the table and the modal ?

- [x] Can we have another calculated field that would do the following: pack size / requested quantity = approx number of packs (for information only, not editable, the result should be rounded up to the upper whole number). Requested by customer specifically, could be an issue if not there apparently (pharmacists used to dealing in packs for ordering). Ideally located in the modal (that where the user enters quantity). 

the alternative would be to have a pref to say if you want to order in number of default pack size or if you want to order in quantity. 

- [x] Now I'm thinking that we should have a way to select the columns that we wanna see, a little bit like in "View Stock": 

![image](https://user-images.githubusercontent.com/74992958/236405449-9f68a2b8-4944-4e45-80b3-f7892cabb20f.png)

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by richardmoizeau** [comment]
this has been noted by the customer as something important

**Comment by richardmoizeau** [comment]
as discussed with @DhanyaHerath and @mark-prins, just the first task is to be done: 

> * [ ]  Add the item's unit to the table:

**Comment by CarlosNZ** [comment]
> * pack size / requested quantity = approx number of packs

I presume you mean the other way round? (quantity / pack size) ;)

**Comment by richardmoizeau** [comment]
> > * pack size / requested quantity = approx number of packs
> 
> I presume you mean the other way round? (quantity / pack size) ;)

I do ! thanks for spotting it

but wait before working on this issue, cause we had a discussion this morning with @mark-prins and @DhanyaHerath and I think we're going to do something else. 

For this issue, we should only add the "unit" in the "internal order" list
