### ISSUE TITLE
Internal Order's "Local" Authorisation

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1652]
#### Currently: 
User could enter the name of the person who approved the internal order in the internal order's comment field and specify first name, last name, job title, phone number and email address
no user permission to "SEND" the internal order - any user do it
we could use the dashboard to use who has "sent" the internal order and retrieve [user details](https://docs.msupply.org.nz/admin:managing_users#details_tab) of whoever sent it. 

There is also the possibility to print a paper form from the internal order "Print Button" (Nepal is working on it) but again, nothing will prevent a user from sending the order. 

#### Option 1: 
No new user permission
We do what they sign for but we need to wait for the 2 branches to be merged together to allow the use for JSON Schema. This option does not include a new user permission to "SEND" the internal orders. 

#### Option 2: 
No new user permission
The [user's details tab](https://docs.msupply.org.nz/admin:managing_users#details_tab)'s following fields are being copied in the comment when order is sent (DO NOT OVERRIDE EXISTING COMMENT): 

"Approved by"&[First Name]&" "&[Last Name]&" ("&[Job Title]&"). Email: "&[E-mail]&" and Phone Number: "&[Phone 1]&"."

Approved by Michel Philipps (Chief Doctor). Email: michel@msupply.foundation and phone number: 0123456789. 
Autorisé par Michel Philipps (Médecin Chef). Courriel: michel@msupply.foundation and Téléphone: 0123456789. 

####  Option 3: 
@mark-prins said:  I think it's not a big task to have a permission in mSupply, use that to block the finalisation button and log when things happen.
New user permission - only a user with this permission can "send" the internal order

The [user's details tab](https://docs.msupply.org.nz/admin:managing_users#details_tab)'s following fields are being copied in the comment when order is sent (DO NOT OVERRIDE EXISTING COMMENT). Why the comment ? Cause the comment is then availabel to the "remote" authoriser on the remote authorisation web interface (he needs to know who authorise the order locally). 

"Approved by"&[First Name]&" "&[Last Name]&" ("&[Job Title]&"). Email: "&[E-mail]&" and Phone Number: "&[Phone 1]&"."

English: Approved by Michel Philipps (Chief Doctor). Email: michel@msupply.foundation and phone number: 0123456789. 
French: Autorisé par Michel Philipps (Médecin Chef). Courriel: michel@msupply.foundation and Téléphone: 0123456789. 

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by mark-prins** [comment]
I've replace `and` with `et` in the French version of the text. @alainsussol @richardmoizeau - is that correct?

**Comment by alainsussol** [comment]
@mark-prins I think "et" is ok or a ""," is good too in my own opinion.

**Comment by richardmoizeau** [comment]
Can we change "approved by" (Autorisé par) by "Sent by" (Envoyé par) ?

Autorisé par Michel Philipps (Médecin Chef). Courriel: [michel@msupply.foundation](mailto:michel@msupply.foundation) and Téléphone: 0123456789.
