### ISSUE TITLE
Stocktakes - Getting "StocktakelineAlreadyexists" error message when clicking on OK or OK and Next

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1662]
## What went wrong? 😲
 

Get "StocktakelineAlreadyexists" error message when clicking on OK and Next

sounds like the issue is only when creating stocktake using below method

![Screen Shot 2023-05-03 at 1 54 53 PM](https://user-images.githubusercontent.com/74992958/235819733-2191e0df-85a1-4628-9da0-fcd276329aae.png)

when updating a line, then you click on OK or OK et Next and it keeps spinning or you get an error message. If you cancel, you also the error message

![Screen Shot 2023-05-03 at 1 26 35 PM](https://user-images.githubusercontent.com/74992958/235817592-577446e1-f6a3-45d5-9725-5d73a9ef451b.png)

## Expected behaviour 🤔

Should show the modal for the next stocktake line 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Stocktake
Add item with stock
click on line - change quantity
click on OK or OK & Next

https://demo-djibouti.msupply.org/ (credentials in Bitwarden for user: TmF Support)
Store CAMME
Stocktake 6
Click on first line and click on OK & Next on the modal

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by richardmoizeau** [comment]
False alarm :-)

**Comment by richardmoizeau** [comment]
actually not a false alarm, the issue keeps coming up: 

![Screen Shot 2023-05-03 at 1 39 47 PM](https://user-images.githubusercontent.com/74992958/235818563-6a0ccd4a-005a-4492-bc8a-b53decf7d16a.png)

**Comment by richardmoizeau** [comment]
reopening

**Comment by roxy-dao** [comment]
Seems to be working for me... will see if anyone else can reproduce it

https://user-images.githubusercontent.com/61820074/236950463-5fb6e36b-1383-4a1f-8be9-186a9314f97f.mp4

**Comment by andreievg** [comment]
I couldn't replicate at first, but realised this is possible if you have this modal (for stocktake item edit) open concurrently in different browsers, then realised if ok isn't debounced (or isn't disabled), it's possible to get this if you quickly double click on ok or ok next, I think this could be the issue

**Comment by mark-prins** [comment]
Unable to reproduce locally. Tried quickly double clicking. tried multiple browsers open.
I could repro on djibouti-demo, by adding `P3TDR0002     TDR CARESTART MALARIA PF PV COMBO`, editing the quantity of an existing line and double clicking. The server is slow enough to allow this; in which case two `upsertStocktakeLines` requests are made, and the second fails.

**Comment by kahn-msupply** [comment]
🧪 Testing - PASSED

omSupply Interpreted V1.2.0
Demo data file

- [x] Delay the server, or use a slow server. Hastily click the ok button when adding/editing a new stocktake_line

Opened multiple browsers with stocktake open, used developer tools to slow connection, unable to reproduce.

LGTM
