### ISSUE TITLE
stocktake line modal: Count this line checked by default for one line ?

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1663]
## What went wrong? 😲
 

![Screen Shot 2023-05-03 at 1 33 37 PM](https://user-images.githubusercontent.com/74992958/235818083-971f3f9a-5011-44d9-939c-1a0e2cb281fa.png)

created a new stocktake for item in stock, when clicking on the first line i could see that one of 4 stock lines was already checked by default (?)

## Expected behaviour 🤔

all stock lines should be checked by default ? or none, but need to be consistent ;-)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by DhanyaHerath** [comment]
To check again - may have been fixed by another change from @mark-prins.

**Comment by roxy-dao** [comment]
All lines are ticked by default now (:
