### ISSUE TITLE
Master lists in outbound shipment doesn't update when changing supplier

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1666]
## What went wrong? 😲

When adding master list in outbound shipment, master list don't update when changing supplier

## Expected behaviour 🤔

They update

## How to Reproduce 🔨

Have two different customers with two different master list, create outbound shipment for one customer, try adding from master list and note master lists that are shown, change customer, note master list didn't change. Master list will change if page is refreshed.

**Comment by nisha-dangol** [comment]
Tested in `v1.4.00-test-2023-10-02-build` exe

## Tests
- [x] Have two customers with different MasterLists
- [x] Create an Outbound Invoice
- [x] Change customer
- [ ] MasterList list should update accordingly **-FAILED-**
Hey @roxy-dao. I notice that the list of  maste-lists doesn't really update quickly on first load. It updates while clicking on second time. This can let us choose the incorrect master-list for the customer/store. I've submitted the issue with details in #2336
