### ISSUE TITLE
Report printing busy screen

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1683]
Printing a programs report with lots of data can take a while. Currently, there is no indication that the printing is ongoing and you even can start the printing process multiple times.

![Image](https://user-images.githubusercontent.com/88299195/236338007-670135df-4ff9-41ac-971f-83f5b951fe6a.png)

- [x] Add loading modal when printing
- [x] Should not be possible to print other reports while a report is printing
- [ ] ~Being able to abort the request would be nice (if its not too difficult to implement)~

**Comment by CarlosNZ** [comment]
What's the easiest way to create a report with "lots of data" in it?

**Comment by clemens-msupply** [comment]
hm not sure, but you could set a breakpoint in the report endpoint and run the remotes_server in debug mode from the IDE. You need to set some env vars for this, let me know if you want to do this... Or just a delay in the JS API hook?
