### ISSUE TITLE
Add "Suggested Quantity" in the remote authorisation web interface table

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1690]
## Describe the solution you'd like 🎁

Add "Suggested Quantity" in the remote authorisation web interface table

Position: before customer requested
FR: Quantité suggérée

### Additional context 💌

![Screenshot 2023-05-05 at 1 54 52 PM](https://user-images.githubusercontent.com/74992958/236363213-0a7f5c5f-f465-4f04-91ed-3764d1061dda.png)

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by richardmoizeau** [comment]
FYI @andreievg and @DhanyaHerath 

part of customer's requirements: 
https://docs.google.com/document/d/1IP-YZTufUea59QjuXLA6hJ6RDp9j9ffl7AniOnLtt00/edit#heading=h.s2jy043j42f6

Sorry...

**Comment by richardmoizeau** [comment]
@mark-prins

**Comment by mark-prins** [comment]
Created issues
- https://github.com/openmsupply/msupply/issues/12951
- https://github.com/openmsupply/msupply-authorisation-web-app/issues/58
