### ISSUE TITLE
When grouped by item, the extend arrow stop working after adding a new batch line  

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1691]
## What went wrong? 😲
 
It seems to occur after I add a new batch line and try to extend another line.  It works again when I toggle the Group by item button.
![extending lines](https://user-images.githubusercontent.com/11624516/236370123-ad63d617-d092-491f-92ee-8d1c93c8d53b.gif)

## Expected behaviour 🤔
Should be able to extend a line even after I have add a batch line of another line

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Create a stocktake for a program
1. Create a stocktake. Make sure you have one item that has multiple stock_lines or if not add extra batches line to your item 
2. Extend a line
3. Add a batch to another line
4. Click on the extend arrow of that line
5. Go back and click on the extend arrow of the first line
6. See error. 
7. Toggle the "Group by item" button and then you can extend again

## Your environment 🌱
 - Version [e.g. 1.1.11]
 - Platform [windows desktop]

**Comment by mark-prins** [comment]
unable to replicate. Can someone else try please?

**Comment by roxy-dao** [comment]
I can't seem to replicate it either, tried both in stocktake and invoices

**Comment by andreievg** [comment]
I think it's safe to close if it can't be replicated
