### ISSUE TITLE
In a stocktake when editing adding a batch line, the Expiry date is cut-off on Windows

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1692]
## What went wrong? 😲
 
As screenshot.

![image](https://user-images.githubusercontent.com/11624516/236370907-2072a620-a160-4b9a-aa63-86e5db13c011.png)

## Expected behaviour 🤔
See the entirety of the date

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a stocktake,
2. Click on a line 
3. See error. the Expiry date is a bit cut-off

## Your environment 🌱
 - Version [e.g. 1.1.11]
 - Platform [e.g. windows desktop]

**Comment by roxy-dao** [comment]
Might be fixed with #1665

**Comment by roxy-dao** [comment]
Fixed~
