### ISSUE TITLE
Program orders: you can still place an "General" order for items on a "Program" master list

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1697]
## What went wrong? 😲
 

once an item is on a "program" master list, you should not be able to place a general order for it

list `PLSS - ARV` is a program master list: 

![Screenshot 2023-05-05 at 4 17 00 PM](https://user-images.githubusercontent.com/74992958/236376696-283258e4-bf03-477b-9d69-50936d429bf4.png)

but you can place a general order with it: 

![Screenshot 2023-05-05 at 4 18 33 PM](https://user-images.githubusercontent.com/74992958/236376839-19da2a27-4991-48c2-a298-b2527ce949ec.png)

## Expected behaviour 🤔

Like for CDI, for tagged stores with program master lists, you should not be able to order items through a general order 

## Your environment 🌱
 - Version 1.1.11
 - Platform macOS desktop

**Comment by DhanyaHerath** [comment]
Hmm @richardmoizeau I definitely see your point - but on current mSupply, you can still order items for a program masterlist through a general order. (I won't screenshot as it's a public repo but can send you one) 

Do you think this is a priority for Djibouti?

**Comment by andreievg** [comment]
I was wondering what the conclusion/decision for this is, and how to implement it best ? Also considering we can add items in general requisition (that are not program item, although Dhanya rightful mentioned, yeah but do we want to make it even easier with master lists ?). So do we hide program master list (that are not assigned to store with tags ?)

**Comment by mark-prins** [comment]
That's what I thought the plan was - don't show program master lists as an option when 'adding from master list'.
