### ISSUE TITLE
Cannot issue added stock (immediately after adding stock)

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1698]
## What went wrong? 😲

Stock is not issuable immediately after adding it via stocktake. At some point it becomes issuable, but not sure when.

## Expected behaviour 🤔

Stock can be issued

## How to Reproduce 🔨

Make sure there is not stock. Add it via stocktake, and straight away go to new outbound shipment, add from master list, you won't be able to issue it, after some time it becomes available to issue, see vide:

https://user-images.githubusercontent.com/26194949/236377067-bb433dc9-383a-48a7-9217-b1ce19e960c7.mov

**Comment by mark-prins** [comment]
testing using current develop branch - unable to replicate now.

**Comment by andreievg** [comment]
I just tried this and can replicate, tried because I thought it was related to this one: https://github.com/openmsupply/open-msupply/issues/1715 (it looks a little bit different, since in this case the lines is visibly not editable)

**Comment by roxy-dao** [comment]
> I just tried this and can replicate, tried because I thought it was related to this one: #1715 (it looks a little bit different, since in this case the lines is visibly not editable), not sure if it's worth re-opening, it's pretty edge case scenario (would be a little bit worried about new user exploring and trying this, or it happening during training

Ah, got the screenshot. I believe it is related to this issue... but only happens if you do stocktake to add stock and then quickly go to outbound shipment to add the new stock line. Maybe within a minute?
![Screenshot 2023-08-15 at 4 48 06 PM](https://github.com/openmsupply/open-msupply/assets/61820074/c01f82ad-8e5a-4f45-8c86-e992477e2f49)
