### ISSUE TITLE
Shipped inbound shipment appears as editable in list

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1699]
## What went wrong? 😲

~~Shipped inbound shipment appears as not editable in list, but it's editable in details view and when going back from detailed view~~

Shipped inbound shipment appears as editable in the list (should be not editable)

## Expected behaviour 🤔

Appears editable in list view

## How to Reproduce 🔨

Create transfer from another site (maybe the same from the same site). See it in receiving store, it will appear not editable in list and not editable in detail view. When navigating to the list using back button (from detail view), it becomes editable 

https://user-images.githubusercontent.com/26194949/236378421-d5d99d32-4bac-4d15-868c-aa1e0549eeec.mov

**Comment by mark-prins** [comment]
As per the message in the blue box - the shipment shouldn't be editable if status is `Shipped`. I'm confused by the issue soz, and can't recreate. the shipment is disable in both list and detail views for me

**Comment by bijaySussol** [comment]
Ditto as above.
Message says `This shipment was created automatically, as the result of an Outbound Shipment in another store. You are unable to edit details until the status is confirmed as Delivered.`

Once the status is changed from Shipped to Delivered > It is back on editable.

**Comment by andreievg** [comment]
it should not be editable but appears as editable in list, when pressing back button to go back to the list from detail view

**Comment by roxy-dao** [comment]
I tried pressing back in the invoice view to go back to the invoices but the shipment is still greyed out for me 🤔

**Comment by CarlosNZ** [comment]
Yeah, I can't reproduce this either. @andreievg can you check it again and see if it's still there for you?

**Comment by andreievg** [comment]
Hmm, I just double checked, i think my original comment might have been correct. It does appear as non editable in the list. And the blue box does say it's not editable, but actually it is editable since confirm as `delivered` is an action that edits the Shipment. 

I am not sure what the change should be, but to me it's confusing that shipment is grey in the list when there is an action pending. To me `grey` means not editable and no action ¯\_(ツ)_/¯ ??

**Comment by DhanyaHerath** [comment]
@CarlosNZ @andreievg +1 to Andrei's proposed solution! If there is an action for me to do, then I would expect it to show up as editable (particularly if it was from something that was created automatically)

**Comment by DhanyaHerath** [comment]
Oh, though same as Carl and Roxy I didn't see it change to becoming editable after I clicked Back - I think it is still a bug that it is showing up as not editable in the first place though

**Comment by roxy-dao** [comment]
> Oh, though same as Carl and Roxy I didn't see it change to becoming editable after I clicked Back - I think it is still a bug that it is showing up as not editable in the first place though

Andrei is saying that the `Confirmed Delivered` button is editable, so technically the invoice is editable not uneditable, so it is confusing to him... Maybe

**Comment by DhanyaHerath** [comment]
No, I agree with that! I think it __is__ editable, and plus, you're expected to change something in it. My expected behaviour would be for it to be blue, not greyed out

**Comment by roxy-dao** [comment]
Would having it not greyed out and message saying `You are unable to edit anything except for the status of the invoice` help with confusion? 🤔

**Comment by nisha-dangol** [comment]
Tested in latest v1.4.00-test-2023-10-02-build exe

## Tests
- [x] Create an outbound shipment from store A to store B and set status to Shipped
- [x] Change to store B and view the list of inbound shipments
- [x] See that the shipment is not greyed out in the list
- [x] Observe that you cannot edit the shipment, but you can change the status (and the info message is shown)
- [x] Change status to Delivered : can now edit details (and shows in the list as editable)
- [x] Change status to Verified: cannot edit details (and shows in list and non-editable)
