### ISSUE TITLE
Why does apk version opt to open browser to create Outbound Shipment from the requisition?

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1704]
## What went wrong? 😲
Why does apk version opt to open browser to create Outbound Shipment from the requisition? 

## Expected behaviour 🤔
Don't throw unnecessary alerts like such when the action is easily being carried away anyways

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get a customer requistion in oms store (idk, create IO from remote desktop to oms? I did that!)
2. Fill in some Supply quantities.
3. Click `Create Shipment` button
4. See error: it'll opt you to complete the action in browser. But if you check the Outbound Shipment, the action (of creating shipment) is already complete! Why bother send that alert everytime on apk?

## Your environment 🌱
 - Version: v1.1.13
 
## Screenshots/Recordings
https://drive.google.com/file/d/116nGjtkHYWlYcADtoRBIwxQ2sPHUUEz_/view?usp=share_link

**Comment by clemens-msupply** [comment]
@mark-prins as far as I can see the shipment opens in a new tab on purpose? I guess to not close the requisition?

To work around this, in the out shipment view, I could remember if the user came from a requisition and navigate back to the requisition once finished with the shipment? Maybe also good to show the matching requisition in the out shipment view?

Or is there already a solution to handle this problem on Android?

**Comment by clemens-msupply** [comment]
Is it correct that only the first outbound shipment gets a comment about the requisition?

![image](https://user-images.githubusercontent.com/88299195/236981859-232c7e21-67ea-4779-bab2-aa96a30b244a.png)

**Comment by mark-prins** [comment]
yes, it opens in a new tab on purpose - as you say, so that the user doesn't lose the requisition.
I thought that this PR would have prevented the opening in a browser when using android: https://github.com/openmsupply/open-msupply/pull/1303 but perhaps not?

**Comment by andreievg** [comment]
@clemens-msupply, I was referring to change in [this PR](https://github.com/openmsupply/open-msupply/pull/1067), when allowNavigation: * was removed (rightfully),  I thought that allowNavigation: * would open navigations to new tab in current browser.

Anyways, i think it should be easily debuggable with android studio:

https://github.com/ionic-team/capacitor/blob/bc302d26887684dd56df6545f4135fd7df008939/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L390

Not really sure why @mark-prins issue not working:

https://github.com/ionic-team/capacitor/blob/bc302d26887684dd56df6545f4135fd7df008939/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L370-L378

**Comment by clemens-msupply** [comment]
@mark-prins and @andreievg thanks for the links these where very helpful!
