### ISSUE TITLE
Outbound shipment - No automatic allocation is done when quantity resqueted is lower than the packsize of all stock lines

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1715]
## What went wrong? 😲
 
Let's say I am requesting 12 units of an item but all the stock_lines of that item have packsize of 100. If I click on the Allocate button, no stock lines are chosen (in fact nothing seems to happens if there tons of stock lines) and my 12 units are put into a placeholder line. 

![allocate stock doesn't work](https://user-images.githubusercontent.com/11624516/236940583-e69624d3-1734-4f39-b39a-57d9e52c4859.gif)

  
## Expected behaviour 🤔
I think there should be at least a message that tells you that you have to allocate manually. And maybe a way to split a pack to be able   to send only the amount of units that the customer is requesting

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an internal order for an item with a quantity less than all the packsize available in supplier stock . For example, order 12 units of an item for which the supplier has only packs of an hundred. Finalise 
2. Go to the supplier store, open the customer requisition and supply the requested quantity by clicking on the requested quantity button
3. Create a outbound shipment. open the line of the item you have requested previously and click "Allocate stock" 

## Agreed behaviour 
Round up when allocating, and add an in-line message that says that has been done 

## Your environment 🌱
 - Version [e.g. 1.1.11]
 - Platform [windows desktop]

**Comment by roxy-dao** [comment]
Seems to be solved with over-allocation implementation


https://github.com/openmsupply/open-msupply/assets/61820074/501c2cac-dfae-4e0d-87ea-62fc26fe9599

**Comment by andreievg** [comment]
Maybe it's somehow related to [this one](https://github.com/openmsupply/open-msupply/issues/1698) (although I can see that the lines are editable ¯\_(ツ)_/¯)

**Comment by fergie-nz** [comment]
Also related to #2227

**Comment by fergie-nz** [comment]
I think this is closed after the refactor of allocate button after [this PR](https://github.com/openmsupply/open-msupply/pull/2293)
