### ISSUE TITLE
Outbound Shipment: can "info" message disappear once shipment is confirmed as "Delivered" ?

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1726]
## What went wrong? 😲
 

once confirm as delivered, the blue "info" message becomes irrelevant. 

<img width="1484" alt="Screenshot 2023-05-09 at 8 06 58 PM" src="https://user-images.githubusercontent.com/74992958/237035268-27b06051-08ce-42cb-ac59-08a999d4e0af.png">

## Expected behaviour 🤔

Can we make it disappear ?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

automatically created outbound shipments (via sync)

## Your environment 🌱

 - Version: 1.1.11
 - Platform:
   - [ ] browser (chrome)

**Comment by roxy-dao** [comment]
Inbound invoices have info messages even if they are created manually... I think keeping the info message will help users know differentiate between an Inbound Invoice that has been manually created and one that was sent by another omSupply store...
What do you think? @mark-prins

**Comment by mark-prins** [comment]
I'd like to have two messages, the current one for the current state, and one which is just the first half, which is shown when the state is `Delivered` or `Verified`
