### ISSUE TITLE
Inbound shipment - all orders have number = -1

### ISSUE THREAD

**Issue by regotaina** [openmsupply/open-msupply#1734]
## What went wrong? 😲

Inbound shipment number is not generated - it returns "-1"  for all orders.

if you double click on the line there is no response.

## Expected behaviour 🤔

A new inbound shipment number is created for every order.

## How to Reproduce 🔨

1. Go to Inbound Shipment
2. Click on any order
3. See error
4. Note that for all orders "Number" = -1
5. Even when customer invoice is Fn, no number is generated

Screenshot for reference:

![image](https://github.com/openmsupply/open-msupply/assets/132425096/8f7208e3-2942-4bdf-9ae8-0a9778cc65cc)

OBS: Invoice number is generated, but inbound shipment number is not

![image](https://github.com/openmsupply/open-msupply/assets/132425096/5d76f7d1-6173-4d51-a439-215721d2b46e)

if you click on the lines, it takes to a blank page

![image](https://github.com/openmsupply/open-msupply/assets/132425096/30c55108-0599-4844-93cc-0902b42bc959)

## Your environment 🌱

 - Version: 1.1.10
 - Platform: omSupply 
   - [X] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
This was fixed in #1239 in v1.1.11. Would it be possible for you to test it on the latest version?

**Comment by regotaina** [comment]
> #1239

I'll test now! Thanks, @roxy-dao !

**Comment by regotaina** [comment]
@roxy-dao what's the V.1.11 for android/tablet? 
<img width="1357" alt="Screen Shot 2023-05-10 at 5 25 40 PM" src="https://github.com/openmsupply/open-msupply/assets/132425096/c4db24e3-6853-40d5-ad7a-58f7ab786af2">

**Comment by mark-prins** [comment]
Oh! did I not upload the android build? Will have a look for it

**Comment by regotaina** [comment]
Thanks, @mark-prins!

**Comment by mark-prins** [comment]
have made a build of the 1.1.11 version and uploaded now. sorry about that

**Comment by regotaina** [comment]
We downloaded the latest version (V.1.11), distributed to the tablet and it worked! 

Thanks @mark-prins and @roxy-dao :) 

![Screenshot_20230511_152250_openmsupply-client](https://github.com/openmsupply/open-msupply/assets/132425096/f1e6bb64-ff98-4099-a8d6-f84fc2a7e64a)

**Comment by roxy-dao** [comment]
> We downloaded the latest version (V.1.11), distributed to the tablet and it worked!
> 
> Thanks @mark-prins and @roxy-dao :)

Should numbers start at 1 instead of 0? 🤔

**Comment by regotaina** [comment]
> > We downloaded the latest version (V.1.11), distributed to the tablet and it worked!
> > Thanks @mark-prins and @roxy-dao :)
> 
> Should numbers start at 1 instead of 0? 🤔

Because on this store the previous inbound shipment generated was -1, maybe it returned 0 as the next available number.

I'll create a new store now and re-do the test. Because I have no inbound shipments on the new store, it should return 1, instead of 0.

I'll keep you posted!

**Comment by roxy-dao** [comment]
Yup thanks Taina ❤️
