### ISSUE TITLE
Json Forms (9) -- Schema validation

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#174]
Part of Epic #81

Enforce schema validation on exiting fields. The JSON Forms package provides validation functionality, we just need to show it in the UI.

We shouldn't be able to submit a form until the `data` object validates against the JSON schema.

**Comment by clemens-msupply** [comment]
I added a check if the form is valid and you can only save it if valid. I also added a red border for text controls with invalid data. Other controls don't give feedback though.

We probably can provide more information about what is wrong with the field but I think we can close this issue. We can open a new one when required.
