### ISSUE TITLE
Not sure if the format of the approval status is displayed as it should

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1741]
The internal order list show the approval status as expected
![image](https://github.com/openmsupply/msupply/assets/11624516/410843df-ef95-4316-a2b5-1d7a9b21a207)

but in the internal order itself, the format of the approval status is not in the same. I am not sure if it is really what you want to display

![image](https://github.com/openmsupply/msupply/assets/11624516/d2c83b6c-ea42-4b4d-b4bc-c158ff2d2ba9)

It should probably be the same format as in the requisition on the supplier side
![image](https://user-images.githubusercontent.com/11624516/237564502-9774dfe2-6bf8-4289-8704-94c597137a72.png)

Also the approval status is not translated in the internal order while it is in the requisition
internal order:
![image](https://github.com/openmsupply/open-msupply/assets/11624516/159ef6f3-7381-41b6-828c-f7b33ce87c3e)

requisition
![image](https://github.com/openmsupply/open-msupply/assets/11624516/62f8063d-c59b-4ab8-bd39-0c66fcf3622f)

_Originally posted by @alainsussol in https://github.com/openmsupply/msupply/issues/12954#issuecomment-1543262431_

**Comment by andreievg** [comment]
This should be fixed, can you please retest and close

**Comment by alainsussol** [comment]
Will close this as it has been fixed in version 1.1.12

![image](https://github.com/openmsupply/open-msupply/assets/11624516/65b9da36-0792-4a55-b223-b425641aefc2)
