### ISSUE TITLE
Infinite barcode sync

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1748]
## What went wrong? 😲

When barcode is created (probably when updated too), it causes infinite sync, this was noted here: https://github.com/openmsupply/open-msupply/pull/1725#pullrequestreview-1419705472

## Expected behaviour 🤔

Does not cause infinite sync, see proposed solution

## How to Reproduce 🔨

[Using this data file](https://drive.google.com/drive/u/1/search?q=short%20configure)

[And this branch](https://github.com/openmsupply/open-msupply/pull/1725#discussion_r1191789651) with [this change](https://github.com/openmsupply/open-msupply/files/11457192/patch.git.zip)(change is required, based on this comment):  

Start two seperate omSupply instances:

And sync them (credentials = supplier->pass, test->pass):

`APP_SERVER__PORT=8000 APP_DATABASE__DATABASE_NAME=db1name cargo run`
and in another terminal
`APP_SERVER__PORT=9000 APP_DATABASE__DATABASE_NAME=db2name cargo run `

On the supplier one do this:

```graphql
mutation MyMutation {
  updateStockLine(
    input: {id: "cce96ae0-72c2-4332-877d-47f55b6149c7", barcode: "somethingorother"}
    storeId: "0FD73FA090764B40AEFCAE38D4FA4012"
  ) {
    ... on StockLineNode {
      id
      availableNumberOfPacks
      barcode
    }
  }
}
```

## Other comments

I think we should have caught this in: https://github.com/openmsupply/open-msupply/pull/1555, it definitely needs more documentation but the reviewers should be aware now different sync data types should be implemented (i.e. if there is pull and push without store_id on the record, it's probably a shared type, which needs is_sync_update, this was introduced in program works originally)

## Proposed solution

is_sync_update, as done for requisitions here:

https://github.com/openmsupply/open-msupply/pull/1721

And database changes here: https://github.com/openmsupply/open-msupply/commit/5b41b5bdfddcbbca42edb898f2ca27a118c9f0db

**Comment by mark-prins** [comment]
Also "And I think one more issue needs to be made, rename value to GTIN for barcode (in api and in schema)"

**Comment by mark-prins** [comment]
I tried to find the datafile.. but the link for https://drive.google.com/drive/u/1/search?q=short%20configure is giving me nothing. I'll use a df I have already and try.

**Comment by andreievg** [comment]
> I tried to find the datafile.. but the link for https://drive.google.com/drive/u/1/search?q=short%20configure is giving me nothing. I'll use a df I have already and try.

https://drive.google.com/drive/u/1/folders/1-5JlYyYA5jArUl6LbSAvH3qsWE--nO2I, it's the short one here
