### ISSUE TITLE
[User Training Feedback] Group by item toggle disappear when you scroll down

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1759]
## What went wrong? 😲
 

![May-14-2023 12-56-08](https://github.com/openmsupply/open-msupply/assets/74992958/f466b964-a177-4748-9920-924578b262d9)

## Expected behaviour 🤔

should always be visible

## How to Reproduce 🔨

Steps to reproduce the behaviour:

![May-14-2023 12-56-08](https://github.com/openmsupply/open-msupply/assets/74992958/f466b964-a177-4748-9920-924578b262d9)

## Your environment 🌱

 - Version: 1.1.12
 - Platform:
   - [ ] browser (explorer, chrome)
   - [ ] desktop (macOS)

**Comment by DhanyaHerath** [comment]
Duplicate: https://github.com/openmsupply/open-msupply/issues/1760
