### ISSUE TITLE
[User Training Feedback] Stocktake (and possibly others) scrolling down the list is misleading / not working well

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1760]
## What went wrong? 😲
 

Here's how it looks on windows:

https://github.com/openmsupply/open-msupply/assets/9192912/e9b00567-dbeb-4999-bc9f-546f13aeadc2

## Expected behaviour 🤔

Users thought the item they were looking for was missing because it was hard to scroll down. 

- [ ] Users are not used to using 2 fingers on the touchpad to scroll up and down or from right to left. Right now, you have to use the touchpad to make the scroll bars appear. 

- [ ] scrolling bar is sometime misleading and you think you're at the end of the list even if there are a lot of items hidden. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

add a lot of items to a stoctake and try to scroll down without the touchpad

## Your environment 🌱

 - Version: 1.1.12
 - Platform:
   - [ ] browser (chrome)
   - [ ] desktop (windows)

## Proposed solution 
Move the Group By toggle up into the first section so that the second scroll bar goes away

**Comment by CarlosNZ** [comment]
> Move the Group By toggle up into the first section so that the second scroll bar goes away

Have made a PR for this specific suggestion, but will leave this issue open so we can discuss the wider scroll bar issue

https://github.com/openmsupply/open-msupply/pull/1775
