### ISSUE TITLE
Rename barcode `value` to GTIN

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1767]
Rename `value` field on barcode to GTIN (in database schema) and rename barcode in stockLineNode to barcodeGTIN or expose barcodeNode in stockLineNode, as per: https://github.com/openmsupply/open-msupply/pull/1725#discussion_r1191931610

**Comment by mark-prins** [comment]
Changed made in #1757 ( though I went with `gtin` rather than `GTIN` )
