### ISSUE TITLE
Cannot delete lines on Outbound Shipments

### ISSUE THREAD

**Issue by regotaina** [openmsupply/open-msupply#1776]
## What went wrong? 😲

After creating a new outbound shipment and adding a line, the lines cannot be deleted later on.
If you try to delete, an error message comes up: "Select rows to delete them ", despite the fact the rows are already ticked.

![Screenshot_20230515_165610_openmsupply-client](https://github.com/openmsupply/open-msupply/assets/132425096/b8da4206-2cb9-4b9e-a6cd-10fc8c15a67e)

## Expected behaviour 🤔

When you select a line and click on "Actions"> "Delete selected lines", the row should be deleted.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a new Outbound Shipment
2. Add a line with any item
3. Select the line and click on "Actions"> "Delete selected lines"4. Click on '.'
6. See error

## Your environment 🌱

 - Version:  V.1.11
 - Platform: 
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by regotaina** [comment]
Also tested allocating placeholder lines ( from the "Actions" menu) but it didn't work.

If I try to delete the full Outbound Shipment, I can. It's just the lines that cannot be deleted.

**Comment by regotaina** [comment]
@DhanyaHerath confirmed it doesn't occurs on Desktop version 

![telegram-cloud-photo-size-1-5120979160624376443-y](https://github.com/openmsupply/open-msupply/assets/132425096/7ed20578-a438-4629-9b57-4cc00c082221)

**Comment by mark-prins** [comment]
likely fixed with #1680 as there was an issue with the selected rows state. Can you retest with v1.1.12 to check?

**Comment by regotaina** [comment]
Hi @mark-prins 

bug fixed on new release V1.1.12

If I click on "Delete select lines", this pop up message comes up:
![Screen Shot 2023-05-16 at 2 28 13 PM](https://github.com/openmsupply/open-msupply/assets/132425096/1e77ebc4-574f-4d5d-b0d9-ec8ace2d90f4)

After I click on "OK", the line is deleted (as per screenshot):

![Screen Shot 2023-05-16 at 2 28 41 PM](https://github.com/openmsupply/open-msupply/assets/132425096/dcd20eae-4e49-452e-85e3-983c86d61080)

**Comment by DhanyaHerath** [comment]
Yay great news @regotaina! Can be closed
