### ISSUE TITLE
[User Training Feedback] OUTBOUND SHIPMENT : Add from master list is not available even when configured on the central server

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#1780]
## What went wrong? 😲
 
When creating an outbound shipment to an external customer and then adding a masterlist (configured in the Central server), there is no option available. 
<img width="1440" alt="Screenshot 2023-05-15 at 6 59 42 PM" src="https://github.com/openmsupply/open-msupply/assets/114633283/6f0b9eee-183c-4e35-9299-46f06d47b428">

Here are the configuration on the central server : 
<img width="1031" alt="Screenshot 2023-05-15 at 7 08 40 PM" src="https://github.com/openmsupply/open-msupply/assets/114633283/40153f2a-172f-453d-a723-6d8e2e1da1f8">

In this example, a master list has been created for this external client of this store but the result is No option.

## Expected behaviour 🤔

When adding a masterlist to an outbound shipment to an external costumer, the masterlists should be shown here.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'https://demo-djibouti.msupply.org/distribution/outbound-shipment/9?sort=itemName&dir=asc
2. Login as 'utilisateur12' password : pass
3. Go to 'Outbound shipment'
4. Click on 'New Shipment"
5. Choose Customer : Agent DOTS
6. Click on 'Add from a masterlist'
7. See error

## Your environment 🌱

 - Version: OpenmSupply 1.1.12
 - Platform:
   - [ ] android (tablet)
   - [X] browser (chrome)
   - [X] desktop (windows) potential similar error 
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment]
Andrei mentioned this may just be a refresh issue - needs testing

**Comment by andreievg** [comment]
> Andrei mentioned this may just be a refresh issue - needs testing

potential duplicate: https://github.com/openmsupply/open-msupply/issues/1666

**Comment by mark-prins** [comment]
Two issues:
1. you cannot add items from a program-based master list ( see #1697 )
There's a configuration problem here - the master list isn't available for the current store


![image](https://github.com/openmsupply/open-msupply/assets/9192912/290db2c0-40a7-43d8-9e40-ed6a7b1dcf28)

![image](https://github.com/openmsupply/open-msupply/assets/9192912/c9e27aa3-9c51-4f21-9395-d75d58c4672e)

**Comment by mark-prins** [comment]
the change made PR #1747 has caused an issue - no master lists are shown for outbound shipments. Updating now
