### ISSUE TITLE
Document deletion

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#179]
User must be able to mark document as (soft) deleted, e.g. when accidentally adding a document for the wrong patient.

Option 1.
- Add a status field like `"Active" | "Deleted" | ...` to the document to mark a document as deleted.
- The deleted document only points to its parent but doesn't need to contain data
- To un-delete a document just add a new document with status "Active" having the deleted document as parent.

~~Option 2: manage deletion in a separate table. Sync would need an extra mechanism to sync this table to multiple sites though.~~

Question: Also add a comment field for why a doc has been deleted?

- [x] add `status` field to the document table (`repository/src/db_diesel/document.rs`) possible values are "Active" | "Deleted"
- [x] add status to related structs, e.g. Document and RawDocument
- [x] fix existing code using status = "Active"
- [x] add service method to delete a Document: a deleted document doesn't has data and status is "Deleted" (parents are still set)
- [x] add service method to undelete a document: fetch the parent of the deleted document and us its data to create new version which has status "Active" and the parent is the deleted document
- [x] service tests
- [x] add graphql endpoint to delete a document

![2022-08-09_document_deletetion drawio](https://user-images.githubusercontent.com/88299195/183561679-3839cd4f-216e-4e92-a338-21e7b08c5a50.png)

**Comment by jmbrunskill** [comment]
Just to clarify Option 1.
For a patient we have multiple versions of a document for that patient.
To delete the document (and essentially hide all old versions) we'd add a new document version with status=deleted?

This makes sense to me, I don't see a lot of value of another table, unless we use to for other purposes. I could imagine we could have a document header table that contains information like a link to the latest version, status, latest edit time etc, which could make it faster to look up or aggregate information e.g 'number of documents created in the last week' (if that additional performance is needed?)
I imagine some aggregations might need to be more complex e.g. extracting data from the latest version for each patient anyway.

**Comment by mark-prins** [comment]
Option 1 sounds good, I don't think an additional table is needed.
I think a comment could be useful - not too sure why an encounter or a patient details document would be deleted, and given that it's a slightly unusual action, perhaps supplying a reason is wise.
