### ISSUE TITLE
[User Training Feedback] Pack quantities and Units quantities get switched during order process

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#1794]
## What went wrong? 😲
CENTRE YEUNISSE TOUSSAINT ordered to CAMME (supplier) 1 box of 100 units, when the order is sent to the supplier, only the requested unit quantities appear in the requisition. When an outbound shipment is created, the **unit quantities** to be shipped (100) appear under **pack quantity**  and the **number of packs** (1) appear under **packsize**. When stock is allocated (either automatically or manually), there is a switch and the correct numbers appear in the correct column.
![ezgif com-video-to-gif (7)](https://github.com/openmsupply/open-msupply/assets/114633283/8c892814-a9af-4e80-bcb8-35c306e73f79)

This is confusing for the user (supplier) because 1. when they receive the requisitions, they don't know what is requested (packs or units) 2. there is a switch between columns between before and after allocation.

I understand that the reasoning behind this is that there shouldn't be any packsize or packs defined in a requisition since a supplier should be able to send any packsizes and packs. Because we added this notion of ordering per packs for Djibouti, the whole ordering cycle is switching between requested units and requested packs.

## Expected behaviour 🤔

When an outbound shipment is created, the **unit quantities** (100) appear under **unit quantities** and the **number of packs** (1) appear under **pack quantity**. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to [https://demo-djibouti.msupply.org/distribution/outbound-shipment/8?sort=itemName&dir=asc](url)
2. Username : msupplysupport / password : pass / Store : CAMME 
3. Click on 'outbound shipment' 
4. . See error under outbound shipment #12 or #13

## Your environment 🌱

 - Version: V.1.1.12
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment]
Hey @Pauline-mSupply, I realised we haven't given you an explanation for this one. I think this is the correct behaviour - when the outbound shipment is created, the lines added are placeholders. Placeholders are always in units, so in your example you see 100 units (which is to say 100 pack quantity of packsize 1). 

When you clicked Allocate, it then tries to match that placeholder line with the stock you have on hand. In your case, you had available boxes of pack size 100. One of those packs is enough to fulfill the order, so you then get a line with 1 pack quantity of packsize 100. 

Generally it really makes sense for placeholders to be in units - items can have multiple packsizes, and you don't know what's available until it's allocated.
