### ISSUE TITLE
When integration step takes a long time provide user feedback 

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1802]
When doing the initial sync for the patient program module with a dataset of about 880 patients and 10000 encounters the integration step took about 15-20min (this step is usually very fast).

This was for omSupply Desktop (sqlite) on a machine with only 8Gb of ram and our guess was that the machine started swapping memory to the hard disk (there wasn't much CPU usage going on).

After about 15min, to debug the problem it has been attempted to set the warning level to `Info` and to restart the local server. Restarting the server service didn't succeed, i.e. the service couldn't be stopped. After a reboot the integration succeeded relatively quickly without error. So maybe the reboot freed up some resources for the integration. However, the initial installation happened after a fresh reboot.

## Suggested solution

What would be nice would be some user feedback if the integration step is making progress.

**Comment by andreievg** [comment]
Duplicate: https://github.com/openmsupply/open-msupply/issues/886
