### ISSUE TITLE
omSupply Desktop: discovery and login problem without network device

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1803]
Initial setup: Desktop machine with Wi-Fi dongle unplugged

After the omSupply Desktop installation the local server couldn't be discovered. After plugging in the Wi-Fi dongle the local server was found. 

Main issue was that omSupply stopped working when unplugging the Wi-Fi dongle, e.g. couldn't reach the login page.

## Expected behaviour 🤔

Steps that don't need internet should work without network.

## Other observations:
- It was not possible for the mobile version to discover the server when connected to the same Wi-Fi
- Also when tethered over a USB cable the server couldn't be discovered 

This mobile discovery problem is maybe related to #1799

**Comment by andreievg** [comment]
@richardmoizeau @Pauline-mSupply 

Had the same issue during Deployment.

I found a fix that involves adding loopback adapter [here](https://techhub.hpe.com/eginfolib/networking/docs/sdn/sdnc2_5/5998-7318prog/content/s_sdnc-dev-nw-adapter-install.html):

![Screenshot 2023-05-22 at 11 37 09 AM](https://github.com/openmsupply/open-msupply/assets/26194949/3c17fa7e-b8be-4185-9de9-9f1fa1a00480)

In my case it wasn't Microsoft Loopback Adapter, it was Microsoft KM-TEST Loopback Adapter.

As a solution we could add this adapter in installer, or do the graphql query to port + 1 of localhost to see if there is a result and add this as server, the only issue with this is that port could change ?

**Comment by Pauline-mSupply** [comment]
@andreievg : it worked for 1 computer out of 3 so far. I have asked Alassane and Noel to see if they can find some clues as to why it didn't work, hopefully we'll have more info on this. For context : their current wifi is provided by a SIM Card router that needs to be recharged with data every month, manually. So we can be sure that in 3 months, no recharge will be done....

**Comment by andreievg** [comment]
> @andreievg : it worked for 1 computer out of 3 so far. I have asked Alassane and Noel to see if they can find some clues as to why it didn't work, hopefully we'll have more info on this. For context : their current wifi is provided by a SIM Card router that needs to be recharged with data every month, manually. So we can be sure that in 3 months, no recharge will be done....

Thanks for update @Pauline-mSupply.

The only thing i would suggest, is restarting the service after adding loopback interface and maybe changing PC name (pc name not to have any special characters, just english letters and not very long, not sure what not very long is). Ohh and it would be great if they can do `ipconfig` in command prompt and capture that output

**Comment by clemens-msupply** [comment]
@andreievg did you already tried to change the service name using https://docs.rs/astro-dnssd/0.3.2/astro_dnssd/struct.DNSServiceBuilder.html#method.with_name ?

I could give it a try otherwise. We could try to sanitize / shorten the hostname... or just choose our hardware id?

**Comment by andreievg** [comment]
@clemens-msupply one thing I've noticed, after disconnecting network and before adding loopback, was that the app didn't discovery anything at all, and previous problem (before the name was changed and when connected to network) app was discovering omSupply service, but didn't have host (host address)

**Comment by Pauline-mSupply** [comment]
@DhanyaHerath

**Comment by clemens-msupply** [comment]
@Pauline-mSupply what exactly is not working for you? The initial discovery? or the normal usage after the desktop app is wired up with the central server (i.e. after the blue screen) ? or both?
For example, if only discovery is the problem we could work around it by temporarily connecting it to some network.

**Comment by mark-prins** [comment]
On windows without the network plugged in you can do this:

![image](https://github.com/openmsupply/open-msupply/assets/9192912/9d3e6d3c-04e6-4c31-a7bc-7987d5d5113d)

i.e. the site is available in a browser, but the connection times out.

**Comment by clemens-msupply** [comment]
This is with loopback device, right?

I just tried again in my VM:
- no connection, no loopback -> now access to the server
- no connection but loopback device -> discovery didn't work straight away but after a server service restart it was working...

Didn't someone mentioned before that discovery can stop working on the server?
