### ISSUE TITLE
[Deployment Feedback] Sync Issue linked to Barcode

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1805]
## What went wrong? 😲
 

![photo_2023-05-20 13 51 55](https://github.com/openmsupply/open-msupply/assets/74992958/c3db05e3-9713-4360-a9b8-ca80ebc72b55)

the sync issue appeared when I tried the barcode scanner, I may have scanned the same barcode over and over on multiple stock lines. 

## Expected behaviour 🤔

should sync properly or software should prevent me from doing whatever broke the synchronisation

## How to Reproduce 🔨

[This site](https://docs.google.com/spreadsheets/d/1ulrSduSkxGEtbS8HnXTsQ3l1TyGQqnK3CaOPoLTVtlY/edit#gid=1541077420&range=B4)

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by andreievg** [comment]
@clemens-msupply, do you know how there could be a change log record like this ? We can't actually delete barcodes (or at least there is no code for this that I could see). 

@richardmoizeau I think this would mean this site can't sync at all and would require some update:

## Fix A

Delete this change log with migration (migration could just be by that id or could check all barcodes or all records in change log to be valid, delete invalid ones)

## Fix B

Silent errors, still log it (similar to pull)

## Fix C -  no code

Stop omSupply server service, connect to DB (via db client, remove this from change log), start service, try to sync.

None of the above fix the core issue, not sure how this could happen

**Comment by clemens-msupply** [comment]
Is this sqlite? The unique constraint could cause a row to disappear:
https://www.db-fiddle.com/f/izBry7rdXHZ2S37DNpAuZ9/0

**Comment by andreievg** [comment]
> Is this sqlite? The unique constraint could cause a row to disappear:
> https://www.db-fiddle.com/f/izBry7rdXHZ2S37DNpAuZ9/1

Wow brilliant !

To replicate (there could be a simplified way, but wanted to record at least one way of replication):

With electron and sqlite, have two stock lines with different packs, enter `321` for barcode in first one, save stock line, enter `321` in barcode for second one, save stock line (should get an error notification), clear barcode from first one, save stock line, enter `321` to second one, save stock line

**Comment by andreievg** [comment]
https://github.com/openmsupply/open-msupply/assets/26194949/36c30d53-41eb-4029-87ae-8b1d6aff0438
