### ISSUE TITLE
[Deployment Feedback] Stocktake: when adding an item to a stocktake, you have to click on Add a new lot to enter data

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1809]
## What went wrong? 😲
 

Stocktake: when adding an item to a stocktake, you have to click on `Add new Batch` to enter data
<img width="1109" alt="Screenshot 2023-05-21 at 7 32 05 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/5a592b3b-c544-428a-8ddf-f432a2db1ae4">

This is not the case when items are being added from a location or a master list. When doing so, you already have the stock line ready for you ;)

## Expected behaviour 🤔

Clicking on `Add a new Batch` sounds like a non necessary step when there is no stockline already

## Your environment 🌱

 - Version: 1.1.13-rc5
 - Platform:
   - [ ] desktop (windows)
   - [ ] desktop (macOS)

**Comment by mark-prins** [comment]
To discuss: it was a deliberate though perhaps not very considered decision.

Adding a batch automatically in this case will make the modal behave inconsistently, as you say, when there are stock lines these are shown but not new batch is added for you. The concern is that if we add a new batch, then users might expect that to be an existing batch line. Requiring them to always click the add button makes is clear when a batch is being added or not.

**Comment by andreievg** [comment]
Unanimous decision to close
