### ISSUE TITLE
[Deployment Feedback] Program orders: when creating an order and then deleting it, period is no longer available

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1810]
## What went wrong? 😲
 

for demo purpose, created an internal order to show them how it would work. Then I deleted it. When creating a new one, I realised that one period was no longer available even though order was never sent. 

## Expected behaviour 🤔

Option 1: period should be made available again if order is deleted, should be only "used" when order is sent
Option 2: you should not be able to delete a program order
Option 3: you should be able to "reactivate" a period on the server

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 1.1.13-rc5
 - Platform:
   - [ ] desktop (windows)
   - [ ] desktop (macOS)

**Comment by andreievg** [comment]
Option 1 if it's replaceable

**Comment by mark-prins** [comment]
To check: is a requisition delete logged?

**Comment by mark-prins** [comment]
Unable to replicate. Followed the steps and the period is available for the next new internal order
