### ISSUE TITLE
[Deployment Feedback] Dashboard page (welcome screen) doesn't update

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#1819]
## What went wrong? 😲

During training, a user noticed that they had 3 expired batches in their dashboard. They removed the expired stock with a stocktake, checked that no late expiry date appears in but when they went to check their dashboards, 3 expired batches were still showing instead of 0. 
Facility : POLYCLINIQUE YONIS TOUSSAINT - LABO (live Djibouti server)

## Expected behaviour 🤔

If expired batches are removed and no longer appear in 'View stock'. The dashboard should show 0 expired items in stock. 

## How to Reproduce 🔨

1. Add expired items in stock with a stocktake
2. Have a look at the dashboard : it should show the number of expired batches
3. Remove expired items with a stocktake (choose reason _produits périmés_)
4. Have a look at the dashboard : See error

## Your environment 🌱

 - Version: Open mSupply v1.1.13 (Before May 22nd release)
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [X] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

@richardmoizeau

**Comment by mark-prins** [comment]
Likely to be cached data. A refresh of the page would fix it - perhaps though we simply remove the cache from the dashboard queries

**Comment by Pauline-mSupply** [comment]
How do I refresh the page on a Desktop app version of the software ?

**Comment by CarlosNZ** [comment]
Can confirm that this is more than a caching issue. If I run the query directly in a GraphQL browser, I get the same "expired" count even after changing the stock levels as described above. 

Query:
```gql
query stockCounts($storeId: String!, $daysTillExpired: Int, $timezoneOffset: Int) {
  stockCounts(
    storeId: $storeId
    daysTillExpired: $daysTillExpired
    timezoneOffset: $timezoneOffset
  ) {
    expired
    expiringSoon
  }
}
```

Returns:
```json
{
  "data": {
    "stockCounts": {
      "expired": 15,
      "expiringSoon": 15
    }
  }
}
```

And those numbers aren't changing as I remove the expired stock via stocktakes. Must be the back-end calculations to return these values are only refreshed periodically. 

I might poke my nose into that tomorrow and see what's going on.

**Comment by richardmoizeau** [comment]
Thanks Carl for following up on this. Yes, we already tried a hard refresh on the computer where we first identified the issue and it's definitely not the cache.

**Comment by nisha-dangol** [comment]
Hi @roxy-dao 
While testing v1.3.0 exe, I notice that the `Expired batches` count is updating in the dashboard as per the changes done in stocktakes, but I do not see clear changes in `Batches expiring in a month` value. Should submit a separate issue for that?

**Comment by roxy-dao** [comment]
> Hi @roxy-dao While testing v1.3.0 exe, I notice that the `Expired batches` count is updating in the dashboard as per the changes done in stocktakes, but I do not see clear changes in `Batches expiring in a month` value. Should submit a separate issue for that?

This was recently fixed in https://github.com/openmsupply/open-msupply/issues/2123#issue-1862436059

**Comment by nisha-dangol** [comment]
> > Hi @roxy-dao While testing v1.3.0 exe, I notice that the `Expired batches` count is updating in the dashboard as per the changes done in stocktakes, but I do not see clear changes in `Batches expiring in a month` value. Should submit a separate issue for that?
> 
> This was recently fixed in [#2123 (comment)](https://github.com/openmsupply/open-msupply/issues/2123#issue-1862436059)

Not in v1.3.0 then I guess!

**Comment by mark-prins** [comment]
The PR for the expired items count on the dashboard did get into v1.3.0. 
Can you give some more details of the issue @nisha-dangol ?

**Comment by nisha-dangol** [comment]
> The PR for the expired items count on the dashboard did get into v1.3.0. Can you give some more details of the issue @nisha-dangol ?

I entered a stocktake with batches expiring in a month, i.e., I kept expiry date as 09/2023 while the date entered is yesterday/today (08/2023). In this scenario, I expect the dashboard to show those numbers in `Batches expiring in a month` value!

**Comment by roxy-dao** [comment]
> I entered a stocktake with batches expiring in a month, i.e., I kept expiry date as 09/2023 while the date entered is yesterday/today (08/2023). In this scenario, I expect the dashboard to show those numbers in `Batches expiring in a month` value!

Ah, so expiry dates actually save for the end of the month... so for 09/2023, the expiry date is 30/09/2023, and is outside the one month range (if you did that yesterday then one month would be 29/09/2023, I'm guessing)

**Comment by nisha-dangol** [comment]
> > I entered a stocktake with batches expiring in a month, i.e., I kept expiry date as 09/2023 while the date entered is yesterday/today (08/2023). In this scenario, I expect the dashboard to show those numbers in `Batches expiring in a month` value!
> 
> Ah, so expiry dates actually save for the end of the month... so for 09/2023, the expiry date is 30/09/2023, and is outside the one month range (if you did that yesterday then one month would have be 29/09/2023)

What I'm finding weird in my test scenario is:
This store clearly has 2 expiring batches:
<img width="1495" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/fd7b2f2f-5369-4058-ba7c-110ba9a486e3">
<br>
and yet the dashboard shows only 1 batch in `Batches expiring in a month` value :
<img width="1497" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/5d5e268e-9b64-438b-be7c-834029f135f4">

**Comment by roxy-dao** [comment]
> What I'm finding weird in my test scenario is: This store clearly has 2 expiring batches: 

Sorry, I can't seem to reproduce this. Could you send me the datafile you're using?

**Comment by nisha-dangol** [comment]
> > What I'm finding weird in my test scenario is: This store clearly has 2 expiring batches:
> 
> Sorry, I can't seem to reproduce this. Could you send me the datafile you're using?

Sure, [here's the link](https://www.dropbox.com/scl/fi/9xfdz1f8lato40s57mqof/omsupply-database-1819.zip?rlkey=zmw7b4m45z6d1975joe7u3ggn&dl=0) to that datafile.

**Comment by roxy-dao** [comment]
Found the problem, one of your stock lines that is expired has 0 available_number_of_packs, so it isn't counted in the count (:

**Comment by nisha-dangol** [comment]
> Found the problem, one of your expired stock lines has 0 available_number_of_packs, so it isn't counted in the count (:

Ooh.. that makes sense. I realized that the stocks(expiring batch) in my datafile were still in some `new` status Outbound shipment lines, and thus not available, so the dashboard did not show them.
Will move this to Done!
