### ISSUE TITLE
Breadcrumb improvement -- allow non-url elements

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#182]
Not sure if this would be complicated or not, but thought it worth mentioning as a possible improvement.

Currently, the Breadcrumb component is made up of URL parts, which is fine for things like "/Customers/#12" but not so great when we have IDs in the URL:
![Screen Shot 2022-06-23 at 2 49 26 PM](https://user-images.githubusercontent.com/5456533/175196910-3ff0b212-89ac-4568-96e6-f50fd20bacf9.png)

Would be good if we could provide some kind of mapping function to the Breadcrumb component, so it could display a field other than whatever is in the URL. In this case, the patient name rather than their id (`patient2`) would be nice.

**Comment by mark-prins** [comment]
yes! - Bijay has raised this as a concern too. The `item` has the same problem

**Comment by mark-prins** [comment]
Already done. have just added PR for patients too.
