### ISSUE TITLE
Translate number of packs differently for stocktakes

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1822]
## Is your feature request related to a problem? Please describe 👀

In French, we'd like to have number of packs (`label.num-packs`) translate as
- `Stock Théorique (boites)` when in stocktakes
- `Qté (boites)` elsewhere

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by richardmoizeau** [comment]
@mark-prins

![photo_2023-05-25 19 34 17](https://github.com/openmsupply/open-msupply/assets/74992958/b26f63c9-60a9-4302-bcee-2e7054d50e7a)

did a forced reload and still showing the above - other strings were also "old" - I have replaced "emb." by "boites" everywhere

**Comment by richardmoizeau** [comment]
forgot to re-open

**Comment by mark-prins** [comment]
This is what I see on v1.1.14 - not sure what to suggest from here. It's working for me.
Can you retry with the latest version?

<img width="159" alt="Screenshot 2023-05-29 at 4 09 22 PM" src="https://github.com/openmsupply/open-msupply/assets/9192912/0a58e858-1e2b-4149-9d6e-edddcba921b0">

**Comment by DhanyaHerath** [comment]
@mark-prins will recheck if we have access to DJ teamviewer

**Comment by mark-prins** [comment]
unable to tv to dj. the central CAMME server however, that has:

![image](https://github.com/openmsupply/open-msupply/assets/9192912/e4875c3f-7414-4457-a812-9e8c119a7144)
