### ISSUE TITLE
[Deployment Feedback] Inbound Shipment: when created manually, you cannot change the quantity when Inbound Status is "Delivered"

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1823]
## What went wrong? 😲
 

Only for manual inbound shipment (it seems)

1. Create a manual Inbound Shipment
2. Add a stock line with a quantity 
3. Confirm status as delivered 
4. Try to change the quantity

## Expected behaviour 🤔

1. user should be able to create an inbound shipment as per an invoice or a delivery note for instance and confirm it as delivered
2. and then change the quantity if there is any missing packs before confirming the stock as "Verified"

## How to Reproduce 🔨

See above

## Your environment 🌱

 - Version: 1.1.14
 - Platform:
   - [ ] desktop (windows)
   - [ ] desktop (macOS)

**Comment by roxy-dao** [comment]
I can still change the quantity of a manually created inbound invoice line even after the status is delivered... Were there any particular steps you took to produce this bug? Or if possible, could you post a video of the bug? 🤔

**Comment by mark-prins** [comment]
Unable to replicate using the current develop branch.
