### ISSUE TITLE
Text in disabled dropdown is too far left

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1829]
As in screenshot, disabled text is too far on the left (fixed when it is enabled)

![Image](https://user-images.githubusercontent.com/88299195/240119920-d9be8101-6f6e-4351-bd78-b1afeaae93f6.png)

**Comment by roxy-dao** [comment]
Component no longer in use.
![2023-06-22 09 49 44](https://github.com/openmsupply/open-msupply/assets/61820074/1557468f-d5b7-40a3-ad82-f07ef2f56b33)
