### ISSUE TITLE
No space between Date inputs on Report modal

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1830]
This example in the "List appointments" report for PNG, but I assume the problem would exist for any report that takes more than one input argument:

![Image](https://user-images.githubusercontent.com/5456533/240121367-610c55d4-9fd2-4f39-a08d-5e2568d7f5ed.png)

**Comment by roxy-dao** [comment]
Completed in schema repo

**Comment by nisha-dangol** [comment]
Spacing looks good; moving to Done!
