### ISSUE TITLE
No save confirmation for patient details view when selecting a different tab

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1835]
To reproduce:

- Edit a patient (save button should now be enabled)
- Move to the programs tab (without saving)
- Move back to the patient detail tab
- Changes to the patient are now lost

Expected behaviour: show confirmation dialog (same as done when leaving the page)

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.3.00 exe

- [x] Go to a patient and edit their details.
- [x] Leave patient view by navigating to another page.
- [x] See alert
