### ISSUE TITLE
Barcode scanning: batch incorrect

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1838]
## What went wrong? 😲
 
For some specific products, when you scan, the serial number is appended to the batch.

![telegram-cloud-photo-size-4-6010265943286070315-y](https://github.com/openmsupply/open-msupply/assets/9192912/ec1143e8-f69c-4773-abf3-23c745a364ab)

![telegram-cloud-photo-size-4-6010265943286070316-y](https://github.com/openmsupply/open-msupply/assets/9192912/2ecdede7-f436-4de7-9f00-33bf2ccc2f90)

![telegram-cloud-photo-size-4-6010265943286070317-y](https://github.com/openmsupply/open-msupply/assets/9192912/11dcc466-1493-4680-b7a8-e504a523957e)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
Unable to recreate when scanned with a zebra scanner in keyboard mode. A tidied (scannable) image is below

![fuzzy-barcode](https://github.com/openmsupply/open-msupply/assets/9192912/4799d691-b819-4136-9f67-9f0c4d9d3abd)

**Comment by richardmoizeau** [comment]
happened again today with 14-rc3 for the same product it seems 

![photo_2023-05-25 19 43 59](https://github.com/openmsupply/open-msupply/assets/74992958/90f265c5-5ff2-431f-b0fb-6acd2e716b31)
![photo_2023-05-25 19 44 00](https://github.com/openmsupply/open-msupply/assets/74992958/b42e2872-ef7b-4576-9216-b0042a1bd1db)
![photo_2023-05-25 19 44 01](https://github.com/openmsupply/open-msupply/assets/74992958/92e5e0e3-db63-4971-b5cd-12ef8856b155)
![photo_2023-05-25 19 43 58](https://github.com/openmsupply/open-msupply/assets/74992958/ebcfac9c-2876-4535-958c-d3fa13be1e8a)

I looked at the console again but there was nothing to see... sorry

**Comment by mark-prins** [comment]
Tested on current version (v1.1.14) using a zebra scanner and it worked fine.

![image](https://github.com/openmsupply/open-msupply/assets/9192912/594f307d-4e9e-4996-9d8e-aea687453e9c)

**Comment by andreievg** [comment]
Can't replicate here, closing, if this happens again we can link the issues and priorities.

**Comment by mark-prins** [comment]
Was keeping this one open, awaiting testing with the teco scanner that Richard has.

**Comment by richardmoizeau** [comment]
@craigdrown has it

**Comment by craigdrown** [comment]
@andreievg has it and no returns! ☮️

**Comment by andreievg** [comment]
I have it, but I do we have any budget for this work ? Afaik the stock view barcode scanning was out of scope (not in contract), and the bug is not critical, it just adds serial to the end of batch

**Comment by mark-prins** [comment]
The ability to scan stock by barcode was in scope - check the requirements under 'adding to an outbound shipment using a barcode scanner' - but even so, this is functionality which we have delivered, that the client is using, and that has a reported bug in it.

Even though non-critical, I think it is still worth trying to replicate using the client's scanner. If we can replicate, surely that's a simple enough fix, and should be covered by the support budget (is there is one!)

**Comment by mark-prins** [comment]
Working with the second barcode above - here's a tidied up version, which scans for me:

![240980815-b42e2872-ef7b-4576-9216-b0042a1bd1db](https://github.com/openmsupply/open-msupply/assets/9192912/6e62ef00-db1c-45bf-8cfc-9bfb4bcfb70b)

This results in 

**Teco**
`010890409382716717240229103131643211H41FFGRCW11210315`
**Zebra**
`010890409382716717240229103131643211H41FFGRCW11210315`

The issue is that the Teco isn't detecting a group separator before the serial number

**Comment by mark-prins** [comment]
Sorry @richardmoizeau I see no way of resolving this one

**Comment by GaryWilletts** [comment]
@mark-prins to be clear, this is a problem with the Teco scanner?

**Comment by mark-prins** [comment]
Yes - in keyboard mode at least. To be fair, we haven't tried serial mode. That would require a reasonable development effort, and I doubt that the result would differ, as the problem is with the interpretation of the code and not the transmission of the information.

The problem is that the Teco scanner isn't parsing that barcode in the same way that the zebra does. It sends us this string as part of the barcode: `103131643211H41FFGRCW` this, which can only be interpreted as a batch (identified by the leading `10`) which ends with `W` since there's no separator within that string.

**Comment by marthakeezy** [comment]
Confirmed this is parked for now, so moving to Done to clear out the QA board ✅
