### ISSUE TITLE
Make person search control more powerful

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1840]
![image](https://github.com/openmsupply/open-msupply/assets/88299195/776bef06-b8d4-4588-9fff-67785535beb7)

Currently, a person can be looked up by code. This turned out to be not enough (code is often not even set). What would be more useful would be to look up a patient by program enrolment ID.

Another useful lookup option would be by name and enrolment ID. Futhermore, it must be possible to enter a person that is not in the system.

For example, have a form like:
```
mSupply ID:       _____________  (usually not shown in the UI, just list here for clarity)
ARV Enrolment ID: _____________  (programEnrolmentID if the patient is enroled)
First Name:       _____________
Last Name:        _____________
Address:          _____________
```

- [ ] When entering data in the ID and name fields (first, last, code and enrolmentId), a search for an existing patient is done using the already entered data. Search results are suggested in a drop down.
- [ ] When a found patient is selected from the drop down the found mSupply patient ID is set.
- [ ] If the mSupply patient ID is set, the input fields are disabled for editing and the fields display the patient information from the patient record (replace edit view with a JsonForms that display the found patient information)
- [ ] There should also be a clear button to clear the mSupply patient ID and revert to edit mode (would be good if previously entered data can be restored)
- [ ] If the mSupply patient ID is not set, the user can enter details manually

**Comment by CarlosNZ** [comment]
So we'd potentially be searching by fields only contained in the JSON document? Would this be a performance issue?

Also, seems like we'd want the "search by" field(s) to be specified in the configuration, since it could easily be for fields that only exist in certain instances.

**Comment by clemens-msupply** [comment]
All search fields should be in the DB, e.g.:

- firstname, lastname
- code, code2
- encounter enrolment id (program_enrolment table)

Think we could have multiple input fields that look like a normal person entry group. Like for an address lookup field where you start typing your number and street and all other input fields like city and zip are autopopulated when selecting a found address. Think this could simplify the search a bit.

**Comment by clemens-msupply** [comment]
Also needed by #1058

**Comment by nisha-dangol** [comment]
Hi @CarlosNZ . I notice a bug here where the patient I select from the list of searched results is not getting selected; but the first one is only getting selected! Recording: https://recordit.co/S4MBEPHXbN
Submitted issue: #3051
