### ISSUE TITLE
Datepicker text field allows years < 1000, e.g. 23

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1842]
The date picker text input expects YYYY. However, entering a number like 23 works as well. This is confusing since this looks like a valid 2023 but the year 0023 is stored in the system.

![Image](https://user-images.githubusercontent.com/88299195/240428257-04e3501d-aa7c-46bd-b191-72b6227ad437.png)

![Image](https://user-images.githubusercontent.com/88299195/240428332-e0768177-886b-48e9-8948-25b72fa670a8.png)

- [ ] force to enter "0023" or don't allow years < 1000

**Comment by roxy-dao** [comment]
Wait for dependency updates.

**Comment by clemens-msupply** [comment]
Do you plan to update the dependencies? And do you know about some lib changes that will affect this?
