### ISSUE TITLE
Improved patient/program search to allow searching by program enrolment id

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1845]
Patient need to be found by:
- program enrolment id

Two options:
- add functionality to existing patient list (taking permissions into account)
- create new program enrolment list

Option 1 might be a bit trickier but nicer since there would only one list to find patients

- [x] Take permissions into account when searching by program enrolment id
   - [x] #1959

**Comment by roxy-dao** [comment]
Might need a design... Current header for patient view will get a bit cramped

**Comment by clemens-msupply** [comment]
Just looked at it a bit more and its already working! but its IMHO very misleading:


![Image](https://github.com/openmsupply/open-msupply/assets/88299195/3eb62a4c-43c5-40f1-bbcf-1ce0d3eef8d4)


Think the UI definitely needs some more explanation, e.g.
- in the search bar say what it can handle
- display column for enrolment id(s)

Some open questions:
- what to display when there are multiple program enrolment ids matching a search? (just concatenate them in the column?)
- permissions are not taken into account, so search results should be filtered by the user's allowed contexts (maybe we can split this out into another issue)

**Comment by clemens-msupply** [comment]
@roxy-dao what do you think about an "Additional Info" column which shows a list of programs the patient is enrolled in? e.g.

`[HIV Care Encounter (KAM0003)] [HIV Testing Encounter]`

(square brackets supposed to be ASCII art for the bubbles)

It might get a bit long though if patients are enrolled in many programs...


Notes for prescriptions where programs are disabled:
- we could either hide the column or simply not show the program information.
- we also need a way to customize the column labels, e.g. there is and hardcoded NUIC
