### ISSUE TITLE
Add note input field when creating a new encounter

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1846]
When creating an encounter, e.g. scheduling an appointment, add option to add at note in the encounter creation modal. E.g. to write down what should be done in the appointment.

**Comment by roxy-dao** [comment]
Where should the note be displayed? In the Encounter View side panel note component?

**Comment by CarlosNZ** [comment]
> Where should the note be displayed? In the Encounter View side panel note component?

All the other Create modal content is displayed in the header, so maybe there would be best? (If it can be made to look okay?)

**Comment by roxy-dao** [comment]
> All the other Create modal content is displayed in the header, so maybe there would be best? (If it can be made to look okay?)

Would the note be clearable/changed? 🤔

**Comment by clemens-msupply** [comment]
The data model supports a list of notes. So it might be better to add a new note if there is already an existing "old" note. Think there is some logic about when notes can be edited in the JSON forms component...

Think the notes would be too large to fit into the header.
