### ISSUE TITLE
For all transactions: add a delete button in the detail panel 

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1855]
## Is your feature request related to a problem? Please describe 👀

User are always looking for a delete button on the detailed view of any of the transaction (stocktake, inbound shipment, outbound shipment, internal orders, etc...)

## Describe the solution you'd like 🎁

- [ ] Add a delete button here: 

<img width="1512" alt="Screenshot 2023-05-25 at 7 21 30 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/543af8ce-2cf7-4daf-9e53-3b05194afd3a">

- [ ] side note: this could replace the current "actions" = "Copy to Clipboard" that does not seem to do anything by the way

### Describe alternatives you've considered 💭

another area in the

**Comment by mark-prins** [comment]
@richardmoizeau the 'copy to Clipboard' is, ironically, a copy of mSupply functionality. It does do something, and is likely not used by anyone. 
It was implemented early on when we had very limited api functionality and the front end team were putting in as many features as we could, without backend work. The button was on the designs, so we made it happen. 
Would be useful to know if it is actually useful or not. Currently it isn't available for android users and it will take a little time to implement on android.

**Comment by kahn-msupply** [comment]
🧪 TESTING

omSupply Develop 1.4 (Interpreted)
Chrome / Edge / Safari Browser
Tested for Stocktake, Inbound Shipment, Outbound Shipment and Internal Order.

- [x] Go to any of the areas mentioned above
- [x] Create a new invoice
- [x] Go to side panel and delete invoice
- [x] Get redirected back
- [x] Go to an invoice that can't be edited anymore
- [x] Go to side panel
- [x] Delete button should be disabled

LGTM!
