### ISSUE TITLE
Desktop cannot connect to server when no networks are available

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1856]
## Is your feature request related to a problem? Please describe 👀
This is #1803, again. The fix made for that issue works fine, but only for HTTP. When using a self-signed certificate to provide SSL, an error is thrown by `fetch`.

Have been unable to find a way for the web client to circumvent SSL errors, though this is possible in node.

In order to get the client working, I've implemented a change in the v1.1.14-rc3 release. This adds the server check to `connectToServer` before connecting. 

## Describe the solution you'd like 🎁

- [ ] Implement the server health check before connecting to android. This was only done for electron so far. 
- [ ] Add error handling - if the check fails, raise that to the renderer. This allows the 'unable to connect' message to be shown almost immediately rather than waiting.
- [ ] Rename `connectToPreviousTimedOut` and remove the `setInterval`

Also, investigate if this can be done from the web app, as that would remove the need to check the server _every_ time you connect to a new server. 

### Describe alternatives you've considered 💭
Installing a loopback adapter also works - this is quicker however because we don't have to wait for `dnssd` to locate the server before connecting.

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by richardmoizeau** [comment]
This has been fixed right ? by @mark-prins le génie ;)

**Comment by mark-prins** [comment]
> This has been fixed right ? by @mark-prins le génie ;)

It has now 😄 I had to re-implement in the develop branch.
