### ISSUE TITLE
Remote authorisation module: add the possibility to authorise in quantity of default pack size (or "packs")

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1858]
Following discussion between customer, @DhanyaHerath and @craigdrown, @craigdrown asked me to do a mockup of they would like to have: 

## Is your feature request related to a problem? Please describe 👀

user is used to deal in packs not in units. 

## Describe the solution you'd like 🎁

have the possibility to authorise in quantity of default pack size (or "packs")

<img width="1024" alt="Screenshot 2023-05-28 at 5 59 26 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/7b6fc951-616a-4410-b1b2-0eeb0bb2bde8">

- [ ] Add a column called "Authorised Quantity (Packs)" (FR: "Quantité Autorisée (Boites)")
- [ ] Column "Authorised Quantity (Units)" (FR: Quantité Autorisée (Unités) is not editable and will only display the following calculation: pack size (FR: "Conditionnement") x "Authorised Quantity (Packs)"
- [ ] you can shorten "Conditionnement" to "Cond." if needed

### Describe alternatives you've considered 💭

That's the only thing I could think of my tired brain but I'm sure there is other stuff we can do. May be just as good to have a button to switch the whole interface in "number of packs" based on the default pack size. For Djibouti, default view would be "Quantity in packs". 

Impacted fields: 
- Supplier SOH
- Customer SOH
- Suggested Quantity (2 decimals max)
- Customer AMC (2 decimals max)
- Authorised Quantity

When in packs, all word "(Units)" (FR: "(Unités)") must be replaced by "(Packs)" (FR: "(Boites)") 

### Moneyworks Jobcode 🧰

DJ

**Comment by mark-prins** [comment]
This would only apply for one customer though - existing clients using the authorisation app are using units. 
We can't change the existing functionality, and we do not have customisation per client in this app.

We could add the packs column and have it calculated based on default pack size. I wasn't keen to do much more than that.

**Comment by andreievg** [comment]
I recommend a toggle

**Comment by DhanyaHerath** [comment]
A toggle could work well (default to units, and then have the user's preference stored in local storage for that browser?). But I'm not certain how much work it would be. 

Other option as Mark said would be to add the packs column

**Comment by mark-prins** [comment]
Add a toggle to switch:
authorise in packs / authorise in units

New column order:

- Comment
- Default pack size
- Requested (packs)
- Authorised (packs)
- Requested (u)
- Authorised (u)

**Comment by mark-prins** [comment]
The change made in [this PR](https://github.com/openmsupply/msupply-authorisation-web-app/pull/71)

**Comment by DhanyaHerath** [comment]
I think this can now be closed - done in a separate repo?

**Comment by kahn-msupply** [comment]
Moving to 'Done' in testers project as this was tested here -> https://github.com/openmsupply/msupply/issues/13172
