### ISSUE TITLE
Configuration changes

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#186]
The changes to `base_dir` result in the server not starting when running in release mode, with existing installations.

In release, the certificates are required for the server to start. The example yaml file has `base_dir: "app_data"` - though if you do use this value, the `certs` folder has to be moved to be under `app_data` - this is a bit of a trap and should be added as a warning to the readme. All current production installs have been updated, so it shouldn't be an issue now - which is why I think updating the docs is enough for now

I wonder though if that folder is the best place for certs? Does it make sense to have them under 'app_data'?
Should the configuration be under there too?

Two other issues, up for discussion
- I think the server should run with a default setup. Currently, to get the server to run, you must create a local.yaml file and add in the `base_dir` - or edit the base.yaml. Can we either add to base.yaml or have the server default to a value?
- A default would be useful: currently there are 139 instances of a hard coded "app_data" as this is required when instantiating a new ServiceProvider. Would be easier when creating tests if the value could be a default instead

**Comment by roxy-dao** [comment]
> * I think the server should run with a default setup. Currently, to get the server to run, you must create a local.yaml file and add in the `base_dir` - or edit the base.yaml. Can we either add to base.yaml or have the server default to a value?

The base_dir was added to base.yaml in #131 😄

**Comment by mark-prins** [comment]
oh! that's great, thanks Roxy 😁

**Comment by mark-prins** [comment]
I'm just going to close this one and leave `app_data` in place
