### ISSUE TITLE
Database error when viewing Programs tab after starting but not saving a new encounter

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1863]
Here's how to reproduce:

- Load a patient and add them to a Program (or pick someone already in a program but with no encounters)
- Start a new encounter, fill in the initial "Creation" modal, then go into the main encounter tab
- DON'T save the encounter, but exit out of it without saving
- Now go to the Programs tab for that patient -- you should get the following error, with nothing listed in the table:

![Screenshot 2023-05-29 at 3 30 37 PM](https://github.com/openmsupply/open-msupply/assets/5456533/950ea3b1-35d9-4a62-ba48-118dfb6d956a)

**Comment by clemens-msupply** [comment]
This is because there is some invalid query parameter in the url, right? We have to clean up the params when changing the tab...

**Comment by mark-prins** [comment]
I get the same error if you click on the encounters tab then the programs tab for a patient that exists, has a program and has no encounters.

I also don't understand the original steps fully.

> Start a new encounter, fill in the initial "Creation" modal, then go into the main encounter tab

does `go into the main encounter tab` mean `click save`? and then you click `Cancel` on the page that you go to?
which takes me to the programs view, so `Now go to the Programs tab for that patient` isn't required?

**Comment by roxy-dao** [comment]
> I get the same error if you click on the encounters tab then the programs tab for a patient that exists, has a program and has no encounters.
> 
> I also don't understand the original steps fully.
> 
> > Start a new encounter, fill in the initial "Creation" modal, then go into the main encounter tab
> 
> does `go into the main encounter tab` mean `click save`? and then you click `Cancel` on the page that you go to? which takes me to the programs view, so `Now go to the Programs tab for that patient` isn't required?

Steps?
- Enrol a patient into a program
- Open the `Create Encounter` modal in the patient view...
- Select a program
- Click outside modal to close unfinished modal
- Go into programs tab in patient view

**Comment by mark-prins** [comment]
oh.. I see! thanks

**Comment by nisha-dangol** [comment]
Don't think this can be recreated anymore since [simply clicking outside modal won't exit it](https://github.com/openmsupply/open-msupply/issues/1899) anymore. So, moving this to Done!
