### ISSUE TITLE
Repack - UI tweaks

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1873]
## Is your feature request related to a problem? Please describe 👀
Wondering about rearranging the UI items on the repack modal & form, to something like this:

<img width="936" alt="Screenshot 2023-06-01 at 10 59 29 AM" src="https://github.com/openmsupply/open-msupply/assets/9192912/b075fe50-59a2-4169-b348-0ad9ec08b35a">

With the table rows being within a fixed height area, with scroll-y auto to provide scroll if required.
Change the Ok to Save also perhaps.

**Comment by roxy-dao** [comment]
Also add an alert and close the modal if the whole stock line has been repacked since we don't show empty stock lines in UI
