### ISSUE TITLE
Master lists which are not programs are not considered for remote authorisation between 2 sites that are omSupply

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1874]
## What went wrong? 😲
 

I know that for Djibouti we were asked no to include normal master list in the process of remote authorisation only programs are included.  Since omSupply doesn't use customisation code and SAMES uses omSupply, uses remote authorisation but don't use programs would they not be adversely affected by this ?

If I remember correctly when we deployed East Timor omSupply site remote authorisation was not developed yet on omSupply but the fact that omSupply stores were ordering to the main warehouses that are using mSupply desktop made it possible to use remote authorisation anyway for these sites.

Remote authorisation response requisition using the same master list. The last requisition has been done with the same master list after I set it up to be a program
![image](https://github.com/openmsupply/open-msupply/assets/11624516/b95cd3e7-8895-4907-8e55-ec975450e288)
More details here https://github.com/openmsupply/msupply/issues/13064#issuecomment-1569474512

Let me know if you need some more details 

## Expected behaviour 🤔

It might come a time though when omSupply sites will have to use remote authorisation when ordering to another omSupply sites for master lists that are not programs or exclude from remote authorisation certain programs.  

A possible solution might be on top of store preferences we can also check if a master_list/program has an active authoriser assigned to it. If there is, we quick in the remote authoriser process if not we don't.

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Make sure that the stores preference are set for both the requesting store and the supplier store. You have setup an authoriser for a master list that is not a program.  See here for more details on how to setup (You have a short version video and a long version with explanation: https://drive.google.com/drive/u/0/folders/1-5JlYyYA5jArUl6LbSAvH3qsWE--nO2I)

You can also use that datafile https://www.dropbox.com/s/9wxy3lgjs5olvjb/Nysa%27s%20Test%20Store%20%282%29.zip?dl=0
1. From a store using omsupply, create an internal order using a master list to a supplier that is also using omSupply. Sync
2. Sync the supplier to receive the order and create the response requisition. Check the authorisation status it says "None" instead of Pending
3. Sync back to Central server
4. Login to the web remote authorisation module. See error the requisition is not displayed to be authorised
5. Make your master list a program. Have both mSupply sites sync. 
6. Retry the steps 1-5.
7. Remote Authorisation is working.

## Your environment 🌱

 - Version: 
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by andreievg** [comment]
Great find @alainsussol, in our [public docs](https://docs.msupply.foundation/docs/replenishment/remote-authorisation/) we mention that remote auth is for program only. I think it's good to park this issue for now, until we have requirements to do remote auth in omSupply by master list
