### ISSUE TITLE
Response requisition that have the status 'NEW' sync back to mSupply status 'cn'

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1875]
## What went wrong? 😲
 
I think that NEW response requisition should sync back a status of 'sg' instead of 'cn'. A reason for this is that the filter of requisitions that are still pending approval are using "sg" as a one of it's parameter to filter still unapproved requisitions. 

The main reason though would be to have a certain consistency with other requisitions done in mSupply where the status will be 'sg' until a customer invoice would be created for that requisition which from that point would be of status 'cn'. 

omSupply
![image](https://github.com/openmsupply/open-msupply/assets/11624516/66d5eeea-6bc2-4638-b2b4-1fb47705353a)

mSupply central server
![image](https://github.com/openmsupply/open-msupply/assets/11624516/b6a566a1-1577-4c02-b442-c754e0f7606f)
 
## Expected behaviour 🤔
Would it be possible for NEW Requsition in omSupply to send sync status 'sg' until a outbound shipment has been created for that requisition?

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Setup a sync setup
1. Create an internal order to a supplier that is a store using omSupply. Sync. 
2. On the supplier store, sync to receive the order so that a response requisition is created from it.
3. Check that the Response requisition has a status of NEW. Sync. Log to that supplier store on the central server. Go to Customer > Requisitions  
4. See error. These requisitions displays status 'cn'

## Your environment 🌱

 - Version: 
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment]
Would agree with Alain's suggestion here - I think nw maps to suggested, and it should only be confirmed if an outbound shipment is created.

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.1.15 apk

### Tests
- [ ] Send an internal order to another store. **-FAILED- New bug: #1912** 
- [ ] Check central to see that requisition status is sg.

Note: I did try sending internal order from v1.1.14 apk; was working fine and the requisition status was `sg` in the central as expected!

**Comment by nisha-dangol** [comment]
Moving to Done as I see the new requisitions status as `sg` in v1.3.00 exe
