### ISSUE TITLE
Installer documentation for our base cloud instance

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1876]
I had a few issues installing omSupply postgres flavour on a windows virtual server.

Had to add postgres bin folder to path env variable, otherwise was seeing this error:

![Screenshot 2023-06-01 at 3 14 22 PM](https://github.com/openmsupply/open-msupply/assets/26194949/49949ab0-1f2b-4cb5-94e5-5a74004ae536)

Then was getting an error that was hard to identify, without any logs (just an event that's hard to understand)

![Screenshot 2023-06-01 at 3 16 12 PM](https://github.com/openmsupply/open-msupply/assets/26194949/1d13e261-c35d-42fe-af38-71ec5bfd5780)

![Screenshot 2023-06-01 at 3 15 15 PM](https://github.com/openmsupply/open-msupply/assets/26194949/2041b6f0-9a4c-46a5-b88b-aa28f1423ba3)

Making omSupply service run as Administrator fixed this.

I chose the same port as existing postgres dashboard, and there was some error at the end of postgres install. I reinstalled omSupply and chose a different port and that worked. I was wondering how this conflict works and looked at the install location and it looks like dashboard was on version 15 and omSupply postgres on version 14, so they were both in adjacent folders (high chance of conflict). I think we should install postgres to omSupply folder and default to another port (not 5432) as suggested by @craigdrown awhile ago.

I also noticed lua5.1.dll in the installed folder, was wondering what this is for ?

**Comment by mark-prins** [comment]
> I also noticed lua5.1.dll in the installed folder, was wondering what this is for ?

lua5.1.dll comes from setup factory - it's the runtime for the scripting language used by SF. It's not part of our setup files or installed deliberately

![image](https://github.com/openmsupply/open-msupply/assets/9192912/74a0a0e7-9e17-4136-beaf-e545cc8b9d7a)

**Comment by mark-prins** [comment]
> I think we should install postgres to omSupply folder

The intention was that if postgres was already installed, there'd be no need to install another instance of it. Perhaps useful if the installer detected an existing install and prompted the user?

> Had to add postgres bin folder to path env variable, otherwise was seeing this error:

This is surprising - the postgres install is detected and added to the path env var automatically. Perhaps due to the install issue with postgres?

```
		local tblPgInstalls = Registry.GetKeyNames(HKEY_LOCAL_MACHINE, "Software\\PostgreSQL\\Installations_");
		
		if (tblPgInstalls ~= nil) then	
			if (Table.Count(tblPgInstalls) &gt; 0) then
				local higherPgVersion = "0.0.0";
				for index, value in pairs(tblPgInstalls) do
					local pgVersion = Registry.GetValue(HKEY_LOCAL_MACHINE, "Software\\PostgreSQL\\Installations\\" .. value, "CLT_Version", true);
					if ((String.CompareFileVersions(pgVersion, "14.0.0") ~= -1) and (String.CompareFileVersions(pgVersion, higherPgVersion) ~= -1)) then
						local pgInstallPath = Registry.GetValue(HKEY_LOCAL_MACHINE, "Software\\PostgreSQL\\Installations\\" .. value, "Base Directory", true);
						pgBinPath = pgInstallPath .. "\\bin"
						pgLibPath = pgInstallPath .. "\\lib"
						higherPgVersion = pgVersion;
					end
				end
			end
		end
		
		-- Postgres bin path has been found, set it to environment variable
		if (pgBinPath ~= "") then
			local pgBinTargetIndex = String.Find(path, pgBinPath, 1, false);
			local pgLibTargetIndex = String.Find(path, pgLibPath, 1, false);
			
			if (pgBinTargetIndex == -1) then
				-- postgres bin path not found, add it
				path = path .. ";" .. pgBinPath;
			end
			if (pgLibTargetIndex == -1) then
				-- postgres lib path not found, add it
				path = path .. ";" .. pgLibPath;
			end
			
			-- Update registry
			Registry.SetValue(HKEY_LOCAL_MACHINE, envKey, "Path", path, REG_EXPAND_SZ);
			SetupData.WriteToLogFile("Info\tNew Path=" .. path .. "\r\n", true);
			
			-- Refresh the 'Path' environment variable
			File.Run(SessionVar.Expand("%TempLaunchFolder%\\RefreshEnvironment.exe"), "", "", SW_MINIMIZE, true);
			local error = Application.GetLastError();
		    if (error ~= 0) then
		        SetupData.WriteToLogFile("Error: Could not execute utility!\r\n", true);
		    end
		end
	end
end
```

Note the demo server [wiki page](https://wiki.sussol.net/doku.php/msupply:support:important_stuff:open_msupply_demo_hosting?s[]=omsupply#api) mentions this too

**Comment by mark-prins** [comment]
The [wiki docs](https://wiki.sussol.net/doku.php/open_msupply:deployment) were created. Is that enough to close this issue?

**Comment by mark-prins** [comment]
@andreievg - do you think we can close this one?

**Comment by andreievg** [comment]
@mark-prins thank you very much for the detailed description in the wiki, it's awesome.

Yeah I think we can close the issue
