### ISSUE TITLE
Changing supplier/customer on shipments can cause strife for sync

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#188]
![image](https://user-images.githubusercontent.com/7684221/175834872-1af11016-e012-45db-8c99-8115c80187d4.png)

When editing an inbound shipment you can change the supplier. This is a useful feature - say you spent a day entering in a 500 lines of information only to realise you selected the wrong supplier! AH! Thankfully you can just correct the supplier rather than start again.

I have one assumption: that currently the logic just updates the `invoice.name_id` of the shipment record. Please correct me if that's not true! 

The central server forwards records to the other party (based on `invoice.name.store.site`) so that they can process the transfer on their end, given that it is a store active on a different site to the store you made the invoice. This leads to an awkward scenario:

1. Create an invoice, select supplier and add some lines.
2. Sync - the central server forwards the records to the supplying store's site indicated by `invoice.name.store.site`.
3. On the invoice, change the supplier.
4. Sync - the central server forwards the records to the new supplier indicated by `invoice.name.store.site`. Any further updates or even deleting the invoice will never get synced to the original supplier. The original supplier has a bunch of records that it really shouldn't have, and we have no means of identifying previous suppliers to correct this.

Further:
- Changing the supplier multiple times, syncing each time, would send records to each supplier that will never get updated 

## What do our other apps do?

- mSupply mobile doesn't let you change the name on an invoice. So this can't happen! Sucks if you chose the wrong supplier though, you'll simply have to delete it and start again.
- mSupply desktop only lets you delete an invoice after deleting all the lines, and lines are always synced before the parent. This makes sure that they can get forwarded correctly before the `name_id` is updated (except for the parent record itself...). Also, it doesn't matter that much, I don't think desktop actually does anything with lines from other sites/stores. Basically still suffer from having to start from scratch if you chose the wrong supplier, though.

### 1. Duplicate the invoice and lines and delete old

Selecting a new supplier will create a new invoice and and clone lines. The old invoice will be deleted immediately. Reuse the same serial number.

On the central server, block updates of `name_id` FKs.

_Pros:_
- the FKs on records don't change, so all the sync logic works correctly.
- UX doesn't change

_Cons:_
- A little more complex/expensive. But it should be a relatively rare event
- Blocking `name_id` updates might be too hardball, but we'll know client apps making invalid updates pretty quickly!

### 2. Duplicate the invoice and lines, warn user

Add an extra step or so to communicate that selecting a new supplier will create a new invoice with all the same lines. Perhaps give the option to delete the original invoice too.

On the central server, block updates of `name_id` FKs.

_Pros:_
- the FKs don't change, so all the sync logic works correctly.

_Cons:_
- A little more complex/expensive. But it should be a relatively rare event
- BLOCKER? If done on an "allocated" invoice, it should affect stock. If not deleting the original then we'll need to allocate more stock, of which we may not have enough. Then the duplicate won't have the same quantities.
  - Likely better to just immediately delete and create the new lines with identical quantities as in option 1, don't need to update stock levels.
- Maybe annoying UX. If the user chooses not to delete then they may end up with a whole lot of invoices that are of no use
- Blocking `name_id` updates might be too hardball, but we'll know client apps making invalid updates pretty quickly!

### 3. Central server has special code handling the update

Whenever an invoice syncs with a `name_id` change to sync v5, the central server does the additional task of sending a `delete` for it and all the lines to the old `invoice.name.store.site`. Additionally, ensure that all the lines are sent to the new `invoice.name.store.site` to ensure the invoice is in a complete state.

_Pros:_
- omSupply doesn't have to change. Changing supplier seems completely seamless which is great UX.

_Cons:_
- Complexity on the central server. Unique rules for records affected must be applied (hoping to have general rules when we can).
- Overhead on the central server. Trying to keep it as fast as possible!

Note: In some ways this is equivalent to omsupply creating a new invoice with the new supplier and deleting the old one. In the end it still results in the new `invoice.name.store.site` getting the inserts, and the old site getting the deletes.

## Additional context

This should affect all records that are forwarded based on `name_id`:
- invoices
- requisitions
- purchase orders
- more?

**Comment by andreievg** [comment]
Another solution, same as the first one suggested but automatic (if name_id is changed we auto delete and re-create invoice)
