### ISSUE TITLE
Patient creation: input data loss when searching for a patient to quickly

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1884]
To reproduce:
- Click "New patient"
- Open network in the debug console
- Enter first name and immediately press enter to start the patient search
- The first name will not be included in the API request nor will it be present when creating the patient

![Image](https://user-images.githubusercontent.com/88299195/243542218-2c323d08-b260-4d0b-bf7e-e15a775e95c8.png)

What probably happens is that the text input delay hasn't elapsed yet, and thus the input is observed as empty.

Think we have this problem in other dialogs as well...

Possible solution:
- [ ] add a delay to the ok button (something like a delayed click) 
- [ ] better solution?

**Comment by DhanyaHerath** [comment]
Linked with https://github.com/openmsupply/open-msupply/issues/1886

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.3.00 exe
Moving to Done as it looks good! 
- [x] Create a patient and press okay straight away. 
- [x] All inputted fields should be populated in the Patient View
