### ISSUE TITLE
Patient creation: Don't search for patients if there is no input data

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1886]
There is no point doing a patient search when there is no input data for the search, e.g. if the form is blank.

Furthermore, get_patients uses pagination while the central search endpoint doesn't. This results in weird results, e.g.:
- a patient is not returned from the local search because of the pagination
- same patient is returned from the global search (but the UI doesn't know that it is a local patient)

Solution:
- [ ] don't search without input data
- [ ] fetch the paginated patient results till we got all matching patients.

**Comment by CarlosNZ** [comment]
> * don't search without input data

Seems like this is the best option to me.

So if nothing is entered here:

<img width="433" alt="Screenshot 2023-06-26 at 2 07 34 PM" src="https://github.com/openmsupply/open-msupply/assets/5456533/ae97f3bd-7823-4cc5-8726-a445bff2bba6">

Then we go straight to the empty patient form rather than show any search results. 

Sound okay, @clemens-msupply ?

**Comment by clemens-msupply** [comment]
Or we require the user to enter some minimal information? e.g. at least first OR last name?

**Comment by CarlosNZ** [comment]
> Or we require the user to enter some minimal information? e.g. at least first OR last name?

Are we expecting that all new patients should be found from a patient search? If yes, then that makes sense -- some minimal data should be required.

But if not, then you should be able to skip the "search" step if you know for sure the patient won't be found. 

I don't know the context well enough -- which situation(s) are we expecting here?

**Comment by clemens-msupply** [comment]
The assumption is that the patient isn't in the system, but we want to make sure that this is really not the case. For example, patient says she isn't in the system because she forgot a previous visit where she has been added. Even if the clinician knows the patient really isn't in the system it doesn't hurt to enter some basic information in this form because this information would need to be entered later anyway. So I think we can at least require a valid name here.

**Comment by CarlosNZ** [comment]
Okay, so just add a minimum requirement (first or last name) before the "Okay & Next" button becomes enabled?

**Comment by clemens-msupply** [comment]
Yes that sounds good to me

**Comment by nisha-dangol** [comment]
Tested in v1.3.00 exe
Moving to Done since "Ok & Next" button is disabled until something has been entered in either the first or last name fields
