### ISSUE TITLE
Patient Programs view

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1892]
## What went wrong? 😲
 
Switching from the Encounter tab to the Programs tab in the patient view gives this error:

<img width="1071" alt="Screenshot 2023-06-08 at 10 31 59 AM" src="https://github.com/openmsupply/open-msupply/assets/9192912/8ee337a5-7740-41ac-99f4-263586e81ca0">

## Expected behaviour 🤔
No error 🤷 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open a patient details page
2. Click on Encounters tab
3. Click on Programs tab

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Duplicate #1863
