### ISSUE TITLE
The numeric value changes whenever you put the very large number in different numeric fields

### ISSUE THREAD

**Issue by santoshkhanal12** [openmsupply/open-msupply#1911]
## What went wrong? 😲

The numeric value changes panics whenever you put the very large number in different numeric fields

## Expected behaviour 🤔

The value should be the same as value entered.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Connect MSupply to Open mSupply
2. Create a outbound shipment
3. Select an Item
4. Enter the value of Issue packs to 9876543210
<img width="635" alt="Screenshot 2023-06-14 at 16 26 54" src="https://github.com/openmsupply/open-msupply/assets/117138852/49bab4bb-9091-4db3-af57-ffafdcf7a9d8">

5. The automatically changes to number changes to 4294967295 (BUG)
<img width="876" alt="Screenshot 2023-06-14 at 16 28 41" src="https://github.com/openmsupply/open-msupply/assets/117138852/58e9f72d-264d-4838-811c-0041e745e9ed">

6. Do Stocktake of an item
7. Enter the Counted packs as 9876543210
8. The value changed to 999999999 (BUG)
<img width="654" alt="Screenshot 2023-06-14 at 16 34 22" src="https://github.com/openmsupply/open-msupply/assets/117138852/c101ead7-b930-4fed-8471-6b494ffcb778">

9. It also happen in other field link inbound shipment

## Your environment 🌱

 - Version: 1.1.15
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by andreievg** [comment]
Great find, but likely low probability and low impact, so will be closing for now.
