### ISSUE TITLE
Reset client mode

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1915]
## What went wrong? 😲

Related to this release: https://github.com/openmsupply/open-msupply/releases/tag/v1.1.16

We need a way to reset mobile mode from client to server (in case there are no local server and user is stuck on discovery).

## Expected behaviour 🤔

While in discovery on mobile, able to reset mode to client 

## How to Reproduce 🔨

Install new mobile version, press client (make sure there are no omSupply servers running on your network), you'll see forever `loading` indicator

**Comment by mark-prins** [comment]
small correction - that there isn't a loading indicator forever, you should get

![image](https://github.com/openmsupply/open-msupply/assets/9192912/57fb95a9-d0c3-4e68-a59e-71d804e8380a)

**Comment by kahn-msupply** [comment]
🧪 TESTING

omSupply 1.3 Windows Compiled

- [x] Message shown when server is unavailable (Changed port so client could not connect)

<img width="713" alt="Screen Shot 2023-10-09 at 4 00 04 PM" src="https://github.com/openmsupply/open-msupply/assets/132425100/6d6fafbb-83b5-4ac9-b4c8-7e4affaabfa2">

LGTM - Will move to Testers: Done
