### ISSUE TITLE
[Program Merge] New mSupply fields and tables, to be om_ fields

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1934]
We've started down the pattern of making new fields and tables to be prefixed with `om_`. It's good idea to follow this. 

Noticed in this PR: https://github.com/openmsupply/open-msupply/pull/1882

Would need to look at all of the translations in that PR and for new fields and document in mSupply rename to om_

**Comment by andreievg** [comment]
I looked at all of the tables, the only fields/tables that don't seem to have `om_` prefix are fields added in this PR: https://github.com/openmsupply/msupply/pull/12571.

I couldn't figure out why report_name2/3 were added. @clemens-msupply do you know if they are used anywhere ?

It's probably ok for the report table to have these fields without `om_` prefix. The main reason for the `om_` prefix was to identify a field as new field used in omSupply, so if there is any logic changes involving those fields, we have to be quite careful (and look at how the field is used in omSupply).

**Comment by clemens-msupply** [comment]
This might be related to the report_name2/3:
https://github.com/openmsupply/msupply/pull/12571#discussion_r1141558138

**Comment by andreievg** [comment]
Thanks @clemens-msupply, i had a look, technically those two fields are not needed, but they were added, I think it's ok to keep (or at least I don't see justifications for doing that work). And the other fields that was added, the sub_context field, could possibly be changed, but it's already used in mSupply UI, so perhaps it's ok to keep. 

Since I made this issue, I think it's ok to close it, given the above justification

**Comment by clemens-msupply** [comment]
thanks for looking into it!
