### ISSUE TITLE
Should oms have purchase order for external suppliers like in the mSupply?

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1945]
## Is your feature request related to a problem? Please describe 👀
**Should oms have purchase order for external suppliers like in the mSupply?**
Currently, under Replenishments>>Internal Orders, we can only create order for existing stores, meaning, order cannot be created for external supplier (like we do in mSupply!)

## Describe the solution you'd like 🎁
Like `Internal Order`, have another section for `Purchase Order`?

### Describe alternatives you've considered 💭
n/a

### Additional context 💌
n/a

### Moneyworks Jobcode 🧰
n/a

**Comment by DhanyaHerath** [comment]
Agreed, but would like to wait for funding! Archiving for now
