### ISSUE TITLE
Decouple `Programs` module from `Dispensary` mode check

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1947]
## Is your feature request related to a problem? Please describe 👀
Need a way to hide programs when dispensary mode is on. 

## Describe the solution you'd like 🎁
Programs should be hidden behind a `preference`, so that the links do not show up when a store is in `dispensary mode`. This can be done as a `store preference` and will require changes in mSupply. All program related components and columns will also need to be hidden from `Patient` list view.

### Describe alternatives you've considered 💭
Keep the `Program` navigation links since they will be empty if the `Programs` module isn't configured, but seems weird to have links that lead to empty pages...

### Moneyworks Jobcode 🧰

OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by andreievg** [comment]
> All program related components and columns will also need to be hidden from Patient list view.

Food for thought, sometimes when there is too much conditionals in one page, it's worth looking into a new page (not sure if it applies here)

**Comment by nisha-dangol** [comment]
Moving to Done as this is tested on mSupply v7-07-00-beta9 as part of https://github.com/openmsupply/msupply/issues/13221#issuecomment-1647730803
