### ISSUE TITLE
Add prescription type to Invoice

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1948]
## Is your feature request related to a problem? Please describe 👀
Currently no way to differentiate between invoices which have been created from shipment or dispensary. 

## Describe the solution you'd like 🎁
- [x] Add `prescription` type to invoice
- [x] Update translations
- [x] Dispensary invoice `nw` - `NEW`, `cn` - `PICKED` and `fn` - `VERIFIED`
      Note: Dispensary invoices also have a `nw` status, but that gets changed to `cn` after they add an invoice line or press Ok -> Ok & Save with no invoice lines...

### Moneyworks Jobcode 🧰

OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by andreievg** [comment]
> Add this filter to existing outbound shipments api invoices/src/OutboundShipment/api/api.ts

Wouldn't se separate the API to be under Prescriptions ?

**Comment by roxy-dao** [comment]
> > Add this filter to existing outbound shipments api invoices/src/OutboundShipment/api/api.ts
> 
> Wouldn't we separate the API to be under Prescriptions ?

We will be having separate API, but currently Outbound Shipments will load prescriptions in the list view as well as outbound invoices...

**Comment by andreievg** [comment]
Sounds good, thanks

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.2.00

### Tests
- [ ] Make sure tests still run in backend
@roxy-dao I can't really tell how to test this! In dev env, just run `cargo test`? Well that's throwing some errors for me! 
<img width="1290" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/a8661d04-f1d8-4456-823e-d4714511f8c9">
<img width="1277" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/ee946bed-92db-43bc-9f43-1d0486894332">

- [x] Frontend change:
    - [x] Make sure store is a dispensary
    - [x] Create some prescriptions in OG
    - [x] Move dispensary to remote site (in OG)
    - [x] Sync site in remote
    - [x] Go to Outbound Shipment
    - [x] Shouldn't be able to see Dispensary invoices
