### ISSUE TITLE
Endpoint: Insert Prescription Invoice

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1949]
## Is your feature request related to a problem? Please describe 👀
Need a way to create invoice for prescription.

## Describe the solution you'd like 🎁
Firstly, add `Prescription` enum to `NumberRowType`.

```graphql
InsertPrescription {
    id: String
    patientId: String
}
```

```graphql
InsertPrescriptionError {
   InvoiceAlreadyExist
   PatientDoesNotExist
   NewlyCreatedInvoiceDoesNotExist
   DatabaseError (RepositoryError)
}
```

### Moneyworks Jobcode 🧰

OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by andreievg** [comment]
> ClinicianDoesNotExist

That shouldn't be here right ?

**Comment by nisha-dangol** [comment]
# Testing
Testing in v1.2.00

## Tests
- [ ] Run tests -- **What tests?** 
OR
- [ ] Call insertPrescription endpoint and see that prescription invoice has been inserted correctly in the database

Hi @roxy-dao 
I'm afraid I don't quite understand the test case mentioned there. Could you be a little more specific here? 
What would be the steps in oms UI to add/create a new prescription for the patient? Plus, will there be the feature for remote-search for the patients as well, like in the mSupply?

**Comment by roxy-dao** [comment]
> # Testing
> Testing in v1.2.00 apk
> 
> ## Tests
> * [ ]  Run tests -- **What tests?**
>   OR
> * [ ]  Call insertPrescription endpoint and see that prescription invoice has been inserted correctly in the database
> 
> Hi @roxy-dao I'm afraid I don't quite understand the test case mentioned there. Could you be a little more specific here? What would be the steps in oms UI to add/create a new prescription for the patient? Plus, will there be the feature for remote-search for the patients as well, like in the mSupply?

This is for backend work... you can run tests in the development environment with `cargo test`
UI coming soon (:
