### ISSUE TITLE
Endpoint: Insert Prescription Invoice Line

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1950]
## Is your feature request related to a problem? Please describe 👀
Need way to insert prescription lines.

## Describe the solution you'd like 🎁
Frontend has an allocate button which can be used to auto-allocate stock lines. 

Total before tax should be calculated in backend. 

```graphql
InsertPrescriptionLines {
    id: String
    invoiceId: String
    itemId: String
    stockLineId: String
    numberOfPacks: Number
    note: String (usage instructions)
}
```

```graphql
InsertPrescriptionLinesError {
   InvoiceDoesNotExist
   NotThisStoreInvoice
   NotAPrescriptionInvoice
   CannotEditFinalised
   ItemNotFound
   StockLineNotFound (StockLine)
   NumberOfPacksBelowOne
   ItemDoesNotMatchStockLine
   StockLineAlreadyExistsInInvoice (String)
   ReducedBelowZero
   DatabaseError (RepositoryError)
}
```

### Moneyworks Jobcode 🧰

OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by andreievg** [comment]
You can probably use InsertOutboundShipmentLine service within this service, and just add 'note' after (or have a common `insert_invoice_line` (a copy of insert_outbound_shipment_line, but with 'note' and use it in both insert_outbound_shipment_line and in insert_perscription_line), I think i prefer the later.
