### ISSUE TITLE
UI: Prescription List View

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1954]
## Describe the solution you'd like 🎁
- Firstly, a link to `Prescriptions` would need to be added under `Dispensary`, and should be hidden if the store is not a dispensary. 
- The `Prescriptions` page should contain a List View of all the prescription invoices like with Outbound Shipments.
- Add a button in `Patient` view to allow users to add a prescription? - future

### Moneyworks Jobcode 🧰
OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by andreievg** [comment]
> Add a button in Patient view to allow users to add a prescription

What does this button do ? Is Patient view a view for one patient or for patients ?

**Comment by roxy-dao** [comment]
> > Add a button in Patient view to allow users to add a prescription
> 
> What does this button do ? Is Patient view a view for one patient or for patients ?

It's a view for one patient (implemented in programs). Not necessary, but think nice to have the button there as well (there was a button for it but was removed)

**Comment by andreievg** [comment]
> Button allows user to add prescription from the patient (one) view

So it would insert a prescription with patient_id = patient ?

**Comment by nisha-dangol** [comment]
Tested in v1.3.0 exe. 

PASSing this as I can see list of new prescriptions:
<img width="1484" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/f2d4cb0b-ac46-49a5-96f3-7e4206f2683f">
<img width="1530" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/55afed09-f28d-4ae6-9ebc-02cb51a47fcc">
