### ISSUE TITLE
UI: Prescription Line

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1960]
#### Prescription Line
- Use Outbound Lines as a base
- Clicking on a row on the List View should direct users to the prescription invoice. 
- Note section (to add dosage instructions, etc). Should not be in a new tab.
- Shouldn't be any unallocated lines in prescription.

### Additional context 💌
<img width="1004" alt="dispensary-line" src="https://github.com/openmsupply/open-msupply/assets/61820074/b02fe041-3b7c-4762-96d9-5540e2a1fc5a">

### Moneyworks Jobcode 🧰
OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by nisha-dangol** [comment]
# Testing
Tested in v1.3.0 exe

## Tests
- [x] Go to a prescription invoice or create a new one
- [x] Click Add Item
- [x] Modal should open
- [x] Enter information into the inputs
- [x] Click Ok
- [x] Go back to just saved invoice line
- [x] Try edit note or number of packs
