### ISSUE TITLE
Default sort for items when adding from masterlists should be A--> Z rather than Z --> A 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1982]
## Is your feature request related to a problem? Please describe 👀

When you use the `Add from masterlist` functionality, either in stocktakes or internal orders (or I assume anywhere you use it), the items get added with the default sort in reverse alphabetical order.  I find this..confusing: 
![image](https://github.com/openmsupply/open-msupply/assets/29744386/107cda9d-807b-4d00-bc0d-b09bc511bdc6)

## Describe the solution you'd like 🎁
I'd like them to be populated in alphabetical order

**Comment by nisha-dangol** [comment]
# Testing
Tested in v1.3.0 exe

## Tests
- [x] Create a stocktake from master list
- [x] All should show from A - Z
