### ISSUE TITLE
I can change the Supplier on an Inbound Shipment created as part of a stock transfer

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1984]
## What went wrong? 😲
 
The inbound shipment below was created as a stock transfer from the Ba Stock Office: 
![image](https://github.com/openmsupply/open-msupply/assets/29744386/bfeb0884-e252-4e4f-9d8c-d6c9f095049a)

Once I confirm the inbound shipment as delivered, I can then change the supplier name. The picture below is after I verify the shipment having changed the supplier to Ba Pharmacy Outpatients: 
![image](https://github.com/openmsupply/open-msupply/assets/29744386/159a15db-6b3d-43a5-a1df-8836143fd912)

## Expected behaviour 🤔
I should not be able to change the supplier name in an inbound shipment created via a stock transfer 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. In Store A, create and finalise an outbound shipment to Store B
2. Log into Store B, and confirm the newly created inbound shipment as delivered 
3. Now try to change the supplier name 
4. See error - I shouldn't be able to change that 

## Your environment 🌱

 - Version: 1.20
 - Platform:
   - [ ] android (tablet)
   - [x] Chrome browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by nisha-dangol** [comment]
# Testing
Tested in v1.3.0 exe

## Tests
- [x] Send an Outbound Shipment from Store A to Store B
- [x] Go to Store B and click on the newly created Inbound Shipment
- [x] Supplier should be disabled
