### ISSUE TITLE
Update f/e dependencies

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1991]
## Is your feature request related to a problem? Please describe 👀

As per title. This one was waiting for the feature branch merge

## Describe the solution you'd like 🎁
`yarn outdated --json | $(yarn bin)/format-yarn-outdated --format markdown`

# Major
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @capacitor-community/barcode-scanner | 3.0.3 | 3.0.3 | 4.0.1 | @openmsupply-client/android | devDependencies | https://github.com/capacitor-community/barcode-scanner#readme |  |
| @capacitor-community/barcode-scanner | 3.0.3 | 3.0.3 | 4.0.1 | @openmsupply-client/common | dependencies | https://github.com/capacitor-community/barcode-scanner#readme |  |
| @capacitor-community/keep-awake | 3.0.0 | 3.0.0 | 4.0.0 | openmsupply-client | devDependencies | https://github.com/capacitor-community/keep-awake#readme |  |
| @capacitor-community/keep-awake | 3.0.0 | 3.0.0 | 4.0.0 | @openmsupply-client/host | devDependencies | https://github.com/capacitor-community/keep-awake#readme |  |
| @capacitor/android | 4.7.3 | 4.8.1 | 5.2.1 | @openmsupply-client/android | dependencies | https://capacitorjs.com |  |
| @capacitor/cli | 4.7.3 | 4.8.1 | 5.2.1 | @openmsupply-client/android | devDependencies | https://capacitorjs.com |  |
| @capacitor/core | 4.7.3 | 4.8.1 | 5.2.1 | openmsupply-client | dependencies | https://capacitorjs.com |  |
| @capacitor/core | 4.7.3 | 4.8.1 | 5.2.1 | @openmsupply-client/android | dependencies | https://capacitorjs.com |  |
| @capacitor/core | 4.7.3 | 4.8.1 | 5.2.1 | @openmsupply-client/common | dependencies | https://capacitorjs.com |  |
| @capacitor/keyboard | 4.1.1 | 4.1.1 | 5.0.6 | openmsupply-client | devDependencies | https://github.com/ionic-team/capacitor-plugins#readme |  |
| @capacitor/keyboard | 4.1.1 | 4.1.1 | 5.0.6 | @openmsupply-client/android | devDependencies | https://github.com/ionic-team/capacitor-plugins#readme |  |
| @capacitor/preferences | 4.0.2 | 4.0.2 | 5.0.6 | openmsupply-client | devDependencies | https://github.com/ionic-team/capacitor-plugins#readme |  |
| @capacitor/preferences | 4.0.2 | 4.0.2 | 5.0.6 | @openmsupply-client/android | devDependencies | https://github.com/ionic-team/capacitor-plugins#readme |  |
| @fontsource/inter | 4.5.15 | 4.5.15 | 5.0.5 | @openmsupply-client/host | dependencies | https://fontsource.org/fonts/inter |  |
| @graphql-codegen/cli | 3.3.1 | 3.3.1 | 4.0.1 | openmsupply-client | devDependencies | https://github.com/dotansimha/graphql-code-generator#readme |  |
| @graphql-codegen/typescript | 3.0.4 | 3.0.4 | 4.0.1 | openmsupply-client | devDependencies | https://github.com/dotansimha/graphql-code-generator#readme |  |
| @graphql-codegen/typescript-graphql-request | 4.5.9 | 4.5.9 | 5.0.0 | openmsupply-client | devDependencies | https://github.com/dotansimha/graphql-code-generator-community#readme |  |
| @graphql-codegen/typescript-operations | 3.0.4 | 3.0.4 | 4.0.1 | openmsupply-client | devDependencies | https://github.com/dotansimha/graphql-code-generator#readme |  |
| @mui/x-date-pickers | 5.0.20 | 5.0.20 | 6.10.0 | openmsupply-client | dependencies | https://mui.com/x/react-date-pickers/ |  |
| @storybook/testing-library | 0.1.0 | 0.1.0 | 0.2.0 | openmsupply-client | devDependencies | https://github.com/storybookjs/testing-library#readme |  |
| @types/node | 18.16.2 | 18.16.19 | 20.4.2 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node |  |
| @typescript-eslint/eslint-plugin | 5.59.1 | 5.62.0 | 6.0.0 | openmsupply-client | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/eslint-plugin | 5.59.1 | 5.62.0 | 6.0.0 | @openmsupply-client/electron | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/parser | 5.59.1 | 5.62.0 | 6.0.0 | openmsupply-client | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/parser | 5.59.1 | 5.62.0 | 6.0.0 | @openmsupply-client/electron | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| electron | 24.1.3 | 24.6.3 | 25.3.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/electron#readme |  |
| eslint-plugin-jest-dom | 4.0.3 | 4.0.3 | 5.0.1 | openmsupply-client | devDependencies | https://github.com/testing-library/eslint-plugin-jest-dom#readme |  |
| graphql-request | 5.2.0 | 5.2.0 | 6.1.0 | @openmsupply-client/common | dependencies | https://github.com/jasonkuhrt/graphql-request |  |
| i18next | 22.4.15 | 22.5.1 | 23.2.11 | @openmsupply-client/common | dependencies | https://www.i18next.com |  |
| lerna | 6.6.2 | 6.6.2 | 7.1.4 | openmsupply-client | dependencies | https://lerna.js.org |  |
| prettier | 2.8.8 | 2.8.8 | 3.0.0 | openmsupply-client | devDependencies | https://prettier.io |  |
| prettier | 2.8.8 | 2.8.8 | 3.0.0 | @openmsupply-client/programs | devDependencies | https://prettier.io |  |
| react-i18next | 12.2.2 | 12.3.1 | 13.0.2 | @openmsupply-client/common | dependencies | https://github.com/i18next/react-i18next |  |

# Minor
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @awesome-cordova-plugins/core | 6.3.0 | 6.4.0 | 6.4.0 | @openmsupply-client/system | devDependencies | https://github.com/danielsogl/awesome-cordova-plugins#readme |  |
| @awesome-cordova-plugins/printer | 6.3.0 | 6.4.0 | 6.4.0 | @openmsupply-client/system | devDependencies | https://github.com/danielsogl/awesome-cordova-plugins#readme |  |
| @babel/core | 7.21.4 | 7.22.9 | 7.22.9 | openmsupply-client | devDependencies | https://babel.dev/docs/en/next/babel-core |  |
| @babel/preset-flow | 7.21.4 | 7.22.5 | 7.22.5 | openmsupply-client | devDependencies | https://babel.dev/docs/en/next/babel-preset-flow |  |
| @electron-forge/cli | 6.1.1 | 6.2.1 | 6.2.1 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-dmg | 6.1.1 | 6.2.1 | 6.2.1 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-squirrel | 6.1.1 | 6.2.1 | 6.2.1 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-zip | 6.1.1 | 6.2.1 | 6.2.1 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/plugin-webpack | 6.1.1 | 6.2.1 | 6.2.1 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @emotion/react | 11.10.6 | 11.11.1 | 11.11.1 | @openmsupply-client/common | dependencies | https://github.com/emotion-js/emotion/tree/main#readme |  |
| @emotion/styled | 11.10.6 | 11.11.0 | 11.11.0 | @openmsupply-client/common | dependencies | https://github.com/emotion-js/emotion/tree/main#readme |  |
| @jsonforms/core | 3.0.0 | 3.1.0 | 3.1.0 | @openmsupply-client/programs | dependencies | http://jsonforms.io/ |  |
| @jsonforms/material-renderers | 3.0.0 | 3.1.0 | 3.1.0 | @openmsupply-client/programs | dependencies | http://jsonforms.io/ |  |
| @jsonforms/react | 3.0.0 | 3.1.0 | 3.1.0 | @openmsupply-client/programs | dependencies | http://jsonforms.io/ |  |
| @mui/icons-material | 5.11.16 | 5.14.0 | 5.14.0 | @openmsupply-client/common | dependencies | https://mui.com/material-ui/material-icons/ |  |
| @mui/material | 5.12.2 | 5.14.0 | 5.14.0 | @openmsupply-client/common | dependencies | https://mui.com/material-ui/getting-started/ |  |
| @testing-library/dom | 9.2.0 | 9.3.1 | 9.3.1 | openmsupply-client | devDependencies | https://github.com/testing-library/dom-testing-library#readme |  |
| babel-jest | 29.5.0 | 29.6.1 | 29.6.1 | openmsupply-client | devDependencies | https://github.com/facebook/jest#readme |  |
| css-loader | 6.7.3 | 6.8.1 | 6.8.1 | @openmsupply-client/electron | devDependencies | https://github.com/webpack-contrib/css-loader |  |
| date-fns | 2.29.3 | 2.30.0 | 2.30.0 | @openmsupply-client/common | dependencies | https://github.com/date-fns/date-fns#readme |  |
| eslint | 8.40.0 | 8.45.0 | 8.45.0 | openmsupply-client | devDependencies | https://eslint.org |  |
| eslint | 8.40.0 | 8.45.0 | 8.45.0 | @openmsupply-client/electron | devDependencies | https://eslint.org |  |
| graphql | 16.6.0 | 16.7.1 | 16.7.1 | openmsupply-client | dependencies | https://github.com/graphql/graphql-js |  |
| i18next-browser-languagedetector | 7.0.1 | 7.1.0 | 7.1.0 | @openmsupply-client/common | dependencies | https://github.com/i18next/i18next-browser-languageDetector |  |
| i18next-chained-backend | 4.2.0 | 4.4.0 | 4.4.0 | @openmsupply-client/common | dependencies | https://github.com/i18next/i18next-chained-backend |  |
| jest | 29.5.0 | 29.6.1 | 29.6.1 | openmsupply-client | devDependencies | https://jestjs.io/ |  |
| jest-environment-jsdom | 29.5.0 | 29.6.1 | 29.6.1 | openmsupply-client | devDependencies | https://github.com/facebook/jest#readme |  |
| lint-staged | 13.0.3 | 13.0.3 | 13.2.3 | @openmsupply-client/programs | devDependencies | https://github.com/okonet/lint-staged#readme |  |
| msw | 1.1.0 | 1.1.0 | 1.2.2 | openmsupply-client | dependencies | https://mswjs.io |  |
| react-router-dom | 6.11.1 | 6.14.1 | 6.14.1 | @openmsupply-client/common | dependencies | https://github.com/remix-run/react-router#readme |  |
| react-router-dom | 6.11.1 | 6.14.1 | 6.14.1 | @openmsupply-client/host | dependencies | https://github.com/remix-run/react-router#readme |  |
| recharts | 2.6.0 | 2.7.2 | 2.7.2 | @openmsupply-client/common | dependencies | https://github.com/recharts/recharts |  |
| recharts | 2.6.0 | 2.7.2 | 2.7.2 | @openmsupply-client/dashboard | dependencies | https://github.com/recharts/recharts |  |
| stylis | 4.2.0 | 4.3.0 | 4.3.0 | @openmsupply-client/common | dependencies | https://github.com/thysultan/stylis.js |  |
| tsconfig-paths-webpack-plugin | 4.0.1 | 4.1.0 | 4.1.0 | openmsupply-client | devDependencies | https://github.com/dividab/tsconfig-paths-webpack-plugin |  |
| typescript | 5.0.4 | 5.1.6 | 5.1.6 | openmsupply-client | devDependencies | https://www.typescriptlang.org/ |  |
| typescript | 5.0.4 | 5.1.6 | 5.1.6 | @openmsupply-client/programs | devDependencies | https://www.typescriptlang.org/ |  |
| webpack | 5.82.0 | 5.88.1 | 5.88.1 | openmsupply-client | devDependencies | https://github.com/webpack/webpack |  |
| webpack | 5.82.0 | 5.88.1 | 5.88.1 | @openmsupply-client/host | devDependencies | https://github.com/webpack/webpack |  |
| webpack-bundle-analyzer | 4.8.0 | 4.9.0 | 4.9.0 | @openmsupply-client/host | dependencies | https://github.com/webpack-contrib/webpack-bundle-analyzer |  |
| zod | 3.18.0 | 3.18.0 | 3.21.4 | @openmsupply-client/programs | dependencies | https://zod.dev |  |
| zod | 3.18.0 | 3.18.0 | 3.21.4 | @openmsupply-client/system | dependencies | https://zod.dev |  |

# Patch
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @storybook/addon-actions | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/addons/actions |  |
| @storybook/addon-essentials | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/addons/essentials |  |
| @storybook/addon-interactions | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/addons/interactions |  |
| @storybook/addon-links | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/addons/links |  |
| @storybook/addons | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/lib/addons |  |
| @storybook/react | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/renderers/react |  |
| @storybook/react-webpack5 | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/frameworks/react-webpack5 |  |
| @storybook/theming | 7.0.7 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/lib/theming |  |
| @swc/core | 1.3.55 | 1.3.69 | 1.3.69 | openmsupply-client | devDependencies | https://swc.rs |  |
| @types/jest | 29.5.1 | 29.5.3 | 29.5.3 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest |  |
| @types/lodash | 4.14.194 | 4.14.195 | 4.14.195 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash |  |
| @types/react | 18.2.0 | 18.2.15 | 18.2.15 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react |  |
| @types/react-dom | 18.2.1 | 18.2.7 | 18.2.7 | openmsupply-client | dependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom |  |
| @types/uuid | 9.0.1 | 9.0.2 | 9.0.2 | @openmsupply-client/common | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/uuid |  |
| babel-loader | 9.1.2 | 9.1.3 | 9.1.3 | openmsupply-client | devDependencies | https://github.com/babel/babel-loader |  |
| dompurify | 3.0.2 | 3.0.5 | 3.0.5 | @openmsupply-client/common | dependencies | https://github.com/cure53/DOMPurify |  |
| html-webpack-plugin | 5.5.1 | 5.5.3 | 5.5.3 | @openmsupply-client/host | devDependencies | https://github.com/jantimon/html-webpack-plugin |  |
| i18next-http-backend | 2.2.0 | 2.2.1 | 2.2.1 | @openmsupply-client/common | dependencies | https://github.com/i18next/i18next-http-backend |  |
| lint-staged | 13.2.2 | 13.2.3 | 13.2.3 | openmsupply-client | devDependencies | https://github.com/okonet/lint-staged#readme |  |
| react-currency-input-field | 3.6.10 | 3.6.11 | 3.6.11 | @openmsupply-client/common | dependencies | https://github.com/cchanxzy/react-currency-input-field |  |
| storybook | 7.0.10 | 7.0.27 | 7.0.27 | openmsupply-client | devDependencies | https://github.com/storybookjs/storybook/tree/next/code/lib/cli |  |
| style-loader | 3.3.2 | 3.3.3 | 3.3.3 | @openmsupply-client/electron | devDependencies | https://github.com/webpack-contrib/style-loader |  |
| ts-jest | 29.1.0 | 29.1.1 | 29.1.1 | openmsupply-client | devDependencies | https://kulshekhar.github.io/ts-jest |  |
| ts-loader | 9.4.2 | 9.4.4 | 9.4.4 | @openmsupply-client/electron | devDependencies | https://github.com/TypeStrong/ts-loader |  |
| webpack-cli | 5.1.1 | 5.1.4 | 5.1.4 | @openmsupply-client/host | devDependencies | https://github.com/webpack/webpack-cli/tree/master/packages/webpack-cli |  |
| webpack-dev-server | 4.15.0 | 4.15.1 | 4.15.1 | @openmsupply-client/host | devDependencies | https://github.com/webpack/webpack-dev-server#readme |  |
| zustand | 4.3.8 | 4.3.9 | 4.3.9 | @openmsupply-client/common | dependencies | https://github.com/pmndrs/zustand |  |

**Comment by andreievg** [comment]
might be related: https://github.com/openmsupply/open-msupply/issues/1842
