### ISSUE TITLE
Review and update patient programs docs

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1992]
## Is your feature request related to a problem? Please describe 👀
Now that the patient programs work is merged, there are some additional changes required in the [docs](https://docs.msupply.foundation/docs/programs/module-hiv/)

## Describe the solution you'd like 🎁
After a brief review, here are some areas to look into:
- Remove the `Work in progress...`
- Add in something about the `Reports` section
- There's an invalid image near the top
![image](https://github.com/openmsupply/open-msupply/assets/9192912/53d3b21e-d39e-49ff-9118-24c43b6a3226)
- Add some information about enabling the patient programs module, and how to configure
- Patient history button?
- Review the text for changes to functionality
- Change the arrows used in images to match the style used elsewhere in the docs?
- Change language from US spelling? (e.g. customizable)

### Moneyworks Jobcode 🧰

`PG23OMD`

**Comment by roxy-dao** [comment]
https://docs.google.com/document/d/1-ePAWcv2hFvaF9iSzlWylrpjs8LWDk7DoRN9Z5RLBgU/edit#heading=h.wtl5tfuhum8e Can use this as a guide for docs

**Comment by mark-prins** [comment]
updated and deployed. Have removed a lot of duplication, and fixed up the inconsistent case of image names.
Added detail about tabs, history and talked about customisableness.
Updated screenshots with more recent ones.
Added a very brief reports note as well.
