### ISSUE TITLE
More detail for repack stock log

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1993]
## Is your feature request related to a problem? Please describe 👀
Currently, the repack log details only show the stock line id. As requested https://github.com/openmsupply/open-msupply/issues/1872#issuecomment-1637207856

## Describe the solution you'd like 🎁
Would like a translation added before id that says `Repacked from stock line (id)`

### Moneyworks Jobcode 🧰
PG23OMD

**Comment by andreievg** [comment]
duplicated by https://github.com/openmsupply/open-msupply/issues/1996
