### ISSUE TITLE
Repack created from oms does not show item details in repack window

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1996]
## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a sync system with at least one oms-site
2. Create a repack from oms-site and sync
3. In cloud, login to that store and open repack list window
4. See error: the item line is empty there

## Expected behaviour 🤔
Repack window definitely must have the item line entry there

## Screenshots 📸
[https://recordit.co/bOhbBoyAh4](https://recordit.co/bOhbBoyAh4)

## Your environment 🌱

 - Version: v1.2.0-RC2
 - Platform: apk
   - [x] android (tablet)

**Comment by andreievg** [comment]
Also mentioned here: https://github.com/openmsupply/open-msupply/issues/1993

**Comment by roxy-dao** [comment]
Caused by line_number being 0 in central. Have made an issue there to handle this change https://github.com/openmsupply/msupply/issues/13447

**Comment by mark-prins** [comment]
Raised as an mSupply issue

**Comment by nisha-dangol** [comment]
Moving to Done in favor of https://github.com/openmsupply/msupply/issues/13321#issuecomment-1772102972
