### ISSUE TITLE
Fail windows build on Jenkins if an error occurs

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2005]
## What went wrong? 😲
 
Currently, if there's a problem with the omSupply main build on jenkins, the installers are still built - using the previous build of main. This is not helpful

## Expected behaviour 🤔
If the main build fails:
- we should be alerted (currently configured to email m2 only, need to add in more people to the list)
- do not build the installers
- mark the build as failed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Fortunately, we have a build issue with the cargo certs currently, which makes this easy to test. Try to build and see what happens 😃 

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment]
You're probably far beyond this, but this is the setting I was mentioning earlier:
