### ISSUE TITLE
Stocktake- adjusting the pack size of a single batch doesn't change the stock

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/open-msupply#201]
Existing stock: Captopril num of packs: 5000  x pack 1
stocktake that line and adjust packsize to 10 - same num of packs: 5000 (so new qty is 50,000)
Finalise stocktake
Result: stock is unchanged.

I am not sure what expected behaviour is, but I don't believe existing mSupply allows editing the pack size of an existing batch as that would mess with the ledger.
If this was knowingly allowed, how the ledger is then reconciled will be a learning moment for me ;-)

**Comment by mark-prins** [comment]
the 'pack size' field was disabled to prevent the issue.
