### ISSUE TITLE
Button hover highlight is same colour as button text

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#2014]
## What went wrong? 😲

In certain theme colours, the navigation menu buttons become impossible to read when you hover over them.

![image](https://github.com/openmsupply/open-msupply/assets/7684221/6206f449-d4fc-455f-a270-bbc7594a2d7c)

## Expected behaviour 🤔

Different highlight approach?

## How to Reproduce 🔨

1. Have a blue theme like demo-open.msupply.org has at the moment. Or perhaps any theme where button text is white, and highlight is also white.
2. Hover over some buttons

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [x] browser **firefox**
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by andreievg** [comment]
Theme was changed on server, please refresh your local data if persists
