### ISSUE TITLE
Contact tracing

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2019]
For contatious diseases such as HIV, TB or Covid19,  it is desireable to record possible contacts that may have contracted the disease.
These contacts needs to be contacted, and if they consented they are then enroled into the matching program.

Contacting contacts is usually done in a separate step.
For this reason its is helpfull to have a list of all recently entered contacts of all patients and their status (e.g. Contacted | UnableToContact | Declined) in one place.

## General Requirements:

- Be able to record contacts for a given program (possibly directly link to existing patient)
- Contact entry may contain program specic data
- List, filter, sort the contacts
- Enrol contact as a patient into a program and link back to the contact entry

## Option 1:
- Record contacts either in the enrolment form or in an encounter.
- Extract contacts automatically, e.g. use specic `contacts` array in encounter or enrolment

Disadvantage: how to show contacts over multiple encounters? (using events would be a bit cumbersome)

## Option 2:
- Create a new "Contact Tracing" view were a list of existing contacts is displayed and new contacts can be entered
- A contact is recorded for a certain program and new contacts are stored in documents, i.e. a contact can contain program specific information
- A contact is in recorded within the patient screen (see new tab in mock below)
- Have another list view to show contacts for all patients

![contact_tracing](https://github.com/openmsupply/open-msupply/assets/88299195/a3a16750-4da4-45e8-975d-1df33527dcb5)

- [x]  Define ContactTrace base schema (in schema repository)
- [x] #2067
- [x] FE: Add "Contact Tracing" patient tab and let user create/edit new contact traces
- [x] FE: Add Contact Tracing overview list with all traces from all patients and programs
- [ ] #2086
- [ ] #2073

**Comment by richardmoizeau** [comment]
For some reason I'm worried to add another tab here, especially since we may have more to come ("Prescriptions" is the only one I can think of) and here are the ones in existing mSupply (not sure if we're going to add them though). 

<img width="509" alt="Screenshot 2023-08-01 at 6 42 48 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/e397fd80-37e7-4874-af0c-e3d256e3a22f">

I do see the value of having a contact tracing capability though for infectious disease...

Anyway, my point is that Option 2 sounds like the best:

- minimum: index patient must be "registered", ideally index patient should be enrolled in one or more programs
- you can "add a contact" to an index patient, you can select a "program" if the patient is enrolled into one ?

How do you turn a "contact" into a "registered patient" ? How do we keep the link between an index and a contact ?

**Comment by clemens-msupply** [comment]
> For some reason I'm worried to add another tab here, especially since we may have more to come ("Prescriptions" is the only one I can think of) and here are the ones in existing mSupply (not sure if we're going to add them though).
> <img alt="Screenshot 2023-08-01 at 6 42 48 PM" width="509" src="https://user-images.githubusercontent.com/74992958/257584497-e397fd80-37e7-4874-af0c-e3d256e3a22f.png">

Good point but I think there are probably a couple of ways to solve it in the UI, so I am not too worried about it...

> I do see the value of having a contact tracing capability though for infectious disease...
> 
> Anyway, my point is that Option 2 sounds like the best:
> 
>     * minimum: index patient must be "registered", ideally index patient should be enrolled in one or more programs
> 
I actually thought we could just have contact tracing document like `HIVPartnerTestingContactTracing` which is customized to a specific program. You could have multiple types of these contact tracing documents for different programs. So you don't need to enrol a contact; a contact belongs to a patient and the patient is already enrolled, you just need to select the correct contact tracing form/document.

>     * you can "add a contact" to an index patient, you can select a "program" if the patient is enrolled into one ?

Yes! see above

> 
> How do you turn a "contact" into a "registered patient" ? How do we keep the link between an index and a contact ?

On a contact's contact tracing page we can have an optional field that refers to the linked omSupply patient ID for the contact. You can then have two options:
- UI to find an existing patient that matches the contact
- Button that leads you to the patient creation page (prepopulated with fields already entered). After the patient is created the contact tracing entry is updated to contain the linked patient ID.

**Comment by mark-prins** [comment]
There is a time dependant nature to contacts, you may have someone living in the household at one point, but they either leave or are away for a period of time, during which there is an encounter / infection.

If you have a static list of 'contacts' associated with a patient then how do you know that a particular contact is relevant for a particular situation? Perhaps that's not a valid concern - having an occasional false positive is worth the convenience of not entering contacts during every encounter.

**Comment by clemens-msupply** [comment]
If the patient names the contact you would add the contact in any case. The clinician can then go through the contact list and contact the contacts. If the clinician figures out the contact is not at risk the status of the contact can be set accordingly (e.g. "RESOLVE" | "NOT_AT_RISK" or similar, do be defined...)

In the current plan, there will be a `contact tracing entry` for a specific program. For example, the same contact could have entries for two different programs. Furthermore, there could be duplicates within a program. Think we can help avoid creating duplicates in the UI by offering previously entered contacts. However, duplicates are not really an issue because somebody has to match them to actual patient anyway (e.g. the root patient might not know the exact details of a contact and the correct contact-patient information should come from the actual contact and not from somebody else).

**Comment by clemens-msupply** [comment]
Closing in favour of https://github.com/openmsupply/open-msupply/issues/2103
