### ISSUE TITLE
Merge 1.1.16 and 1.2.0 migrations

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#2020]
1.1.16 tag was released to a client, although there were [no migrations](https://github.com/openmsupply/open-msupply/blob/v1.1.16/server/repository/src/migrations/mod.rs) in that release, I forgot to increase develop version after that, and migrations were added under 1.1.16. If we don't merge 1.1.16 and 1.2.0 migrations, there would be a problem applying current develop 1.1.16 migration to the client with 1.1.16 version.

**Comment by nisha-dangol** [comment]
I'll just PASS this and move to Done as I upgraded the oms apk from v1.1.16 to the latest v1.2.00: data was not lost, no crashes and the upgrade went fine!
