### ISSUE TITLE
JSONForms Control: Display values from previous encounters

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2025]
Motivation: In vacination programs it is common that you have multiple dose of vaccines in different encounters. Similiar, for infants you have multiple follow up visits.
One solution to do this is to have special encounters for every visit, e.g. VaccineEncounter1, VaccineEncounter2, etc. However, this could become quite cumbersome. For example: if an encounter has been missed two vaccines might be given at the same time and this would require to create two encounter durring the same visit. Furthermore, you may want to see all vaccines that has been given so far, switching back and forth between encounter is not very user friendly.

Suggested solution:
- [ ] Have all encounter steps visible in a single encounter
- [ ] Display previous steps from previous encounters as readonly
- [ ] Use events to keep track which steps have been done, e.g. have one required field for the section and if it is truthly set an event that the section has been done. The use a special control to display the section as read only (see below).
- [ ] ~Bonus: Add option to redo a step, e.g. a clear button which then allows to enter data for an already taken step~

![mock_staged_encounter](https://github.com/openmsupply/open-msupply/assets/88299195/f3f8cc9e-678a-4225-b30a-a899c365c140)

## Previous Data Control:
Requirements:
When a configurable event is active the control should display data from the event's encounter as read only. If event is not set the data is editable for the current encounter.
- [ ] show source encounter date?
- [ ] Custom layout, e.g. use default JsonSchema syntax to configure which fields are displayed.

Example config:
```json
   {
      "type": "PreviousEncounterData", // better name?
      "label": "Vaccination 1",
      "scope": "#/properties/extension/properties/vaccination1",
      "options": {
        "conditions": [
          { "field": "field1", "isTruthly": true }
        ],
        "elements": [
          {
            "type": "Control",
            "scope": "properties/field1",
          },
          ...
        ]
      }
    }
```

**Comment by CarlosNZ** [comment]
![Screenshot 2023-07-24 at 3 19 57 PM](https://github.com/openmsupply/open-msupply/assets/5456533/5b8d7359-8f1b-4eea-91c8-9fb4c6c54527)

We already show a list of previous encounters in the sidebar. Would it work to just extend this with some more detail and filtering options (including filtering by event)?

**Comment by clemens-msupply** [comment]
Was more thinking of a view to have all information available in one view.

However, if we go with multiple encounter types for every step we could indeed use the sidebar, e.g. by also displaying the encounter name.
