### ISSUE TITLE
V1.2.0 latest dmg file says that it is damaged

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2040]
## What went wrong? 😲
 
Low priority since this is for mac, but when I download the dmg file from the [latest build from Github ] (https://github.com/openmsupply/open-msupply/releases/download/v1.2.00/omSupply_v1.2.00.dmg) and then try to open the app, I get this error: 

<img width="520" alt="image" src="https://github.com/openmsupply/open-msupply/assets/29744386/d724d1ab-6a06-484b-8d96-db6921be24bd">

## Expected behaviour 🤔
Would like to be able to open it 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. On a mac, download the dmg file from https://github.com/openmsupply/open-msupply/releases/download/v1.2.00/omSupply_v1.2.00.dmg 
2. Run the app
3. See error

## Your environment 🌱

 - Version: 1.1.20
 - Platform:
   - [x] desktop (macOS)

**Comment by mark-prins** [comment]
The `.dmg` file verifies ok with Disk Utility - and the application is fine locally.
The issue is with the `.app` file and the attributes after downloading: running `xattr -cr /Applications/open\ mSupply.app/` allows the application to run correctly.

**Comment by andreievg** [comment]
Maybe it's good to just make the test build version, I think signing will require a new key form apple ?

**Comment by DhanyaHerath** [comment]
Closed as duplicate of https://github.com/openmsupply/open-msupply/issues/2119
