### ISSUE TITLE
Patient created in oms are not syncing well to mSupply Desktop

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2046]
## What went wrong? 😲
Patient created in oms are not syncing well to mSupply Desktop dispensary despite the store pref `Patients created in other stores not visible in this store` OFF

## Expected behaviour 🤔
With that `Patients created in other stores not visible in this store` store pref OFF, all created patients should sync well to the cloud?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a sync setup with multiple remote sites: both oms and mSupply desktops
2. Create a patient1 from oms first and sync
3. Login to Desktop and see error: patient1 is not showing despite that store pref
4. Also try checking that pref ON/OFF (for desktop store) as [in the recording](https://recordit.co/hTYPju5l8h)
5. SYnc well
6. See error: you'll now notice the patient1's homestore is changed to that Desktop store.

## Screenshots
https://recordit.co/hTYPju5l8h

## Your environment 🌱

 - Version: v1.1.12 server, apk
 - Platform:
   - [x] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [x] server (windows)

**Comment by nisha-dangol** [comment]
Hi @roxy-dao 

While testing this out in new build exe (v1.3.0-test), from the `develop` branch, a few set of questions(expected behavior) pops up while testing this:
1. Should oms-stores respect the store pref `Patients created in other stores not visible in this store` strictly? I'm clearly seeing that patients created in individual oms-stores not being synced over the oms-stores despite the pref OFF, i.e., `Patient1` created in `oms1` is not syncing/showing up in `oms2` by default when the store pref for `oms2` is OFF. The only time it works is when I switch the pref from ON to OFF and resync the patient details.
2. Should the oms patients be editable from any oms dispensary stores? i.e., `Patient1` created from `oms1` can be editable from `oms2` store as well? 
3. Should oms UI allow to edit the patients originally created in mSupply desktop dispensary stores as well? related to [this issue](https://github.com/openmsupply/open-msupply/issues/2045) as well!

**Comment by roxy-dao** [comment]
@clemens-msupply can probably answer those questions better

**Comment by clemens-msupply** [comment]
>     1. Should oms-stores respect the store pref `Patients created in other stores not visible in this store` strictly? I'm clearly seeing that patients created in individual oms-stores not being synced over the oms-stores despite the pref OFF, i.e., `Patient1` created in `oms1` is not syncing/showing up in `oms2` by default when the store pref for `oms2` is OFF. The only time it works is when I switch the pref from ON to OFF and resync the patient details.

In omSupply `Patients created in other stores not visible in this store` is ignored right now. And patients that are on a site are visible on all stores at this site. Is this in line with your observations? There might be some sync logic based on this setting in mSupply?

>     2. Should the oms patients be editable from any oms dispensary stores by default? i.e., `Patient1` created from `oms1` can be editable from `oms2` store as well by default? Or are they going to be respecting the mSupply user permission: `Edit patient details`?

When you are logged into a store, and you have patient edit permissions for this store, you can edit patients that are located on the store's site. (there is no homestore in omSupply right now, a patient is just on a site)

> 
>     3. Should oms UI allow to edit the patients originally created in mSupply desktop dispensary stores as well? related to [this issue](https://github.com/openmsupply/open-msupply/issues/2045) as well!

Yes and this should already work.

**Comment by nisha-dangol** [comment]
> In omSupply `Patients created in other stores not visible in this store` is ignored right now. And patients that are on a site are visible on all stores at this site. Is this in line with your observations? There might be some sync logic based on this setting in mSupply?
> 
This really can't be tested right now, because I can't login to multiple stores within a site for oms. I've submitted [an issue here](https://github.com/openmsupply/open-msupply/issues/2099) for that to be addressed separately.
<br><br>
> When you are logged into a store, and you have patient edit permissions for this store, you can edit patients that are located on the store's site. (there is no homestore in omSupply right now, a patient is just on a site)
> 
Okay, #2099 surely does block this testing in some way. But for default user(or let's say the very first user registered in that oms-store), I see that oms needs `Edit patient details` user permission more than the `Add patients` permission. 
Turns out with add permission but NO edit permission, it will stop/block adding of patient anyways, followed by the annoying `Permission denied` alert message everytime. See [this recording](https://recordit.co/yx5y6UTnCE) for reference!
![SCR-20230817-e4f](https://github.com/openmsupply/open-msupply/assets/59193490/eb718628-b84b-4402-ac0b-02926de78c0d)
**Shouldn't `Add patients` permission be strictly for adding patients while `Edit patient details` permission for only editing?** @clemens-msupply 
<br><br>
> > ```
> > 3. Should oms UI allow to edit the patients originally created in mSupply desktop dispensary stores as well? related to [this issue](https://github.com/openmsupply/open-msupply/issues/2045) as well!
> > ```
> 
> Yes and this should already work.
>
As long as [this issue](https://github.com/openmsupply/open-msupply/issues/2045) persists, it'd be a problem for those desktop patients to be processed at oms-store!

**Comment by mark-prins** [comment]
> because I can't login to multiple stores within a site for oms

You can if the site in mSupply has multiple store assigned to it, and the current user has access to more than one of those stores. In this case you can use the store selector at the bottom of the page, as [shown here](https://docs.msupply.foundation/docs/introduction/tutorial/#footer)

**Comment by nisha-dangol** [comment]
> > because I can't login to multiple stores within a site for oms
> 
> Just as an aside.. you can if the site in mSupply has multiple store assigned to it, and the current user has access to more than one of those stores. In this case you can use the store selector at the bottom of the page, as [shown here](https://docs.msupply.foundation/docs/introduction/tutorial/#footer)
>
Aah.. almost missed/forgot that! Thanks @mark-prins 
<br><br>
Edit:
> In omSupply `Patients created in other stores not visible in this store` is ignored right now. And patients that are on a site are visible on all stores at this site. Is this in line with your observations? There might be some sync logic based on this setting in mSupply?
> 
I notice that the patients on a site are visible on all store in the site, as long as the `Edit patients` user permission is ON in that store

**Comment by roxy-dao** [comment]
> Okay, #2099 surely does block this testing in some way. But for default user(or let's say the very first user registered in that oms-store), I see that oms needs `Edit patient details` user permission more than the `Add patients` permission. Turns out with add permission but NO edit permission, it will stop/block adding of patient anyways, followed by the annoying `Permission denied` alert message everytime. 
https://github.com/openmsupply/open-msupply/issues/2106

> I notice that the patients on a site are visible on all store in the site, as long as the Edit patients user permission is ON in that store

All patients on a site in omSupply is accessible by any store on that site.

**Comment by nisha-dangol** [comment]
> #2106
>
Thanks!
 <br><br>
> All patients on a site in omSupply is accessible by any store on that site.
>
Is this the expected behavior that all patients on a site is accessible by any user of the stores on that site, regardless of the user permissions `Edit patients` ? 
In my test setup, `site1` has two stores `store1` and `store2` . `store1` is default store with all permissions for`user1` while `store2` for `user2` (i.e., `user1` has no any permissions in `store2` while `user2` has no any permissions in `store1` [except login rights of course]). In this case, are all the patients created in any of these stores accessible by each other all the time? My observation is only for users with `Edit patients` permission ON, it is enabling the user to view the patients(of all stores on that site) currently!

**Comment by clemens-msupply** [comment]
Yes this is correct, currently you need the EditPatientDetails permission to view them. This is the current mapping in omSupply. We might need to change this though when querying patients for prescriptions. Furthermore, we would need to handle a missing mutate permission in the program UI...
