### ISSUE TITLE
Programs forms lets you save invalid dates

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#2065]
![Image](https://user-images.githubusercontent.com/5456533/258266088-4bae007e-6cb0-4bf8-8ca0-e35c82b30d93.png)

The date shows as invalid in the form, but you can still save it.

Noted during upgrade of Mui date pickers: https://github.com/openmsupply/open-msupply/pull/2044#issuecomment-1661252327

**Comment by roxy-dao** [comment]
Might want to limit the year to > 1000 or > (current human age possible) as well 🤔

**Comment by CarlosNZ** [comment]
> Might want to limit the year to `> 1000` or `> (current human age possible)` as well 🤔

It seems to already be doing the first part. Will see if I can do that latter.

**Comment by roxy-dao** [comment]
> > Might want to limit the year to `> 1000` or `> (current human age possible)` as well 🤔
> 
> It seems to already be doing the first part. Will see if I can do that latter.

I saved a DoB with 0025 🤔

**Comment by CarlosNZ** [comment]
> I saved a DoB with 0025 🤔

Yes, but that's cos it currently lets you save invalid dates, but the component still considers that invalid. My fix just prevents it being saved, doesn't actually change anything about how "invalid" is calculated -- that's already okay :)

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.2.02

I can actually enter DoB as future dates in v1.2.02 exe. I can wait for new exe, in case v1.2.02 does not have this changes 🤷

In `develop` branch, I notice that in case I enter future dates (invalid), **it just saves the patient with no DoB at all! Is that expected?** I thought DoB was a mandatory field! @CarlosNZ @mark-prins 
Recording: https://recordit.co/bGEkFNXStC

**Comment by mark-prins** [comment]
yeah, sorry for the long drawn out issues with dates Nisha! We're now waiting for #2107 to be merged which should fix the patient creation too. 

In develop, the DoB not saving if it's invalid was sort of intended.. when the date value isn't valid the saving of the date is prevented, but the validation which stops the 'OK' button is handled separately, so you can still save the patient.

Essentially.. the dates are a little better with this issue (2065) and all the date problems should be fixed when 2107 is finished. Maybe hold off testing until then? I don't want to waste your time re-testing everything!

**Comment by nisha-dangol** [comment]
Thanks @mark-prins. I can wait for the new exe once #2107 is fixed/merged!
