### ISSUE TITLE
Confirm on Leaving alert -- update to work with ReactRouter 6

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#207]
Namely the `useConfirmOnLeaving` hook. Currently it alerts correctly when refreshing the page, but not when navigating otherwise (which is handled through React Router):

Current note in `useConfirmOnLeaving.ts`:

> Note: if the unsaved condition can be navigated away from using react-router
then this hook won't catch the navigation action
you will need to use the `Prompt` component instead ( or usePrompt or useBlocker )
however, these weren't implemented in react-router-dom v6 at the time of implementation

Ideally we can figure out how to capture ReactRouter-based navigation events too.

---

Here is a code sandbox demonstrating it working with `usePrompt`: https://codesandbox.io/s/react-router-6-use-prompt-use-blocker-17r2f

**Comment by mark-prins** [comment]
The example code is using an alpha version of 6 - there's still no `usePrompt` in the [docs](https://reactrouterdotcom.fly.dev/docs/en/v6)

**Comment by mark-prins** [comment]
A non-final-but-good-enough-for-now fix is in the programs branch: #600 
Will implement in develop when approved.
