### ISSUE TITLE
Cannot create new patients in oms exe's

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2079]
## What went wrong? 😲
Patients feature was working fine with mSupply server on v707-RC13/14 but with the latest mSupply v707-RC20, we cannot add new patients in oms exe's.  

## Expected behaviour 🤔
Should be able to add new patients in oms-exe with the correct permissions and setups

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. I have [this datafile with patients permissions](https://www.dropbox.com/scl/fi/q0phma36kvg0rlucqou70/Pokemon-Testing-Store-oms-2079.zip?rlkey=q5z7p5ut2hx4q5zds1tdbv0hi&dl=0) and all `4dinit` FC code run already!
2. One day, upgrade the mSupply server to latest v707-RC20 
3. Re-initialise the oms-site
4. Try to add new patients there
5. See error: that button doesn't work anymore!

## Your environment 🌱

 - Version: v1.2.01
 - Platform:
   - [x] android (tablet)  - weirdly, works for mobile! 
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] server (windows)

## Additional Context
I was actually trying to [test this ](https://github.com/openmsupply/msupply/issues/13175#issuecomment-1662861433)and realized I can't add new patients anymore here!

**Comment by roxy-dao** [comment]
There were some recent program changes that haven't been built yet that fixes this. Were you testing with a build version or with develop? 🤔

**Comment by mark-prins** [comment]
The build version. Develop branch is fine :) 
@nisha-dangol Possibly this PR fixed the issue #2052

**Comment by clemens-msupply** [comment]
Is this with or without programs config? Without programs config it is not suppose to work right now https://github.com/openmsupply/open-msupply/issues/2023

**Comment by nisha-dangol** [comment]
> Is this with or without programs config? Without programs config it is not suppose to work right now #2023

With program config, in v1.2.01 exe

**Comment by roxy-dao** [comment]
Think this can be closed since it is working... there's just not a build for it
