### ISSUE TITLE
Prescription Docs

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2081]
## Is your feature request related to a problem? Please describe 👀
Docs for prescriptions

## Describe the solution you'd like 🎁
Add prescriptions to public docs.

### Moneyworks Jobcode 🧰
OMS:MVP

**Comment by mark-prins** [comment]
talk about timing! I've been meaning to make an issue for this for a while.. and was just about to do it! 🙏

**Comment by roxy-dao** [comment]
Completed and up on omSupply public docs
