### ISSUE TITLE
v1.2.01 sync problems with earlier version of mSupply

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#2083]
## What went wrong? 😲

I tried initialising from reference file and notice that a lot of data was missing. Investigation showed that it was because program functionality relies on new fields being present in mSupply, we thought this was safe during discussion with @clemens-msupply, because no one is using program functionality yet, it turns out that other tables, not related to programs had additions:

`om_created_datetime` was missing from name (would mean missing transaction data)
`omSupplyUsesProgramModule` missing from pref thus store preferences wont' be integrated
`sub_context` is missing from report (document printing may be affected) 

I had a look an it seem that om_created_datetime and sub_context have been added to mSupply prior to max sync version going to 2 (it's just that reference data wasn't updated), but omSupplyUsesProgramModule is still in develop branch of mSupply (so we need to increment version there, or make it optional when syncing)

## Expected behaviour 🤔

Either backward compatible with future versions of mSupply or increase sync version compatibility

## How to Reproduce 🔨

With mSupply on master (prior to v7.7), set pack to one preference on for store active on omSupply site, creating customer invoice for the new omSupply site (make sure there are pack size > 1 lines on the invoice), it should be converted to pack size 1 when it arrive to omSupply (but that wouldn't happen) 

## Suggested solution

Either increment versions as per:

https://github.com/openmsupply/open-msupply/commit/784dbafabe8ba22aadb00b29eda8eaf0330e2f2e
https://github.com/openmsupply/msupply/commit/9a76711c06fb921db4803b947fedf1072cfed729

Or make it the new pref backwards compatible (still integrated even if mSupply version does not have it).

I would suggest the first option as the backwards compatible option can lead to confusion (when that preference is always off and there is no option in mSupply to enable it)

**Comment by roxy-dao** [comment]
Merged to main
