### ISSUE TITLE
Versioning and git flow

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#209]
### Issue Outcome

- [ ] Summarised in contribution doc (or somewhere in our dev docs)

### Motivation/Requirements

When we distribute our application to testers or customers:
* Keep track of which version bugs are found and fixed
* Keep track of which version minor features are added
* Keep track of version major features are added
* Ability to test/explore pre release versions
* Advise API (graphql) users of breaking changes
* Compatibility between client electron app and remote server

### Suggestion

Use semantic versioning, even though we don't have anyone using our repository as a service yet, three way differentiation is common and can work quite well as long as we know what each one means (this is very similar to current mobile and desktop):

`release` v{major}.{minor}.{patch}
`pre-release` v{major}.{minor}.{patch}-rc{pre release version}
`custom` b{branch}.{timestamp}

### Patch

Bug fix, straight into main branch. Develop is updated straight away with this change. (we assume all patches are in next minor)

### Minor

Feature or improvement, the stuff in develop branch vs main.

### Major

Not really sure, maybe major milestones ? (i.e. full features set of program, or full features set of procurement). Breaking Graphql API changes

### Pre Release

Before we merge develop to main or before bug fix is merged into main if we want to validate that built version working correctly, we make RC, if RC doesn't fix the issue or breaks something else another RC is made after the changes. When we happy with RC we can merge and create a patch. So v1.0.1 is higher version then v1.0.1-rc5

### Develop Branch

Version is always +1 minor from main. We work in develop branch when feature set/improvements are small enough to fit within a release cycle or when a part of bigger features set can be introduced into main release safely. Need to RC and full manual test before merging into main

### Feature Branches

Ideally all new features will be in features branches, but some maybe small enough to be done in develop. When a feature set is identified to be either too big to fit within release cycle, or part of the set are unstable without the whole, we definitely need to use feature branches.

If multiple features branches are to be merged into develop then main in one release cycle, we need to identify the order (priority or risk) and merge them one by one (updating other features from develop and testing entirely)

### API, Cargo.toml, package.json and version.rs 

`Cargo.tomls` and `package.jsons`, seem like extra overhead that is hard to keep in sync ? Is it ok to just leave them as 0.0.0 ? 

We do need to store current app version, on top of the tag somewhere, accessible by the server (for database migrations and display in UI). So some file `version.rs` with app version, api version, and information about the build (being replaced by build process with information from the trigger, i.e. tag or branch and sha etc...).

`API`, this is the Graphql API, we don't have any consumers ATM, and if we think that front end is always bundled together with the server, we don't really need it. 

### TODO

Compatibility
* Between central
* Between client electron app and remote server
* Between existing remote server ? (if it's too difficult to do migrations and requires re-initialisation ?)
* Forms and Report on central and remote sever ?

**Comment by Chris-Petty** [comment]
Looks great nothing to add off the top of my head! 

I am wondering if this will be indicative/useful for client/frontend apps knowing when they need to refresh their bundles?

**Comment by jmbrunskill** [comment]
>Cargo.tomls and package.jsons, seem like extra overhead that is hard to keep in sync ? Is it ok to just leave them as 0.0.0 ?

I think it's ok unless we are creating shared packages (e.g. if we ever get around to publishing  common package independently of the app), then we'd want to have proper versions for those packages/libraries.

**Comment by mark-prins** [comment]
@andreievg Is #721 enough to close this issue?
