### ISSUE TITLE
Handle changed password for manual user sync

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2092]
## Is your feature request related to a problem? Please describe 👀
If the user changes their password in the central server while they're not connected, then they will get a LoginFailure error when they try to manually sync the user in server.

## Describe the solution you'd like 🎁
Log the user out and make them login again to refresh the password for manual sync.

### Describe alternatives you've considered 💭
- Error message telling the user they need to log out and sign back in again...
- Update token when syncing user thus updating password

**Comment by mark-prins** [comment]
Rather than immediately logging the user out, can we detect the 'invalid login' error, display a modal / prompt and tell the user that they'll need to login again to sync the user details. Give the option to cancel and continue working perhaps?

**Comment by andreievg** [comment]
Sorry I didn't see this one for some reason and created my own issue: https://github.com/openmsupply/open-msupply/issues/2095, i'll close it. 

For Sync Carry Over we would need:

1. When server responds with credentials mismatch, log user out (rather then displaying credentials error, or as per Mark's suggestion)
2. Use token (mSupply to respond with token on user auth, and seperate end point to get useInfo) rather then storing credentials in memory on back end

I think if we save the token on mSupply end we don't need to do worry about 1, so would prefer waiting for 2. Also 1. would usually only happen if user is not logged in (so low probability and impact)

@nisha-dangol @roxy-dao

**Comment by mark-prins** [comment]
@roxy-dao are you ok if we close this and implement the token change in mSupply?
Thinking that this is a bit of an edge case, so it's ok to keep in for a while

**Comment by roxy-dao** [comment]
> @roxy-dao are you ok if we close this and implement the token change in mSupply? Thinking that this is a bit of an edge case, so it's ok to keep in for a while

Yup~ Can close and do token change in mSupply

**Comment by santoshkhanal12** [comment]
@andreievg @roxy-dao @mark-prins 

May be we should have discussion on this one

1. Have a omSupply site with `OMSite1` with `OMStore2`
2. Sync Successfully the OMSsite
3. Go to mSupply Cloud and go to `OMSite1` remove `OMStore2`and add `OMStore1`
4. Now so the OMS site, and resync by user.
5. You will see same old store `OMStore2` logged in even if you already changed the stores in the site?

https://github.com/msupply-foundation/open-msupply/assets/117138852/70c8c0ba-d84e-4fbf-9fa0-61f24e5b057d
