### ISSUE TITLE
Programs mSupply Dashboard report: "PEPFAR RAW"

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2102]
Report to be implemented in mSupply Dashboard: 

Link to the [report](https://docs.google.com/spreadsheets/d/1a5bzRNpFZoGtadrcn7yd40CYvxD1uV54/edit#gid=575406945) 

Name of the report: `HPDB - PEPFAR RAW`
Location in HPBD: Home > Reports > Reports - General > PEPFAR RAW
Program: HIV Care & Treatment
Description: This report displays data from **the most recent encounter** for each patient. 

See "Details" tab of this doc for more explanations about each field. 

### Moneyworks Jobcode 🧰

PG23THRFC

**Comment by clemens-msupply** [comment]
I just had a look at the Access queries, tts actually not just the most recent encounter... will try to replicate the report from the Access queries.

**Comment by richardmoizeau** [comment]
Thanks for checking - looking at it again, you are right - not all fields are from the latest encounter (some are from the first encounter or the first encounter when patient started ARV).

**Comment by clemens-msupply** [comment]
@richardmoizeau there are two unclear fields:
- RiskSummary and KeyPop (patient registration): We only do the riskGroup in the encounters now. We also don't really import these right now so maybe these need some more discussion...
- status: in the original report there is a mix of "LTFU" and "active", etc. I guess I can replicate the original logic though?
