### ISSUE TITLE
Problem with create stocktakes user permission in oms

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2105]
## Agreed solution
Remove `View Stocktake line` permission mapping and map QueryStocktake to `View Stock` permission

## What went wrong? 😲
For a oms-user with `create stocktake` permission, it's not reflecting same in oms-UI. 
This may probably need further investigation as I observed that other permissions like 'Create customer invoices' are working well.

## Expected behaviour 🤔
As long as the user-permission is set, it should refelect accordingly.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create a user with `create stocktake` permission ON and login rights to the oms-store
2. In oms, login and try to create stocktake
3. See error: you can't create stocktake as the annoying message `permission denied` keeps popping up
4. Sync.
5. See another error: there are number of records to be pushed (meaning, the stocktake lines are being generated?)
6. In mSypply Cloud, login to that oms-store and see stocktakes
7. See error: there actually are those stocktake lines entered.

## Recording Reference
https://recordit.co/qNppG6oTb8

## Your environment 🌱

 - Version: v1.3.00-test
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by roxy-dao** [comment]
Quite a few permissions are needed to use stocktake as a whole...

The `Create stocktake` permission is working correctly in your video. It allowed you to create a stocktake from a master list, but you don't have permissions to view the stocktake (mSupply's `View stocktake lines` wasn't enabled), so it popped up with the permissions denied message.

**Comment by nisha-dangol** [comment]
> Quite a few permissions are needed to use stocktake as a whole...
> 
> The `Create stocktake` permission is working correctly in your video. It allowed you to create a stocktake from a master list, but you don't have permissions to view the stocktake (mSupply's `View stocktake lines` wasn't enabled), so it popped up with the permissions denied message.

I'm noticing that the both `Create stocktake` and `View stocktake line` permission is not enough to stop that annoying alert message' which is the weird part. Also, with just these two permissions ON while `Add/Edit/Delete stocktake lines` permissions are OFF ,it still allows to add/edit/delete stocktake lines. The permissions do not look mapped correctly for oms.
![image](https://github.com/openmsupply/open-msupply/assets/59193490/32aeb37c-c17d-40ae-96e8-a445d5e0288b)
<br>
Also, after checking ALL Stocktake permissions, I still see the `Permission denied` message popping up in stocktake list window even after syncing `User Synchronisation Status` as well!

**Comment by roxy-dao** [comment]
Hmm, the `New Stocktake -> Items with Stock` uses the `View Stock` permission, that's why you're getting the permission denied when you first go to the stocktake view (Just needs it to display the message that there's no stock lines)... Is there a case where a user can do stocktake but not view stock? 🤔 

omSupply is only mapping permissions in a simple way right now, so add/edit/delete are all mapped into one mutate permission

**Comment by nisha-dangol** [comment]
> Hmm, the `New Stocktake -> Items with Stock` uses the `View Stock` permission, that's why you're getting the permission denied when you first go to the stocktake view (Just needs it to display the message that there's no stock lines with stock)... Is there a case where a user can do stocktake but not view stock? 🤔
> 
Yup, you're right. That does look like the current behavior:  For creating stocktake, `View stock` permission seems to be required as regardless of `Create stocktake` permission is ON or OFF.  And the 'View stocktake lines` permission looks useless here. 😬
<br>
>  Is there a case where a user can do stocktake but not view stock? 🤔
> 
So, for your question, answer is NO, user can't do stocktake without being able to view stocks currently!

**Comment by DhanyaHerath** [comment]
OK so question: we could remove the `View stocktake lines` permission in mSupply - it's not used anywhere. Should we do that since it is causing confusion?

**Comment by DhanyaHerath** [comment]
Oops, forgot to tag in [above comment ](https://github.com/openmsupply/open-msupply/issues/2105#issuecomment-1743995044): @roxy-dao @mark-prins @andreievg @JonnaQuismundo

**Comment by roxy-dao** [comment]
> OK so question: we could remove the `View stocktake lines` permission in mSupply - it's not used anywhere. Should we do that since it is causing confusion?

Apparently it is being used to 'view stocktake lines' in mSupply though 👀

**Comment by roxy-dao** [comment]
> Oops, forgot to tag in [above comment ](https://github.com/openmsupply/open-msupply/issues/2105#issuecomment-1743995044): @roxy-dao @mark-prins @andreievg @JonnaQuismundo

Yes remove and replace with `View Stock` I believe, since that's what's being used to View Stocktakes? https://github.com/openmsupply/msupply/issues/13618#issuecomment-1740315547

**Comment by DhanyaHerath** [comment]
Nah - @JonnaQuismundo will confirm but afaik it is not being used in mSupply

**Comment by roxy-dao** [comment]
> Nah - @JonnaQuismundo will confirm but afaik it is not being used in mSupply

I was being a little trigger happy and misread something 😆

**Comment by JonnaQuismundo** [comment]
> Nah - @JonnaQuismundo will confirm but afaik it is not being used in mSupply

yup `View stocktake lines` permission is not used in mSupply. We plan to create a PR to remove the permission in the UI.

**Comment by JonnaQuismundo** [comment]
> > Nah - @JonnaQuismundo will confirm but afaik it is not being used in mSupply
> 
> yup `View stocktake lines` permission is not used in mSupply. We plan to create a PR to remove the permission in the UI.

PR to remove the `View stocktake lines` https://github.com/openmsupply/msupply/pull/13725

**Comment by roxy-dao** [comment]
Updated issue with agreed solution
