### ISSUE TITLE
(Stock) expired and expiring soon count on dashboard the same

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2123]
## What went wrong? 😲
The count for expired stock and stock expiring soon is the same on dashboard... 

![Screenshot 2023-08-24 at 3 02 45 PM](https://github.com/openmsupply/open-msupply/assets/61820074/57f4d190-bce8-4a86-a40a-5bf9a2ce953b)
Last two stock lines are expired and the three before that are expiring soon....

![Screenshot 2023-08-24 at 3 03 15 PM](https://github.com/openmsupply/open-msupply/assets/61820074/e14480e6-acdd-4940-9495-a5a275b32848)
Stock count is only showing the expired count for both expiring soon and expired.

## Expected behaviour 🤔
Stock expiring soon should only count stock that is expiring soon, not stock that has already expired.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have some stock that has expired and some expiring in a month 
2. Check dashboard
3. Count is the same for `Inventory Management` card.

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by nisha-dangol** [comment]
Moving to Done as [it looks fine! ](https://github.com/openmsupply/open-msupply/issues/1819#issuecomment-1707746581)
