### ISSUE TITLE
Pricing in first stocktake line shows NaN

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2126]
## What went wrong? 😲
![Screenshot 2023-08-24 at 9 55 01 AM](https://github.com/openmsupply/open-msupply/assets/61820074/ead51e2c-990e-44a8-9a8c-5de3b93c29b5)

## Expected behaviour 🤔
Should show 0 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create stocktake
2. Add item that has 0 stock lines
3. Go to pricing
4. See $NaN

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Hmm... doesn't seem to be happening anymore

**Comment by CarlosNZ** [comment]
Yeah, can't replicate here either.

**Comment by kahn-msupply** [comment]
I also was unable to reproduce issue on Android Tablet! Did multiple new stocktakes and tried a few different items.
