### ISSUE TITLE
Standard patient edit layout

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2128]
## Is your feature request related to a problem? Please describe 👀
When using the standard patient edit form, the layout does not look good to me. There's too much whitespace on the left which also leaves the heading isolated 

<img width="1511" alt="Screenshot 2023-08-24 at 10 01 06 AM" src="https://github.com/openmsupply/open-msupply/assets/9192912/1d8d6472-4fb4-403e-8129-105e2b9a2969">

## Describe the solution you'd like 🎁

Something more like this:

<img width="1511" alt="Screenshot 2023-08-24 at 12 46 28 PM" src="https://github.com/openmsupply/open-msupply/assets/9192912/7a07f750-90bb-444a-96f5-53a5258114d1">

**Comment by richardmoizeau** [comment]
if we could, I'd like to go even further with something like below (below example for the item detailed view but would apply for the patient form too): 

<img width="1022" alt="Screenshot 2023-08-28 at 3 22 22 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/123ee8d7-6f4a-40f4-bccb-39b126e40010">

**Comment by mark-prins** [comment]
ooh! that looks good 😁

**Comment by nisha-dangol** [comment]
Hi @CarlosNZ 
I checked this on the latest v1.4.00-test-2023-10-02 exe (that was build just yesterday). 

##  On data with program config, 
I see the alignment correct as below: 
<img width="1505" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/bb8d78c3-092a-4ac4-a5d7-558c464463b3">

##  But for non-program datafile, 
I see the alignment as below:
<img width="1319" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/4c31d186-a873-4dec-9611-c91d06c0ec3c">
**I do not see any tabs like Details, Programs, Encounters and Contact Tracing (which looks correct to me) like in the PR you mentioned (for non-program datafile) Is that even expected there? Can we access Programs,Encounters in data with no programs configs?**
<img width="836" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/9c93d462-4876-4ab2-855f-d14fbc870860">

**Comment by nisha-dangol** [comment]
> > Can we access Programs,Encounters in data with no programs configs?
> 
> My understanding is that these tabs will show up if Programs is enabled in preferences (and therefore you'll see them in the sidebar menu), whereas the display of the Patient (basic or complex) depends on whether there is a schema defined. Normally these two things would go together, but they don't technically have to be.

Cool thanks! I can see the tabs after enabling the programs module store-pref for oms-store (in non-programs data as well). They look good to me:
<img width="1334" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/54a36cc7-09b3-4d4b-bfd0-fe1ed50a192b">
