### ISSUE TITLE
HIV Module - Grafana Report: HTC eRegister

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2138]
### General Description

In this report, I should be able to see 
- all the HIV Testing and Counselling (HTC) encounters of a patient
- for all facilities

### Variables

- Store Code
- Store Name
- Time Range

### Report layout

|Fields           |Open mSupply (if different)    |Source       |Comments                                                                                                                             |
|-----------------|-------------------------------|-------------|-------------------------------------------------------------------------------------------------------------------------------------|
|ID               |do we have an Open mSupply ID ?|System       |In HPDB, this is a sequential number for the encounters in one facility If we maintain a mSupply encounter ID, we can display it here|
|Facility ID      |Store Code                     |System       |the mSupply store code                                                                                                               |
|Facility ID      |Store Name                     |System       |the mSupply store name                                                                                                               |
|HTC Serial Number|                               |HTC Encounter|                                                                                                                                     |
|Date of Visit    |                               |HTC Encounter|                                                                                                                                     |
|(N)UIC           |                               |Registration |UIC = NUIC                                                                                                                           |
|Age              |                               |Registration |Age at the time of the visit                                                                                                         |
|Gender           |                               |Registration |                                                                                                                                     |
|Point of Entry   |                               |HTC Encounter|                                                                                                                                     |
|Risk Group       |                               |HTC Encounter|                                                                                                                                     |
|Partner Status   |                               |HTC Encounter|                                                                                                                                     |
|GBV Screening    |                               |HTC Encounter|                                                                                                                                     |
|HIV Test Result  |                               |HTC Encounter|                                                                                                                                     |
|TB Screening     |                               |HTC Encounter|                                                                                                                                     |
|ART Number       |                               |HTC Encounter|ART Number = HIV Care & Treatment Enrolment ID                                                                                       |
|HIV Clinic Code  |                               |HTC Encounter|                                                                                                                                     |
|Known Positive   |                               |HTC Encounter|                                                                                                                                     |
|Escorted         |                               |HTC Encounter|                                                                                                                                     |
|GBV or PEP       |                               |HTC Encounter|                                                                                                                                     |
|Comments         |                               |HTC Encounter|                                                                                                                                     |

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
@richardmoizeau 
We don't record "Known Positive" do we?  We also don't record the referred "HIV Clinic Code"... Should I add it? 

"GBV or PEP" This is true when GBV or PEP is selected in the multi select, right?

**Comment by clemens-msupply** [comment]
The TB screening is missing as well..

**Comment by richardmoizeau** [comment]
- [ ] `Known Positive` (or `Known HIV+`):  indicate if client is already a known HIV positive with Yes. Else enter No or leave blank 

![Screenshot 2023-09-04 at 11 05 10 AM](https://github.com/openmsupply/open-msupply/assets/74992958/2e6bcaa5-cebd-449c-9493-7bb65799c4cc)

I have asked the team if that's something they want to keep. I can see that we already have including the `Previous HIV Test Result` and `Previous HIV Test Date:` in the "Risk Behaviour" bubble. Maybe not the right place (at it least it should no be under "Have you experienced any of the following in the past 12 months ?"

- [ ] `HIV Clinic Code` and `Escorted ?` are both recorded in the "HIV Testing" bubble: `if another facility, name of the facility` (we need check if that should the code instead of the name)

<img width="710" alt="Screenshot 2023-09-04 at 11 10 55 AM" src="https://github.com/openmsupply/open-msupply/assets/74992958/2675b5a6-c6a5-42dd-a724-018edb349196">

- [ ] _"GBV or PEP" This is true when GBV or PEP is selected in the multi select, right?_ Yes. 

- [ ] TB Screening: yes, don't know how we missed that one.  I may have forgotten to include it under in my original specifications. 

![Screenshot 2023-09-04 at 11 15 50 AM](https://github.com/openmsupply/open-msupply/assets/74992958/f23f57e4-1235-4926-bada-3b7b6dbfa7ca)

**Comment by clemens-msupply** [comment]
Done
