### ISSUE TITLE
HIV Module - Grafana Report: Covid-19 Vaccination History

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2139]
### General Overview

In this report, I want to see 
- all Covid-19 Vaccination's encounters (encounter type of the HIV Care & Treatment program) 
- for all facilities

### Variables

I would like to filter the data by: 
- store code
- store name

### Report Layout

|Fields           |Open mSupply (if different)    |Source       |Comments                                                                                                                             |
|-----------------|-------------------------------|-------------|-------------------------------------------------------------------------------------------------------------------------------------|
|Facility ID      |Store code                     |System       |                                                                                                                                     |
|Facility Name    |Store name                     |System       |                                                                                                                                     |
|Patient ID       |Enrolment ID                   |Registration |                                                                                                                                     |
|Client offered Vaccination ?|                               |Encounter    |                                                                                                                                     |
|Reason for decline|                               |Encounter    |                                                                                                                                     |
|Vaccination Date |                               |Encounter    |                                                                                                                                     |
|Vaccine Manufacturer|                               |Encounter    |                                                                                                                                     |
|Comments         |                               |Encounter    |        

## Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
Merged
