### ISSUE TITLE
HIV Module - Grafana Report: ICFPT eRegister (Contact Tracing)

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2142]
### General Description

As a program manager, I want to see a list of all contacts for all the facilities 

### Report Layout / Structure

|Field            |Open mSupply Field (if different)|Source       |Comments                                                                                                                             |
|-----------------|---------------------------------|-------------|-------------------------------------------------------------------------------------------------------------------------------------|
|Index Record ID  |mSupply UID for the contact      |System       |                                                                                                                                     |
|Facility ID      |Store code                       |System       |                                                                                                                                     |
|                 |Store name                       |System       |                                                                                                                                     |
|ICFPT Serial No  |                                 |Encounter    |                                                                                                                                     |
|Index ART Number |                                 |Index Patient HCare&T Enrolment ID|                                                                                                                                     |
|Index HTC Number |                                 |Index Patient HTesting&C Enrolment ID|                                                                                                                                     |
|Index NUIC       |                                 |Index Patient Registration Details|                                                                                                                                     |
|Entry Date       |                                 |System       |Date when contact was created in the system                                                                                          |
|Index Type       |                                 |Encounter    |                                                                                                                                     |
|Index Age        |                                 |Index Patient Registration Details|                                                                                                                                     |
|Index Gender     |                                 |Index Patient Registration Details|                                                                                                                                     |
|Accepted ICT     |                                 |Encounter    |Not sure if we need it since it's already recorded in the HCare&T program                                                            |
|Contact Age      |                                 |Encounter    |                                                                                                                                     |
|Contact Gender   |                                 |Encounter    |                                                                                                                                     |
|Contact Know HIV+|                                 |Encounter    |                                                                                                                                     |
|Contact ARV Status|                                 |Encounter    |                                                                                                                                     |
|Clinic confirmed KP ?|                                 |Encounter    |                                                                                                                                     |
|Relationship     |                                 |Encounter    |                                                                                                                                     |
|IPV Risk Outcome |                                 |Encounter    |                                                                                                                                     |
|Disqualified from PNS|                                 |Encounter    |                                                                                                                                     |
|Indec Referred Post-GBV|                                 |Encounter    |                                                                                                                                     |
|Preferred PNS Approach|                                 |Encounter    |                                                                                                                                     |
|Partner Contacted ?|                                 |Encounter    |                                                                                                                                     |
|Partner Consented ?|                                 |Encounter    |                                                                                                                                     |
|Partner Test Result ?|                                 |Encounter    |                                                                                                                                     |
|HIV Testing Date |                                 |Encounter    |                                                                                                                                     |
|Contact ART Enrolled|                                 |Encounter    |                                                                                                                                     |
|Contact ART Number|                                 |Encounter    |                                                                                                                                     |
|Contact IPV post PNS|                                 |Encounter    |                                                                                                                                     |
|Comments         |                                 |Encounter    |                                                                                                                                     |

## Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
```sql
-- qryIndexTestingeRegister
SELECT
    tblIndexTestingeRegister.ID,
    tblIndexTestingeRegister.Fac_Id,
    tblIndexTestingeRegister.SerialNo,
    tblIndexTestingeRegister.[ART Number],
    tblIndexTestingeRegister.[HTC Number],
    tblIndexTestingeRegister.UIC,
    tblIndexTestingeRegister.Date_Reg,
    tblIndexTestingeRegister.IC_Age,
    tblIndexTestingeRegister.IC_Gender,
    tblIndexTestingeRegister.IC_Type,
    tblIndexTestingeRegister.Accept_ICT,
	tblIndexTestingeRegister.Contact_Age,
	tblIndexTestingeRegister.Contact_Gender,
	tblIndexTestingeRegister.Contact_HIVpos,
	tblIndexTestingeRegister.Confirmed_KP,
	tblIndexTestingeRegister.Contact_ARTstatus,
	tblIndexTestingeRegister.Relationship,
	tblIndexTestingeRegister.IPV_Risk_Ocome,
	tblIndexTestingeRegister.PNS_Disq,
	tblIndexTestingeRegister.IC_GBV_Ref,
	tblIndexTestingeRegister.PNS_GBV_APP,
	tblIndexTestingeRegister.Part_contacted,
	tblIndexTestingeRegister.Part_consented,
	tblIndexTestingeRegister.Part_tested,
	tblIndexTestingeRegister.Part_Test_Res,
	tblIndexTestingeRegister.[HIV Testing Date],
	tblIndexTestingeRegister.[HCT Number],
	tblIndexTestingeRegister.Part_ART_enrol,
	tblIndexTestingeRegister.IC_post_IPVpns,
	tblIndexTestingeRegister.Comments
FROM tblIndexTestingeRegister
WHERE (((tblIndexTestingeRegister.Date_Reg)>=return_g_FromDate()
    And (tblIndexTestingeRegister.Date_Reg)<=return_g_ToDate()));
```
