### ISSUE TITLE
Encounter list view pagination is not working

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2144]
![image](https://github.com/openmsupply/open-msupply/assets/88299195/d89c5a98-a719-4e68-8daa-e69324d49225)

- [x] Be able to select page
- [x] Be able to select entries / page

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.3.00 exe

- [x] pagination, filter, and sort works for both encounter lists and the program enrolment list. Noticed that sorting doesn't really work well in Dispensary>Encounters window. Issue here: #2204
