### ISSUE TITLE
Browser-specific bug: Requested quantity bar chart not showing up only in Firefox

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#2145]
## What went wrong? 😲
 

May be other places too, but I noticed in Requisitions -> Detail View -> Item Modal

The "Requested quantity" bar chart is not showing up in Firefox but is fine in Chrome (and Safari). This is on Mac, haven't tried other OSes.

### Firefox view:

<img width="1088" alt="Screenshot 2023-08-29 at 3 56 22 PM" src="https://github.com/openmsupply/open-msupply/assets/5456533/4a6b92ab-eb4b-4cbd-ac8c-96a6572a7a54">

### Chrome view (of the exact same item)

<img width="1062" alt="Screenshot 2023-08-29 at 3 56 28 PM" src="https://github.com/openmsupply/open-msupply/assets/5456533/a4b3689c-5f68-4dd3-91a3-3ccbc3b09bef">

**Comment by mark-prins** [comment]
on my version of firefox, the content is there, but down the page - with a vertical scroll:

<img width="1086" alt="Screenshot 2023-08-29 at 4 15 27 PM" src="https://github.com/openmsupply/open-msupply/assets/9192912/ce2d3efd-8fef-4950-b6a3-0f31cf740790">

**Comment by CarlosNZ** [comment]
> on my version of firefox, the content is there, but down the page - with a vertical scroll:

Yeah, that seems to be the case. Weird to have these kind of browser-specific bugs -- Material UI should normally handle any discrepancies invisibly. 

I'll have a quick look and see if this is anything obvious.

**Comment by mark-prins** [comment]
> Material UI should normally handle any discrepancies invisibly

( usually, and quite likely in this case, it isn't mui that's the problem - it's what we've done with flex 🙄 )
