### ISSUE TITLE
When lines are sorted, the Ok&Next button should respect the sorted sequence in Inbound shipment

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2151]
## What went wrong? 😲
In Inbound shipment, when lines are sorted, the `Ok&Next` button should respect the sorted sequence instead of the originally added line sequence.
This would look problematic if user sorts the lines and happens to notice that `Ok&Next` button not working randomly when selected the first line after sorting, like in the Recording below! 

## Expected behaviour 🤔
The 'Ok&Next` button should respect the sequence even when sorted.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create a manual inbound shipment
2. Add items; remember the sequence in which you add them
3. For example, add `item B` first, add packs and batches and all.
4. Then let's say add `item C`, then add `item A`
5. Try to sort the lines by item name
6. You'll see items sorted alphabetically, i.e., `item A` first, then `B` then `C`.
7. Click `item A` in that SORTED list
8. See error: the `OK&Next` button is disabled, because it's the lastly added item in the list; regardless of the sorting applied
9. Try sorting alphabetically in reverse this time, i.e., from Z-A, NOT A-Z. You'll see `item C` first followed by `B` then `A`
10. CLick `item B` line. You can see `Ok&Next` button enabled.
11. Click it
12. See error: you'll see the next `item C` instead of `item A`; meaning the `Ok&Next` button is not respecting the sorted list sequence at all!

## Your environment 🌱

 - Version: v1.3.0 exe
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)
 
## Recordings
https://recordit.co/xyUXiTAr7L
https://recordit.co/x3CV8Hi88r

**Comment by mark-prins** [comment]
We've had this before.. I thought it was resolved for Inbounds 🤷 
the approach used for Outbound lines can be applied to Inbounds. The problem is that the state of useColumns and the applied sortBy isn't shared between the two instances (DetailView and EditModal)

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Create an inbound shipment from a master list
- [x] Change how the inbound shipment lines are sorted
- [x] Click of one of the lines to go to the edit modal
- [x] Enter some packs and click Ok & Next
- [x] Should go to next item on the list instead of going to the next item in the alphabet
