### ISSUE TITLE
More than 5k records of item list do not appear in transaction window

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2158]
## What went wrong? 😲
 
When the datafile has more than 5k no. of items, it turns out it won't show all the list of items while issuing or any other transaction like stocktakes or replenishments as well.

## Expected behaviour 🤔
All items (not just limited 5k items but all) should load properly.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure your data has more than 5k items. (5k seems to be the limit currently as per @raviSussol )
2. Go to that master-list window
3. See first error: it takes some noticeable time to load all those items. **Maybe add pagination in that window as well?**
4. Check the last time, for eg: `test` item in the last
5. Now create any transaction, for eg: create anew stocktake
6. Click 'Add item' button
7. Search for `test` item
8. See error: the list doesn't even show that `test` item at all. (since it doesn't lie within the 5k loaded items in that list)

## Recordings
https://recordit.co/dwYRFP8k4i

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)
 
## Additional context
@raviSussol seems to be working [on similar issue](https://github.com/openmsupply/health-supply-hub/pull/1036) in hsh, so can apply the same fix here as well?

**Comment by nisha-dangol** [comment]
@raviSussol 
Checked/Tested this in the newly built v1.3.0-2158 exe. **Doesn't work**: the list still does not show the last item `test` in the `Add item` field in any transaction window
<img width="1025" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/0e84992c-2a0d-4d5e-ba15-4cc4fba38bbd">

**Comment by AnushaUp** [comment]
Tested in `v1.6.00`
Looks good with very smooth slider and items can be search and its not slow mention in issue.

https://github.com/msupply-foundation/open-msupply/assets/115983430/59d635b5-7b11-41ee-83c2-7260658ea460
