### ISSUE TITLE
Plugins: validation

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2164]
## Is your feature request related to a problem? Please describe 👀

Part of epic: #2084 
Two aspects for the plugin validation
- [ ] Sign plugins: provide a way to sign and create a manifest of the plugin files
- [ ] Enforce a minimum version of omSupply 

## Describe the solution you'd like 🎁

for the signing - create a cli action to sign a plugin which creates a manifest and signs it (using a private key?). The server can then check validity of the signature and verify that only the signed files, with correct size and hash are in the plugin directory.

version check: a simple minimum version number that the plugin will require for omSupply

**Comment by clemens-msupply** [comment]
### Plan of action:

Idea: roughly follow https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin

#### Signing a plugin:
- Create a CLI tool to create a manifest file `manifest.json`, e.g. collect all files + file hash values in the plugin dir
- Use [sslsign](https://docs.rs/openssl/latest/openssl/sign/index.html) to sign the manifest and store the signature in a `manifest.signature` file. This means plugins are signed with normal ssl keys which are easy to generate. Furthermore, we already have openssl in the code base.
- In the previous step the ssh public key fingerprint is included in the `manifest.json` (needed to know which public key is required for validating the signature) 

This means two files (`manifest.json` + `manifest.signature`) are added to the plugin dir.

#### Verifying plugins on the backend
- Load a list of trusted public ssl keys, e.g. stored in special dir on the backend

When the frontend makes a request to fetch a file from a certain plugin, the server checks if a plugin has already been verified.
If not the following steps are executed to validate the plugin and the results are cached (to avoid validation for every request):

- Load manifest file and manifest signature file for a plugin
- Lookup matching key as specified in the manifest and verify the signature

The backend then serves the request file if:
- The plugin manifest file has been validated
- The requested file is in the validated manifest file
- The requested file hash matches the entry in the manifest file

#### Considered alternative:
- Plugin beeing a single signed zip file. When fetching a plugin file, stream the file data straight from the zip file. While this is very easy to install you would need to go through some extra hoops when developing plugins, i.e. effectively have two implementations.
- JWT: apparently not very secure or at least has many gotchas
- OpenPGP: too complicated...

**Comment by mark-prins** [comment]
Sounds great - thanks @clemens-msupply 
My only concerns is the need to store public keys for all plugin creators - and if we do get to the stage of having external agencies creating plugins then we'll need to issue and maintain keys. Given that we are likely to be the only creators of plugins initially, it won't be a problem for some time anyway.

In the grafana example, the message and signature are both in the same file (MANIFEST.txt) - is there a reason for separating out the `manifest.json` and `manifest.signature`?

**Comment by clemens-msupply** [comment]
We could have our own certificate chain. Fox example, we sign a 3rd party public key and this public key is included in the plugin. When validating the plugin we have verify that we signed the 3rd party key and that the plugin is signed with the 3rd party key. Haven't tried but openssl might already support the tricky bits...

I wasn't sure what envelop format to use. But I probably can use PEM as OpenPGP does in the graphana plugins. Will have another look. (main problem is that the message data must stored exactly as it has been signed otherwise you can't verify it, e.g. putting message and signature into json is tricky)
