### ISSUE TITLE
Decision tree component requires a patient Document

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2171]
The `DecisionTree` component (`packages/programs/src/JsonForms/components/DecisionTree/DecisionTree.tsx`) assumes that a patient always has document. This is assumption is wrong for patient that haven't been created through the program patient module. However, it is possible to enrol and create an encounter for patients without document.

- [ ] Fallback to fetch the name patient when no patient document is found
- [ ] Create a "fake" patient document from the name row which can be used in the `DecisionTree`

Note, currently the patient document is used to get the patient's gender. This also works with a basic patient from the name table.

**Comment by CarlosNZ** [comment]
> However, it is possible to enrol and create an encounter for patients without document.

Should we make it so that the Create Program Enrolment modal always creates a Patient document if one doesn't exist yet? Then we don't have to worry about accounting for missing patient docs downstream.

**Comment by clemens-msupply** [comment]
Or just use the patient graphql fragment. Then you can access the default patient fields as well as the document data (if it exists).
