### ISSUE TITLE
Plugins: Store plugin data

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2184]
## Is your feature request related to a problem? Please describe 👀

Part of epic #2084 

The plugins will need somewhere to store data - data that relates to other records in the database and is accessible and unique to a particular plugin

## Describe the solution you'd like 🎁

Create a database table (`plugin_data`?)

| id | plugin_name | related_record_id | related_record_type | store_id | data |
|----|----|----|----|----|----|
| text (uuid) | text | text | text (data type of table names?) | text | text (JSON data?) |

and methods to query data with filters for
- id
- plugin_name
- related_record_id
- related_record_type
- store_id

and mutate functions for insert / update.

We would also have to create a table in mSupply (`om_plugin_data`) and sync between the two tables.

### Describe alternatives you've considered 💭
The plugins will need to store data somewhere, and this needs to be in a persistent data store.
This data is related to other records and is potentially a larger recordset than should be stored in a generic table such as `key_value_store`

### Additional context 💌
The plugin [example 02](https://github.com/openmsupply/open-msupply/tree/feature/front-end-plugins-example-02) will be making use of this and could be a helpful branch to test with. This example adds a field to the stock edit form, so it relates to a stock line record, and requires the edited value to be stored and retrieved

### Moneyworks Jobcode 🧰

OMS:PLUG

**Comment by andreievg** [comment]
Nice, I agree with schema. 

> text (JSON data?)

Yeah I think stringified JSON stored as text would be the way to go for now. We shouldn't need to parse the text on backend, just pass it along to front end.

There is an issue with permissions if this table is to be queried and mutated without related record. I think this needs addressed before jumping into any graphql implementation

**Comment by andreievg** [comment]
We had a chat during standup about permissions, and identified two areas of plugin permissions (btw I am mainly talking about back end permissions)

# Does user have permission to related record 

**Q1** Is it ok to allow back end to mutate and query for any plugin data ? (front end will already restrict back access to the related record)

1. Idea is to can expose plugin data as an array when we query for the related record. But doing something similar in mutation might be a bit harder (not all of the data is optional during mutations, and do we want plugin to be saving other data when saving it's own data ?)

2. Idea is to have a special query and mutate for plugin, with an enum specifying which record type it is, and we add the permission check in that query and mutate

**Q2** Idea 1 or Idea 2 or another Idea ?

# Does user have permission to the plugin

**Q3** Do we see use cases where we need user access restricted to the plugin ?

We can potentially use the context permission idea, as per programs

**Q4** Use permission context for plugins ?

**Comment by mark-prins** [comment]
> Q2 Idea 1 or Idea 2 or another Idea ? -> I like idea 2, idea 2 also means we can get going quickly (don't actually need to add permissions atm)

I prefer idea 2 - it's a neat solution to the query permissions issue.

> Q3

Not at this stage no - I don't see the need to restrict plugins to users. 

> Q4

I think can wait too, we can implement and then explore the option of using permission context
