### ISSUE TITLE
Early Infant HIV Detection - Enrolment Form

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2189]
## Enrolment Form

- [x] title should be `Early Infant HIV Detection` instead of `HIV Early Infant Detection`

### Section 1: `Enrolment`

- [x] `Enrolment date` format should be DD/MM/YYYY and not MM/DD/YYYY (applies for all dates)
- [x] `Referred from` (clinic/organisation): free text field 

### Section 2: `Delivery Details`

- [x] `Place of Delivery`: dropdown list ["Facility" , "Home"]
- [x] `Facility name`: free text field, only if `Place of delivery` = `Facility`

### Section 3: `Mother Details & Infant's Risk of MTCT`

- [x] `Mother HIV Patient ID`: you can look up the HIV Care & Treatment ID from a list of existing patients
- [x] `Mother First Name`: automatically retrieved from mother's HCT registration/enrolment data, if not, can be entered manually
- [x] `Mother Last Name`: automatically retrieved from mother's HCT registration/enrolment data, if not, can be entered manually
- [x] `Mother Phone Number`: automatically retrieved from mother's HCT registration/enrolment data, if not, can be entered manually
- [x] `Mother ART Start Date`: dropdown list  ["Before pregnancy" , "Early Ante-natal" , "Late Ante-natal" , "Post-Natal" , "Labour & Delivery" , "Never got ARVs" , "Unknown"]
- [x] `Mother's VL prior to delivery`: dropdown list  ["Suppressed" , "Unsuppressed" ,  "Unknown/Not done"]
- [x] `Child's HIV Exposure`: dropdown list  ["Clinical Suspicion" , "Mother Known Positive"]
- [x] `Risk of MTCT`: dropdown list ["High risk" , "Low risk"]

_Note: `Risk of MTCT` should be the last field of this section since the risk of MTCT (Mother to Child Transmission) is determined by the value of preceding fields_

- [x] Remove "Infant's ARV Prophylaxis" section from the enrolment form:

![Screenshot 2023-09-06 at 12 55 16 PM](https://github.com/openmsupply/open-msupply/assets/74992958/de1d4a06-6bdc-4a57-a973-57bf95120a94)

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
Blocked by: #1840 for the mother details
