### ISSUE TITLE
Creating new shipment takes you to existing shipment

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#219]
This could be data issue:

In demo data file, after login, when creating new outbound shipment for Kamo, i am taken to existing outbound shipment (the first time, after that it's fine). After logout and login, seeing the same issue

**Comment by mark-prins** [comment]
perhaps related to #208 ?

**Comment by andreievg** [comment]
@mark-prins I've asked @roxy-dao to try and replicate this (and if it's replicable maybe fix it too)

**Comment by roxy-dao** [comment]
Seems to be related to #298 ... New invoices get assigned numbers that already exist in Central.

**Comment by mark-prins** [comment]
I tried, I couldn't recreate. bye bye issue.
