### ISSUE TITLE
Early Infant HIV Detection - Encounter Form

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2190]
## Encounter Form

- [x] for all the fields in this encounter form, the value displayed must always be the value from the previous visit (if none, leave blank). This will make it clear to the user that the values have already been entered. 

#### 1.1. Section: `Infant's ARV Prophylaxis`

- [x] `ARV prophylaxis provided`: boolean (Yes/No)
- [x] `ARV Regimen`: dropdown list ["Nevirapine 6 weeks" , "Zidovudine 6 weeks & Nevirapine 12 weeks" , "Other"]. Only if `ARV prophylaxis provided` = `Yes`. 
- [x] `Initiated on CTX at 6 weeks ?`: boolean (Yes/No)

#### 1.2.  Section: `Early Infant Diagnosis at 6 weeks`

same as existing, just a few things to change: 

- [x] `DBS Collected ?`: add a "?" and use a "switch button" (for consistency with the other forms for booleans)
- [x] `DBS result received by patient ?`: add a "?" and use a "switch button" (for consistency with the other forms for booleans)

#### 2.1. Section: `Treatment for Confirmed HIV Positive Infant`

same as existing, just a few things to change: 
- [x] `ARV Given`: add a "?" and use "switch button" instead of dropdown list (for consistency)
- [x] it should be `ART regimen code` (typo in the HPDB)
- [x] no value for `ART regimen code`
- [ ] looks like there is a "space" between `ART regimen code` and `ART start date`
- [x] `TB prevention therapy given ?`: add a "?" and use "switch button" instead of dropdown list (for consistency)

#### 2.2. Section: `Repeat DBS Test`

- [x] `Repeat DBS collected ?`: add a "?" and use "switch button" instead of dropdown list (for consistency)

_following fields only active if `DBS collected ?` = `Yes`_
- [x] `Date DBS Collected`: date picker
- [x] `DBS Number`: free text
- [x] `DBS result received by patient`: yes/no
- [x] `Date DBS result given to patient`: date picker
- [x] `DBS result`: dropdown list ["Positive" , "Negative"]

### 3. Bubble: `Follow-up Visits`

same as the one you already did. A few things to change:
- [x] add a separator between each "visit" (line) for clarity 
- [x] add a "s" for months (eg. "6 month*s*")
- [x] Immunisations up to date ?: we usually use a "switch button" for boolean field (yes/no)
- [x] add a "s" and "?" for `Immunisations up to date ?`
- [x] `Weight (kg)` instead of `Weight`
- [ ] ~remove the `18mo Antibody Test Date:` & `18mo Antibody Test Result` from the `18 months` section~

#### 3.1. Section: `Post-BF DBS Test`

- [x] `Post-BF DBS collected ?`: add a "?" and use "switch button" instead of dropdown list (for consistency)
- [x] `Post-BF DBS result received by patient:`: add a "?" and use "switch button" instead of dropdown list (for consistency)

#### 3.2. Section: `18 Months Antibody Test`

- [ ] ~`18 months Antibody Test Date`: date picker~
- [ ] ~`18 months Antibody Test Result`: dropdown list ["Positive" , "Negative"]~

#### 3.3. Section: `Final Outcome`

- [x] Final Outcome Status: dropdown ["Death" , "LTFU" , "On ART" , "Discharged"]
- [ ] ~`Comments`: large comment section (not just one line)~

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
ARV prophylaxis provided is not a boolean...
![Image](https://github.com/openmsupply/open-msupply/assets/88299195/520ba1d2-d830-4f8c-8514-38b80af34778)

**Comment by clemens-msupply** [comment]
>  remove the 18mo Antibody Test Date: & 18mo Antibody Test Result from the 18 months section

are you sure?


![Image](https://github.com/openmsupply/open-msupply/assets/88299195/b7a45f7c-4bd4-4b95-889f-b7d1eba47ca0)

**Comment by roxy-dao** [comment]
Closing because moved to done.
