### ISSUE TITLE
Update theme to allow customisation of nav link hover

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2192]
## Is your feature request related to a problem? Please describe 👀

In creating custom themes, this is a problem I come across regularly, so have decided to put in a patch fix.
The NavLink hover is using the `theme.palette.background.toolbar` colour which is necessarily a light colour.
However, it means that if you use a light colour for the app nav text links, you get this:

<img width="256" alt="image" src="https://github.com/openmsupply/open-msupply/assets/9192912/33276c9c-af26-45d8-ad9f-380f6942b53d">

## Describe the solution you'd like 🎁
Add a mixin for the hover background and text, so that you can specify what the background should be.
Otherwise you need to update the toolbar background colour, which causes other problems:

<img width="1510" alt="Screenshot 2023-09-06 at 4 07 26 PM" src="https://github.com/openmsupply/open-msupply/assets/9192912/cde32269-0f17-46b0-a793-c79d9f2877a5">

**Comment by roxy-dao** [comment]
Merged above
