### ISSUE TITLE
Clarify min / max MOS on internal orders

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2202]
## Is your feature request related to a problem? Please describe 👀

There is some confusion regarding the terms `Minimum MOS` and `Maximum MOS` which are parameters on an internal order.
The min MOS is a threshold; if the store has fewer months of stock on hand than this value then a reorder quantity is suggested.
The max MOS is a target number of months of stock on hand that the store should have, and is used in the suggested quantity calculation.

There is also a concern that the introduction of the min MOS value will cause problems for existing mSupply users, who are only used to setting a single max MOS value and would expect that the system suggests a reorder quantity if the months of stock on hand is less than this value.

## Describe the solution you'd like 🎁
Rename the parameters:
- `Minimum MOS` to `Reorder threshold MOS`
- `Maximum MOS` to `Target MOS`

Add another option to the `Reorder threshold MOS` selection - `Not set` which sets the `min_months_of_stock` value to `0` for the requisition. If this option is selected, then the `max_months_of_stock` value is used for the reorder threshold.

It was suggested that setting the reorder threshold to the target MOS value when the target is changed would work around the problem for existing users. This however introduces the problem of handling changes to both values. If the threshold is changed and then the target is changed, should we overwrite the threshold value? Simplest to retain another state for the threshold.

**Comment by andreievg** [comment]
> Add another option to the Reorder threshold MOS selection - Not set which sets the min_months_of_stock value to 0 for the requisition.

That sounds great, so a drop down and a number input ?

Was wondering if "Reorder Threshold MOS" is too verbose, and maybe hard to translate, @richardmoizeau ? How about just "Threshold MOS" and 'info' component with more detailed info ?

**Comment by mark-prins** [comment]
yep - "reorder threshold MOS" is too much! I think that "threshold MOS" is an improvement on "min MOS" and worth changing. I suppose it could be "Reorder MOS" too.. don't mind. easy enough to change again

**Comment by fergie-nz** [comment]
In regards to "Reorder Threshold MOS" being verbose, I've had a go at changing the localised strings as well.
Some of them (in develop) are quite long: 
 "Mínimo MOS (Stock de Seguridad Mínimo)"
 "Mínimo MDE (Meses De Estoque)"
 
 Regardless of new wording, maybe these need to be shortened also?
