### ISSUE TITLE
Sorting doesn't work well in Encounters list window

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2204]
## What went wrong? 😲
Sorting doesn't work well in Encounters list window

## Expected behaviour 🤔
List should be able to be sorted in both ascending and descending order.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Go to Dispensary>Encounters
<img width="958" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/bddc65a4-de7e-43ce-ae43-3201cb6d7b75">

2. Try to sort the encounters list
3. You'll see the list sorted in ascending order
4. Sort again by clicking on the same field
5. See error: the list doesn't get sorted in descending order this time.

## Your environment 🌱

 - Version: v1.3.00
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by mark-prins** [comment]
🤔 Unable to replicate locally - the sort is working, and changing direction ok for me

**Comment by clemens-msupply** [comment]
Can confirm: no sort for Type and sort order is not taken into account. I did some recent changes, so maybe it broke recently.
