### ISSUE TITLE
The 'clear' button on filter inputs is funky

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2205]
## What went wrong? 😲
 
I don't like the behaviour of the 'clear' button which has been added to inputs. If the input has focus, clicking 'clear' does not clear, but loses focus. Only on clicking again does it work. It's not helped by the resizing of the input, which moves the button around when the focus changes.
See the end of this clip:

https://github.com/openmsupply/open-msupply/assets/9192912/f90dd25b-9c0a-45b3-8bbb-fd8b76a226d4

## Expected behaviour 🤔
The clear should work when clicked.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by clemens-msupply** [comment]
Another related issue:
- fill first search input
- press tab -> Focus goes onto the clear button
- continue typing a `d` (because as a user you would assume focus is now on the second input)
- you will leave the modal end up on the Dashboard page :(

**Comment by mark-prins** [comment]
Adding to the 'design' column because it would be good to have an opinion on whether the expanding search input is weird and whether the changing width should just be removed. 

Currently, when you click into the search bar it does expands, as you can see in the video above. when the input loses focus it shrinks again. The reason, I think, is to give you more space to type stuff into. The disadvantage is that (a) it causes this issue with the clear button and (b) it is slightly unexpected behaviour and (c) it makes other UI elements move around.

**Comment by CarlosNZ** [comment]
> (c) it makes other UI elements move around.

Yeah, this is the main negative for me. Other than that I think it's pretty good (this particular issue notwithstanding). I wonder if it's possible to only allow it to expand to certain maximum (in each context), so it doesn't move other things around, but can expand when there's room to spare?

**Comment by mark-prins** [comment]
Mostly the moving around is fine - because the search bar exists alone in the 'toolbar' area and there's nothing to the right of it. 

The situation here, where there are three search inputs, all on the same horizontal line, is the most glaring example I've seen.
In this case we could add a max width? or disable the expansion? 

I mainly raise the question about keeping the expansion because the fix I've done for the clear button makes the transition a little clumsier - there's now a small delay before it expands. It would be nicer to remove the expansion - thought it's such a minor thing that I'm undecided either way

**Comment by CarlosNZ** [comment]
> In this case we could add a max width? or disable the expansion?

A simple solution might be to just add a "expandOnFocus" prop to the component, with a default value of `true` -- so that it'll expand most of the time but we can explicitly disable it in cases where it doesn't look good (like in the video above)?

**Comment by GaryWilletts** [comment]
I think you can disable the expansion in this instance. The field looks big enough without expansion.

**Comment by DhanyaHerath** [comment]
Anisha says: filter inputs should not change size, and check why the input changes height (mark p says check padding on clear icon)

**Comment by nisha-dangol** [comment]
Just did a basic search on Patient List window and cleared it. Looks good to me (not looking funky at all); moving to Done!
