### ISSUE TITLE
The "no stock available" message needs to be set for prescriptions

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2210]
## What went wrong? 😲
 
When I try to dispense stock and have no stock available, it gives me an error but it's not in user-friendly language. 
It's a different behaviour to the outbound shipment which doesn't give me an error. 

## Expected behaviour 🤔
I would like a user friendly message! 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to prescriptions
2. Click on 'Add item'
3. Try to add an item with no stock

Prescription behaviour:  
![image](https://github.com/openmsupply/open-msupply/assets/29744386/d620e102-5b7c-41da-bae2-6d44783ea11c)

Outbound shipment behaviour: 
![image](https://github.com/openmsupply/open-msupply/assets/29744386/c5d9e553-8a4b-4295-bc4a-7db7d6c1d2ce)

## Your environment 🌱

 - Version: 1.3.0
 - Platform:
   - [ ] android (tablet)
   - [x] browser Chrome :) Both on demo server and my local 
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Merged to main
