### ISSUE TITLE
[Multi Unit Item] Apply pack size components

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#2214]
From epic: https://github.com/openmsupply/open-msupply/issues/2078

Multi Unit Item Components:

"PackUnitCell"
"PackUnitQuantityCell"
"PackUnitSelectCell"

Need to be applied to all UI areas:

In this issue we need to list all of the UI areas, with screenshots, and try to `align` them (i.e. quantity column having the same name, appearing in the same order).  

There are some detail view (like Stock->DetailView and Catalog -> Item Detail View), I don't think they can use cell components, so we would need to extract that ?

Blockers:

"UnitInputCell" (not implemented yet)
User selected variant to be stored in app data

**Comment by andreievg** [comment]
@roxy-dao, I've mentioned this morning that I'll try break down this into an issue, but there seems to be some pre-requisites: blockers and some 'alignment'. If you want to you can start on this one:

```
In this issue we need to list all of the UI areas, with screenshots, and try to align them (i.e. quantity column having the same name, appearing in the same order).
```

**Comment by roxy-dao** [comment]
### Distribution

- Outbound Shipment / Prescriptions (?)
![Screenshot 2023-09-12 at 2 08 02 PM](https://github.com/openmsupply/open-msupply/assets/61820074/6888c619-2000-4051-88b2-b5bea1468c6d)
![Screenshot 2023-09-12 at 2 08 36 PM](https://github.com/openmsupply/open-msupply/assets/61820074/e67005b7-f0f5-443f-9a2f-7ab3a9f0071d)

- Requisition
![Screenshot 2023-09-12 at 2 10 25 PM](https://github.com/openmsupply/open-msupply/assets/61820074/7bd68bfd-9a03-4d82-bab2-758277b77e17)
![Screenshot 2023-09-12 at 2 10 39 PM](https://github.com/openmsupply/open-msupply/assets/61820074/e980c383-7030-428f-8c99-756ca4515850)

### Replenishment
- Inbound Shipment
![Screenshot 2023-09-12 at 2 12 10 PM](https://github.com/openmsupply/open-msupply/assets/61820074/96ab122f-b922-4126-b3e6-127ae24a78d6)
![Screenshot 2023-09-12 at 2 12 18 PM](https://github.com/openmsupply/open-msupply/assets/61820074/468a36d3-1e05-4fc4-81a0-ce3d2644e058)

- Internal Orders
![Screenshot 2023-09-12 at 2 13 09 PM](https://github.com/openmsupply/open-msupply/assets/61820074/817a9168-23c4-4e8d-a27e-7b3f084629d2)
![Screenshot 2023-09-12 at 2 13 24 PM](https://github.com/openmsupply/open-msupply/assets/61820074/37f6f94d-233a-4d01-a6f6-7e0b4e8bd314)

#### Catalogue 
- Items (done)
![image](https://github.com/openmsupply/open-msupply/assets/61820074/d2fad2e2-9aba-439c-842b-e7853ea6fff9)
![Screenshot 2023-09-12 at 2 28 24 PM](https://github.com/openmsupply/open-msupply/assets/61820074/ac8b01d9-28cf-4ec4-8833-ea4b6dc54cc6)

#### Inventory
- View Stock (Repack???)
![Screenshot 2023-09-12 at 2 27 13 PM](https://github.com/openmsupply/open-msupply/assets/61820074/3a338af3-d7c5-4488-a34b-868bb207194f)
![Screenshot 2023-09-12 at 2 27 06 PM](https://github.com/openmsupply/open-msupply/assets/61820074/dae8c829-e67a-40e9-a2a7-93ca3abce0ea)

- Stocktake
![Screenshot 2023-09-12 at 2 30 31 PM](https://github.com/openmsupply/open-msupply/assets/61820074/f0b764c8-9ef3-4ea1-a5ff-f5b6a3aeb578)
![Screenshot 2023-09-12 at 2 29 51 PM](https://github.com/openmsupply/open-msupply/assets/61820074/7b6cea6c-f77d-4ee4-8042-762b5bef34c0)

**Comment by marthakeezy** [comment]
Tested as a part of Epic in V2.0.0 release, moving to Done ✅
