### ISSUE TITLE
Prescription Statuses

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2217]
## Is your feature request related to a problem? Please describe 👀
Need a better way to handle prescription statuses to reduce the amount of `NEW` prescriptions. 

A pharmacists enters all the information needed for a prescription but they might not always change the status from `NEW` to `PICKED` (quoted from Jonna & Dhanya).

Also currently an issue when deleting prescriptions; user might accidentally delete `PICKED` or `FiNALISED` prescriptions because they didn't change the status and kept it as `NEW`.

## Describe the solution you'd like 🎁
1. When a pharmacist enters a line, automatically change the prescription status to `PICKED`. 
2. This means that the behaviour of adding a line should also change - when you add a new line to a prescription, it should take that item _out of stock_, not just change how much is _available_. 

### Describe alternatives you've considered 💭
Leaving it as is 🤷🏻 

### Moneyworks Jobcode 🧰
OMS:MVP

**Comment by mark-prins** [comment]
and the winner is.. option 1!

_When a pharmacist enters a line, automatically change the prescription status to `PICKED`_

Within mSupply, adding a line to a prescription does not change the status automatically. However, you cannot leave the modal without clicking `OK` and when you do, the status is change to `cn` and the stock level is adjusted.

Within a browser, we have less control over the page - people can navigate away or close the window / tab or close the browser. The alert confirmation (used elsewhere) cannot be styled fully and is intrusive, requiring action from the user.

The assumption is that standard behaviour in a pharmacy is that stock is handed over at the point of creating the prescription, and so adjusting the status and therefore the stock level, at this point most clearly matches reality. The prescription remains editable after the status changes to `PICKED` so the user can modify if required.

**Comment by CarlosNZ** [comment]
> and the winner is.. option 1!
> 
> _When a pharmacist enters a line, automatically change the prescription status to `PICKED`_
> 
> Within mSupply, adding a line to a prescription does not change the status automatically. However, you cannot leave the modal without clicking `OK` and when you do, the status is change to `cn` and the stock level is adjusted.
> 
> Within a browser, we have less control over the page - people can navigate away or close the window / tab or close the browser. The alert confirmation (used elsewhere) cannot be styled fully and is intrusive, requiring action from the user.
> 
> The assumption is that standard behaviour in a pharmacy is that stock is handed over at the point of creating the prescription, and so adjusting the status and therefore the stock level, at this point most clearly matches reality. The prescription remains editable after the status changes to `PICKED` so the user can modify if required.

My only concern would be that it becomes too easy to inadvertently create a prescription that can no longer be deleted. Currently only "NEW" can be deleted. But if you start creating a prescription then want to cancel out of it part way through, you can't do that if it's already been set to "PICKED". I feel like you should be "committed" to keeping the document until you've "confirmed" it somewhere in the process.

So maybe we make "PICKED" delete-able, and it's only permanent when "VERIFIED"?

**Comment by roxy-dao** [comment]
Will prescriptions be deleted though? 🤔 The pharmacists enter the prescriptions pretty fast in the pharmacy... and often times they don't change the statuses at all, so if we make PICKED delete-able, then all prescriptions will remain delete-able.. 🤔

**Comment by CarlosNZ** [comment]
> Will prescriptions be deleted though? 🤔 The pharmacists enter the prescriptions pretty fast in the pharmacy... and often times they don't change the statuses at all, so if we make PICKED delete-able, then all prescriptions will remain delete-able.. 🤔

Sure, maybe that's not the best solution. I just don't really like the idea of having to keep a prescription that you don't want. It's standard throughout omSupply that you can start an order/invoice/document/whatever, play around with it, then safely delete it if you don't want to actually follow through with it. It would be weird if Prescriptions were an exception in this regard.

**Comment by mark-prins** [comment]
In mSupply you can delete confirmed prescriptions - and if we are taking inspiration from mSupply then that would correlate with deleting `Picked` prescriptions.

You do need to delete all lines from a prescription - so to be strictly consistent we should add that check as well.
