### ISSUE TITLE
Outbound Shipment: editing placeholder line & allocating stock doesn't delete the placeholder

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/open-msupply#2221]
## What went wrong? 😲
As per title

## Expected behaviour 🤔
Placeholders should disappear if they have zero quantity

## How to Reproduce 🔨

1. Go to outbound shipments
2. Add items from master list
3. Edit item that has stock, allocate quantity
4. Click OK > back in the list the placeholder still exists with zero quantity

<img width="1304" alt="CleanShot 2023-09-12 at 17 31 35@2x" src="https://github.com/openmsupply/open-msupply/assets/254026/6ecfa749-9fdd-4366-b478-36c5f80290ea">

## Your environment 🌱

   - [X] browser - Firefox Mac
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment]
@raviSussol were you able to reproduce this? I couldn't on V1.3.0

**Comment by roxy-dao** [comment]
Video on how to reproduce... V1.3.0

https://github.com/openmsupply/open-msupply/assets/61820074/3a458a06-8141-4c68-9254-2a982c08f2fd

**Comment by raviSussol** [comment]
> @raviSussol were you able to reproduce this? I couldn't on V1.3.0

Yes I was and have pushed a fix. Thanks @roxy-dao for showing the video.
