### ISSUE TITLE
More theme updates

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2222]
## Is your feature request related to a problem? Please describe 👀

Another day, another customised theme.
This time I noticed that the hover text in the left nav isn't updated, and that the icon colours on the dashboard aren't updated.

## Describe the solution you'd like 🎁
Setting the `mixins.drawer.hoverTextColor` should update the link text colour when hovering:

<img width="1106" alt="image" src="https://github.com/openmsupply/open-msupply/assets/9192912/84750f59-68ff-4b83-aabf-a60eb6d37167">

And the stock icons on the dashboard should change from being blue.

**Comment by roxy-dao** [comment]
Merged already~
