### ISSUE TITLE
When issuing stock, alert if a line isn't allocated 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2227]
## What went wrong? 😲
When you issue stock either on an outbound shipment, or a prescription, you don't get an alert if you click OK on the modal without actually allocating stock. 

This happens both if you forget to allocate stock, and if there is an expired stockline (so it doesn't get issued). I think this will leave a lot of customers confused (and I am often confused too!) 

## Expected behaviour 🤔
I would like an alert if I have not allocated stock when closing the Issue Item modal. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an outbound shipment or prescription 
2. Click "Add item"
3. Select an item, and then (optional, but my general workflow) enter in a quantity
4. Now click OK - note that the line has not been added, but there is no alert. 

This also happens if you DO allocate but the lines are expired 

## Your environment 🌱

 - Version: 1.3.0
 - Platform:
   - all

**Comment by DhanyaHerath** [comment]
Alternate option is this one: https://github.com/openmsupply/open-msupply/issues/2091 which may help reduce the need for this

**Comment by roxy-dao** [comment]
Or could disable the `Ok` and `Ok & Next` button if nothing has been allocated 🤔

**Comment by DhanyaHerath** [comment]
@roxy-dao I find disabled actions a bit frustrating sometimes - it's like you have to guess what is happening. I think I prefer explicit alerts

**Comment by fergie-nz** [comment]
I'm seeing that I can still allocate expired stock via prescriptions and outbound shipments. So it looks to me like it is both being issued AND there is no warning. 

Is this how you understood the current behaviour?

**Comment by fergie-nz** [comment]
> I'm seeing that I can still allocate expired stock via prescriptions and outbound shipments. So it looks to me like it is both being issued AND there is no warning.
> 
> Is this how you understood the current behaviour?

I'm wondering if the desired solution would be to add back end validation to check if allocation is empty or expired, and returning an error if so including an alert or snack in the front end

OR 

Just the front end alert / warning if the stock is expired or allocation is empty
