### ISSUE TITLE
Can we apply the "use auto-generated patient codes" preference for omSupply patients?

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2228]
## Is your feature request related to a problem? Please describe 👀
There is a "auto-generate patient code" preference in mSupply, which is set per site. 

<img width="853" alt="image" src="https://github.com/openmsupply/open-msupply/assets/29744386/520cdd75-11da-423a-be26-d18875928e56">

It helps with not creating duplicate patient codes, and also having sane codes for countries and facilities that are not used to having to create patient codes. 

## Describe the solution you'd like 🎁
It would be great to be able to account for this, but it would require some admin UI for setting the prefix...

### Moneyworks Jobcode 🧰
OMS:MVP

**Comment by mark-prins** [comment]
This would require syncing Dispensary mode preferences somehow. Ideally we would not do this until the new central server is in place and do the work there rather than bringing more data from mSupply

> but it would require some admin UI for setting the prefix...

you wouldn't use the mSupply admin and take the value from there? somehow?

**Comment by DhanyaHerath** [comment]
@mark-prins I was hoping we could use mSupply admin, but the only problem with that is there's a lot of room for patient code duplication: if all sites have the same prefix (eg. ABC), then they won't know what patients are created on other sites and they will auto-generate the same sequence on all sites (eg. ABC-01, ABC-02...)

**Comment by clemens-msupply** [comment]
Possible solution is to make it configurable with a custom patient creation UI schema like:
![image](https://github.com/openmsupply/open-msupply/assets/88299195/059d09ff-b586-46c7-8202-7b4a7e66b4e8)
![image](https://github.com/openmsupply/open-msupply/assets/88299195/d8d13ad0-b035-4deb-bc50-0dc8f553bf8e)

This particular id is generated by taking the store code and fetching a unique, store based number. I.e. code would be based on the store where the patient is created...

**Comment by DhanyaHerath** [comment]
Thanks @clemens-msupply! Cooks likely won't mind just having a store code, so if this is easy to implement and the others agreed (@andreievg @mark-prins) I would be keen to do it!

**Comment by fergie-nz** [comment]
I'm wondering if I could clarify with someone the approach to this before I get started.

Right now I'm thinking
- Adding an iterating number (patient created number) per store
- Calling both store code and patient created number when creating a new patient
- The auto generated patient code is a concatenation of these values
- Upon patient creation, set the patient created number as += 1

For the front end
- Have an auto generate button which populates this auto generated code as the patient code
- Also allow manual entry of a patient code if the user wishes.

**Comment by fergie-nz** [comment]
Or alternatively (if I'm understanding this correctly)

Would be to query all patients, and find the patient with the highest auto generated number with that store code pattern, and add 1 to it. This would save having the auto generated number in the database associated with that store.

But there would be some funny edge cases such as if a user manually entered a patient code of the storecode followed by a high number or other string.

**Comment by clemens-msupply** [comment]
Good thought and hopefully this already has been solved, but please have another look over it :) Here is the short version:

You can replace the `code` entry in `packages/system/src/Patient/DefaultPatientUISchema.json` with:

```json
{
      "type": "IdGenerator",
      "label": "Code",
      "scope": "#/properties/code",
      "options": {
        "parts": [
          {
            "type": "StoreName",
            "mutations": [{ "firstNChars": 3 }, { "toUpperCase": true }]
          },
          {
            "type": "Number",
            "numberName": "PatientCode",
            "mutations": [{ "padString": "0000" }]
          }
        ],
        "allowManualEntry": true,
        "validations": [
          {
            "type": "UniqueEnrolmentId"
          }
        ]
      }
    },
```
There are some more examples in the https://github.com/openmsupply/programschemas repo...

This will use the `packages/programs/src/JsonForms/components/IdGenerator.tsx` (omSupply repo). There are some more docs in this files about the options.

**Comment by clemens-msupply** [comment]
Once this is working you have to move the IdGenerator config out of the `packages/system/src/Patient/DefaultPatientUISchema.json` again and move it to a `formschema` table entry with name: `PatientCreationJSONForms`. So that it is only loaded where needed: `packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx`
