### ISSUE TITLE
Rename the "Notes" field on prescriptions to be "Directions" 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2235]
## What went wrong? 😲
 ]
We made this for dispensing directions so it would be good if it had the appropriate field label: 
![image](https://github.com/openmsupply/open-msupply/assets/29744386/aa88bd40-9949-4995-8c7a-c76b403cfe08)

## Your environment 🌱

 - Version: 
 - Platform: all

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Add item to prescription
- [x] Should say direction instead of note
- [x] Finish adding item
- [x] Hover over speech bubble
- [x] Should say direction instead of note
