### ISSUE TITLE
Edits to patient names don't seem to update on past prescriptions 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2236]
## What went wrong? 😲
 
If you edit a patient's name, for example Emily Porrello's here, which originally only had one `r`: 
![image](https://github.com/openmsupply/open-msupply/assets/29744386/e201c151-4bf8-4380-aacc-56cb351b66e5) 

It doesn't update the name on prescriptions that were previously created for that patient. 
![image](https://github.com/openmsupply/open-msupply/assets/29744386/2dcb76fa-c866-491d-8f85-0a73b57d4f75)

Should it?

## Expected behaviour 🤔
I think it should update, I suspect?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a prescription for a patient 
2. Save the prescription 
3. Go to edit the patient and change the patient's name
4. Go back to the prescription and see whether it has been updated 

## Your environment 🌱

 - Version: 1.3.0
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by raviSussol** [comment]
It looks to be working on mine.
![](http://g.recordit.co/vWcAY4aZK3.gif)

**Comment by roxy-dao** [comment]
> It looks to be working on mine. 

Works if you have programs enabled... you'll have to reproduce on a fresh database...
