### ISSUE TITLE
(Android) Collapsed navigation menu directs to the wrong place

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#2243]
## What went wrong? 😲

Under certain circumstances clicking on an item in the side navigation menu does not take the user to the correct destination. 

E.g. If the user is in the Inbound Shipments screen and clicks on the Inventory icon, it takes them to the Suppliers list instead. 

https://github.com/openmsupply/open-msupply/assets/19318937/e1ff2a2e-6033-44d7-890d-0f4295183e02

## Expected behaviour 🤔

Menu should always take user to the correct destination.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inbound Shipments
2. Click on the Inventory icon in the nav bar
3. Note that you are taken to the Suppliers List

## Your environment 🌱
 - Version: 1.3.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by nisha-dangol** [comment]
Have seen these issues in mobile only; in some Lenovo tablets I think. Not in desktop browsers yet so far!
