### ISSUE TITLE
Field "Regimen Type (before visit)" is empty

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2244]
## What went wrong? 😲
 

regimen type of the ARV regimen is not displayed: 

![Screenshot 2023-09-18 at 4 22 27 PM](https://github.com/openmsupply/open-msupply/assets/74992958/f16d5d0e-f78d-4240-9aba-2d2357dfeae6)

## Expected behaviour 🤔

field "Regimen Type (before visit)" should display the type of regimen for the value in "ARV Regimen (before visit)"

## How to Reproduce 🔨

HIV Care & Treatment Encounter > Bubble: ARV / Medication

## Your environment 🌱

 - [Version: 1.4.00 ](https://png-hiv-field-test.msupply.org/admin)
 - Platform:
   - [ ] android (tablet)
   - [X] browser (Chrome)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by clemens-msupply** [comment]
This is caused by https://github.com/openmsupply/open-msupply/issues/2171. You can work around it by saving the patient, i.e. creating a patient document.

**Comment by richardmoizeau** [comment]
ok. do you mean it will be solved with issue https://github.com/openmsupply/open-msupply/issues/2171 ?

**Comment by clemens-msupply** [comment]
Yes I think so maybe leave this one open till tested...
