### ISSUE TITLE
Blood Pressure chart not displaying any value - OK to remove it and keep weight only

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2245]
## What went wrong? 😲
 

Blood Pressure chart is not displaying any value:

![Screenshot 2023-09-18 at 4 36 47 PM](https://github.com/openmsupply/open-msupply/assets/74992958/37d82607-dca0-4c3d-9826-d32783351814)

OK to remove and to keep the "Weight" chart only

## Expected behaviour 🤔

should display values over time

## How to Reproduce 🔨

Steps to reproduce the behaviour:

HIV Care & Treatment Encounter > Physical Exam

## Your environment 🌱

 - Version: 1.4.0
 - Platform: 
[   - [X] browser (chrome)
](https://png-hiv-field-test.msupply.org/dispensary/encounter/f1e9543a3b2eef7b838b8413efda03a2e7807f79a7cbc822238ac65ac76de571)

**Comment by roxy-dao** [comment]
Removed in programschema repo
