### ISSUE TITLE
List expansion causing screen to shake

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2248]
## Is your feature request related to a problem? Please describe 👀
https://github.com/openmsupply/open-msupply/assets/61820074/e84d63e0-499d-43bb-96b5-acd00daf72e1

**Comment by mark-prins** [comment]
😆  that's awesome! 
Perhaps the combination of viewport and expansion - perhaps we shouldn't have expansion and viewport together? the expansion should be on smaller data sets, where the viewport isn't required.

**Comment by CarlosNZ** [comment]
Is this the problem you get sometimes when one of the scrollbars rapidly toggles and off? In which case, it only happens at a very particular window size near the threshold for needing a scroll bar.

Or is it a rendering bug in our code?
