### ISSUE TITLE
UI - Int. Order > Req > OS > IS: Multiple Issues

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#225]
Using the web app

**1. Enter an Internal Order from Kopu Health Center (KHC) to Opua Health Center (OHC):** 
- [x] Add Item: should the item field be activated/highlighted by default ? 
- [x] Add Item: tabulation order should be: Item > Requested Quantity > Comment > OK > Ok & Next > Cancel
- [x] Add Item: when selecting an item (eg. Paracetamol), only `target quantity` charts appears. Others are missing. If I validate and re-open, all charts are visible. 
- [x] Add Item > `Stock Evolution` chart: requested quantity should update the chart (not suggested quantity)
- [x] Add Item > `Consumption History` chart > Moving Average: chart gives the impression that the AMC is taken into account to calculate the Mov. Avg (which should not be the case)
- [x] Add Item > Buttons: when pressing `Enter` on my KB, it does not activate the highlighted button (OK, OK & Next or Cancel). I can only click on it to activate the action button. 
- [x] Print > does not seem to be working while writing up this issue

For information, I have entered a comment at the int. order level, at the order line level (Amoxicillin) and a (customer) reference. 

**2. OHC Store: receiving and processing a requisition from KHC**
- [x] Requisition line comment: req line comment have disappeared. Is it only meant for the supplying store ? I thought it could be useful to communicate with the supplier. 
- [x] Requisition comment: same as above. 
- [x] Requisition line window: elements are not in the order as the internal order line window (comment should be on the right)
- [ ] Requisition line window: no charts (could be a priority choice)
- [ ] Create Shipment Button (1/2): opens the shipment in another window (why ?) + sometimes it takes very long time to load the Outbound Shipment or it simply fails. 
- [ ] Create Shipment Button (2/2): does not happen all the time but on multiple occasions it created an O/S for another customer and with different products  and Status = Verified (see screenshots below) - Similar to [issue 208 ?](https://github.com/openmsupply/open-msupply/issues/219#issue-1288164631):
<img width="1059" alt="Screen Shot 2022-06-29 at 6 09 32 PM" src="https://user-images.githubusercontent.com/74992958/176484772-3a7b5760-7bfb-469b-9bcb-a1b29d681928.png">
<img width="1051" alt="Screen Shot 2022-06-29 at 6 09 54 PM" src="https://user-images.githubusercontent.com/74992958/176484807-5204b60f-c833-484d-bc77-819632270f0f.png">

- [x] Outbound Shipment: I try to confirm Allocation while line is unallocated. I get the error message (OK) and then I'm logged out (that being the issue here). See video below:

https://user-images.githubusercontent.com/74992958/176487552-57123a98-ccad-4577-a341-75d0b0787df3.mp4

- [x] Outbound Shipment > Manual Allocation > list of batch numbers: we should no longer see batch with 0 stock (see screenshot below - last batch number of the list): 
<img width="768" alt="Screen Shot 2022-06-29 at 6 28 15 PM" src="https://user-images.githubusercontent.com/74992958/176488329-b8c22701-4cfb-43ae-8afd-9f6373fc1121.png">

**3. KHC receives an Inbound Shipment**
- [x] Inbound Shipment > Details Panel: shipment level comment entered by OHC is lost as well as the transport reference (could be useful for the customer cause it could be a tracking reference)
- [ ] Inbound Shipment > Details Panel > Related Documents: when I click on the link to the Req, most of the time the requisition fails to load or it takes a long time.

**Comment by mark-prins** [comment]
I have no helpful answer to the problem of slow-loading-pages. Haven't been able to repro that issue.
The question of charts for requisitions, requires a new issue I think.

**Comment by richardmoizeau** [comment]
Here is the issue for Response Requisitions charts. 
https://github.com/openmsupply/open-msupply/issues/491
