### ISSUE TITLE
HIV Care & Treatment Enrolment Form: Field "Mother" does not seem to work

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2253]
## What went wrong? 😲
 

I try to search for the patient's mother using her name or patient code but nothing seems to work. 

![Screenshot 2023-09-19 at 5 22 05 PM](https://github.com/openmsupply/open-msupply/assets/74992958/15cf3aa5-b852-45e7-9ecf-5b9cccb5cf75)

## Expected behaviour 🤔

you should be able to link the patient record to his/her mother's (if patient is an infant)

**Comment by CarlosNZ** [comment]
This is fixed by #2216

**Comment by richardmoizeau** [comment]
Thanks Carl !
