### ISSUE TITLE
patient list view's last columns not consistent with other list views

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2254]
## What went wrong? 😲

I should have caught this sooner...

![Screenshot 2023-09-20 at 9 41 32 AM](https://github.com/openmsupply/open-msupply/assets/74992958/a851496c-7127-4f27-8830-6e3c3a14b96f)

## Expected Behaviour? 😲

in Open mSupply, the last column of a list view is usually a column with check boxes so we can apply actions from the dropdown menu `Select` (see below screenshot). For consistency, we should apply the same logic for list view, patient list view included. So the column `deceased` should ideally be... somewhere else. Maybe another format than a check box so it's not too confusing ?

![Screenshot 2023-09-20 at 9 45 32 AM](https://github.com/openmsupply/open-msupply/assets/74992958/5fee19b8-4e4f-42e2-a1eb-86a158f9a72e)

## Agreed solution 
As in Roxy's comment: https://github.com/openmsupply/open-msupply/issues/2254#issuecomment-1740081148
Add the usual column with checkboxes, and replaced the deceased column's checkboxes with ticks

**Comment by roxy-dao** [comment]
Can remove the checkbox and just have a tick if the patient is deceased like with invoice lines
![Screenshot 2023-09-29 at 11 26 47 AM](https://github.com/openmsupply/open-msupply/assets/61820074/ddb58bd1-8d01-4946-8a17-4e4e4052a4f8)

**Comment by fergie-nz** [comment]
While technically correct, I do feel a little uncomfortable marking someone as deceased with a tick. I wonder is this how it is recorded in mSupply?
I might have a very quick look and see if there are other affirmative UI markings which seem more tactful somehow? Maybe it is my own value judgements with a tick being a positive thing

**Comment by mark-prins** [comment]
agree, a check/tick is usually a positive thing, and doesn't sit well for a death indication - thanks @fergie-nz 
Some alternative thoughts:
- A nice, neutral circle (which I am not calling a bullet point!) **&#8226;**
- an `Alive` column instead, then the ✔️ would be acceptable
- Once the deceased date is implemented - we could sidestep the indication question and have a 'date of death' column

**Comment by richardmoizeau** [comment]
> Once the deceased date is implemented - we could sidestep the indication question and have a 'date of death' column

fyi, it is implemented in the "PNG" version: 

<img width="491" alt="Screenshot 2023-10-03 at 2 58 33 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/dd8d3c43-9fe8-4ad3-b2ba-94f2260764d2">
