### ISSUE TITLE
wrong label for "Partner Serial No:" field

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2257]
## What went wrong? 😲
 

wrong label for "Partner Serial No:" 

![Screenshot 2023-09-20 at 10 56 44 AM](https://github.com/openmsupply/open-msupply/assets/74992958/a8873e29-0fdd-4671-8cae-37cde5bc5935)

## Expected behaviour 🤔

should be `HTC Record ID` or `HTC Serial No`

## How to Reproduce 🔨

Contact Tracing > Bubble: Tracking Outcome

## Your environment 🌱

 - Version: 1.4.0
 - Platform:
   - [ ] browser (Chrome)

**Comment by clemens-msupply** [comment]
Maybe have a small title for this lower section like: "Partner HIV Testing/Care Details" and then remove the "Partner" from the labels?

**Comment by richardmoizeau** [comment]
> Maybe have a small title for this lower section like: "Partner HIV Testing/Care Details" and then remove the "Partner" from the labels?
> 
> ```
> "Partner HIV Testing/Care Details"
> - HTC Serial No:       ____________
> - HTC Test result:     ________
> - HTC Testing Date: _________
> ----------------------------
> - ART number:          ____________
> ```

Yes that would work for me !
