### ISSUE TITLE
oms unable to map the user permissions set in mSupply Cloud

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2262]
## What went wrong? 😲
oms unable to map the user permissions like `View patients` set in mSupply Cloud

## Expected behaviour 🤔
user permissions set in mSupply Cloud should reflect accordingly for oms sites as well

## How to Reproduce 🔨
Seems like the `View patients` permission does not really work for users in oms. Here's an example: 
User with only `View patients`ON:
![image](https://github.com/openmsupply/msupply/assets/59193490/0a89cb8e-e7d7-4888-af66-313f982ca231)
But back in oms, the same user does not seem to have the permission to view patients actually: 
<img width="1481" alt="image" src="https://github.com/openmsupply/msupply/assets/59193490/f896d91b-481d-427e-9cb8-a7c3af1d5a1f">

## Your environment 🌱

 - Version: v1.3.00 exe
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

## Additional Context
From [here](https://github.com/openmsupply/msupply/issues/13592#issuecomment-1724851405)

**Comment by roxy-dao** [comment]
Are you testing with an omSupply build? 🤔 Cause it hasn't been released in a build yet and seems to be working locally for me... hbu @clemens-msupply ?

**Comment by nisha-dangol** [comment]
> Are you testing with an omSupply build? 🤔 Cause it hasn't been released in a build yet and seems to be working locally for me... hbu @clemens-msupply ?
>
uh-oh! my oms setup is in the last successful build - v1.3.00! So, if this has been addressed in later changes, it's yet to be tested in new build!

**Comment by nisha-dangol** [comment]
Tested/Checked this in `v1.4.00-test` exe build by @raviSussol on Jenkins. Looks good, this can be closed!
