### ISSUE TITLE
Weird message when allocating outbound shipment

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#2264]
## What went wrong? 😲
 

I don't know quite what's going on here, but the message isn't really helpful as it makes no sense:

"Due to the pack sizes available a total quantity of 10 has been allocated rather than 10"

🤷‍♂️

<img width="1022" alt="Screenshot 2023-09-20 at 5 01 48 PM" src="https://github.com/openmsupply/open-msupply/assets/5456533/587e7493-167d-49dc-bf9e-49a13b0ee78e">

Nothing is actually allocated, so the line remains a placeholder.

This only happens on some items, and I can't tell you what the conditions are, sorry. Will try and look further into it

## Expected behaviour 🤔

Should allocate correctly. Or, if there is actually a problem, provide an informative message.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to an Outbound Shipment
2. Click on a line
3. Select an amount to issue
4. Click "Allocate"
5. You (might) see the aforementioned message and no allocation is done

## Your environment 🌱

 - Version: 1.4.0
 - Platform:
   - [ ] android (tablet)
   - [x] browser (Firefox)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
it's due to the way that alert is triggered, which badly needs some refactoring.
Basically if the allocated quantity differs from the amount in the `issue` input then you get alerted. It should only trigger after clicking `Allocate` but it's using an effect as a shortcut and it doesn't always work
