### ISSUE TITLE
Long medicine names are not able to be fully displayed

### ISSUE THREAD

**Issue by louisaw123** [openmsupply/open-msupply#2270]
## What went wrong? 😲
Unable to see full medicine names for longer items 
![Screenshot 2023-09-21 at 4 21 02 PM](https://github.com/openmsupply/open-msupply/assets/143057869/8776f0c4-b47f-4852-908f-ee49dd0dd95c)

## Expected behaviour 🤔
Would need to see the full name of the drug for users to know what they are supplying or dispensing 

1. ?Expect to be able to as a user drag the column out to see the entire description or hover over the item and have the full name appear in the list page
![Screenshot 2023-09-22 at 9 24 43 AM](https://github.com/openmsupply/open-msupply/assets/143057869/b8ceb7c4-7560-4ad4-8a5f-a3b1eedfa254)

3. when selecting on the item would expect to be able to see the full name of the medicine. note also some medicine names can be very long (e.g. HIV meds like: efavirenz 600 mg + emtricitabine 200 mg + tenofovir disoproxil maleate 300 mg ) so maybe the text should adjust itself to fit to size of the row instead of being the same font size and the row be made longer? 

![Screenshot 2023-09-22 at 9 21 02 AM](https://github.com/openmsupply/open-msupply/assets/143057869/2b8c6c85-143c-4dfb-b0e7-310019f27a20)

## How to Reproduce 🔨
No

## Your environment 🌱
 Desktop v 1.3

## Agreed solution 
- expand the width of the item name in the modal, make the top half of the modal bigger to allow shifting down the Unit-pack toggle
- add a tooltip over the item names column in the listboxes

**Comment by roxy-dao** [comment]
Linked to #1764

**Comment by Gwalior-84** [comment]
This is very important as the last few characters of the item name are often critical, e.g. 250mg or 500mg!

**Comment by DhanyaHerath** [comment]
**Anisha says:**
-  expand the width of the item name in the modal, make the top half of the modal bigger to allow shifting down the Unit-pack toggle 
- add a tooltip over the item names column in the listboxes

**Comment by DhanyaHerath** [comment]
@fergie-nz possible issue for you!

**Comment by fergie-nz** [comment]
I am seeing that this also occurs in the stock list view.

Is it best practice to make this into a separate issue, or include in this same PR?



![Image](https://github.com/openmsupply/open-msupply/assets/90807420/687df190-2643-4bc3-a27c-35a8d0751cd2)

**Comment by roxy-dao** [comment]
> I am seeing that this also occurs in the stock list view.
> 
> Is it best practice to make this into a separate issue, or include in this same PR?

I usually fix everything in one issue... but up to you

**Comment by mark-prins** [comment]
I would do in the same PR as it's probably small enough in this case.
The table cell could probably do with a tooltip, and I'm thinking that you could just add to all table cells.. and if that is strange or annoying to use then make it configurable i.e. a Column property.
There might be a maxWidth set on the column in the stock table which is causing the truncation 🤔
