### ISSUE TITLE
Location function in stocktake

### ISSUE THREAD

**Issue by louisaw123** [openmsupply/open-msupply#2278]
## What went wrong? 😲
Cannot see locations when doing a stocktake

![Screenshot 2023-09-25 at 3 26 06 PM](https://github.com/openmsupply/open-msupply/assets/143057869/489bc9b9-b62a-47c0-8649-f31cf4687134)

## Expected behaviour 🤔
Need to see locations otherwise users will not know where to go to find the stock to count

## How to Reproduce 🔨
No

## Your environment 🌱
v 1.3 desktop

**Comment by fergie-nz** [comment]
Hey @louisaw123 ,

I think more complex than simply adding a location as a table column, because an individual item might have different batches in different locations, ie:

![F2891C14-3E01-4651-A889-8B701CC10161](https://github.com/openmsupply/open-msupply/assets/90807420/53e07a9f-6098-420d-82d2-7284f49d20ce)

And those locations are visible in the item detail modal.

Do you think that is sufficient?

If not, another option might be adding another filter in the toolbar for a specific location like here:

![E7035837-BDC6-4350-86CB-9AA9C200158D](https://github.com/openmsupply/open-msupply/assets/90807420/6733e17c-a7df-47c2-adbf-b27c95aef8e9)

**Comment by louisaw123** [comment]
> Hey @louisaw123 ,
> 
> I think more complex than simply adding a location as a table column, because an individual item might have different batches in different locations, ie:
> 
> ![F2891C14-3E01-4651-A889-8B701CC10161](https://user-images.githubusercontent.com/90807420/271418489-53e07a9f-6098-420d-82d2-7284f49d20ce.jpeg)
> 
> And those locations are visible in the item detail modal.
> 
> Do you think that is sufficient?
> 
> If not, another option might be adding another filter in the toolbar for a specific location like here:
> 
> ![E7035837-BDC6-4350-86CB-9AA9C200158D](https://user-images.githubusercontent.com/90807420/271418719-6733e17c-a7df-47c2-adbf-b27c95aef8e9.jpeg)

thats fine - if theres multiple locations it can say [multiple] like the batch columns does and then when u expand out it will show the location individually?

**Comment by roxy-dao** [comment]
> @fergie-nz thats fine - if theres multiple locations it can say [multiple] like the batch columns does and then when u expand out it will show the location individually?

That's the plan (:

**Comment by louisaw123** [comment]
i would consider removing the "comment" column and put location at the start if trying to fit it is a problem.. generally if i do a stocktake i want my screen to tell me where something is and be able to sort the locations so that the same ones appear together otherwise i would be running around the whole warehouse looking for things if i am going by item alphabet if that makes sense..

and also if i select for the locations to sort in order - the items should sort alphabetically after the location is sorted like below:

<img width="629" alt="Screenshot 2023-09-29 at 11 55 45 AM" src="https://github.com/openmsupply/open-msupply/assets/143057869/b0362b0f-ed6c-470d-bd93-22b073b8d4b3">


and then on oms:
<img width="1489" alt="Screenshot 2023-09-29 at 11 46 47 AM" src="https://github.com/openmsupply/open-msupply/assets/143057869/b8253bf4-5206-495c-8b37-a9cf7e8d61c7">

**Comment by richardmoizeau** [comment]
Hi All, we got the same requirement for Côte d'Ivoire to see the location in the stocktake table. I'm even questioning the relevancy of the "Group by item" button. In a stocktake, you always need to see the details at the batch number level. Stocktake view should default to "Group by item" = FALSE in my opinion.

**Comment by adamdewey** [comment]
>  In a stocktake, you always need to see the details at the batch number level. Stocktake view should default to "Group by item" = FALSE in my opinion.

Yeah I agree too - it's actually a little bit of a weird UX to click on a batch line and then see details for other batches in the same modal, especially as you can't see the location on the first tab 🤔

**Comment by adamdewey** [comment]
I guess the key takeaway is that stocktakes need to be Batch-centric, not Item-centric at a minimum. 

With the option of being Location-centric (if locations are being used and users want to operate that way)..

**Comment by mark-prins** [comment]
I'd rather not add Location as the first column - and would want to have the column order consistent across all of the item-in-a-table usages.

We usually have `code`,`name`,`unit`,`batch`,`expiry`,`location`

I'm reluctant to take away the group by item functionality too - I thought that this was added because it was requested

**Comment by richardmoizeau** [comment]
> I'm reluctant to take away the group by item functionality too - I thought that this was added because it was requested

We can keep it. Although I think it was added only because it exists for the other item-in-a-table usages :)

> We usually have code,name,unit,batch,expiry,location

Good to keep the system consistent.

**Comment by louisaw123** [comment]
fair - as long as the location can be sorted alphabetically as it is not sortable currently from "inventory > view stock", and then each item be sorted alphabetically per location on the second level

**Comment by Gwalior-84** [comment]
Stocktakes are used for quite a few different purposes, each of which needs to be supported.  Main purposes include:

- Entering stock for the first time:  Each stock line will be entered separately.  Sort order is a little academic initially, but as the stocktake progresses, it will need to be sortable by location.
- Full stocktake:  Sort by location, and need to have all stock lines shown separately.
- Location stocktake:  As per Full stocktake, but filter by location
- 'Item' stocktake:  Filter by item and show all stock lines of the item.
- Expiry date stocktake:  Filter by expiry date (shows all stock lines with expiry less than the date).   Defaults to all today, but can be set to another date.  It's also common to want to filter by item code or category because expiry date is a more sensitive issue for medicines than it is for sundries / consumables.

I can't think of any stocktake situation where you would want to aggregate by item.

**Comment by mark-prins** [comment]
This has ballooned into a bigger issue than originally intended!
Fine to remove the 'group by item'.. though if we do that, then we may want to look at the modal as that currently is per-item not per-batch. If we simplify the modal to only show a single batch, then we need to find a way to insert a new batch : and all of this is a different approach to how item and batch management happens elsewhere.

My suggestion summary of changes:
- Remove the grouping by item ( and all the logic that goes with that in the Detail table )
- Retain the per-item modal which shows all batches for the current item
- Add the highlight animation, or some other visual cue to show which batch you've clicked on when editing
- Add location as a column, in the order noted above
- Add a sort for location
- Change comment to be the speech-bubble-icon, show on hover column (possibly?)

and later make these changes:
- filters as noted by MG 
  - by item
  - expiry date

**Comment by roxy-dao** [comment]
> This has ballooned into a bigger issue than originally intended! Fine to remove the 'group by item'.. though if we do that, then we may want to look at the modal as that currently is per-item not per-batch. If we simplify the modal to only show a single batch, then we need to find a way to insert a new batch : and all of this is a different approach to how item and batch management happens elsewhere.
> 
> My suggestion summary of changes:
> 
> * Remove the grouping by item ( and all the logic that goes with that in the Detail table )
> * Retain the per-item modal which shows all batches for the current item
> * Add the highlight animation, or some other visual cue to show which batch you've clicked on when editing
> * Add location as a column, in the order noted above
> * Add a sort for location
> * Change comment to be the speech-bubble-icon, show on hover column (possibly?)
> 
> and later make these changes:
> 
> * filters as noted by MG
>   
>   * by item
>   * expiry date

Should this be moved into a new issue...? Since it's not really related to adding location to the list view..

**Comment by adamdewey** [comment]
> Stocktakes are used for quite a few different purposes, each of which needs to be supported. Main purposes include:
> 
> * Entering stock for the first time:  Each stock line will be entered separately.  Sort order is a little academic initially, but as the stocktake progresses, it will need to be sortable by location.
> * Full stocktake:  Sort by location, and need to have all stock lines shown separately.
> * Location stocktake:  As per Full stocktake, but filter by location
> * 'Item' stocktake:  Filter by item and show all stock lines of the item.
> * Expiry date stocktake:  Filter by expiry date (shows all stock lines with expiry less than the date).   Defaults to all today, but can be set to another date.  It's also common to want to filter by item code or category because expiry date is a more sensitive issue for medicines than it is for sundries / consumables.
> 
> I can't think of any stocktake situation where you would want to aggregate by item.

I like Mark G's reply here - it helps to explain how actually there are actually several distinct user stories when it comes to doing stocktakes.

Perhaps in the future we could revisit and see if there's a case to be made for streamlining the UX to help with each of these specifically - e.g. there could be a button for 'Initial stocktake' and one for 'Stocktake by location' which would lead to a slightly different layout that is tailored to suit that specific user story.
