### ISSUE TITLE
Cold Chain authentication

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2281]
### Login
- The server accepts an object with the shape {username: string, password: string}
- The credentials are validated against the store credentials, which we don't have. Suggest that we add a permission type for users of `COLD_CHAIN_API` and manually (for now) create a user and grant this permission. Next step is to take the store credentials during sync and create a user
- If validated, the server creates a JWT token and returns the cookie. This contains the storeID currently - we will be consuming the JWT so can define the shape

### Validation
- If a JWT is presented, this is checked for a valid storeID

### Estimate
2 days

### Moneyworks Jobcode 🧰
OMS:COLC

**Comment by mark-prins** [comment]
Added [a suggestion](https://github.com/openmsupply/msupply/issues/13764) for implementation within mSupply

**Comment by AnushaUp** [comment]
If this user permission is given then only the connection is established
![Screenshot 2024-03-04 at 3 14 17 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/d2c407c9-9453-4719-9f72-f17e2cd67820)
If the omSupply is not given then

https://github.com/msupply-foundation/open-msupply/assets/115983430/3939409e-dba7-446d-9dac-daa81a2254bf
