### ISSUE TITLE
Add `Breaches` tab and breach list view in `Monitoring` page

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2283]
## Is your feature request related to a problem? Please describe 👀
Cold chain needs a way to view breaches in the UI.

## Describe the solution you'd like 🎁
- The monitoring page has 3 tabs ( only implementing the breach tab in this issue ) 
- Hook to query `temperature_logs` and ( hook to update temperature log comment - comment not yet implemented tho...)
- Columns: 
  - Status. Icon for unacknowledged breaches: ![Group 125](https://github.com/openmsupply/open-msupply/assets/61820074/c936443c-d3ae-4dc1-b98b-2d7fbd672eda)
  - Sensor name
  - Storage location
  - CCE
  - Breach start (datetime)
  - Breach end (datetime)
  - Duration (minutes)
  - Ongoing
  - Hot or cold. Cold icon: ![🦆 icon _snow flake_](https://github.com/openmsupply/open-msupply/assets/61820074/26682894-acb4-4a0f-8d97-43fd6386e446) Hot icon: ![🦆 icon _sun light_](https://github.com/openmsupply/open-msupply/assets/61820074/5f06f231-35dd-408a-9f41-8ee8aec0cec5)
  - Highest/Lowest Temperature
  - Type
  - Comment ( will need backend/mSupply issue first to implement )

UI mockup: 
![Screenshot 2023-10-12 at 12 01 05](https://github.com/openmsupply/open-msupply/assets/61820074/8e1e71fb-43a8-429f-baa6-77b6550db923)

### Estimate
6 hours

### Moneyworks Jobcode 🧰
OMS:COLC

**Comment by adamdewey** [comment]
Couple of observations: 

- Think the hot / cold icons are a bit too similar perhaps? 
- How will we handle start / end date times for cumulative breaches - will it be the first datetime of the first excursion and the last datetime of the last excursion?

**Comment by roxy-dao** [comment]
Updated to `Must have` based on feedback from Craig

**Comment by adamdewey** [comment]
After meeting today: 

- Not doing comment field until we can acknowledge locally
