### ISSUE TITLE
Add `Sensors` link under ColdChain nav and sensor page with a list view of sensor information

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2285]
## Describe the solution you'd like 🎁
- Add `Sensors` sub-link under `Cold Chain menu`
- Clicking on link leads to the sensors list view
- Hook to query sensor information
- Columns: 
   - Name
   - Storage Location
   - CCE
   - Serial Number
   - Battery Level
   - Last reading
   - Sensor Type
   - Breach
   - Last recording date / time
- Clicking on a row will direct user to sensor detail view  

Mockup: 
<img width="841" alt="Screenshot 2023-09-26 at 12 18 46 PM" src="https://github.com/openmsupply/open-msupply/assets/61820074/d04e02c2-7755-4581-9dba-4b462d0f8b0f">

### Estimate
3 hours

### Moneyworks Jobcode 🧰
OMS:COLC

**Comment by adamdewey** [comment]
Observations: 

- Maybe group the last reading and last reading datetime together?
- Should be consistent - either use 'last reading' or 'last recording' for both
