### ISSUE TITLE
Cold chain: Rename main menu

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#2287]
We need to rename the main cold chain menu - it shouldn't be one word. 

Jury is out for whether it should be `Cold Chain` or `Cold chain`

UNICEF and WHO use `Cold chain`

But I'm unsure on convention for double word titles elsewhere in the product. 

Perhaps @anisha-msupply has some thoughts?

## Describe the solution you'd like 🎁

![image](https://github.com/openmsupply/open-msupply/assets/19318937/4f460f07-e870-48c9-94cf-833c8a5a8f24)

**Comment by adamdewey** [comment]
Perhaps Cold Chain is better as that would align better with CCE for Cold Chain Equipment?

**Comment by roxy-dao** [comment]
Closed and added to issue where it's being implemented
