### ISSUE TITLE
Add `Chart` tab with sensor temperature chart in `Monitoring` page

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2288]
## Describe the solution you'd like 🎁
- Top
   - Chart of min/max threshold data from sensor
   - Colours will be associated with cards at the bottom
   - Hovering over lines will display a bubble with following information: 
       - Sensor name and breach hot/cold icon
       - Location
       - Breach start
       - Breach end

Mock up: 
![Screenshot 2023-10-12 at 11 52 41](https://github.com/openmsupply/open-msupply/assets/61820074/449a054d-e594-4cea-97f9-df88cc37bcfb)

### Estimate
2 days

### Moneyworks Jobcode 🧰
OMS:COLC

**Comment by adamdewey** [comment]
Observations: 

- We're using the same icon here for 'malfunctioning' as we're using for 'unacknowledged' in the breaches tab - I think this could get confusing - suggest a different icon for each?
- @richardmoizeau - did we decided to combine the graph and card views? I think I missed that...

**Comment by richardmoizeau** [comment]
> * We're using the same icon here for 'malfunctioning' as we're using for 'unacknowledged' in the breaches tab - I think this could get confusing - suggest a different icon for each?

yes, that's something that was brought up by @louisaw123 during the user testing so definitely to be discussed during the "final final design review" 

> @richardmoizeau - did we decided to combine the graph and card views? I think I missed that... (I mean, if we can do it well then great! But 1 day seems a bit conservative to me.. 🤔)

We are probably going to only focus on the charts but once again, to be decided in the same meeting as above. 1 day seems conservative even for charts only.

**Comment by adamdewey** [comment]
Comments from meeting today: 

- Cards are not for MVP
- Only show icon for breaches, not excursions
- Bubble to be shown when click on breach icon
- Palette of 6 colours to be determined for sensor lines
- Fixed axes of 0C to 10C with thresholds shown at 2C and 8C

Anything else @richardmoizeau , @mark-prins , @andreievg , @roxy-dao , @anisha-msupply ?

**Comment by richardmoizeau** [comment]
following meeting on Oct 4th (Final Final Requirements): 

- [ ] Remove the cards (we only keep the chart)
- [ ] boundaries of chart foccussed on 2-8°C (-/+ 2°C)
- [ ] On the mockup, these are just sensor's names: 
<img width="106" alt="Screenshot 2023-10-04 at 1 07 59 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/2cf9c09b-88af-4208-a260-504f53e74220">
- [ ] Click on a the breach icon (warning icon) and will show a popup/bubble that display details about the breach and a link to the breach view 
- [ ] colours for the charts lines: pre-defined set of colours (up 6 colours)
- [ ] when hovering over a datapoint, see details (date, value, sensor name)

**Comment by mark-prins** [comment]
Additional notes, after looking into the data aggregation currently implemented. Both mobile and CCA are plotting single sensors at a time only. The colouring of the lines can therefore be tied to temperature and there is more scope when adding breach icons.

**CCA**
- y axis limits are the min and max temperatures +/- 5
- x axis limits are simply the min / max timestamps
- all data is plotted
- no breach indication is shown
- the line colour is a gradient showing red when in the top 40% of the plot region, which in the middle and blue in the lower 20%

![IMAGE 2023-10-19 11:05:45](https://github.com/openmsupply/open-msupply/assets/9192912/b1ca5c33-4f75-4520-a2b1-de76df83dcef)


**Mobile**
- y axis limits simply the max temp
- x axis limits the min temp
- the chart has a date range selection which defaults to the current day. For the given range, the chart shows a max of 30 data points, unless the range is a day or less (note: there's no time selection on the range, so less than a day isn't actually possible!) then it shows a max of 24 data points
- the number of data points is the minimum of the value above (24 or 30) and the number of actual log entries
- the max and min temperatures within the period are plotted; giving different lines for max and min values across the chart
- all breaches within the range are plotted as clickable icons. the time value is the timestamp of the breach start time

![mobile-line-chart-3](https://github.com/openmsupply/open-msupply/assets/9192912/8d956d20-b8c3-44e2-be4e-4a8592a74cab)

![mobile-bar-chart-2](https://github.com/openmsupply/open-msupply/assets/9192912/8d5849bb-f7a9-43f0-8bbe-33502b4dd902)

**Comment by adamdewey** [comment]
Anecdotally, I and several others, found the Mobile graphs hard to read. 

The CCA graph is better but not really granular / big enough to be very useful. 

Here are some examples of graphs that were on display in various places at the TechNet 2023 conference, I find them easy to read (also I find Grafana graphs easy to read) 

<img width="1965" alt="2023-10-18_20-30-59" src="https://github.com/openmsupply/open-msupply/assets/19318937/1f8b833c-c64e-4b1f-b000-2ed82d9b06f0">
<img width="1903" alt="2023-10-18_20-31-45" src="https://github.com/openmsupply/open-msupply/assets/19318937/3b4b3413-1873-4abd-9351-ee9603241ca2">
![2023-10-18_20-32-31](https://github.com/openmsupply/open-msupply/assets/19318937/5da46d26-f28c-40fd-80f7-a3bfe3914d45)

**Comment by roxy-dao** [comment]
Those graphs are all with just one sensor, no?

**Comment by louisaw123** [comment]
> Those graphs are all with just one sensor, no?

yes looks like one sensor to me

**Comment by adamdewey** [comment]
Yep, one sensor 👍
