### ISSUE TITLE
Stock transfer not created when you change statuses step by step unless you sync 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2292]
## What went wrong? 😲
 
When you create an outbound shipment for another store on the same site as you (ie. a stock transfer), it creates the stock transfer on the customer store immediately if you change the outbound shipment to picked status all in one go. 

However, if you do it step by step by changing the statuses one by one, you don't see the inbound shipment on the other store unless you manually sync. 

## Expected behaviour 🤔
Shouldn't require sync to create a stock transfer on the same site

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an outbound shipment
2. Add some lines and change the status one by one until it is allocated 
3. Log into the customer store
4. See that the inbound shipment hasn't been created yet 
5. Manually sync 
6. See that the inbound shipment is now there 

## Your environment 🌱

 - Version: 1.3.0.00
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one) - Chrome, I was on the demo server 
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by fergie-nz** [comment]
I'm seeing that I can't change the status to allocated all in one go. 

Is this what you had also, or I wonder if there is a workaround to skip to verified status?



![Image](https://github.com/openmsupply/open-msupply/assets/90807420/656d8c5c-8e47-4f4f-81e1-42abb2a8fcd7)

**Comment by fergie-nz** [comment]
I'm struggling to recreate this issue.

I'm getting inbound shipments appearing immediately as soon as their status is changed to 'picked', with no syncing required.
This includes not having an automatic sync - it is showing up immediately, with no syncs taking place.

**Comment by fergie-nz** [comment]
I'm seeing that this is requiring sync for either single stepping or if you manually go straight to 'confirm shipped'

**Comment by mark-prins** [comment]
Unable to repro - with the two stores on the same site, the inbound shipment is created as soon as the outbound shipment is PICKED

**Comment by fergie-nz** [comment]
Thanks @mark-prins!

Yes agree, I also cannot reproduce. I'm also unable to reproduce on demo server now.

@DhanyaHerath I wonder if we can put this to back log and revisit if issue re occurs or more precise causes of failure can be identified?

**Comment by mark-prins** [comment]
Even better.. can we close it?

**Comment by DhanyaHerath** [comment]
Ahhh fascinating, also can't reproduce on demo server now (even though we saw it together yesterday @fergie-nz 🤔). Such magic - we can close it
