### ISSUE TITLE
Encounter "bubble" layout not centred

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2294]
![image](https://github.com/openmsupply/open-msupply/assets/88299195/92aa8203-a0fc-424e-b5a7-d63f32874e7b)

@CarlosNZ Is this a regression of: https://github.com/openmsupply/open-msupply/pull/2259 ?

**Comment by CarlosNZ** [comment]
> @CarlosNZ Is this a regression of: https://github.com/openmsupply/open-msupply/pull/2259 ?

Yeah looks like it. I'll take a look today.
