### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#23]
Need a way to log user activity though the app - essentially just a log of mutations made, with date and user.
For V1 this log doesn’t have to be accessible by users via UI - though, that would be awesome and is already in designs. 

Main motivation for this is to have an audit of who did what (would be helpful when users find discrepancy in data, and we need to point out who (when) caused this discrepancy. 

Will audit will need to be available on central? I thought that we'd said not, others disagree. It would create more sync traffic - would it be possible to have a second class sync priority?

**Comment by clemens-msupply** [comment]
Summary from an offline discussion:

Problem: if, for example, FE wants to query logs for invoice of type InboundShipment we would need to encode this information somehow in a DB column. It get worse if we want to query for InboundShipments of a certain status.

Option 1: have a log_type for every combination e.g. InboundShipmentAllocated, OutbountShipmentAllocated (lots of combinations)
Option 2: json data columns which contains unstructured data such as invoice type and status (but this is not easy to query)
Option 3: have a set of more columns, e.g. context = "Invoice", sub_context_1 = InboundShipment, sub_context_2 = Allocated, sub_context_3 = ...

Google has some resource type in their logs, e.g. "projects/[PROJECT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/views/[VIEW_ID]"
@jmbrunskill any useful idea from Azure?

**Comment by jmbrunskill** [comment]
@clemens-msupply  I don't have a heap of insight here, but I think the google style resource path could be useful.
E.g. if you search by LOCATION ID, BUCKET_ID etc all related events will show up. I'm not sure what you'd do for bulk transactions though.

I like the idea of storing JSON as I believe postgres and sqlite both have at least some functions for dealing with JSON and there's lots of other log search tools that can decode JSON on the fly to interpret at query time. This could be useful for tools like elasticsearch to query if we used something like that in future.

I'm thinking for UI users they will want to be able to do simple queries like find the recent invoices, or find invoices relating to the record they're looking at (Maybe filter by store?). For more complex queries (query within json, etc) can we say we'll download the logs and analyse them outside of the UI?

Azure's activity log is documented here and is probably worth a look?
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log

Here's an example of the JSON they record:
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log#send-to-azure-event-hubs

Seems to have a `resourceId` (which looks quite like the google `resource type`)
`/subscriptions/s1/resourceGroups/MSSupportGroup/providers/microsoft.support/supporttickets/115012112305841`

They also have:
```
            "time": "2019-01-21T22:14:26.9792776Z",
            "operationName": "microsoft.support/supporttickets/write",
            "category": "Write",
```
Seems like they have different schemas for different types of events...
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log-schema

**Comment by jmbrunskill** [comment]
BTW: for the record I think option 3 is terrible idea :)

**Comment by Chris-Petty** [comment]
@clemens-msupply The current msupply schema has `log.table_name` (well, `table_number` in desktop/4D but same same... foreshadowing headaches?) and `log.record_id`. Should be straightforward to list the log for a particular record (be it shipment, requisition...)? I'm not aware of use cases beyond that. What did you have in mind? Should note that by having a link to the table/record, that record likely has much of the related info you might be looking for (e.g. `invoice.type`).

Being able to narrow down to a particular `log` for some logic might warrant it but I'd refrain from that road, if we were on that train we should have probably designed the whole application with event driven architecture in mind.

**Comment by clemens-msupply** [comment]
@Chris-Petty main use case was to query/filter for logs. e.g. filter by store_id, by type, etc. I guess a table_name or more general a `context` column would be enough for a start (?). For example, context = Stocktake, context = InboundShipment, context = Login.

**Comment by Chris-Petty** [comment]
> @Chris-Petty main use case was to query/filter for logs. e.g. filter by store_id, by type, etc. I guess a table_name or more general a `context` column would be enough for a start (?). For example, context = Stocktake, context = InboundShipment, context = Login.

Speaking of `store_id`, that's another field already on the log table in mSupply. I believe generally indicative of the store of the ID the record pertains to (e.g. invoice.store_id). `type` being the old `event_type` yea?

I had originally thought that maybe we'd need a system for hierarchal contexts, but I can't think of any instance that isn't already covered by the current fields:

![image](https://user-images.githubusercontent.com/7684221/175848126-82970bf6-964b-484d-b1a5-e546c3485be0.png)

- `store_id` relating to store and/or its data. Including adjacent things like "what users have logged into this store".
- `source_record_ID` gives use any logs relating to a record, for instance CRUD of an invoice.
- `source_table` complements above. Can see all invoice events across stores, or for a particular store.
- `user_ID` you can see who did what above, or look at a list of all things a user did.

That seems like it covers the vast majority of use cases for us. Where you're going sounds like:

I want to query all logs specifically by "inbound" shipments that have had their status changed to "allocated". We could try capture all that within the log, but we could currently achieve this by querying something like (forgive me, haven't written SQL for a while):
```SQL
SELECT * FROM log
WHERE log.record_id IN (
  SELECT invoice.id FROM invoice 
  WHERE status IS 'allocated' 
  AND type == "inbound"
)
```

There is likely a gap in my understanding because of little knowledge of gql API for this. I'd have thought you could filter the `invoices` just as in the sub query above, then request the related logs of those records?

**Comment by jmbrunskill** [comment]
> There is likely a gap in my understanding because of little knowledge of gql API for this. I'd have thought you could filter the `invoices` just as in the sub query above, then request the related logs of those records?

I think you are right, this is a great idea. Essentially the sub query becomes a 'loader' in graphql.

**Comment by jmbrunskill** [comment]
> > There is likely a gap in my understanding because of little knowledge of gql API for this. I'd have thought you could filter the `invoices` just as in the sub query above, then request the related logs of those records?
> 
> I think you are right, this is a great idea. Essentially the sub query becomes a 'loader' in graphql.

Sorry think I may be wrong about this, it would be the other way around.

You could definitely do a query on the the invoices (in this example) and get the associated log records.

Something like...
```
query invoices(
  $first: Int
  $offset: Int
  $key: InvoiceSortFieldInput!
  $desc: Boolean
  $filter: InvoiceFilterInput
  $storeId: String!
) {
  invoices(
    page: { first: $first, offset: $offset }
    sort: { key: $key, desc: $desc }
    filter: $filter
    storeId: $storeId
  ) {
    ... on InvoiceConnector {
      __typename
      totalCount
      nodes {
        id
        logs
      }
    }
  }
}
```
You'd then need to combine all the log records for display (Assuming you were wanting to re-use the existing filters on the current invoice query)

**Comment by Chris-Petty** [comment]
> You'd then need to combine all the log records for display (Assuming you were wanting to re-use the existing filters on the current invoice query)

Right so you'd have basically a collection of invoices, each containing a collection of logs. Would then need to flatten the collections across the logs - front end should be alright to do that in typescript? Unfortunately this is janky if you're looking at a paginated list of logs though? Usually want the logs chronologically, which may differ to any of the dates in invoices. i.e. hard to achieve this right?:

```SQL
SELECT * FROM log
WHERE log.record_id IN (
  SELECT invoice.id FROM invoice 
  WHERE invoice.status = "allocated"
  AND invoice.type = "inbound"
)
ORDER BY log.datetime
```

**Comment by andreievg** [comment]
I think it's a good idea to validate requirements before we get too deep into implementation details. Sorry I didn't end up listing requirements in: https://github.com/openmsupply/open-msupply/issues/155, yet. The plan was to start with the minimum (with allowance for extension), and see what product owner/stakeholder with domain knowledge would want, vs thinking of all of the possible ways user can interact with logs and implement a flexible system that deals with all foreseen use cases. 

The very base requirement would be to see activities when looking at particular invoice/requisition/stocktake, this hasn't been validated as requirement in written form though, but I think I've seen UI designs for this and it's available in existing mSupply (which is kind of a base for validating specs). I'll remember to add 'being' able to search by record type to the list of requirements to be confirmed by stakeholders/product owner, hmm not to find one of those hehe.

**Comment by Chris-Petty** [comment]
> I think it's a good idea to validate requirements before we get too deep into implementation details. Sorry I didn't end up listing requirements in: #155, yet. The plan was to start with the minimum (with allowance for extension), and see what product owner/stakeholder with domain knowledge would want, vs thinking of all of the possible ways user can interact with logs and implement a flexible system that deals with all foreseen use cases.
> 
> The very base requirement would be to see activities when looking at particular invoice/requisition/stocktake, this hasn't been validated as requirement in written form though, but I think I've seen UI designs for this and it's available in existing mSupply (which is kind of a base for validating specs). I'll remember to add 'being' able to search by record type to the list of requirements to be confirmed by stakeholders/product owner, hmm not to find one of those hehe.

I agree! On that note in the discussion here I made a stab at user stories https://github.com/sussol/msupply/discussions/9527 (just clarified it a bit now):

> User should be able to:
> - View a table of all log events
>   - Search
>   - Filter by all event types
>   - Filter by date/time range
>   - Sort by all scalar fields (i.e. not the (JSON) object)
>   - View log details (i.e. the (JSON) object)
> - See all events (which may be of several types) relating to feature
>   - e.g. view log events related to the current UI view for a record, such as store/patient/name/transaction/requisition etc.

I've felt in the past that maybe it'd be good to do something like `invoice/<id>/created`, similar to the google `resource type` thing. But:
- Complexity? Can't really enum that I think, or enforce constraints (though maybe you wouldn't want to!). Indexing and querying effectively... blah. How fast is SQL `LIKE`?
- `table_name`, `record_id` and `event_type` fields actually capture the same information! What's more the event_type likely has the table name in it
- Only edge case is that you can't effectively query for "Give me ALL the logs where an invoice was changed to status "allocated"". The SQL I've written in above comments would filter out logs where that isn't the _current_ status of the record. You'd have to check the log data... but, if you get every log for `event_type = invoiceUpdate` and sequentially search on the log data it's probably fast enough for the edge case that isn't a requirement 😁.

For filtering there is one caveat and mostly what I think @clemens-msupply was getting at. If you want to see all the logs relating to prescriptions for a particular patient. This is an invoice of a particular type, and there isn't an obvious way to capture that's agreed upon.

- invoice_<event_type> (generic, which might be appropriate given invoice has many contexts. Can filter by IDs of invoices relating to the patient in question)
- prescription_<event_type> (More specific. We still have `table_name` to filter by `invoice`. Bit more human friendly if looking at all the logs relating to a store. Still have to filter by IDs of invoices relating to the patient in question)
- prescription/<id>/<event_type> (likely unnecessary complexity and redundancy! Still haven't got patient in there)
- patient/<id>/prescription/<id>/<event_type> (exaggerating to highlight a crucial problem - from a store perspective this should be `store/<id>/invoice/<id>/<event_type>`. How do we decide? Log both?)

In the end, I've come round to the generic approach is probably fine, maybe the slight specificity of the second point can help readability of a list of largely unfiltered logs. The other 2 options create new ambiguity.

Thinking about the different contexts, I'd guess that the google logs example they aren't logging to the DB but to a text file stored elsewhere, where utilising the DB data to help analysis isn't practical. At their scale and requirements I suspect the overheads of a DB would be prohibitive. In our case though, we can!
