### ISSUE TITLE
Update central-remote version dependencies

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2304]
The current remote server version doesn't handle a missing dateOfDeath column, i.e. the remote server expects a minimum version of the central server.
The reason is that the deserialization code in the remote server expects the dateOfDeath column.

There are the following changes required:
- [x] Test that sync indeed fails with an old version of the central server
- [x] Increment `iMaxVersion` and `iMinVersion` in `Project/Sources/Methods/syncV5API.4dm`
- [x] Increment `SYNC_VERSION` in `server/service/src/sync/settings.rs`
- [x] Test that sync fails with version mismatch
- [x] Test that sync works with correct versions

**Comment by JonnaQuismundo** [comment]
closed in `V7-09-00-Beta10`
