### ISSUE TITLE
Update problem in Encounter view

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2317]
@richardmoizeau noticed this issue:

![image](https://github.com/openmsupply/open-msupply/assets/88299195/72858a75-25c5-492e-9c79-32945d886289)

- [ ] try to reproduce
- [ ] fix

**Comment by mark-prins** [comment]
Unable to reproduce. Suggest that we close

**Comment by clemens-msupply** [comment]
thanks for trying! I also can't reproduce it will close and monitor if we run into it again. @richardmoizeau or do you remember more details on how we got to it?

There are a couple of hook dependency warnings, but I couldn't see if they would cause this issue...
