### ISSUE TITLE
patient erroneously flagged as "Missed Appointment"

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2321]
## What went wrong? 😲
 

patient is flagged as "Missed Appointment" on 03/10/2023:

![Screenshot 2023-10-03 at 9 20 03 AM](https://github.com/openmsupply/open-msupply/assets/74992958/56dd5d8f-bdc6-4e2d-afd2-0794a13cd1a8)

However, patient was prescribed 90 pills (Encounter on 18/09/2023) with an end of supply date = 20/12/2023

## Expected behaviour 🤔

patient should not be flagged as "Missed Appointment". He will potentially be flagged as "missed appointment" if nothing is prescribed from 20/12/2023

## How to Reproduce 🔨

[See patient "Laurence Fishburne"](https://png-hiv-field-test.msupply.org/dispensary/patients/9d412e4e-fdd2-49ef-98d6-685ade890b91?tab=Programs&sort=enrolmentDatetime&dir=desc)

## Your environment 🌱

 - Version: https://png-hiv-field-test.msupply.org/
 - Platform: 
   - [ ] browser (extra points if you tell us which one)

**Comment by richardmoizeau** [comment]
Similar issue with patient "Hugh Laurie" who is flagged as "Early LTFU" even though according to the last encounter he should have enough supply until 05/11/2023

**Comment by DhanyaHerath** [comment]
This one is done, but still open + no PR linked @clemens-msupply, should it be closed?

**Comment by clemens-msupply** [comment]
thanks PR had the wrong number...
