### ISSUE TITLE
contact tracing: populate/update some contact details based on linked patient

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2323]
## Is your feature request related to a problem? Please describe 👀

when a patient is linked to a contact in the contact tracing functionality, we expect the data to be automatically populated with the patient details. 

![Screenshot 2023-10-03 at 10 03 01 AM](https://github.com/openmsupply/open-msupply/assets/74992958/b8a1c133-7900-4fcd-8139-d3f3e650d0d7)

## Describe the solution you'd like 🎁

when a patient is linked to a contact in the contact tracing functionality, we expect the data to be automatically populated with the patient details (previously manually entered data to be overwritten): 

![Screenshot 2023-10-03 at 10 03 01 AM](https://github.com/openmsupply/open-msupply/assets/74992958/b8a1c133-7900-4fcd-8139-d3f3e650d0d7)

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
One concern is that if you link the wrong person you get the wrong details, this might become very confusing.

In general, we shouldn't edit on behalf of the user, i.e. the user should make changes not the software. What we can do is to make it easy for the user to enter data and to support the user to enter data correctly.

There is already a warning if the linked user doesn't match the details from the recorded contact fields.

What we can do though is to add a label or make it more clear in the form that the details are coming from the original patient. And that the details might differ to the actual details of the linked patient. The original data is IMHO also important information to keep, e.g patient might know two contacts only by first name and the first names are similar.

**Comment by richardmoizeau** [comment]
> What we can do though is to add a label or make it more clear in the form that the details are coming from the original patient. And that the details might differ to the actual details of the linked patient. The original data is IMHO also important information to keep, e.g patient might know two contacts only by first name and the first names are similar.

Agree !

**Comment by clemens-msupply** [comment]
How does this look?

![image](https://github.com/openmsupply/open-msupply/assets/88299195/4faa724d-0c3b-4dc4-98cd-db57bac84501)

**Comment by richardmoizeau** [comment]
that would work ! Thanks

**Comment by clemens-msupply** [comment]
Ok done thanks!
