### ISSUE TITLE
... > Patients > Patients: Encounter tab: program column is empty

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2325]
## What went wrong? 😲
 

... > Patients > Patients: Encounter tab

the column "Program" is empty

![Screenshot 2023-10-03 at 12 12 24 PM](https://github.com/openmsupply/open-msupply/assets/74992958/3eb8e78d-6887-4353-843a-29ad937670a7)

## Expected behaviour 🤔

We should see the name of the program the encounter is related to (eg. HIV Care & Treatment, HIV Testing and Counselling)

## How to Reproduce 🔨

... > Patients > Patients: Encounter tab

## Your environment 🌱

 - Version: https://png-hiv-field-test.msupply.org/dispensary/patients/9d412e4e-fdd2-49ef-98d6-685ade890b91?tab=Encounters&sort=startDatetime&dir=desc
 - Platform: 
   - [ ] browser (extra points if you tell us which one)

**Comment by clemens-msupply** [comment]
working in local setup, will check again when updating the server...

**Comment by clemens-msupply** [comment]
Its working now, but I can't remember a change that fixed it or what the cause for it was... Maybe central config was out of sync to some api changes...
