### ISSUE TITLE
contact tracing: add a "Comments" field in the tracking outcome bubble

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2327]
## Describe the solution you'd like 🎁

Add a "Comments" field in the contact tracing form > Tracking Outcome (existing in HPDB):

<img width="1027" alt="Screenshot 2023-10-03 at 12 32 53 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/52bdfc23-81ae-4454-b838-9d6b06ac3940">

### Additional context 💌

![Screenshot 2023-10-03 at 12 30 42 PM](https://github.com/openmsupply/open-msupply/assets/74992958/6d656a12-d139-48b8-aa80-07b3adc135b2)

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
Its here:

![image](https://github.com/openmsupply/open-msupply/assets/88299195/10bd0c47-1a23-4ab9-a163-057056e3c394)

Find it more logical to have it there. From the existing UI it looks like a general comment field. I might be wrong though and easy to change, please let me know what you prefer.

**Comment by richardmoizeau** [comment]
Ok sorry I missed this. 

I thought it was more likely to add a comment once contact has been contacted and to comment about the tracking outcome "eg. contact refused to take the test".

**Comment by clemens-msupply** [comment]
Ok should I leave it where it is? will close please reopen if I should change it...
