### ISSUE TITLE
Cannot enter decimals in `Stock Line Details`

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2328]
## What went wrong? 😲
![Screenshot 2023-10-03 at 13 10 12](https://github.com/openmsupply/open-msupply/assets/61820074/469f94c3-861f-47f4-b0d2-5bb5755c14ea)

Cannot enter decimals in `Stock Line Details` for cost/sell price

## Expected behaviour 🤔
Should be able to enter decimals, e.g. $1.21

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `View Stock`
2. Click on a stock line
3. Try to edit either the cost or sell price with cents

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by richardmoizeau** [comment]
![Screenshot 2023-10-03 at 12 48 17 PM](https://github.com/openmsupply/open-msupply/assets/74992958/895c83cc-f117-4edb-86f3-5204fb7b892e)

I was able to do it

**Comment by roxy-dao** [comment]
> ![Screenshot 2023-10-03 at 12 48 17 PM](https://user-images.githubusercontent.com/74992958/272111703-895c83cc-f117-4edb-86f3-5204fb7b892e.png)
> 
> I was able to enter decimals

Sorry, have updated issue with screenshot. It's for the `Stock Line Details` 😆

**Comment by richardmoizeau** [comment]
my apology, I read "stocktake"

**Comment by nisha-dangol** [comment]
Checked in v1.6.2 exe
Can enter decimals in prices in Stock line details. Moving to Done!
