### ISSUE TITLE
List of masterlists doesn't update right after changing customer in outbound shipment window

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2336]
## What went wrong? 😲
List of master-lists doesn't update right after changing customer in outbound shipment window leading to possibility of choosing incorrect master-list for a store and therefore OK button keeps loading forever since it could not be selected. See [recording](https://recordit.co/8kVgImUUF3) for reference

## Expected behaviour 🤔
List should update on first time

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get two stores with different list of master-lists such that one master-list1 is only accessible to store1 while master-list2 is in use by store2 only.
2. In store1, create outbound shipment. Choose any other store
3. Click `Add from master list` button. You'll see list of master-lists to be in use by that store
4. Change customer, now to say store2
5. Click `Add from master list` button.
6. See error: the same previous list repeats (this list doesn't show master-list2)
7. Click `Add from master list` button again. Now the correct list shows up
8. Repeat this to a point where you can choose incorrect master-list for a store like [in this recording](https://recordit.co/8kVgImUUF3)
9. Click `OK` on the alert to add items from that master-list. You'll see toast messages like Master list not found, which is correct
10. But also notice another bug now: **that OK button keeps loading forever, you can't even quit it, except restart the page** 

## Your environment 🌱

 - Version: v1.4.00-test-2023-10-02-build exe
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

## Additional Context
Found while testing #1666

**Comment by raviSussol** [comment]
Checked in the v1.4.0. Seemed to be fixed.

**Comment by nisha-dangol** [comment]
Moving to Done since it is not replicable anymore the v1.4.00
