### ISSUE TITLE
Fix new Rust warnings

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2349]
After a compiler update there are new warnings now. The clone() warning is actually quite nice:

![image](https://github.com/openmsupply/open-msupply/assets/88299195/dd6dace4-3c92-451c-b1f9-ca15217d846b)

- [ ] Fix them

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest `develop` branch

- [x] Run cargo check
- [x] See no warnings
