### ISSUE TITLE
Cold chain generic filters -- Date and Time filters

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#2351]
Part of Epic #2282 

- These should be **range** filters or specific date.
- Suggested url format for date range: `&date=2023-04-01_2023-05-01` (split by "_")
- Should be a separate "Date" filter and a "Time" filter -- you can create "Date/Time" just by combining them. Maybe include an option to instantiate them both at once?

**Comment by CarlosNZ** [comment]
Okay, so MUI has a Date Range picker, a Date/Time picker, but no Date/Time range (or event just Time range). We can do time range just by having two time filters, one for each end of the range, but then I'm wondering if we should just do the same for the Date range or Date/Time range.

I think this would be simpler, and would give a more consistent UI. I can have both ends of the range instantiated by the same "Filter Menu" item. They'd have to interact with each other somewhat, in that they'd both be updating different parts of the same URL query parameter, but I think this could work quite well.

**Comment by mark-prins** [comment]
I would usually push for using the material components and not reinvent the wheel. In this case though, they're not available and there's no knowing when they'll come in.

there are also date range fields and time range fields available now.. but not pickers. and the pickers are better to use.

I'm not too worried by the inconsistency, because I'm swayed by how nice the date range picker is to use. So my preference is to use the date range picker for date ranges, and to create two grouped filters for the date/time and time ranges

**Comment by CarlosNZ** [comment]
> So my preference is to use the date range picker for date ranges, and to create two grouped filters for the date/time and time ranges

Great, yeah, that's exactly what I've started going with. :)

**Comment by CarlosNZ** [comment]
Actually, I think it's better to use `_` for the range separator and keep the `:` for time separator -- it looks nicer (as the `:` is escaped to `%3A` in the url, and leaving `:` for times makes it simpler to parse the time string.

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Tested using the pickers - looks good (Due to shortcuts, with testing with keyboard looks not necessary)
- [x] Ensure filters are re-instantiated from the url when refreshing page

**Comment by adamdewey** [comment]
2 comments I have on the date / time filters: 

1. They don't persist across the different tabs - I think they should (but they should reset if you leave the monitoring section)
2. You can't choose both Start and End at the same time - you have to select the start, then exit , and then go back in to select the end which is a bit of a clumsy UX if you're wanting to select a date range. Perhaps we could display both start and end modals side by side at the same time?

**Comment by nisha-dangol** [comment]
> 2 comments I have on the date / time filters:
> 
> 1. They don't persist across the different tabs - I think they should (but they should reset if you leave the monitoring section)
>
Yes, I've noticed that as well. The filters don't persist when we switch to different view, like from `Monitoring>Logs` to `Monitoring>Breaches` tab; (and it totally resets when moving from one section to another[like from Coldchain to Inventory or so]) but isn't that intended? 
<br>
> 2. You can't choose both Start and End at the same time - you have to select the start, then exit , and then go back in to select the end which is a bit of a clumsy UX if you're wanting to select a date range. Perhaps we could display both start and end modals side by side at the same time?
>
It looks expected that we'd be able to choose start-time and end-time differently as they appear as two different fields to enter in the UI; so no complaints on that unless this will be modified again with new view as you described? 🤔

**Comment by adamdewey** [comment]
> Yes, I've noticed that as well. The filters don't persist when we switch to different view, like from Monitoring>Logs to Monitoring>Breaches tab; (and it totally resets when moving from one section to another[like from Coldchain to Inventory or so]) but isn't that intended?

I think a more intuitive UX would be to have the filters at the top of the page apply to all of the tabs that appear below them and persist them as you change tabs. 

> It looks expected that we'd be able to choose start-time and end-time differently as they appear as two different fields to enter in the UI; so no complaints on that unless this will be modified again with new view as you described? 🤔

I agree that the date/time pickers are functioning as designed, my issue is with the design 😉
Small UX issues like this don't appear like a big deal on their own, but they can add up to a frustrating user experience if you need to use it on a daily basis. 
Ideally we would have QA input during the design stage but appreciate resources are limited. 
Perhaps though we could explore the idea of doing a 'QA UX review' at various points when major pieces of functionality are due for release? 
Taking a step backwards and really trying to imagine how a user would experience using the product in the real world and highlighting any pain points - it could result in some really valuable feedback and big improvements to the UX. 
What do you think @nisha-dangol ? @ujwalSussol ? @DhanyaHerath ?

**Comment by ujwalSussol** [comment]
@adamdewey  : I just had @nisha-dangol  translate your point to me :-)  ......  It seems you want a discussion before the development is done... This is a good idea but we need to find the time and the people to do it...  :-) 

I think since you deal with the users more than the developers, you may have such/better ideas than most of us. 

The fact that the world has supports Remote working ( Work from home) doesn't really help.... You are not in the same office to bug or stop the developers from doing a bad UX  :-) 

So I am guessing we may have to have a UX phase for issues when form changes are done.  We will discuss this possibility with @DhanyaHerath  during the next DEV meeting.

**Comment by adamdewey** [comment]
Thanks @ujwalSussol, that would be great.

No blame on the developers - sometimes it's hard to see the big picture
until you step back!

In an ideal world QA would be embedded along with the design and
development process but this is quite resource intensive.

One alternative would be to schedule the occasional UX 'QA blitz' - where
enough time is given to the QA team for them to take a step back from
individual GitHub issues and to examine the product (or area of
functionality) holistically to see how it is performing in the 'real world'
and to make recommendations based on their findings.

My real reason for bringing this all up is that I would like to highlight
that UX is an important aspect of a product and it would be fantastic if we
could take it into consideration as part of our wider QA processes.

**Comment by Chris-Petty** [comment]
The UX part of the convo has moved to this issue I think https://github.com/msupply-foundation/open-msupply/issues/3075
