### ISSUE TITLE
Fix android build for temperature-sensor

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2371]
## Is your feature request related to a problem? Please describe 👀
The crate `temperature-sensor` prevents the android build from compiling due to the inclusion of the `jni` crate which is available on the win, linux and mac platforms only.

Try to build android and you get

```
error[E0463]: can't find crate for `jni`
```

## Describe the solution you'd like 🎁
Some solutions:
- find an alternative to the jni crate which has broader platform support
- add some compilation flags, so that the temperature-sensor is not included in the android build

I'm thinking option 2, with the expectation that we won't need to read temperature sensors from the android build. That would be a quicker and safer change than replacing the current library.

**Comment by andreievg** [comment]
Fixed here: https://github.com/openmsupply/temperature-sensor/commit/958c3422b332b516dc9325473d53ab0752c78d54#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L311-L332
