### ISSUE TITLE
Cold chain breach notification 

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2374]
## Is your feature request related to a problem? Please describe 👀
Need a way to alert users that there has been a breach

## Describe the solution you'd like 🎁
Will only be implementing a singular alert for now. Create a notification strip that will pop up at the top of the page when there is a breach and the user can click on `View Details` to see information about the breach... (Redirect to breach list view with filters in place). Breach notifications must stay active until they are acknowledged.

![Screenshot 2023-10-17 at 10 31 12](https://github.com/openmsupply/open-msupply/assets/61820074/12f58d13-d7bc-402b-b6e0-ce998054b56c)

### Moneyworks Jobcode 🧰
OMS:COLC

**Comment by adamdewey** [comment]
Do we need separate github issues to distinguish between notifications for excursions and breaches?

**Comment by roxy-dao** [comment]
> Do we need separate github issues to distinguish between notifications for excursions and breaches?

I thought we weren't doing excursions for MVP...

**Comment by adamdewey** [comment]
> > Do we need separate github issues to distinguish between notifications for excursions and breaches?
> 
> I thought we weren't doing excursions for MVP...

Ah possibly, it's not actually clear from our notes what we decided is it - requirement 6 is talking about both breaches and excurisons -  d'oh

Ok, so let's say this github issue is just for breaches then anyway - maybe let's change the title of the issue to reflect that?

P.s. Breach notification will need to stay visible until they are acknowledged...
