### ISSUE TITLE
Outbound shipment: Clicking Confirm allocated takes to Login page

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#239]
### Steps to reproduce

- Create Outbound shipments
- Add lines including `Placeholder`
- Click on `Confirm Allocated`
- Automatically takes to `Login Page`

#### Branch

- Main

### Video

https://www.dropbox.com/s/h21qo7qf7ug15m1/20220701233737508.mp4?dl=0

**Comment by mark-prins** [comment]
unable to replicate using current develop branch

**Comment by mark-prins** [comment]
Fixed with another PR 😄
