### ISSUE TITLE
Only allow sensor name edit for berlinger type sensors 

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2391]
## Is your feature request related to a problem? Please describe 👀
Carry over from #2286. Currently, user can edit sensor name as long as it exists.

## Describe the solution you'd like 🎁
Only allow user to edit sensor name if the sensor is a berlinger 

### Moneyworks Jobcode 🧰
OMS:COLC

**Comment by adamdewey** [comment]
@roxy-dao @andreievg - perhaps we should actually do 'Only disable sensor name edit for CCA sensors' ?

As it's likely we'll only be able to rename those types of sensors outside of Open mSupply.

Pretty sure any future sensor types we add are unlikely to have naming capabilities.

**Comment by roxy-dao** [comment]
> @roxy-dao @andreievg - perhaps we should actually do 'Only disable sensor name edit for CCA sensors' ?
> 
> As it's likely we'll only be able to rename those types of sensors outside of Open mSupply.
> 
> Pretty sure any future sensor types we add are unlikely to have naming capabilities.

Sure. What are CCA sensors though? 🤔

**Comment by adamdewey** [comment]
@roxy-dao - oh sorry, I mean the sensors that come to Open mSupply via the Cold Chain App (CCA)
