### ISSUE TITLE
Improve programs configuration in mSupply

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2392]
Currently, a mSupply dev version is needed to update programs config. The reason for this is that the current script is that the footrunner window can't hold enough content to include all schemas and the script needs to be executed from a "proper" 4d method. 

Especially during the pilot and the initial phase this would be annoying/error-prone, e.g. we don't want to install the 4D ide on a live central server. For this reason it would be good to have a script that can be run from footrunner.

Possible solutions:
1) One option would be to just increase this editor limit of the footrunner input field (if possible).

2) Another option would be to include an init script in mSupply which loads schemas and other needed information from a directory.
This would have the advantage that you don't have to generate the 4d script anymore. This would also mitigate the problem that we currently don't have a way for a third party to config the programs module through the UI.

3) Create a config UI to manage programs + schemas in mSupply

**Comment by JonnaQuismundo** [comment]
footrunner code closed in mSupply desktop `V7-09-03`
