### ISSUE TITLE
Customer Name to be locked in and non-changeable when you select create shipment

### ISSUE THREAD

**Issue by louisaw123** [openmsupply/open-msupply#2393]
## Is your feature request related to a problem? Please describe 👀

During requisition the customer name is grayed out and you cannot change the customer name. However once you select create shipment the customer name becomes changeable.

## Describe the solution you'd like 🎁

The customer name should not be changeable at any stage

### Describe alternatives you've considered 💭

no

### Additional context 💌

https://github.com/openmsupply/open-msupply/assets/143057869/425688c7-69bf-433e-a5ce-a5f37a5131ea

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.6.0-rc3 exe

### Tests
- [x] Send an internal order to a store B
- [x] Go to store B and supply some units in Requisition
- [x] Create outbound shipment
- [x] See customer name is disabled
