### ISSUE TITLE
Stock take: Reducing stock creates ledger problem

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#240]
### Steps to reproduce

- Choose the item that does not have ledger problem
- Make a Stock take -> Add stock adding line -> Click `Confirm Finalised`
- Wait to sync, Once synced, Stock should be introduced for that item
- Do a next stock take, This time Reduce the stock
- Click `Confirm Finalised` -> Wait to sync
- Once synced to central server, Check that item -> stock
- Do ledger check, Ledger problem will be seen

**Branch:** _Main_

Video:
https://www.dropbox.com/s/cjvxj5qdlcqews8/Ledger%20problem.mp4?dl=0

The problem is: The reduced stock is also treated as a stock In type meaning `transaction type = si` over `type = sc` seeing that, Maybe it was not on the Roster.... ?

**Comment by mark-prins** [comment]
Have watched Bijay recreate the issue with the current develop branch.
The resulting inventory adjustment in mSupply is showing as `Add stock` when stock was reduced by the stocktake.

**Comment by andreievg** [comment]
The idea was to use one inventory adjustment, we should have detailed our decision in KDD. Since we have stock_in and stock_out line type, one inventory adjustment seemed like an appropriate solution. It looks like mSupply is using invoice type rather then line type to determine ledger thought, so that's something that was overlooked. 

Two suggestions:

* Rework mSupply ledger calculation
* Split omSupply stocktake adjustment into reductions and additions

The later is probably less work overall, so perhaps need to go with that (it would also be easier in terms of sync I think, especially for existing sites)

**Comment by andreievg** [comment]
In our discussion today we've agreed that we should split omSupply stocktake adjustment into reduction and addition (same as mSupply)

**Comment by andreievg** [comment]
I used this to check ledger:

```sql
-- POSTGRES
-- DROP VIEW IF EXISTS ledger CASCADE;

-- SQLITE 
DROP VIEW IF EXISTS ledger;

CREATE VIEW ledger AS
SELECT
    CASE 
		WHEN (invoice.type = 'OUTBOUND_SHIPMENT' AND invoice.picked_datetime  IS NULL) 
				OR (invoice.type = 'INBOUND_SHIPMENT' AND invoice.delivered_datetime IS NULL) THEN 0
		ELSE quantity_movement 
	END AS total_quantity_movement,
	CASE 
		WHEN invoice.type = 'INBOUND_SHIPMENT' AND invoice.delivered_datetime IS NULL THEN 0
		ELSE quantity_movement 
	END AS available_quantity_movement,
	stock_line_id,
	invoice_id
FROM invoice_line_stock_movement 
JOIN invoice
	ON invoice_line_stock_movement.invoice_id = invoice.id;

DROP VIEW IF EXISTS ledger_sums;
CREATE VIEW ledger_sums AS
SELECT 
	stock_line_id,
	SUM(total_quantity_movement) - MAX(total_number_of_packs * pack_size) as total_quantity_sum,
	SUM(available_quantity_movement) - MAX(available_number_of_packs * pack_size) as available_quantity_sum
FROM  ledger
JOIN stock_line on stock_line_id = stock_line.id
GROUP BY 1;

DROP VIEW IF EXISTS stock_lines_with_discrepancy;
CREATE VIEW stock_lines_with_discrepancy AS
SELECT stock_line_id, total_quantity_sum, available_quantity_sum  FROM ledger_sums 
WHERE total_quantity_sum != 0 OR available_quantity_sum != 0;

DROP VIEW IF EXISTS stock_lines_with_discrepancy_history;
CREATE VIEW stock_lines_with_discrepancy_history AS
SELECT
	stock_line.id as stock_line_id,
	item.name as item_name,
	available_quantity_movement,
	total_quantity_movement,
	invoice.created_datetime,
	total_number_of_packs * pack_size as final_total_quantity,
	total_quantity_sum AS total_quantity_discrepancy,
	available_number_of_packs * pack_size as final_available_quantity,
	available_quantity_sum AS available_quantity_discrepancy,
	invoice.type,
	invoice.status,
    store_name.name as store_name,
	other_party.name as other_party_name,
	invoice_id
FROM stock_lines_with_discrepancy 
JOIN ledger ON stock_lines_with_discrepancy.stock_line_id = ledger.stock_line_id
LEFT JOIN invoice ON invoice_id = invoice.id
LEFT JOIN store ON invoice.store_id = store.id
LEFT JOIN name AS store_name ON store.name_id = store_name.id
LEFT JOIN name AS other_party ON invoice.name_id = other_party.id
LEFT JOIN stock_line ON stock_lines_with_discrepancy.stock_line_id = stock_line.id
LEFT JOIN item on stock_line.item_id = item.id;

SELECT * FROM stock_lines_with_discrepancy_history
ORDER BY stock_line_id, created_datetime






```
