### ISSUE TITLE
Repository `count()` doesn't take pagination into account

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2414]
For example, an API call with limit 1:

![image](https://github.com/openmsupply/open-msupply/assets/88299195/19f98306-932f-4ed5-ba85-9c7add5f4c77)

returns a total count which is greater than 1:

![image](https://github.com/openmsupply/open-msupply/assets/88299195/186cc3c3-4932-4734-bec5-957f7932586e)

Think we do this wrong in all repositories. Suggested solution:
- [ ] change count functions to look like `pub fn count(&self, pagination: Pagination, filter: Option<TemperatureBreachFilter>) -> Result<i64, RepositoryError> `

**Comment by roxy-dao** [comment]
Should it take pagination into account? 🤔  

The prescription patient search is currently using total count to display a warning message to tell the user to narrow their search

**Comment by clemens-msupply** [comment]
Yes you are right my bad...
