### ISSUE TITLE
Sort column resets to default when loading page

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#265]
Noticed in this PR comment: https://github.com/openmsupply/open-msupply/pull/227#issuecomment-1173267042

The sort column specified in the URL is no longer being maintained on page load, it resets back to the default sort column. (Which of course defeats the whole purpose of storing the sort state in the url)

**Comment by Gwalior-84** [comment]
It's not just when re-loading the page that this happens.  It happens when a placeholder line is opened to allocate stock.

**Comment by adamdewey** [comment]
Example of what we're seeing:
