### ISSUE TITLE
Ignore empty placeholder lines when confirming Outbound Shipments

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#274]
Placeholder lines are created for all items when a user adds a Master List to an Outbound Shipment. 

The user may then only populate details for 1 or 2 items from that list. 

Currently they are then required to manually delete all the remaining placeholder lines before they can proceed. 

Would like to ignore any remaining placeholder lines that have not been edited

(Sorry no screenshots - don't have access to an instance at the mo!)

**Comment by andreievg** [comment]
I think the logic should be:

Trim (delete) unallocated lines with 0 quantity, but keep existing logic if unallocated lines are of quantity above zero (as in show waring and not allow to proceed, have to manually delete there lines)
