### ISSUE TITLE
Ability to hide columns in Outbound Shipments

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#275]
Users want to be able to de-clutter their screen to save real estate. 

Would like to be able to hide unnecessary columns such as Batch, Expiry, Cost etc. 

Sorry, don't have a screenshot right now (but it would be a lot clearer if I did!)

**Comment by andreievg** [comment]
@mark-prins I wonder if the simple option for AV for time being is to just store in app data ?

It looks like it's pretty simple to have an object with 'screen' (i.e. inbound shipment) and 'hide columns' (column identifier) as json configuration for this in Admin panel

**Comment by mark-prins** [comment]
yep - I was thinking to implement client side, using `localStorage`. We could put that in the admin section - though I was thinking a right-click / long-press on the column headers might work?

I'm not expecting this to be a heavily used feature - we have column selection and ordering in mSupply, and when I last asked about it, that wasn't being used by anybody. Which is to say, that we shouldn't spend a lot of time on a gold plated solution, not at this stage anyway.

local storage would persist for each user; it doesn't give the option of setting for a group of users - though it does allow each user to specify which I think is good for this.

**Comment by andreievg** [comment]
> yep - I was thinking to implement client side, using localStorage. We could put that in the admin section - though I was thinking a right-click / long-press on the column headers might work?

Sure, that sounds way better in terms of usability, we would also need a place to re-enable the column.

> I'm not expecting this to be a heavily used feature - we have column selection and ordering in mSupply, and when I last asked about it, that wasn't being used by anybody. Which is to say, that we shouldn't spend a lot of time on a gold plated solution, not at this stage anyway.

> local storage would persist for each user; it doesn't give the option of setting for a group of users - though it does allow each user to specify which I think is good for this.

Does it have to be by 'user' for now, can it be for that 'browser instance' ? (by user seems like it would persist when user changes device).
