### ISSUE TITLE
Serial Numbers

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#298]
We seem to be getting some duplicates, not sure if it's data file issue or sync issue, but it's much easier to reason about numbers (invoice, requisition, stocktake) by just using max number for type. Since we have a hard sync rule about record ownership, this shouldn't be an issue.

- [ ] Remove number table entirely
- [ ] Just use max serial number (by type) when creating new records

**Comment by mark-prins** [comment]
had this yesterday during a demo

**Comment by mark-prins** [comment]
See also #177 - maybe worth looking at while in the same area?

**Comment by clemens-msupply** [comment]
From our meeting discussion I created a basic test case, where the existing number code can generate duplicates in postgres but not in sqlite. (It artificially creates the error case so doesn't say anything of how often it happen in real life)

```rust
   /// Existing number method but with a configurable sleep after read
   fn next_number(
        connection: &StorageConnection,
        r#type: &NumberRowType,
        store_id: &str,
        sleep_after_read_ms: u64,
    ) -> Result<i64, RepositoryError> {
        // Should be done in transaction
        let next_number = connection.transaction_sync(|connection_tx| {
            println!("START");
            let repo = NumberRowRepository::new(&connection_tx);

            let current = repo.find_one_by_type_and_store(r#type, store_id)?;
            println!("EXISTING {:?}", current);
            std::thread::sleep(core::time::Duration::from_millis(sleep_after_read_ms));
            let updated_number_row = match current {
                Some(mut row) => {
                    // update existing counter
                    row.value = row.value + 1;
                    repo.upsert_one(&row)?;
                    row
                }
                None => {
                    // insert new counter
                    let row = NumberRow {
                        id: uuid(),
                        value: 1,
                        r#type: r#type.clone(),
                        store_id: store_id.to_owned(),
                    };
                    repo.upsert_one(&row)?;
                    row
                }
            };
            Ok(updated_number_row.value)
        })?;
        Ok(next_number)
    }

    #[actix_rt::test]
    async fn test_concurrent_numbers() {
        let (_, _, connection_manager, _) = test_db::setup_all(
            "test_concurrent_numbers",
            MockDataInserts::none().names().stores(),
        )
        .await;

        let manager_a = connection_manager.clone();
        let process_a = std::thread::spawn(move || {
            let connection = manager_a.connection().unwrap();
            next_number(&connection, &NumberRowType::Stocktake, "store_a", 300).unwrap()
        });

        let manager_b = connection_manager.clone();
        let process_b = std::thread::spawn(move || {
            let connection = manager_b.connection().unwrap();
            next_number(&connection, &NumberRowType::Stocktake, "store_a", 300).unwrap()
        });

        let a = process_a.join().unwrap();
        let b = process_b.join().unwrap();

        println!("RESULT: a={} b={}", a, b);
        assert!(a != b);
    }
```

**Comment by clemens-msupply** [comment]
And this is a fix using the Postgres only method `for_no_key_update()` (`for_update()` works as well but `for_no_key_update` is enough here)
```rust
pub fn find_one_by_type_and_store(
        &self,
        r#type: &NumberRowType,
        store_id: &str,
    ) -> Result<Option<NumberRow>, RepositoryError> {
        match number_dsl::number
            .for_no_key_update()
            .filter(number_dsl::store_id.eq(store_id))
            .filter(number_dsl::type_.eq(r#type))
            .first(&self.connection.connection)
        {
            Ok(row) => Ok(Some(row)),
            Err(diesel::result::Error::NotFound) => Ok(None),
            Err(error) => Err(RepositoryError::from(error)),
        }
    }
```

**Comment by jmbrunskill** [comment]
> And this is a fix using the Postgres only method `for_no_key_update()` (`for_update()` works as well but `for_no_key_update` is enough here)

Nice work. Didn't think that `for_update()` would be enough!
>FOR UPDATE causes the rows retrieved by the SELECT statement to be locked as though for update. *This prevents them from being locked, modified or deleted by other transactions until the current transaction ends*

It seems that by running a for key update on one select, it applies for the whole transaction, I miss-read that earlier.

**Comment by andreievg** [comment]
Nice, this seems solid, but would mean we need to keep the number table, which is fine with me. I would assume based on postgres docs that within the same transaction the lock doesn't matter and it looks like deadlock resolution is built into postgres, thus it seems the simplest solution

**Comment by jmbrunskill** [comment]
Wouldn't it still work with the invoice table (or whatever entity type we need?) What's special about the number table in this example?

**Comment by andreievg** [comment]
> Wouldn't it still work with the invoice table (or whatever entity type we need?) What's special about the number table in this example?

It locks a row not a table right ? `max` if it did lock a row, would lock the row with the `max` and not the inserted row of invoice

**Comment by jmbrunskill** [comment]
Yes, an the second transaction would potentially get the old max row, which was my original concern.
Maybe number table is good :(

Other option would be back to Advisory Locks

**Comment by mark-prins** [comment]
Does anyone know the status of this one? Is there more work to be done?

**Comment by clemens-msupply** [comment]
If I haven't missed it we still need a postgres featured version of `find_one_by_type_and_store` (maybe rename to `find_for_update` or similiar). Can try to squeeze it in.

For programs we also need a custom number type enum variant and another custom_type string column...

**Comment by jmbrunskill** [comment]
I could probably pick this up if that'd be helpful? I might need quick hand over from you @clemens-msupply

**Comment by mark-prins** [comment]
that'd be super helpful, thanks @jmbrunskill!
