### ISSUE TITLE
Add VSCode launch.json config for FE

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#352]
Add default config to start/debug the client:
``` json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug app (chrome)",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3003",
      "sourceMapPathOverrides": {
        "webpack://@openmsupply-client/host/..": "${workspaceRoot}/packages"
      }
    }
  ]
}
```

@mark-prins or will this clash with existing local configs?

**Comment by mark-prins** [comment]
I think it's ok to have, last time I suggested this I was encouraged to leave it up to individuals to manage their own configs though. Surely a default won't affect user's config?

**Comment by mark-prins** [comment]
I think it's ok to have, last time I suggested this I was encouraged to leave it up to individuals to manage their own configs though. Surely a default won't affect user's config?

**Comment by mark-prins** [comment]
I think it would be helpful to put it in. perhaps if you put the default in a branch, then I can check and see if my config is affected?

**Comment by clemens-msupply** [comment]
I created a PR, think there will be a problem if people start adding their own configs since VSCode only supports one launch.json. However, if nobody does this currently it is not a problem and it might be unlikely that people add other personal configs to the FE launch.json anyway...
