### ISSUE TITLE
Inbound shipment : Duplicated item_lines

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#37]
Raised by Bijay in https://github.com/openmsupply/openmsupply-client/issues/1206

The problem is that mSupply ends up with duplicated `[item_line]` records when the status changes from `Delivered` to `Verified`

To reproduce:

- From Web client, Click on Replenishment -> Inbound Shipment
- Create a new Inbound Shipment clicking New Shipment
- Add at least one batch line
- Confirm by changing status to 'Delivered'
- Sync and then change status to 'Verified'

The issue is that when the second sync takes place ( update status to verified ) the `item_line` updates have an incorrect `record_ID`. This means that these lines are hit: https://github.com/sussol/msupply/blob/master/Project/Sources/Methods/sync_process_sync_record.4dm#L106-L108
and the status changes from `U` to `I` which creates a new `[item_line]` for each `[stock_line]`

I cannot see where in the remote-server database the `[item_line]ID` is being retained. Perhaps it isn't? Regardless, in the update, only the `[transact]` needs updating, so perhaps limit the update to that table?

**Comment by clemens-msupply** [comment]
Yes it looks like a new stock_line is generated on every update:
`service/src/invoice/inbound_shipment/update/generate.rs`
