### ISSUE TITLE
Only save document when it changed

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#391]
Currently its possible to save document that hasn't been changed.
For example, edit a field and revert it manually.
After saving the document the edit will show in the history, however, only metadata has been changed.

To solve this FE could check if the document data object actually differs from the original data.
If no change is detected the save button can be disabled again.
(Alternatively BE could do this and return an error code but this seems more complex to me than doing it on the FE)

**Comment by mark-prins** [comment]
I've used `isEqual` from lodash in #405 to update the `isDirty` flag and we could use the same to reset the isDirty state which would do the above
