### ISSUE TITLE
Patient/program url route

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#400]
- [ ] Simplify url, e.g. `http://localhost:3003/patients/patient1/programs/TestProgram1?doc=patients/patient1/programs/TestProgram1&patientId=patient1&type=TestProgram1` contains redundant information; patientId and program type are already in the path .
- [ ] remove doc query and do an extra query to get the document name (?)

Note, the later requires an extra api call to find the document name in a document details view. The document name is usually already known from the patient/programs/encounter list so this feels a bit wasteful.

**Comment by mark-prins** [comment]
Done with #438
