### ISSUE TITLE
Program status

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#401]
- [x] table and endpoints
- [x] status in list view
- [x] demo control to schedule events

There are can be various patient status for a program:

- died (generic from patient document)
- ~~opted out; patient stopped program (program data)~~
- Transferred to another clinic (program data)
- active at this clinic (default state no need to store it)
- opted out of treatment  (encounter data)
- interruption of treatment, (encounter data)
- missed appointment (calculated from encounter)
- lost to follow up -> patient hasn't shown up for x days and ran out of medicine

While it is required to show one single program status I think we should not use a single status field to store this information. Reasons are:
- status is gathered from multiple documents (patient, program, and encounters)
- status might not be mutually exclusive, e.g missed appointment and transferred to another clinic.

Alternative is to have a (customizable) view that gathered the available information from different sources and displays it as required. For example, a quite generic status control can be added to the program details view which merges all information into a single status field.

### Lost to follow up
This is the most tricky status since it involves custom logic.
Instead of storing a "lost to follow up" status field we can actually introduce a more generic field from which the "lost to follow up" status can be derived.
A suitable field would be a generic `requiredEncounterDate` field which gives the latest date before the patient must come to the clinic, e.g. to get more critical medicine.
This seems reasonably generic to be included into the encounter base type.
For example, `requiredEncounterDate` can be updated by a custom specialized control that knows the logic how to calculate the next required encounter date before medicine runs out.
`requiredEncounterDate` can be queried in a generic way, e.g. "lost to follow up" programs are programs that have encounters with `requiredEncounterDate < now()`.

To bring this idea even further we can associate a list of events (which are not encounter events) with an encounter. For example (2020_08_08 now):
- 2020_11_11: vaccine becomes active/ patient is now immune
- 2020_12_01: next dentist appointment due
- 2022_01_15: lost to follow up

**Comment by richardmoizeau** [comment]
I like your idea of having the LTFU status managed separately. Now that I think about it, Active, Missed Appointment, IIT and LTFU sounds like the three stages of a patient getting away from the program as in: 0. Active > 1. Missed Appointment > 2. IIT > 3. LTFU. All of them are calculated based the latest encounter except missed appointment but maybe we could suggest to Poran to calculate it this way: 
- Active: treatment hasn't run out
- Missed Appointment: treatment ran off
- IIT: treatment ran off for 28 days
- LTFU: treatment ran off for 90 days

What do you think ?
