### ISSUE TITLE
Program data transfer

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#402]
When starting a new program some data may already be stored in a follow up program.
For example, a field from a HIV testing program should automatically be filled when creating a HIV care program.
We need a way to copy data when creating a new document.

Maybe this can be configured through the document registry, e.g. by specifying a list of path that should be auto-populated from compatible source data. For example, if the data of a testing program looks like:
```typescript
{
  value1: "test",
  value2: true,
}
```
and the document registry specifies to copy `value1` the initial version of the follow up program looks like:
``` typescript
{
  value1: "test"
}
```

The same mechanism can be used for encounters where some data can/should be copied from the previous encounter.

**Comment by DhanyaHerath** [comment]
Closed - now handled differently
