### ISSUE TITLE
Program enrolment patient id

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#430]
Add way to add/generate a program id number

Generate number following a certain pattern
- [x] Use first/last x chars from the current store
- [x] Use program counter number
- [x] Allocate number endpoint (stub)

Possible to concatenate above options in any order.

**Comment by richardmoizeau** [comment]
For png they use the 1st 3 characters of the clinic

**Comment by clemens-msupply** [comment]
> For png they use the 1st 3 characters of the clinic

Implemented already in another PR :)
