### ISSUE TITLE
Avoid conflicts in serial number

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#442]
From: 

https://github.com/openmsupply/open-msupply/pull/423

@clemens-msupply 

Just thought a bit about race conditions. Sqlite has a transaction isolation level of SERIALIZABLE which means if a tx succeeds its like a single user accessed the DB -> all good. Postgres has a lower isolation level of READ COMMITTED which can lead to tx anomalies.

Already in the old code there was a bug in next_number. If two transaction run concurrently they could both start with same old number which would result in a number used twice. However, this can be fixed by using SELECT FOR UPDATE (see https://www.postgresql.org/docs/current/explicit-locking.html row level locks).

With the new way to calculate the number I am not sure if this would work, e.g. don't think it helps to lock the row with the highest number because two tx might have a different idea what this row is.

We can increase the isolation level for the particular tx but this would be quite complicated and would require us to handle retries if there is a concurrent number update.

We might need to lock the table in ACCESS EXCLUSIVE mode? I haven't worked with advisory locks but this might be a solution as well. @jmbrunskill do you have some knowledge about it?

@jmbrunskill 

I haven't read all the code or understand the full situation, but here's some thoughts.

1) Databases like postgres provide a `sequence` generator for purposes like this, they are multi user safe so we could generate the next invoice number using this. https://www.postgresql.org/docs/9.1/functions-sequence.html
It looks like postgres allows this sequence to be set to a particular number, so would allow us to say set it to the largest number seen after a sync or something if that's a requirement.

I remember Chris saying something about number-reuse where we fill in numbers that didn't get used? 
I hope this isn't still a requirement with open-mSupply?

2) Could we just use BigSerial for our invoice numbers? I haven't tried it but I'm pretty sure you can insert into a serial column without breaking the serial (e.g. for syncing the records.) Sqlite has autoincrement which would serve a similar purpose. To use this, if you have other records that need that value,  you'll need to get the serial number back from the db after an insert.

3) I agree an Exclusive lock or advisory lock is probably required if we want to ensure two concurrent queries can't get the same 'max' record. 

>  SELECT FOR UPDATE will wait for a concurrent transaction that has run any of those commands on the same row, and will then lock and return the updated row (or no row, if the row was deleted). 
https://www.postgresql.org/docs/current/explicit-locking.html

My read of this suggests both SELECT FOR UPDATE queries would return the same row and then increment to receive the  same number. Advisory locks look like they would probably work here, we could create one for each `next_number` table. It would allow pure read transactions to succeed on the table, but prevent reads that hold that lock from running concurrently.

We'd need to make sure the lock is acquired at the higher level transaction where the record is written, not just in the 'get max number' transaction, otherwise we could end up not fixing the problem at all.

I think a `Sequence` or `Serial` are probably the best solutions unless we have some business rules or constraint that would mean we need something more custom.

@jmbrunskill 

After reading the code a bit more I see the goal is to give a incrementing number for each store and type, so can't just use a serial or auto increment if we need that constraint.

Creating a sequence for each use case it probably plausible, but might be hard to reason about and require raw sql, as not sure how it would map on to diesel. 

@jmbrunskill 

Advisory Locks sound like a good solution for postgres.
I guess we'd need to create a function that we call to set and unset the lock that is a no-op on sqlite. We wouldn't want to have postgres specific code leaking too deeply into the code base.

Pretty sure you can just start the transaction with this
`SELECT pg_advisory_xact_lock(123);` 

This should unlock when the transaction ends, which sounds like the safest way to do this.
We could probably use an enum for the lock_id (123 in this example), so we only lock the related record type (e.g 123 == invoice 124 == requisition).

Alternatively, we could probably have a number service in rust that gets initialised from the database on startup, and ensures non-concurrent access via a mutex, but I think that's unnecessarily complex.

@clemens-msupply 

Or just have one global Mutex serializing any number generation. Would avoid sqlite/postgres differences (and at least for me easier to understand, I am never 100% sure what is locked/safe in Postgres)

@jmbrunskill 

> Or just have one global Mutex serializing any number generation. Would avoid sqlite/postgres differences (and at least for me easier to understand, I am never 100% sure what is locked/safe in Postgres)

Agreed, we'd just need to hold the mutex till the database write is completed, or decouple the number generation from the database `max` query.

What would happen during a sync? I think it will be ok because we shouldn't be generating numbers for our stores on any other site right?

@andreievg 

> What would happen during a sync? I think it will be ok because we shouldn't be generating numbers for our stores on any other site right?

Yep

> Or just have one global Mutex serializing any number generation. Would avoid sqlite/postgres differences (and at least for me easier to understand, I am never 100% sure what is locked/safe in Postgres)

I think this would work nicely as long as we grab mutex before transaction starts, services are kind of meant to be `mixable`, as in transaction can be already ongoing and another service may call a service with connection in a transaction, so I would say it might be hard.

We kind of need a quick mutex increment that can happen within a transaction and will alway give a new number. Potentially we would want to keep number table for this.

### A

* On startup grab max for all types and initialise number provider
* Number provider is shared across all services
* When number is requested, lock and provide next number (incrementing cached next number)

### B

Actually, i can't think of any other way because of these constraints:
* When invoice/requisition service is called it could already be in a transaction
* Can't start write transaction while another write transaction is ongoing in Sqlite

### Suggestion

I think we want to start with benchmark / test since we would need this anyways to validate that our changes work, I think we can look at the threshold of when this problem occurs, and access the urgency of the fix (bench can be done as a test, but it would required having two async runtimes I think).

**Comment by jmbrunskill** [comment]
A Number Generation Service would be fun to write too :)

I still think that sqlite should be ok, as would advisory locks.
If an advisory lock is requested by the same transaction more than once, it translates to a no-op. With SQLite it shouldn't be possible for two transactions to be open at the same time which should prevent this issue if all number generation is done within a transaction. 
Deadlocks would be possible with Advisory locks if different locks were acquired in a different order.

Totally agree writing a test case first is the way to go.

**Comment by clemens-msupply** [comment]
Here is a test (+fix) to reproduce the problem form the old number table:
https://github.com/openmsupply/open-msupply/issues/298#issuecomment-1204588687

**Comment by andreievg** [comment]
My conclusion so far:

* Keep number sequence table, because it sounds like we need it for custom serials (for programs), but would suggest keeping enums and having custom enum with another column for custom type (would need to add new field in mSupply)
* Use ` .for_no_key_update()` behind postgres features branch, as per https://github.com/openmsupply/open-msupply/issues/298#issuecomment-1204588687
* After initialisation, do a check for know number sequences and update if needed (to deal with original issue of demo data number table being out of sync), log as a warning what's been updated.
