### ISSUE TITLE
Encounter details view

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#447]
- [x] encounter info view (in the app bar) (1) 
- [x] create "bubble tab" interface, each bubble is a tab (implemented as a JSONForms tab control) (2) 
- [x] each tab is displayed as a modal (3)

(1) encounter info view
![Image](https://user-images.githubusercontent.com/88299195/182761736-e7232e8e-cf8c-4a84-a69c-ddd1dd96fb20.png)

(2) bubble tab interface
![Image](https://user-images.githubusercontent.com/88299195/182760902-6cb67ca8-96e4-4f0a-ad32-8f00bdddf1bb.png)

(3) tab as modal
![Image](https://user-images.githubusercontent.com/88299195/182761224-61a810fa-6f66-4524-880f-60b9133edd49.png)

**Comment by mark-prins** [comment]
Apologies to whoever has put the mockup together.. and please be aware that this is very subjective feedback! 
I don't like how the 'bubble tab' interface looks. The heavy use of blue, the inconsistent padding and alignment and the iconography. Also the alignment of the inputs in the app bar is bothering me. Could we flag this for a designer to look at?

**Comment by clemens-msupply** [comment]
Think @richardmoizeau meant to only have these mockups as general design ideas and left us some freedom to implement it. But agree the bubbles don't fit very well with the other page designs. To keep going, should we just start with the default tab interface that we already have and then we can swap it out once we have a better design?

**Comment by richardmoizeau** [comment]
Hey ! @mark-prins, you're breaking my amateur UI designer's heart :-) Clemens is right, only suggestions at this stage and absolute freedom on your side to change it and make it better (shape, colours, padding). The main idea was to avoid the tab interface and have a nice little encounter form easy to use when a patient is visiting you.  Are you against the idea of bubbles tab at all ?

**Comment by mark-prins** [comment]
I think we can make the bubbles work ok - the current version is so different to what we have it stands out a bit much (for me!) 

Side note: we might need to chat about how to structure things - seems that this is under an 'encounters' section and not 'patients'?

**Comment by clemens-msupply** [comment]
Yes this is only for the encounter details view so far.

Could use it for program enrolments and patients as well if the form gets too big? which tabs are used can be configured by each customer though...

**Comment by richardmoizeau** [comment]
Yes. If we like it, we could potentially expand this design to other transactions (patient registration, patient enrolment) but so far, only for encounters where we probably need it the most. 

Here are the pros for the bubbles interface as already mentioned during our catch-up: 
- easier to use on a mobile device: facility data capture and review;
- easier to accomodate a large number of sections (we can’t forsee how many sections an encounter may have for all programs/country)
- possibility to look at the data for one section rather having to scroll down in one big form
