### ISSUE TITLE
Extend service context

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#449]
When store id and user id was added to some services, it required adjustment of method to propagate user_id from Graphql down to the service layer.  Some services are still lacking user_id for logging (deletes) as per [this pr](https://github.com/openmsupply/open-msupply/pull/213). Would be good to consolidate all extra information in service context.

This is an example of a typical graphql method:

```
    let user = validate_auth(
        ctx,
        &ResourceAccessRequest {
            resource: Resource::MutateInboundShipment,
            store_id: Some(store_id.to_string()),
        },
    )?;

    let service_provider = ctx.service_provider();
    let service_context = service_provider.context()?;

    map_response(service_provider.invoice_service.delete_inbound_shipment(
```

We can do something like this:

```
let service_context = service_provider.context(store_id, &user.user_id)?;
```

Some services may not need store_id or user_id or store_id and user_id may not be available when service is called. Making store_id/user_id optional would make it too cumbersome to use, I think for now those can just be empty for those cases ?

I think we should be consistent, so existing services would need to be adjusted.

@clemens-msupply thoughts ?

**Comment by andreievg** [comment]
@roxy-dao this should be ready to go, Clemens mentioned that this is ok

**Comment by andreievg** [comment]
After chatting with @roxy-dao, it appears we also can simplify log_entry method:

```
// FROM
    log_entry(
        &ctx.connection,
        &LogRow {
            id: uuid(),
            r#type: LogType::RequisitionCreated,
            user_id: Some(user_id.to_string()),
            store_id: Some(store_id.to_string()),
            record_id: Some(requisition.requisition_row.id.to_string()),
            datetime: requisition.requisition_row.created_datetime,
        },
    )?;
// TO
 log_entry(ctx,  LogType::RequisitionCreated, Some(requisition.requisition_row.id.to_string()), Some(requisition.requisition_row.created_datetime))?;
// If datetime is None calculate
```

A couple of special cases:
* what if store_id is not present, it would be empty string in service context. log_entry should check that and set to None (which is not that standard but would be ok i think @clemens-msupply  ?)
* For login we also don't have user_id in context, i think in this case we can use repository directly

**Comment by clemens-msupply** [comment]
Nice, sounds good to me
