### ISSUE TITLE
Program enrolement form: control to lookup patient by enrolment id

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#460]
Add a control to refer to a related patient:

![Image](https://user-images.githubusercontent.com/88299195/183324060-c7025b29-5fec-401c-88a7-7b05a7ed7154.png)

- [ ] define related patient json schema
- [ ] control should help to look up a patient in the system
- [ ] if related patient is found control looks up if related patient is enroled in a specified program and displays the enrolment id (screenshot)
- [ ] if patient is not found/not in omSupply add option to manually add name and HIV status

**Comment by CarlosNZ** [comment]
@clemens-msupply I just saw this. Would this cover both #1070  and #1071? Looks like it does, so maybe we close those other two?

**Comment by clemens-msupply** [comment]
Yes I think its included

> @clemens-msupply I just saw this. Would this cover both #1070 and #1071? Looks like it does, so maybe we close those other two?

Yes think this issue covers it, the infant problem mentioned in #1070 can probably solved through a different mechanism...

**Comment by DhanyaHerath** [comment]
@clemens-msupply Since @richardmoizeau has put this as low priority, should we move it out of the sprint for now?

**Comment by DhanyaHerath** [comment]
Not part of scope
