### ISSUE TITLE
Programs: Registration Form UI and misc. issues

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#464]
Based on the current version of https://demo-open.msupply.org:88/dashboard: 
- [x] to access the patient list, you should first click on the main menu ("Patients") and then click on the submenu "Patient List" or "List of Patients" or "Patients". All the other menus work the same way. 
- [x] New Patient Modal: Is "Id" for National ID ? 
- [x] Patient Detailed View: title / subtitles and fields are very close to each other, not easy to read / differentiate each section;
- [x] Patient Detailed View: Estimated DOB switch button: if an Age is entered instead of a DOB, then DOB is estimated. It's not up to the user to say whether it is estimated or not. 
- [x] Patient Detailed View: National ID is missing from the Unique Identifiers (should be with a NUIC, manually entered by user, not automatically generated)
- [x] Patient Detailed View: SCTID and label  should not appears in the fields (but good to know that we can have "subtitles" to help the user know what to enter
<img width="448" alt="Screen Shot 2022-08-08 at 7 18 34 PM" src="https://user-images.githubusercontent.com/74992958/183475947-88e04741-ad6a-4fdd-a577-e2975737a8d5.png">

- [x] Patient Detailed View:  I think there's a lot a confusion around patient codes and patient ID. Logic should be similar to existing mSupply:
- When creating a patient, a mSupply Patient **UID** (eg. 4d6de8f7-10b4-4e45-9feb-022e83da3558) is automatically generated (but user don't see it, only for audit purpose I think ?)
- A mSupply patient **code** can be entered by user when creating a new patient (can be manually entered or automatically generated depending on customer preference ? (@mark-prins ?)
- In PNG, we need to assign country-specific UID such as National ID or NUIC

- [ ] UI is not very clear: why is it on 2 different rows (taking a lot of space) ? Not sure if we should number them (eg. "1"), not clear how to remove a field (the minus icon is kind if hidden:
<img width="481" alt="Screen Shot 2022-08-08 at 7 30 21 PM" src="https://user-images.githubusercontent.com/74992958/183478108-696bbe64-86fc-4996-a8ac-b0f8cd370607.png">

**Comment by mark-prins** [comment]
> to access the patient list, you should first click on the main menu ("Patients") and then click on the submenu "Patient List" or "List of Patients" or "Patients". All the other menus work the same way.

There aren't any other pages under the 'patients' area though, which is why we have taken this approach. It would be annoying to have to click `patients` then click `patient list` ( or `patients` then `patients` ) when a single click would have worked!

I suggest returning to this *if* there are other pages to add in to the `patients` section

> It's not up to the user to say whether it is estimated or not.

Yeah, but that's really hard. ( with the JSON forms component each field is a separate concern ) Point taken, and we'll discuss again - just saying that we have spent quite some time already on this, and the manual 'DOB estimated' input is the best compromise we have atm

> patient code: can be manually entered or automatically generated depending on customer preference

Yes that's right. in mSupply you can enable a preference for this to be generated

**Comment by richardmoizeau** [comment]
> There aren't any other pages under the 'patients' area though, which is why we have taken this approach. It would be annoying to have to click `patients` then click `patient list` ( or `patients` then `patients` ) when a single click would have worked!
> 
> I suggest returning to this _if_ there are other pages to add in to the `patients` section

Understood. I think we may have other pages for Patients even within the HIV/TB modules (Medical Staff, Encounters) and of course at a later stage Prescriptions (or Dispensing) and so many others. But I think it would make sense from a functional point of view to access the list of encounters for a particular store. 

> Yeah, but that's really hard. ( with the JSON forms component each field is a separate concern ) Point taken, and we'll discuss again - just saying that we have spent quite some time already on this, and the manual 'DOB estimated' input is the best compromise we have atm

Ok I see. But I think I understand better now. So you can either enter an age (that automatically generates a DOB) or a DOB (that automatically generates an Age) but the switch is only a way to specify that DOB has been estimated. But you don't need the switch to automatically generate Age or DOB, right ? If that's the case, do we need the switch at all ?

**Comment by clemens-msupply** [comment]
The switch was just to store the extra information that the dob is not known, i.e. that your birthday is maybe not on the 1.1. but just an estimate.

**Comment by clemens-msupply** [comment]
The drug allergy array looks different now but I created an issue to improve it anyway [#487](https://github.com/openmsupply/open-msupply/issues/487). Otherwise I think the other issues are more or less resolved.
