### ISSUE TITLE
Number table: custom number column

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#468]
Programs needs some custom numbering. For example, a number for HIV programs.

- [ ] introduce a NumberRowType::Custom enum variant
- [ ] add a `custom_name: Option<String>`
- [ ] extent the number service to get a next number for a custom number

TODO move to another issue:
- [ ] add om_custom_name column to mSupply (4d)
- [ ] sync new column 

Also see: https://github.com/openmsupply/open-msupply/issues/442#issuecomment-1205795906

**Comment by andreievg** [comment]
Just adding om_custom_name would be enough on 4d end. (it should have similar properties to other `om_` columns) 
And on omSup end should be pretty simple

**Comment by jmbrunskill** [comment]
New approach discussed.

We'll keep the enums as they are currently, but add a new Program(String) option.
``
pub enum NumberRowType {
    InboundShipment,
    OutboundShipment,
    InventoryAdjustment,
    RequestRequisition,
    ResponseRequisition,
    Stocktake,
    Program(String),
}
```
and use the display method to handle the custom string for programs
```
impl fmt::Display for NumberRowType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            NumberRowType::InboundShipment => write!(f, "INBOUND_SHIPMENT"),
            NumberRowType::OutboundShipment => write!(f, "OUTBOUND_SHIPMENT"),
            NumberRowType::InventoryAdjustment => write!(f, "INVENTORY_ADJUSTMENT"),
            NumberRowType::RequestRequisition => write!(f, "REQUEST_REQUISITION"),
            NumberRowType::ResponseRequisition => write!(f, "RESPONSE_REQUISITION"),
            NumberRowType::Stocktake => write!(f, "STOCKTAKE"),
            NumberRowType::Program(custom_string) => write!(f, format!("PROGRAM_{}", custom_string),,
        }
    }
}
```

If a new type of custom number needs to be added we can easily add another enum with `Custom(String)` or if it's more defined such as Programs we'll be able to add an enum type for that use case in future.

The code will then use enums, but they won't be enforced by the database (for this table)
