### ISSUE TITLE
Remember sort, filter options when changing tabs

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#469]
Currently, sort options are shared between all tabs. In the worst case the sort option is not applicable in another tab and an error message is shown.

**Comment by mark-prins** [comment]
heh. I commented on the listview PR.. you are a step ahead of me!

**Comment by clemens-msupply** [comment]
Current plan:
- remove sort/filter options from url
- store them in the component for now

(this means options are not remembered after unmounting...)
