### ISSUE TITLE
Fractional number of packs

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#505]
As per discussion: https://github.com/openmsupply/org-issues/discussions/40

Need this to allow existing mSupply sites to be switched to omSupply

Things to consider:
* Auto distribution in outbound shipment (change to distribute in fractions ?)
* Everywhere in UI where number of packs is displayed/enterable (also how to enter a recursive fraction)

**Comment by andreievg** [comment]
This should really be a KDD. Just wanted to summarise our discussion while it's still fresh.

decimal = 0.333333...
fraction = 1/3

Conclusion from our discussion:

* Storing decimals in database may cause loss of precision but is desirable for 'aggregate' database operations (like ledger calculation via SQL would be easier)
* Storing fraction in database avoid precision problems
* Could still restrict number of packs to whole numbers, and split the pack to pack size of one whenever there is a need (instead of decimals), and do something similar during sync. This adds quite a bit of extra complexity.


Proposal number of packs to be represented via 3 columns:

* number_of_packs to be changed to decimal
* update this in UI and just round for now
* for now it's ok for number of packs to be manually and not equal to whole pack size (i.e. pack_size of 10 with quantity 0.37)

Next step, API would return a fraction for number of packs (i.e. two numbers, numerator and denominator), similar, for mutations, numerator and denominator to be set (with denominator being a default of 1). Still store as a decimal in DB, but should be pretty easy to figure out a fraction (i.e. decimal number of packs of 3.6666.. with packsize of 3, would be 11/3, where numerator = 3.6666 * 3 and rounded.

In UI we would allow fractional edits

* Storing fraction in database avoid precision problems

There was a discussion to store three fields:

* number_of_packs_decimal
* number_of_packs_denominator
* number_of_packs_numerator

On second thought I couldn't quite figure out why this would be needed, in the discussion I tried to replicate a rounding [error](https://github.com/openmsupply/org-issues/discussions/40#discussioncomment-2400770) in database, but couldn't. Is there a particular case that would require denominator and numerator to be saved ?

**Comment by roxy-dao** [comment]
Should these fields in the Requisition Line row:
 `pub requested_quantity: i32,
   pub suggested_quantity: i32,
   pub supply_quantity: i32,` also be decimals? 

Supply quantity is being used in a method to calculate the remaining number of packs, so unsure if we want to keep it as a whole number or not. I'm unsure whether these quantities refer to the pack size or number of packs 🤔
