### ISSUE TITLE
Reduce release binary size

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#512]
The release build size is currently > 190Mb.

One part of it are webpack files that are not needed, i.e. stats.json and *.js.map files. When deleting the files from the dist folder the binary size goes done to 75Mb. Still not small but much better.

I tried to exclude these files in `server/src/serve_frontend.rs`:

```rust
#[derive(RustEmbed)]
// Relative to server/Cargo.toml
#[folder = "../../client/packages/host/dist"]
#[exclude = "stats.json"]
#[exclude = "*.js.map"]
struct Asset;
```

but this doesn't work (any idea?).

**Comment by mark-prins** [comment]
there shouldn't be map files in a release build of the front end, would be good to review the f/e build process. 
and the stats.json file! 😆  yes, should exclude that! It is huge and only used by the github bundle size action.

**Comment by clemens-msupply** [comment]
To reduce the size further I tried:
https://github.com/johnthagen/min-sized-rust

|Option| Size|
|----|----|
| base line | 194.4MiB|
|remove stats.json + *.js.map files| 75 MiB|
|strip = "abort"| 52 MiB|
|panic = "abort" + strip = true| 43 MiB|
|panic = "abort" + strip = true + opt-level = "z"| 35MiB|

**Comment by craigdrown** [comment]
Fantastic- thanks @clemens-msupply

**Comment by clemens-msupply** [comment]
Current settings:
```toml
[profile.release]
strip = true
opt-level = "z"
lto = true
```
(35Mb)
I added lto and removed panic = "abort" because I am not sure if the better panic stacktrace would be helpful (would remove another 5Mb)

**Comment by clemens-msupply** [comment]
@mark-prins @andreievg I am very sorry had a typo when creating a feature branch from develop but didn't noticed and I pushed my changes straight into develop :( could you please have a look at my last two commits?

Think we should protect the develop branch against direct pushes?

**Comment by mark-prins** [comment]
😁 I was trying to find the PR which introduced the commits.. and eventually remembered this notification..
I would say, that will affect the bundle size action.. but I am too late to comment on that.

Agree with the change to the rust optimisation, I think what you have is plenty, and there's no need to go further at this stage.

**Comment by andreievg** [comment]
I don't think we should priorities size over speed (both runtime speed and compilation speed), I checked on feature/v5-sync branch, it's 191.4mb but goes to tiny 21.5 mb compressed), is 21.5mb compressed too big for installer ?

**Comment by mark-prins** [comment]
how much compilation time are we talking? can you give me numbers on how much smaller and how much slower, so we can decide? and the runtime speed slowdown? any idea how much?

190MB is too big imho, but with the removal of the embedded stats json file that will already be much smaller. and will also not compress so much!

**Comment by andreievg** [comment]
> how much compilation time are we talking? can you give me numbers on how much smaller and how much slower, so we can decide? and the runtime speed slowdown? any idea how much?

It would be really hard to bench all of this (when i was playing around with actions using `z` would double compilation time, without caching of course), but as a general idea why do we want to sacrifice runtime and compilation speed for size, especially when binary compressions is very good.

> 190MB is too big imho

I don't quite understand tbh, I can't see it being a problem with hard drive space, and for `transport` of installer, 21.mb seems very reasonable

**Comment by clemens-msupply** [comment]
How about just `strip = true` and  `lto = true`? -> no runtime overhead. Think compile time overhead is not important for the release build, is it?

I guess the installer compresses automatically, right?

**Comment by andreievg** [comment]
> How about just strip = true and lto = true? -> no runtime overhead. Think compile time overhead is not important for the release build, is it?

As per our convo, would be good to know `lto = true` affect on compilation time, and there is also `lto = 'thin'` option

**Comment by clemens-msupply** [comment]
Some more dodgy incomplete benchmarks ("?" means I haven't recorded it):
| method | time| size| compressed|
|--|--|--|--|
| base| 6m44s| 75Mb| ?|
| lto=true + strip=true| 13m| ? | ?|
| lto=thin + strip=true| 9m43s|59.8Mb| 16.7Mb|
| strip=true| 6m38s| 60.4Mb| 16.7Mb|

- strip seems good without drawback and small compressed size.
- lto=thin is faster but with almost no size reduction
- lto=true takes twice as long to compile

Ok to go just with strip?
