### ISSUE TITLE
Encounter listview and detail view back navigation

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#548]
1) There are two encounter list views, one for the encounter for a single patient and one for all patients. Think this can be done in a single list view with `patientId: string | undefined` prop.

2) Related when opening an encounter details view from the patient encounter list view and clicking the Encounter breadcrumb link brings you back to the "all patients" encounter view instead of the patient encounter list view. (maybe just have a patient path in the breadcrumb?, e.g. "Encounters / Patient Name / Encounter Id")

**Comment by mark-prins** [comment]
There are some key differences which I think is a good reason to keep the list views separate. We may be able to rationalise though, perhaps generating the columns in a common method.

Differences
- Query parameters : URL parameters are used for the main encounter list
- Columns: Currently the patient view has `Program` and the main view doesn't; the patient view has `startDateTime` and the other has a date and a start time; the patient view doesn't require the `Patient` column
- The data source differs: though the patient view could use the system api if that is extended to have an optional patient id
- the patient view is using a calculated status value, which I think should be applied to both
