### ISSUE TITLE
Follow up program / program transition (e.g. testing -> care)

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#551]
We need a way to do program transition, e.g. testing to care program.

1) An encounter can be configured in such a way that it emits an event once a certain condition is met, e.g. when a patient is tested positive.
2) This event is used in the UI to suggest to practitioner to enroll the patient into a follow up program.

There are multiple reasons why the practitioner should enroll a patient manually into the follow up program instead the patient is enrolled automatically:

- enrolling a patient automatically is technically more challenging and more complicated to configure
- automatic enrolment could go wrong and patient is enrolled even though he shouldn't
- main reason: practitioner is in control and the source of truth (we merely support the practitioner by suggesting the right action)

**Comment by DhanyaHerath** [comment]
Duplicate of https://github.com/openmsupply/open-msupply/issues/854
