### ISSUE TITLE
Document groups (e.g. document permission groups)

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#596]
Especially for document permissions it would be useful to group documents.
For example, instead of specifying user has Query access to ProgramA, EncounterA1, EncounterA2 it would be nicer to have a way to group document types and use these groups to validate document access.

- [ ] add a group column to the document registry
- [ ] validate permissions based on document groups rather than on document types

**Comment by clemens-msupply** [comment]
Probably not needed when using #779

**Comment by DhanyaHerath** [comment]
Hey @clemens-msupply is this issue still needed? Has 779 superceded it, and in that case should we close this issue?

**Comment by clemens-msupply** [comment]
Yes this is obsolete thanks!
