### ISSUE TITLE
Programs > Patient Registration >  Fields "Id" and "Secondary Id" too generic, must be adapted to PNG context

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#632]
Fields "Id" and "Secondary Id:" labels are too generic and should be customised to fit the PNG context (Id = National Health ID / Secondary ID = NUIC) as we cannot expect from users to know beforehand what "id" and "secondary id" stand for. Following discussion with @craigdrown, we should set it as a "Preference" so users can choose what these fields are in the context of their organisation/country. 

A temporary solution would be to use the PNG ID in the meantime:

- "Id" = National Health ID
- "Secondary Id" = NUIC

Where we can see "Id" and "Secondary id" (not exhaustive):

- Patient Registration > Check for Duplicate Modal
- Patient Registration > Patient Detailed View > Headers ("Patient ID")
- Patient Registration > List of Patients > Column headers

![Screen Shot 2022-09-21 at 10 42 39 AM](https://user-images.githubusercontent.com/74992958/191377909-cc3b79d7-7e21-42af-8442-25513c3e7fe0.png)
![Screen Shot 2022-09-21 at 10 42 18 AM](https://user-images.githubusercontent.com/74992958/191377913-75786a91-5ead-4c69-936d-e28634f4635d.png)
![Screen Shot 2022-09-21 at 10 44 04 AM](https://user-images.githubusercontent.com/74992958/191377897-f36e0e94-aba2-4a0f-a36b-61add76fb530.png)

**Comment by CarlosNZ** [comment]
We should be able to define this in the JSONschema, right? 

Speaking of which, we should probably start keeping a library of json/ui schemas somewhere. Not sure where, but something to bring up in next meeting, perhaps?
