### ISSUE TITLE
Programs/Enrolment/HIV Care and Treatment: multiple issues 1

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#644]
- [x] confirmed code and name = code: `ART` / name: `HIV Care and Treatment`

![Screen Shot 2022-09-23 at 3 26 21 PM](https://user-images.githubusercontent.com/74992958/191886796-06579396-4336-430e-8a7d-a9385b00beaf.png)

####  `Enrolment Datetime`: 
- [x] no need to capture the time of enrolment
- [x] rename  to `Enrolment date`
Issue to only display date in UI: #835 

####  `Hiv Confirmation Date`: 
- [x] rename to `HIV Confirmation Date`

####  `Hiv Test Type Date`: 
- [x] rename to `HIV Test Type`

#### `Partner Hiv Status`:
- [x] to be renamed to `Partner HIV Status`
- [x] missing value: `Not done`

#### `Mother`:
- [ ] only when patient is an infant (Poruan checking the age threshold, most likely expressed in months. We are considering creating a specific program for infants)
- [ ] the objective is to link the patient record to the mother's patient record. Would it be possible to select mother's patient ID from a dropdown ?

#### `Treatment Supporter`:
- [ ] should be able to specify if TS is same as `Next of Kin` from the registration details (avoid unnecessary data entry). That would require to pull NoK data from the registration form into the enrolment if that checkbox is ticked. 
- [ ] TS can be different from NoK cause sometimes patient do not want to share health data with their family

#### `Referral Details` section is missing from the enrolment form:
- [x] `Referred from`: ["HCT/Other PICT" , "Index" , "Post-Natal" , "TB" , "Community" , "Transfer-In" , "STI" , "ANC" , "Exposed-Infant/Well Baby Clinic" , "In-Patient" , "Labour"]
- [x] `Prior ART ` should be part of this section

#### `Note`:
- [x] Add the possibility to write a note in the Enrolment form (Issue: #838)

**Comment by CarlosNZ** [comment]
> * missing value: `Not done`

Do you mean the "HIV STATUS" type should have values: "Positive", "Negative", "Unknown", "Not Done" ?

**Comment by clemens-msupply** [comment]
> > * missing value: `Not done`
> 
> Do you mean the "HIV STATUS" type should have values: "Positive", "Negative", "Unknown", "Not Done" ?
> 
> Just wondering if "Partner HIV Status" should be a different type to "HIV Status".

We also have an option to clear the enum know, would this already enough? the we don't need another option but the user can just clear it? Might be slightly different meaning though; "Not recorded" vs "Not Done"

**Comment by richardmoizeau** [comment]
> > * missing value: `Not done`
> 
> Do you mean the "HIV STATUS" type should have values: "Positive", "Negative", "Unknown", "Not Done" ?

Yes that's it.  

> Just wondering if "Partner HIV Status" should be a different type to "HIV Status".

Only three values for Partner 'HIV' Status indeed:

![Screen Shot 2022-11-23 at 11 13 05 AM](https://user-images.githubusercontent.com/74992958/203431964-4a1dcbe8-74bc-4e60-8a0b-6666b9b6c6c9.png)

**Comment by CarlosNZ** [comment]
> > > * missing value: `Not done`
> > 
> > 
> > Do you mean the "HIV STATUS" type should have values: "Positive", "Negative", "Unknown", "Not Done" ?
> 
> Yes that's it.
> 
> > Just wondering if "Partner HIV Status" should be a different type to "HIV Status".
> 
> Only three values for Partner 'HIV' Status indeed:

Sorry @richardmoizeau , slightly confused there. Those two responses seem contradictory. Your original request suggested we should add "Not Done" as an option for the Partner status. (Feel free to clarify in person if that's easier)

**Comment by CarlosNZ** [comment]
> * no need to capture the time of enrolment

It seems the "enrolmentDateTime" field is well and truly baked into many areas of the app. It's probably best to leave it as a date-time under the hood but just display it in the UI as a date only. @clemens-msupply is this something we can do by tweaking the "Date" json form renderer? (I'm thinking that would be the simplest way, but perhaps there is another?)

**Comment by CarlosNZ** [comment]
> * the objective is to link the patient record to the mother's patient record. Would it be possible to select mother's patient ID from a dropdown ?

It'd be good to have a chat about how we can implement arbitrary complex logic like this in configurations. I have a suggestion (basically a modification of the Conforma solution), but it'd be good to discuss it before starting down this path. No rush, but let's have a chat before starting on this issue, @clemens-msupply ?

**Comment by clemens-msupply** [comment]
> > * the objective is to link the patient record to the mother's patient record. Would it be possible to select mother's patient ID from a dropdown ?
> 
> > * should be able to specify if TS is same as Next of Kin from the registration details (avoid unnecessary data entry). That would require to pull NoK data from the registration form into the enrolment if that checkbox is ticked
> 
> It'd be good to have a chat about how we can implement arbitrary complex logic like this in configurations. I have a suggestion (basically a modification of the Conforma solution), but it'd be good to discuss it before starting down this path. No rush, but let's have a chat before starting on these issues, @clemens-msupply ?

@CarlosNZ For this specific cases I thought about a special "contact input" control which can get suggestions from multiple sources. Happy to chat about it!

**Comment by clemens-msupply** [comment]
> > * [x]   confirmed code and name = code: `ART` / name: `HIV Care and Treatment`
> 
> I think the old name is still showing when you look at the Program tab in the Patient Detailed View:
>

The column actually only shows the internal program id. But should show the human readable program name (which is available in the document registry).

**Comment by CarlosNZ** [comment]
Closing -- have made new issues for the two remaining items:
- #1070 
- #1071
