### ISSUE TITLE
Programs > HIV Care & Treatment > Encounter > Physical Exam section: units and formats

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#645]
Physical Exam: Measurements should indicate the units: 
- Height in m / format "0.00"
- MUAC in cm / format "0.00"
- Weight in kg / format "0.00"
- BP in mmHg / format: "000/00"

![Screen Shot 2022-09-23 at 3 34 15 PM](https://user-images.githubusercontent.com/74992958/191887456-2baf452d-5cf8-4e09-8cd6-616ba2e6b285.png)

**Comment by richardmoizeau** [comment]
BP in mmHg / format: "000/000" instead of "000/00" - my apologies !

**Comment by clemens-msupply** [comment]
This has been done in another PR....
