### ISSUE TITLE
Outbound Shipment Allocation

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#648]
(Might be a discussion instead 🤔 )

Current omSupply allocates outbound shipments by whole pack sizes and thus goes to the next available stock line if the previous stock line has a fractional number of packs if the allocated packs are of different pack sizes as shown below. 

<img width="876" alt="Screen Shot 2022-09-27 at 2 11 07 PM" src="https://user-images.githubusercontent.com/61820074/192408386-a903b328-bc73-40f0-ae31-a79d10ea16d2.png">

Should packs be allocated by FEFO with fractional no of packs (like in mSupply)? E.g. 650 units in packs of any = 12 packs of 50 and 0.5 of 100. Which might possibly lead to the edge case that Andrei talked about in https://github.com/openmsupply/org-issues/discussions/40#discussion-3945986 (Image 3). Also see https://github.com/openmsupply/open-msupply/pull/642#discussion_r980647439

Should users be allowed to enter fractional number of packs themselves? Or should the packs be auto-allocated and input disabled? And if the packs are being auto-allocated by fractions, then should the user be warned that they are allocating a fraction of xx pack? 

Richard brought up possibly implementing re-packing?

**Comment by mark-prins** [comment]
small clarification: the allocation is FEFO already, but with the difference that it does not split packs

I would prefer to retain allocation of whole packs. later, maybe, we could add in a setting which allows pack splitting?

Currently we haven't allowed users to enter fractional packs on this screen either.. if they want to manually do so. I'm fine with that - decimals are confusing when talking about packs. Would prefer to explore what Andrei has been proposing re fractional packs instead ( not allowing any old decimal - you can only go down to a base level of 1 unit. e.g. if the pack size is 3, you can only enter multiples of 1/3 )

and repacks are a necessary feature.. we will have to add that in. It's related, but a separate area, I think.

**Comment by DhanyaHerath** [comment]
@mark-prins @roxy-dao It seems like the decision for this issue has been made - does it need writing down anywhere as a decision so we can look back at it later? Should we close this issue?

**Comment by mark-prins** [comment]
Thanks @DhanyaHerath - will add to the upcoming discussion of this window
