### ISSUE TITLE
Desktop client "local server" icon doesn't seem to render

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#651]
On opening the desktop client on my local machine where I had installed the server, I noticed that it said there will be a little 🏠 emoji next the listed server that is on the local machine. It seems to not have detected that it was local though:

![image](https://user-images.githubusercontent.com/7684221/192660088-0940c92a-3b10-4226-bbfe-b00fd8553a7f.png)

Potentially a different issue: after clicking the client only showed a blank window. Never loaded anything. Perhaps it's because I hadn't started server sync initialisation via browser client yet?

Tangent issue idea: If can't already, perhaps good if users can name the server and show that in the server list.

**Comment by mark-prins** [comment]
This was a problem because the code is testing for `127.0.0.1` but, as you can see, the actual IP is returned by the server.
We would need a more comprehensive test to determine if a server is local

**Comment by mark-prins** [comment]
unable to replicate - tested on mac and windows.
the local server check is using the package `ip` to get the local ip address. 
Have looked at the server name, and will leave that for now. The current name is hardcoded in the server.. something to consider for later.
