### ISSUE TITLE
Programs/Patient Registration: Misc

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#655]
Note: we are currently working with the local team to confirm the patient registration form layout (what section and what fields). Here is the [suggested one](https://docs.google.com/spreadsheets/d/17rON9mmUjPQzYbPlaTr1IYFJ68YowvsqX7hNx4n000E/edit#gid=29084700&range=A1) (not confirmed yet). 

- [x] `Gender` should have the following values (as per HPDB): `Male`, `Female` and `Transgender` (related https://github.com/openmsupply/open-msupply/issues/370)
- [x] `Birth Province` and `Birth District` are dynamic dependent dropdown fields (eg. you should be only able to select districts that are within the province you picked). Logically, `Province` should appear before `District`. [List of province/district](https://docs.google.com/spreadsheets/d/17rON9mmUjPQzYbPlaTr1IYFJ68YowvsqX7hNx4n000E/edit#gid=570522303&range=A1).
- [x] `National Health ID`:  data validation: 10 numeric characters
- [x] `Education Status` = dropdown field ([list of values](https://docs.google.com/spreadsheets/d/17rON9mmUjPQzYbPlaTr1IYFJ68YowvsqX7hNx4n000E/edit#gid=2069147995&range=A1))
- [x] `Occupation` = dropdown field ([list of values](https://docs.google.com/spreadsheets/d/17rON9mmUjPQzYbPlaTr1IYFJ68YowvsqX7hNx4n000E/edit#gid=242545937&range=A1))
- [x] A patient keeps the same `NUIC`, it should not change even if there is a change in one of the key components (eg. a woman get married and has to change her last name)
- [x] `Mother` to be removed from patient registration. Only relevant for HIV programs enrolment form, to link an infant patient to the record of its mother. 
- [x] `Birth Order`: format directions not clear enough (suggestion: "Format: 01, 02, 03...")
![image](https://user-images.githubusercontent.com/74992958/193154651-ddd5c3fb-de04-4e7c-8faa-c9426f8cdbb0.png)

**Comment by clemens-msupply** [comment]
@mark-prins for the Birth Province and Birth District point I was thinking about a similar solution as we did with date of birth. Do you know a good standard component for this? otherwise I would just create a control with two input fields making it effectively look like it looks now.

**Comment by mark-prins** [comment]
in the other json forms component there was the concept of dependencies which is configured in the ui schema. I thought that this one had the same? In which case just standard enums / select components, with the districts shown depending on which province is selected would work.

**Comment by richardmoizeau** [comment]
I see that below item is marked as done but I can still see the Mother information on the registration form. Thanks. 

Mother to be removed from patient registration. Only relevant for HIV programs enrolment form, to link an infant patient to the record of its mother.

**Comment by clemens-msupply** [comment]
The demo server hasn't been update yet...

**Comment by CarlosNZ** [comment]
> * A patient keeps the same `NUIC`, it should not change even if there is a change in one of the key components (eg. a woman get married and has to change her last name)

Just thinking about how to best implement this. We obviously want to be able to regenerate the value any time during the first data entry, but never change it again after it's been saved for the first time. Is that correct?

And should we just restrict this in the UI by adding some kind of "is data saved?" check to the idGenerator component, @clemens-msupply?

**Comment by richardmoizeau** [comment]
I think this is a good idea !

**Comment by clemens-msupply** [comment]
> > * A patient keeps the same `NUIC`, it should not change even if there is a change in one of the key components (eg. a woman get married and has to change her last name)
> 
> Just thinking about how to best implement this. We obviously want to be able to regenerate the value any time during the first data entry, but never change it again after it's been saved for the first time. Is that correct?
> 
> And should we just restrict this in the UI by adding some kind of "is data saved?" check to the idGenerator component, @clemens-msupply?
 
We asked client about it previously, it should be enough to just have a modal to ask the user if the id should be regenerated, e.g. "Regenerate? The ID should not change even if there are change to the patient data". The reason is that a patient could be created, a wrong id generated and the patient then be saved. The user might then want to fix the ID immediately (still in the process to create the patient). Thus the ID should be editable even when data has been saved.

Sorry didn't update this issue...

**Comment by CarlosNZ** [comment]
Closing, as all listed items are now ticked off.
