### ISSUE TITLE
Settings API

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#657]
Currently the f/e has the option to customise the logo and theme. The values are saved only in local storage, so are specific to the browser in which they are saved.

Ideally, the values will be persisted to the database and shared across the entire instance. 
Further question: should they be per site or per store?

The values could be stored as a string value in the `[key_value_store]` and perhaps that's enough for now.
There's a `[pref]` (I'm ignoring the `[pref_blobl]`!) in mSupply - perhaps we need a pref or settings table though I see no mention of migrating the table in the `omSupply table-field changes master` spreadsheet. Just that the `[pref]` is complicated with regard to sync.

**Comment by andreievg** [comment]
Just remembered the columns selection, it's in app data would it also be a preference for user/store ?
