### ISSUE TITLE
Merge programs feature into develop

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#658]
What it says in the title: taking into consideration

- the effect on sync
- whether the dispensing section should be displayed for non-programs users, and how this is en/disabled
- database initialisation for programs ( currently users and documents are added, and these should only come from sync I think )

**Comment by DhanyaHerath** [comment]
Prerequisite: https://github.com/openmsupply/open-msupply/issues/1048

**Comment by mark-prins** [comment]
Good to do - though after discussion we're thinking not immediately
