### ISSUE TITLE
Log transfer operations

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#660]
Using the same logging that is done in services for shipments/requisition, add logs for insert, update, deletes.
We would like to show in UI that it was a system user that did the operation.

### A - Created on central

Similar to how we do name for inventory adjustment. This use will need to be created on central server when new data files is created or on migration. 

**pros**
* Consistent with how we do inventory adjustments etc

**cons**
* It would have to be a special user that no one can log into and that is not editable 
* Changes would need to be done on central

### B - Hard coded system user

Although for (A) some hard coding is done (the code of system user), with B user is completely hard coded. In service layer, when `code` or `id` of user is `system` then return a hard coded UserRow.

**pros**
* No cons of A
* Fast to implement and allows to transition to A

**cons**
* No pros of A

`consideration` -> when logging user in, and user is not found on central, when we confirm user/password matches locally we should filter out users with no password (which system user will have)

## System user decision

@andreievg votes for B

### Extra

This is from a placeholder point from the epic: 

Should system user be used/displayed for transfer creation/edit ? And at the same time we want to make sure we log operations like we do in services https://github.com/openmsupply/open-msupply/pull/581#discussion_r971429435 https://github.com/openmsupply/open-msupply/pull/581#discussion_r971430336

**Comment by mark-prins** [comment]
Under **B** I think this should be A in a couple of spots?

**pros**
* No cons of _A_
* Fast to implement and allows to transition to _A_

**cons**
* No pros of _A_

**Comment by andreievg** [comment]
Oops, thank @mark-prins
