### ISSUE TITLE
Programs/Enrolment/HIV Testing and Counselling: multiple issues 1

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#667]
- [ ] Code = HTC / Label = HIV Testing and Counselling

#### Enrolment Datetime: 
- [ ] no need to capture the enrolment time
- [ ] rename to Enrolment Date
- [ ] Should be able to manually enter a date (the date can be in the past)

#### Enrolment Patient ID: 
- [x] not required for HIV Testing and Counselling

#### Status:
- [x] not required for general population (note: could be required for high risk group but we could consider creating a specific program for them)

#### Partner Hiv Status:
- [x] rename to Partner HIV Status
- [x] missing value: Not Done

#### Mother
- [x] to be removed from HTC enrolment form

**Comment by roxy-dao** [comment]
Closing. Mostly done and the enrolment date is mentioned in #1151
