### ISSUE TITLE
Programs/Enrolment Form/All program: rename OK button to Save

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#668]

**Comment by clemens-msupply** [comment]
I might be mistaken but I think @mark-prins had a reason to call it "OK"?

**Comment by richardmoizeau** [comment]
@mark-prins ?

I think when you are enrolling a patient, you have already created it so the only thing you're doing now is saving a new documents for that patient. Save is probably more appropriate when talking about a document ? 

For reference: 

![Screen Shot 2023-01-20 at 10 06 33 AM](https://user-images.githubusercontent.com/74992958/213559759-932442f5-f83d-4221-8a1e-9fe75e4974b3.png)

**Comment by mark-prins** [comment]
The only reason I could think of is 'consistency' 
Don't recall if there was a specific reason for this one. I rather like having action buttons say what they do.. and having `Save` `Cancel` `Create` ( or possibly `Add` ) - though there's the potential for confusing folk if the button says 'Create' sometimes and 'Save' other times 🤷 

Elsewhere in the app we have `Ok` consistently on modals when editing or adding things, and we appear to have gone a little rogue in programs. I'd like the button labels to be consistent throughout, whichever approach we end up taking.

**Comment by clemens-msupply** [comment]
@roxy-dao there were some recent change to the dialog, think its called "Save" now, right? We might have to go through the creation process to see if "Save" makes sense everywhere. Otherwise, I think we can close this issue.

**Comment by roxy-dao** [comment]
> @roxy-dao there were some recent change to the dialog, think its called "Save" now, right? We might have to go through the creation process to see if "Save" makes sense everywhere. Otherwise, I think we can close this issue.

It's still called okay... just have an option to change the text to `Save` instead of okay

**Comment by clemens-msupply** [comment]
Ah ok thanks, we introduced a 'create' variant and I removed it in the recent programs merge...

I will leave this issue open to review this again, i.e. if we should reintroduce the 'create' variant.

**Comment by roxy-dao** [comment]
Only place left with `Ok & Next` is in Patient creation and makes sense to have it there since nothing has been saved yet. Closing as complete.
