### ISSUE TITLE
'Unable to sync' error while synchronisation still in progress (setting up new client Android)

### ISSUE THREAD

**Issue by jmbrunskill** [openmsupply/open-msupply#669]
With mSupply Server running on a laptop and open-msupplyclient (phone hotspot) setting up a Lenovo Tablet

After entering sync settings the ui waits for a bit then returns an error 'Unable to sync. Please check your settings'.
However on the server side we can see that synchronisation is still in progress.

This is with Approximately 50,000 sync records via a cellphone hotspot (but local connection)

After waiting for the sync to finish records appear to be available.

**Expected Behaviour**
- Ideal: Sync Progress Bar
- Ok: Some kind of ui saying 'still syncing' instead of error message

**Comment by andreievg** [comment]
This should be done with: https://github.com/openmsupply/open-msupply/pull/640, which will be merged with https://github.com/openmsupply/open-msupply/pull/679
