### ISSUE TITLE
Programs/Encounters: ability to navigate to previous encounters from the current/new encounter

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#674]
In the HPDB, when creating a new encounter, we have the possibility to navigate to the previous encounters of the selected patient (see video attached) 

https://user-images.githubusercontent.com/74992958/193173126-8d6d3caf-f8fc-48df-b5d7-fc28b2872b27.mov

We would need to reproduce this in the Encounter interface if possible. 

Here are 2 options from a UI perspective: 

- Option 1: previous encounter can be accessed from the details panel as one of the sections (last encounters). Possibility to limit the number of previous encounters (eg. last 5 encounters). User clicks on one of them and it opens in a new window. 

![Screen Shot 2022-09-30 at 3 36 07 PM](https://user-images.githubusercontent.com/74992958/193178025-78543139-e73f-4998-b5b5-ec984d0c8281.png)

- Option 2: we add a `previous` button to navigate to the last encounter for this patient. we also add a `next` when we're looking at a previous encounter. It would probably mean that we need to automatically save the changes before going to the next encounter ?

![Screen Shot 2022-09-30 at 3 39 57 PM](https://user-images.githubusercontent.com/74992958/193178866-9f258765-6bc4-44af-9605-0cb25e6e2f47.png)

![Screen Shot 2022-09-30 at 3 40 21 PM](https://user-images.githubusercontent.com/74992958/193178854-059a7996-7c8b-4d21-9859-08d732d7be21.png)

**Comment by DhanyaHerath** [comment]
Done!
