### ISSUE TITLE
open-mSupply reverts to synchronisation setup screen when network is disconnected.

### ISSUE THREAD

**Issue by jmbrunskill** [openmsupply/open-msupply#675]
After network connection is dropped open-mSupply Android App reverts to synchronisation settings screen (after displaying an authorisation error)

**Steps to Reproduce**
- Setup application to sync to a mSupply server
- Login with valid user account
- Disconnect WIFI
- Restart the application in Android
- Should be able to login again (not see sync settings screen)

**Comment by andreievg** [comment]
This should be done with: https://github.com/openmsupply/open-msupply/pull/640, which will be merged with https://github.com/openmsupply/open-msupply/pull/679

**Comment by mark-prins** [comment]
tested in v1.01 and is working - thanks @andreievg
