### ISSUE TITLE
HIV Testing and Counselling > Encounter form: forms should take the HTC client intake form for the basis

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#680]
[HTC client intake form](https://docs.google.com/document/d/1-dHq-scMDgHec9gd8k8pDFGoW3RA_J0H/edit)

Most of the fields in Section A - Demographics data are already captured at Patient Registration or Enrolment level. Checking with local team for the following: Partner's HIV Status, Referred from, was client referred by a peer educator ?

Note: numbering is just to state the ordering and dependencies, no need to number each property. 

**For dependencies, would be nice to have a dynamic form (eg. if I have entered "NO" for "Have you been tested for HIV before" then we don't need the dependent property "If yes, what date ? Test Result ?".** 

### Risk Behaviour:

- [x] 1. Have you been tested for HIV before and know your result ? Yes or No (only for tests not captured in mSupply, otherwise we know if patient has already been tested, we can just look at previous encounters)
- [x] 1a If yes, what date ? Test result ? 
- [x] 2. Have you ever experienced any of the following in the past 12 months (refer to the [form](https://docs.google.com/document/d/1-dHq-scMDgHec9gd8k8pDFGoW3RA_J0H/edit))
- [x] 3. How many sexual partners have you had in the last 6 months ? Males and Females
- [x] 4. Risk Group (preferred to Target Population): FSW, MSW, MSM, TG, HR, GP
- [x] 5. GBV Screening outcome: positive, negative, not done, declined
- [x] 5a If GBV screening = positive, referred for GBV services ? Yes or No

### Informed Consent:

- [x] Was pre-test counselling done ? Yes or No
- [x] Was the consent form signed ? Yes or No

note: Could we add the possibility to upload the form ? Will suggest it to Poruan. 

### HIV Testing:

- [x] 1. Date of HIV test done: 
- [x] 2. Confirmed HIV test result: Negative or Positive (note: test results are provided immediately, like RAT for Covid)
- [x] 2a. Did you refer the patient for ART services ?
- [x] 2aa. Where  ? This facility or Another Facility
- [x] 2aaa. if another facility, name of the facility (= list of ART clinics = stores ?)
- [x] 2b. Was the client escorted ? Yes or no
- [x] 3. Post-test counselling done ? Yes or No
- [x] 4. If serodiscordant, was couple counselling provided ? Yes, No, N/A
- [x] 5. Was client screened and referred for other services ? Yes or NO
- [x] 5a. If yes, which one(s): TB, STI, GBV, PEP, Other
- [x] 5aa. If other, specify: 
- [x] 6. Where condoms and/or lubricants offered to the client ? Yes or No
- [x] 6a. If yes number of males condoms provided ? number of female condoms provided ? Lubricants ?
- [x] 8. Did you conduct condom demonstration ? Yes or no

**Comment by clemens-msupply** [comment]
> note: Could we add the possibility to upload the form ? Will suggest it to Poruan.

file upload needs some more implementation design... @jmbrunskill or did we made a decision how to best do it?

**Comment by jmbrunskill** [comment]
I don't think there's a design done for omSupply.

Code wise I have an implementation you could base it on here: https://github.com/openmsupply/health-supply-hub/pull/286
Happy for any review comments.

For health-supply-hub we don't have to consider sync though, we just need to make sure the files get backed up from the one central server. 
We probably need to extend this design to include any constraints around android, and how to backup and/or make files available via some kind of sync process.
I remember a discussion was started around this, but couldn't easily find a link to it.

**Comment by clemens-msupply** [comment]
I combined 1. and 1a in only two controls (from the description it sounded like three):


![Image](https://user-images.githubusercontent.com/88299195/216472717-3008c952-8b16-4a0c-bb6d-62cfdf521a58.png)

**Comment by clemens-msupply** [comment]
This issue mentioned "referred from" I believe this is not part of this issue, so will close now...
