### ISSUE TITLE
ET Feedback::misc issues

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#681]
A selection of issues to look at, which hopefully are small enough to combine in a single issue. If you find something becomes a rabbit hole, create a new issue for it and take out of here. 

<img src="https://media1.giphy.com/media/XFpCAWSfTwXh2uSEk2/giphy.gif"/>

### General
- [x] Clicking on an item in the `View stock` list could take you to that item
- [x] The item detail tab view isn't using the correct component ( it has a space under the tabs )
- [ ] ~Can we add the item name into the breadcrumb please, in place of the ID~
- [x] On the dashboard ‘Expiring Soon’ and ‘Expired’ are showing the same number. Needs checking..
- [x] Internal orders::add from master list - add a spinner / progress indicator. It can take a while if there are a lot of items

### Android
- [x] When you accidentally press the back button and the app exits, when it re-opens we get an authentication error and have to login again. ( [related issue](https://github.com/openmsupply/open-msupply/issues/675) )

### Stocktakes
- [x] The location list drop down in stock take isn’t working, they can’t re-assign a location for stock lines
- [ ] New stocktake using select items. Loads stocktake but there are no items on it?
- [ ] keyboard enter/next doesn’t move from “counted # of packs” to expiry and not sure if it should show year/month dialog or give mm/yy number input - needs user feedback
- [x] Add item shows no items by default. Users were immediately confused by this and thought it was broken, had to tell them to type something before options would show.. ( auto open, as per OS etc? )

**Comment by andreievg** [comment]
> When you accidentally press the back button and the app exits, when it re-opens we get an authentication error and have to login again. ( https://github.com/openmsupply/open-msupply/issues/675 )

Another related issue: https://www.google.com/url?q=https://github.com/openmsupply/health-supply-hub/issues/50&sa=D&source=docs&ust=1664764296117846&usg=AOvVaw2oyyU1HUltIOg3s9oKO7sh

**Comment by mark-prins** [comment]
>  New stocktake using select items. Loads stocktake but there are no items on it?

Cannot replicate this one

**Comment by mark-prins** [comment]
> keyboard enter/next doesn’t move from “counted # of packs” to expiry and not sure if it should show year/month dialog or give mm/yy number input 

I don't see anything to address here. Tabbing works fine, as per the other fields. The expiry date entry works for me. you can also press space and activate the date selection popup 🤷
