### ISSUE TITLE
Programs:Patient Registration Form layout

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#682]
== ON HOLD, waiting for PNG's approval ==

As PNG stakeholders, patient registration form should be as close as possible to the [ART CT Booklet](https://drive.google.com/file/d/176Cbv1AhHmJbZFgMKOJUOx6BFWs1aL_r/view?usp=sharing). Data entry will be carried out afterwards,  based on the paper form so would be easier if patient registration layout in mSupply is similar to the booklet. 

Suggested Layout (in the right order)

| Patient Identity | 
| --------------- | 
| First Name(s) | 
| Last Name | 
| National Health ID |
| NUIC |
| Sex |
| Date of Birth |
| Age |
| Birth Province |
| Birth District |
| Birth Order |
| Handedness |

| Address and Contact Details |
| --------------- | 
| Address 1 | 
| Address 2 |
| Province |
| District |
| Phone |
| Mobile |
| Email | 

| Next of Kin |
| --------------- | 
| Relationship |
| First Name |
| Last Name |
| Phone |
| Mobile |
| Email |

| Demographics |
| --------------- | 
| Marital Status | 
| Occupation |
| Education Status |

**Comment by clemens-msupply** [comment]
@richardmoizeau we check these, right?
For drug allergies, they are not only HIV specific, right? or should they be moved to the care program?

**Comment by richardmoizeau** [comment]
Sorry yes you're right, I forgot to include drug allergies to this form. They should be part of the registration form. I think Poruan hasn't come back to me yet. I'll check.

**Comment by richardmoizeau** [comment]
Just got the greenlight from Poruan for the layout: https://docs.google.com/spreadsheets/d/17rON9mmUjPQzYbPlaTr1IYFJ68YowvsqX7hNx4n000E/edit#gid=29084700&range=A1
