### ISSUE TITLE
itemStats query returns error

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#684]
On the demo database, the `itemStats` query returns an error when run in the **Opua** store.
Try switching to Opua and looking at the dashboard. You should get:

<img width="390" alt="Screen Shot 2022-10-03 at 12 10 38 PM" src="https://user-images.githubusercontent.com/9192912/193480489-d1cf9aa8-0494-44c3-b183-2e29c27266d5.png">

<details>
<summary>Query</summary>

```
query itemStats($storeId: String!) {
  items(storeId: $storeId, filter: {isVisible: true}) {
    ... on ItemConnector {
      nodes {
        ...ItemStats
      }
      totalCount
    }
  }
}

fragment ItemStats on ItemNode {
  stats(storeId: $storeId) {
    averageMonthlyConsumption
    availableStockOnHand
    availableMonthsOfStockOnHand
  }
}
```

</details>
<details>
<summary>Variables</summary>

```
{
  "storeId": "8D967C2618BE4D78B3A6FAD6C1C8FF25"
}
```

</details>

**Comment by andreievg** [comment]
hmm, is it `demo_primary.4dd` on jotta ? Just wondering since it's been last updated 2020 (opening with 4d feature/sync-v5 wouldn't run migrations and initial sync would certainly fail)

**Comment by mark-prins** [comment]
no - it was based off of a copy of the reference datafile on jotta ( which was based on demo_primary, but updated by CD a while ago )
but I had run all of the applicable migrations manually - I'll have to investigate and see..

**Comment by andreievg** [comment]
I was just running postgres test after merge from develop, looks like some decimal number of pack things are messing with item stats view : /, will ignore those tests in the merge I am doing. To replicate we can just run postgres tests
