### ISSUE TITLE
Look up a patient by Program Enrolment ID (eg. HIV Patient ID)

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#686]
Discussed with @mark-prins and @andreievg 

We must have a way to define user permissions based on programs. A user who has the right to see the "Program A" data should be able to: 
- [x]  look up a patient by "Program Enrolment ID" (Dispensary > Patients). Eg. "HIV ID" for PNG HIV Treatment and Care program)
- [x] to see if patient has been enrolled in program A (Dispensary > Patients > Patient Detailed View > Tab Programs) and view enrolment data
- [x] to enrol a patient into program A (Dispensary > Patients > button "Add Program" > Select Program A)
- [x] to see the encounters of the patient for Program A (Dispensary > Patients > Patient Detailed View > Tab Encounters)
- [x] to create a patient's encounter for program A (Dispensary > Patients > Patient Detailed View > button Add Encounter > Select Program A)
- [x] to see the encounters for program A (Dispensary > Encounters)

A user who isn't linked to any programs should not be able to do any of the above. Purpose is to prevent sensitive data captured in the programs forms to be accessible to anyone. A user with no permissions to edit/view Program A: 
- [x] even if looking for a patient program ID, query would not succeed and nothing is displayed
- [x] there would be no Program A data under the Program Tab
- [x] there would be no Program data under the Encounter Tab

Notes: 
- Some user may have rights to edit/view more than 1 program. They should see/edit/create transaction data for these programs. 
- during the discussion, there was the possibility to add a column in the patient list (Dispensary > Patients) with Program IDs for the programs you have the permission for

**Comment by andreievg** [comment]
As per our discussion, one suggestion (which I would endorse) is to add dynamic_id table. Summarise below, but first areas that need to be filtered and adjustments to existing structure

### Permissions by programs not document type

We have a hierarchical document structure with `program` being the root parent, I haven't been able to understand the need for this and it makes filtering more complex (either in configurations or in logic). Clemens suggested that there is a need to have lab test being a `child` of encounter (don't want to misquote so please correct me if I am wrong). Richard mentioned it's not needed. 

I would suggest a simpler structure, with program being a seperate entity (not a document), a program is also something that is used outside of HIS data, and sometimes links to HIS data in aggregate form (for example in requisition regimen data). 

I would also suggest removing hierarchy from document registry and documents and linking documents directly to patients.

### Filtering document registry

This is to see what encounters can be added by the user

Should be pretty simple if document type is linked to a program.
* When document registry is filtered, we look up what programs user has in store and filter all document registry by this program (there should be a join to program in document registry repository, to outsource this to database)

### Filter existing encounters

Both for table and single encounter selection. Encounter should be linked directly to patient and program. Encounter repository should have the join between patient and program (and patient store if we restrict patient visibility by store vs by site). Then we can filter out by programs that user has permission to see.

### Searching patient by program id

A dynamic_id table, with `patient_id`, `program_id` and `id` (`id` is the patient id for that program), this table can be joined to patient in patient repository and we can filter dynamic_ids associated to programs that user can see. This table can also be extended for other patient ids (insurance id etc..)

dynamic id can be exposed for the table in UI as json object for each patient (we would have to use group by either way). This allows front end to display it in any way (seperate columns, one columns with multiple etc..)

### Suggested schema and queries


```mermaid
erDiagram
    DYNAMIC_ID {
        TEXT id PK "NOT NULL"
        TEXT patient_id
        TEXT program_id
    }
    PATIENT {
        TEXT id PK "NOT NULL"
        TEXT address 
        TEXT phone
        TEXT age
    }

    PROGRAM {
        TEXT id PK "NOT NULL"
        TEXT name
    }
    ENCOUNTER {
        TEXT id PK "NOT NULL"
        TEXT document_type_id
        TEXT data
    }
    DOCUMENT_TYPE {
        TEXT id PK "NOT NULL"
        TEXT program_id
        TEXT schemas
    }
    PERMISSION {
        TEXT id PK "NOT NULL"
        TEXT user_id
        TEXT store_id
        TEXT permission "In this case 'Program'"
        TEXT context "Would be program id or name, reference not enforced"
    }
    STORE {
        TEXT id PK "NOT NULL"
        TEXT name
    }
    USER {
        TEXT id PK "NOT NULL"
        TEXT username
    }
    
    PATIENT ||--o{ DYNAMIC_ID : patient_id
    PATIENT ||--o{ ENCOUNTER : patient_id
    PROGRAM ||--o{ DYNAMIC_ID : program_id
    PROGRAM ||--o{ DOCUMENT_TYPE : program_id
    PROGRAM ||--o{ PERMISSION : context
    DOCUMENT_TYPE ||--o{ ENCOUNTER : document_type_id
    USER ||--o{ PERMISSION : user_id
    STORE ||--o{ PERMISSION : store_id
```

I think encounter and document queries are pretty self explanatory, the patient one is a bit more complex, say we want to query by some id (we would have to group by)

```sql
SELECT id, name, all_others, (some grouping method for dynamic_id.id + program_id)
FROM patient
JOIN dynamic_id on patient.id = dynamic_id.patient_id
WHERE dynamic_id.program_id IN (list of ids from allowed contexts)
GROUP BY id, name, all_others
```

###

Could potentially see what patients are enrolled in a program by looking at dynamic_id link to program/patient

I didn't add name_store_join, as the diagram is already pretty complex

**Comment by clemens-msupply** [comment]
Should have looked into this issue earlier because I working on some of the part last week.

For program access I actually thought about a group (used to store the program) attribute in the document registry #596 (branch https://github.com/openmsupply/open-msupply/tree/596-add-group-to-document-registry). Means once you figured out which group/program a document type belongs to you can figure out if you have access to the document. However, while working on it I was unsure if this is really needed or if it would be better to keep the more fine grained per document type access permissions (the config UI could automatically apply permissions, or we implement permission groups on an even higher level).

Currently, documents are missing an owner/patient column though. This relation is needed to figure out if we have access to the document, i.e. do we have access to the patient (through the name_store_join) and thus access to the document that is owned by a patient? This is mentioned in #29 but I plan to write an extra issue for it.

Otherwise we can already do the things from the top list :-)

Regarding program enrollments; a patient is enrolled into a program if there is an enrollment document in the system.

**Comment by richardmoizeau** [comment]
Linked to https://github.com/openmsupply/open-msupply/issues/1014 and https://github.com/openmsupply/open-msupply/issues/686.
