### ISSUE TITLE
Manual Sync carry over

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#688]
- [x] Improve ErrorWithDetails component: https://github.com/openmsupply/open-msupply/pull/677#discussion_r986204835
- [x] Add generic numeric field https://github.com/openmsupply/open-msupply/pull/677#discussion_r986229472
- [x] Action/docs to enforce generation of graphql schema on back end and generating types from that schema + compilation (to make sure front end and back end align), also use file link to ../server/schema.graphql rather then needing demo server or local server for introspection in codegen config (btw if thats changed in codgen config we can run `cargo run --bin remote_server_cli -- export-graphql-schema` on b/e and then `yarn generate` on fe (dont' have to start any servers) 
- [x] Document api hooks patterns, when to use cache and keys, where to `data mangle` (get data ready for downstream consumer), how and where do we use cache, etc..
- [x] Duration format for last sync: https://github.com/openmsupply/open-msupply/pull/685#discussion_r986296906
- ~Sync state indication in navigation (https://github.com/openmsupply/open-msupply/issues/656, extra req) #698~
- ~Use graphql subscriptions for sync statuses (low priority, we have change log, can subscribe to that on b/e) #697~
- ~https://github.com/openmsupply/open-msupply/issues/649~
- [x] Saving syncSettings with `enter` doesn't work in firefox (should check initialisation and login screen too): https://github.com/openmsupply/open-msupply/pull/677#discussion_r986225459

**Comment by mark-prins** [comment]
WRT the ErrorWithDetails component, my other issue with the snackbar implementation is the multiple-click problem:

![errors](https://user-images.githubusercontent.com/9192912/193948043-7ea544b9-62f7-4a26-8e37-e63fd94faec6.gif)
