### ISSUE TITLE
Issues with location, item & master lists

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#710]
Bugs taken from #696 

#### Location
- Added location but location doesn't show up in invoice
<img src="https://user-images.githubusercontent.com/61820074/194781450-5f615072-47de-4a53-86f7-eed0179cb53f.png" width="500"/>
<img src="https://user-images.githubusercontent.com/61820074/194781486-0f0d52c6-b19a-4f6a-9cee-f1b890d44c07.png" width="500"/>

#### Item
- New items that have never been used in the store before will have 0 months of stock... might be confusing? 🤔 

#### Master Lists
- Pagination disappears if Master List is too long
![Screen Shot 2022-10-11 at 9 24 24 AM](https://user-images.githubusercontent.com/61820074/194946717-1c9b2dda-2a20-4b04-afc1-917a2590a3e1.png)

**Comment by roxy-dao** [comment]
I forgot to add that location doesn't show up in stock take either >.<
