### ISSUE TITLE
New shipment button text is wrong - "button.new-shipment"

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#72]
![image](https://user-images.githubusercontent.com/7684221/171090591-66c73b20-2e5d-49d6-aac1-ead0b6258033.png)

Affects both inbound and outbound on the demo server

**Comment by Chris-Petty** [comment]
Probably something awry with localisation thingy, cropping up in a few places: 

![image](https://user-images.githubusercontent.com/7684221/171090836-5d5c8f32-a627-43d2-ab04-48c2428823fd.png)

**Comment by mark-prins** [comment]
the hosting of the f/e in the server is causing issues with JSON language files e.g. https://demo-open.msupply.org/replenishment/locales/en/replenishment.json returns a 404

**Comment by andreievg** [comment]
ouch, sorry, did check this change but not thoroughly enough (dashboard seemed to have worked).
