### ISSUE TITLE
Invoice Pricing 

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#741]
Transferring from #696 for easy discussion.

- [x] Tax can be set on each individual line for invoices. This means that the total tax in the side bar is recalculated to reflect the overall tax of the invoice. This may be confusing for users as it is not apparent to them that the tax is only set for individual lines. 
![Screen Shot 2022-10-31 at 12 47 28 PM](https://user-images.githubusercontent.com/61820074/198907890-7fe3ff9b-5c5a-4487-bf60-26432b6d8289.png)
- [x] You cannot enter tax on service charges for Inbound Shipments. 
- [x] The calculations for total_after_tax created in Inbound Shipments is incorrect as this is calculated as cost_price_per_pack * number_of_packs. mSupply transfers tax costs over from Outbound Shipments, so omSupply should probably do the same instead of having it disappear? I can't imagine that the supplier is the one who pays for the tax...

**Comment by andreievg** [comment]
> 2

Yeah i think it should be enterable

> 4

Agree we should just do what mSupply does

> 3 

Agree, should show transport details

> 1

Roxy just showed me how to replicate this, add one item than edit tax, then add the second item. 
Need to think about this a bit further

**Comment by roxy-dao** [comment]
> 2\. Inbound

Will have the same problem as Outbound tax input so should decide how the tax should be set in the UI (:

**Comment by mark-prins** [comment]
For transport details: the thought was that for manual inbound shipments you do not need transport info. That's the result of a discussion about it anyway.

The understanding was that typically you create a manual inbound shipment to record a shipment that has arrived. In which case there is no need for a transport reference - in that the purpose of the ref was to track the progress of a shipment

**Comment by roxy-dao** [comment]
Update from IRL discussion: Add tax field on invoice for now and have that populate the invoice line tax
