### ISSUE TITLE
Show version on login screen

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#744]
Request from Ujwal - that we can see the version on the login.
Not all users have access to the admin section 😉

**Comment by ujwalSussol** [comment]
> Request from Ujwal - that we can see the version on the login. Not all users have access to the admin section 😉

Thanks @mark-prins   :  if this doesn't get added... I will make sure that we will get it added :-)  ... a simple way to get into OpenmSupply   :-)
