### ISSUE TITLE
Internal Order form : OK & Next button appears not to work.

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/open-msupply#785]
Internal Order form : OK & Next button appears not to work.

Create an internal order on omSupply Client web app. The `OK` button works but not the `Ok & Next` button is not function. 

To reproduce : 

- Create an internal order for a Supplier.
- Add items to order, use `Ok & Next` button for the next item.
- Note down the items you are adding.
- On the final item, click `OK`
- Error only one item is added. 

![open_msupply_ok_and_next_not_working](https://user-images.githubusercontent.com/6764266/201048706-1e15910e-ec8b-4bc0-9d9d-f6fc9a831020.png)

**Comment by DhanyaHerath** [comment]
I don't think this happens anymore - I couldn't replicate it on the demo server. @ujwalSussol would you mind testing this again and closing if it's fixed?

**Comment by roxy-dao** [comment]
I cannot replicate this in development either. Okay to close? @mark-prins

**Comment by mark-prins** [comment]
Sounds good to me
