### ISSUE TITLE
OpenmSupply windows electron app : Searches for OpenmSupply server for ever, when server is not found !

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/open-msupply#786]
OpenmSupply windows electron app : Searches for OpenmSupply server for ever, when server is not found !

Install the OpenmSupply windows electron app. Have a openmSupply server running. It may be that the OpenmSupply windows electron app fails to locate the local server. The search icon goes for ever. 

![openmsupply-electron](https://user-images.githubusercontent.com/6764266/201056140-6efc14ff-2aaa-4860-9e62-811a8d8ee744.png)

**Solution** 

I think we need time out feature.... After a minute, we are displayed a URL where the server address can be set.

**Comment by mark-prins** [comment]
fixed - added timeout and warning message
