### ISSUE TITLE
TB/HIV Module (programs): HTC/HIV Testing and Counselling Program 

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#789]
There will be 2 programs for testing: one for the general population and one for key population. Key populations are going through a routine check while general population is only getting tested when exposed. 

Here we are talking about HTC for the general population enrolment form

- [x] remove the patient status from the enrolment form
- [x] for the encounter headers or details panel: add a field to manually enter the HTC reference (a data that is found on the paper form)
- [ ] ~mSupply should generate its own sequential ID for each encounter for a specific program (does not have to be visible by the user)~ There is a unique id for an encounter (the name)

**Comment by clemens-msupply** [comment]
@richardmoizeau :

> for the encounter headers or details panel: add a field to manually enter the HTC reference (a data that is found on the paper form)


This is the program id? or is it something else? The program id is already in the program enrollment form so I guess we don't need it?

> mSupply should generate its own sequential ID for each encounter for a specific program (does not have to be visible by the user)

Is this needed? we have a unique internal encounter name which is an increasing string but is not a number...

**Comment by richardmoizeau** [comment]
> This is the program id? or is it something else? The program id is already in the program enrollment form so I guess we don't need it?
> 
This is the uniue ID of the encounter. I think you already have added a HTC section so should be fine. 

> Is this needed? we have a unique internal encounter name which is an increasing string but is not a number...
>
I was referring to the unique ID of the encounter automatically generated by mSupply in the background (like a record ID) to be able to identify this encounter in a database or something like this. All "records" in mSupply OG have unique ID.
