### ISSUE TITLE
Programs enrolment IDs / manual entered IDs

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#791]
- [x] the patient "Program ID" is the unique identifier given to a patient for a specific program. Currently named "Patient enrolment ID"
- [x] System should generate a sequential Program ID (and it is OK if there are gaps in the sequence) but also have the ability to enter a Program ID manually (we should avoid duplicate though).

**Comment by clemens-msupply** [comment]
IDs can have different format other than a simple number, e.g. "AB000045".

We need a way to keep track of used ids. Idea: Have a "ID" table which has a row for each used ID. The user can than store arbitrary IDs for a certain context. The users can generate new IDs using an automatic counter (as done currently) or get the ID from another source such as the program id from a paper form. If an id is already in the table the user has to resolve the conflict, e.g. by manually choosing a new id or using the next autogenerated id.

@andreievg any additional thoughts on how to solve this problem?
