### ISSUE TITLE
HiV Care Program/Encounter: GBV section is missing

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#792]
GBV = Gender Based Violence

Fields: 
- [x] GBV Screened: Positive, Negative, Declined, Not Done
- [x] Type of GBV: Physical, Psychological, Sexual, N/A (only one choice)
- [x] Referred for external services ? Yes, No, N/A
- [x] IPV (=intimate partner violence): Yes, No, N/A
- [x] Rape? Yes, No, N/A
- [x] Post GBV Services provided ? Yes, No, Declined, N/A
- [x] GBV Service type: Received at least service service (not min. package per type of violence), received min. package of services per type of violence, N/A

**Comment by mark-prins** [comment]
Completed in #795
