### ISSUE TITLE
HIV Testing & Counselling/Risk behaviour secion: a patient can have more than 1 risk group

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#794]
According to the TWG, patients can be assigned multiple risk groups so it's more like a flag. 

- [x] Based on the answers to the 'have you ever experienced" questions, the risk group(s) should be automatically assigned to the patient. 
- [x] Patient's risk group(s) should not be visible or just as a code (no clear label)
- [x] Since patient risk group is the results of the "have you ever experienced any of the following" questions, it should appear at the bottom of the section
- [x] https://github.com/openmsupply/open-msupply/issues/892

**Comment by clemens-msupply** [comment]
All handled in #892
