### ISSUE TITLE
Invoices, requisitions and stocktakes missing when syncing previously mSupply Desktop site

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#818]
## What's wrong?

If you create records in mSupply desktop on a remote site (using current production/master v6.06), then use mSupply desktop and sync to omSupply, you get errors recorded in the sync_buffer:

![image](https://user-images.githubusercontent.com/7684221/202131314-b643de30-ed48-4f4a-8bef-3b4f37e699ac.png)

The outcome of this is that omSupply is missing transactional and ordering data when in use. All child lines will have FK constraint violations when integration is attempted for them.

```json
{"Colour":1710361,"Date_order_received":"0000-00-00","Date_order_written":"0000-00-00","ID":"0BC1BD19BD32413B817039E0BCD0AB28","amount_outstanding":0,"arrival_date_actual":"0000-00-00","arrival_date_estimated":"0000-00-00","authorisationStatus":"","budget_period_ID":"","category2_ID":"","category_ID":"","comment":"","confirm_date":"0000-00-00","confirm_time":0,"contact_id":"","currency_ID":"8009D512AC0E4FD78625E3C8273B0171","currency_rate":1,"custom_data":null,"diagnosis_ID":"","donor_default_id":"","encounter_id":"","entry_date":"2022-11-16","entry_time":75471,"export_batch":0,"finalised_date":"0000-00-00","foreign_currency_total":0,"goodsReceivedConfirmation":null,"goods_received_ID":"","hold":false,"insuranceDiscountAmount":0,"insuranceDiscountRate":0,"internalData":null,"invoice_num":2,"invoice_printed_date":"0000-00-00","is_authorised":false,"is_cancellation":false,"lastModifiedAt":1668585555,"linked_goods_received_ID":"","linked_transaction_id":"","local_charge_distributed":0,"mode":"store","mwks_sequence_num":0,"nameInsuranceJoinID":"","name_ID":"6582C406F549451DABDBFE141B34F766","number_of_cartons":0,"om_allocated_datetime":"","om_colour":"","om_created_datetime":"","om_delivered_datetime":"","om_picked_datetime":"","om_shipped_datetime":"","om_status":"","om_transport_reference":"","om_type":"","om_verified_datetime":"","optionID":"","original_PO_ID":"","paymentTypeID":"","pickslip_printed_date":"0000-00-00","prescriber_ID":"","requisition_ID":"","responsible_officer_ID":"","service_descrip":"","service_price":0,"ship_date":"0000-00-00","ship_method_ID":"","ship_method_comment":"","status":"nw","store_ID":"D0E298893F3945DABE80B138E25D3D15","subtotal":0,"supplier_charge_fc":0,"tax":0,"their_ref":"","total":0,"type":"si","user1":"","user2":"","user3":"","user4":"","user_ID":"0763E2E3053D4C478E1E6B6B03FEC207","wardID":"","waybill_number":""}
```
Culprit: `"om_allocated_datetime":""` char 1152 is the value here

```json
{"ID":"E64719C276A84A6F9910A43616305A56","authorisationStatus":"none","colour":1,"comment":"","custom_data":null,"date_entered":"2022-11-16","date_order_received":"2022-11-16","date_required":"2022-11-16","date_stock_take":"2022-11-16","daysToSupply":30,"isRemoteOrder":false,"is_emergency":false,"lastModifiedAt":1668585555,"linked_purchase_order_ID":"","linked_requisition_id":"","name_ID":"6582C406F549451DABDBFE141B34F766","nsh_custInv_ID":"","om_colour":"","om_created_datetime":"","om_expected_delivery_date":"0000-00-00","om_finalised_datetime":"","om_max_months_of_stock":0,"om_sent_datetime":"","om_status":"","orderType":"","periodID":"","previous_csh_id":"","programID":"","requester_reference":"","requisition_category_ID":"","serial_number":3,"status":"sg","store_ID":"D0E298893F3945DABE80B138E25D3D15","thresholdMOS":0,"type":"response","user_ID":"0763E2E3053D4C478E1E6B6B03FEC207"}
```
Culprit: `"om_created_datetime":""` char 486 is the value here

```json
{"ID":"E64719C276A84A6F9910A43616305A56","authorisationStatus":"none","colour":1,"comment":"","custom_data":null,"date_entered":"2022-11-16","date_order_received":"2022-11-16","date_required":"2022-11-16","date_stock_take":"2022-11-16","daysToSupply":30,"isRemoteOrder":false,"is_emergency":false,"lastModifiedAt":1668585555,"linked_purchase_order_ID":"","linked_requisition_id":"","name_ID":"6582C406F549451DABDBFE141B34F766","nsh_custInv_ID":"","om_colour":"","om_created_datetime":"","om_expected_delivery_date":"0000-00-00","om_finalised_datetime":"","om_max_months_of_stock":0,"om_sent_datetime":"","om_status":"","orderType":"","periodID":"","previous_csh_id":"","programID":"","requester_reference":"","requisition_category_ID":"","serial_number":3,"status":"sg","store_ID":"D0E298893F3945DABE80B138E25D3D15","thresholdMOS":0,"type":"response","user_ID":"0763E2E3053D4C478E1E6B6B03FEC207"}
```
Culprit: `"om_created_datetime":""` char 249 is the value here

## Relevant data from the willing

[demo_data 606 number test.zip](https://github.com/openmsupply/open-msupply/files/10019828/demo_data.606.number.test.zip)

Use the "Gryffindor" site. Data mostly relates to the store "Gryffindor District store".

## Solution

**Suggestion:** I suspect the solution is making sure sync translators can handle there potentially being empty string values for these datetime fields. While time will be lost in most cases, perhaps it should at least get the date from the old mSupply fields.

**Alternative:** mSupply central server could do the mapping when records are pulled from the v5 API. 

## Other areas to think about

I strongly believe applications shouldn't ignore errors that can affect data integrity. I think integration should fail and the app should not be usable until we fix integration errors, otherwise they may be inadvertently ignored until the app is in production. Fixing errors like these we should want to be apparent fast and jump to the top of the TODO list 🚀 !

**Comment by Chris-Petty** [comment]
Bonus aside, a basic template with the above headers for bugs reports could be good?

**Comment by Chris-Petty** [comment]
This likely causes #787. Haven't tested, but presumably any transfer record from a desktop site will fail to integrate when received on omSupply in the same way described in this issue. So CIs owned by the supplier arrive, but get stuck in `sync_buffer` and do not get inbound shipments (SIs) generated.

**Comment by andreievg** [comment]
Hmm, i wonder how these nullable fields end up having empty strings, it's not worth investigating imo. 
Anyways we have `#[serde(deserialize_with = "empty_str_as_option")]`, not sure if this would also work for empty string or null as option, but we can created one and make sure all nullable `om_` string fields have this added

**Comment by Chris-Petty** [comment]
> Hmm, i wonder how these nullable fields end up having empty strings, it's not worth investigating imo.

Without investigating, it's likely because the code in sync v1 that maps values from the sync records in the body sent is setting empty strings to the fields, so the fields end up saved with empty strings rather than nulls.

`serde` fix looks likely to be quick and easy, keen!
