### ISSUE TITLE
Add separate "code" field for Program names

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#834]
As mentioned here: https://github.com/openmsupply/open-msupply/issues/644#issue-1383248595

Currently there is no "code" field, the code displayed is just the first three characters of the name, which can easily lead to duplication:

![Screen Shot 2022-09-23 at 3 26 21 PM](https://user-images.githubusercontent.com/74992958/191886796-06579396-4336-430e-8a7d-a9385b00beaf.png)

First three chars is a good default if nothing else is supplied, but would be good to specify code.

**Comment by clemens-msupply** [comment]
Had a quick chat with Mark this morning and we think it would be the simplest thing to not have a code column. If I remember correctly we did it because the used component had one and it looked nice. So we can just removed the code column from the UI.
