### ISSUE TITLE
JSON Forms widget -- multi-line text box

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#838]
For entering "Notes" and other longer bits of information.

**Comment by clemens-msupply** [comment]
Regarding the note author and note creation time I had something like this in mind when creating the type definition:

![Image](https://user-images.githubusercontent.com/88299195/208776520-64b3ab84-5421-40e6-b32f-48f25750e2ff.png)

Think this could be useful if there was, for example, an initial comment on some encounter and then another practitioner added a note to the encounter at a later point. For example:

1) Patient will call too confirm issue ABC (Dr. A 2022/20/12)
2) Patient called and confirmed that the info for issue ABC is correct (Dr. B. 2022/21/12)

@richardmoizeau what do you think?

**Comment by CarlosNZ** [comment]
Do you think the "Author" needs to be the actual id of a user in the system, or just a text field where they can put whatever name they like (e.g. "Dr Jones" -- which is probably not their user account name)?

**Comment by clemens-msupply** [comment]
Good question. Best would be to just capture it automatically, e.g. use the logged in user id,  but we also have the feature to select a practitioner who did the actual encounter and the current user is just a "data clerk". Should we leave the author out for now?

**Comment by CarlosNZ** [comment]
I think the simplest way to do this would be to create a component for a single note, then use the existing "Array" component to wrap it to allow multiple notes.

(And the "Note" component will in turn compose the "Text" component)

**Comment by richardmoizeau** [comment]
> @richardmoizeau what do you think?

I think this is a really good idea. While in Djibouti I could take a look at HIV patients file there and the way they are also entering multiple notes so yes if we can do it, then that's great. 

Practitioner for the encounter should be captured/entered in the Encounter's headers. So maybe we can assume that the author of the note is the practitioner of the encounter ?

**Comment by CarlosNZ** [comment]
@clemens-msupply -- one thing I've realised is that the "created" timestamp is a bit tricky to capture properly. Ideally, the timestamp would be the time the document was saved (when pressing the "Save" button for the whole form). However, we don't really have a way to inject data into a particular node when saving the whole form. 

So we'll either need to:
1. set the timestamp when the note is instantiated in the UI ("Add note") (which could be several minutes or even longer before they actually save the form or finish the note)
2. set the timestamp in the "onChange" function (so it'll be updated whenever the note is entered)
3. something else?

Which also raises the question -- should notes be editable after saving? 

My suggestion would be to make only the most recent note editable (and only by the user who created it). Sound okay?

**Comment by clemens-msupply** [comment]
I would just use the current timestamp for the note creation time (the time when the user first edited the note and a new entry in the array is created; so the note creation time would be before the document timestamp but this would IMHO be ok).

Good question about editing/deleting a note. Think it would be good to make this possible at some point. Then we could also record the note modification time to show an "edited" label if we want to go fancy ;) So I would say yes if we could delete/modify existing notes this would be great!
