### ISSUE TITLE
Clicking OK on certain dialogs logs the user out

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#842]
To reproduce, click on a patient in the "Patients" table who doesn't have an associated document. You should receive this message:
![photo_2022-11-24 10 58 08](https://user-images.githubusercontent.com/5456533/203652921-9f3d35c5-e757-4c04-bf91-116ff508113f.jpeg)

Then when clicking "OK", you get taken back to the login screen and have to log in again. Seems unnecessary 🙁.

Similar thing happens when clicking "Create Shipment" modal in Response Requisitions too:
![photo_2022-11-24 11 00 09](https://user-images.githubusercontent.com/5456533/203653652-997206f6-bd24-456d-9628-730e48fadaa0.jpeg)

**Comment by mark-prins** [comment]
note: you don't have to login again, they just redirect you to login but don't log you out!
The first one was a temporary thing in the programs feature iirc, and the second I thought was resolved [with this](https://github.com/openmsupply/open-msupply/blob/feature/programs/client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/CreateShipmentButton.tsx#L25)

**Comment by DhanyaHerath** [comment]
@CarlosNZ when you get back, would you mind checking whether these are still problems?

**Comment by CarlosNZ** [comment]
> @CarlosNZ when you get back, would you mind checking whether these are still problems?

Seems to be okay now, thanks.

Will close.
