### ISSUE TITLE
[prog][ui misc]: ARV Care/ARV Medication section

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#843]
Feedback from PNG TWG on 24/11: 

![Screen Shot 2022-11-24 at 12 28 20 PM](https://user-images.githubusercontent.com/74992958/203663088-622f5392-dceb-4d0f-92f8-6d50f565b9ef.png)

**'ARV Regimen':** 
- [ ] dropdown of available regimen should be linked to the item catalogue (list of items flagged as ARV medication?) to enable the generation of a dispensing record (see ). However, PNG should still see the codes and names they are using in the HPDB. https://github.com/openmsupply/open-msupply/issues/948
- [x] should have a "No ARV" option
- [x] only 1 regimen at a time
- [x] should **not** populate ARV from last encounter

**'Pill Count':** 
- [x] number of units (pills) that the patient has left from the last dispensing event (last encounter)
- [x] can be renamed into a clearer way than "Pill count"

**ARV Adherence Status (automatic/dynamic):** 
- Ideally system should automatically calculate the adherence based on the last encounter dispensed quantity (Num days dispensed), the number of days since last encounter and number of remaining pills (Pill Count):
- Formula: ( Dispensed Quantity (last encounter) - Remaining Quantity ) / Number of days since last encounter
- should be able to select the value manually

- [x] https://github.com/openmsupply/open-msupply/issues/909

**Number of days dispensed:**
- [x] Ok to rename it: Quantity prescribed
- [x] End of supply: encounter's date + Qty prescribed

**ARV Status (automatic/dynamic) - not to be confused with HIV Status:** 
1. No ARV: Default value when creating 1st encounter for a patient
1. Start ARV:  when an ARV is selected for the 1st time
2. Continue ARV: when ARV is the same as in the last encounter
3. Change ARV: when ARV is different from the last encounter
4. Stop ARV: when "no ARV" is selected in the Regimen field and this is not 1st encounter

**ARV reasons:** 
If ARV Status = Change ARV
- [x] Select values from a dropdown (see values [here](https://docs.google.com/spreadsheets/d/17rON9mmUjPQzYbPlaTr1IYFJ68YowvsqX7hNx4n000E/edit#gid=23017610&range=A1))
- [ ] ~~some of reasons should update the patient registration form(?) eg. "Patient has died"~~
- [x] possibility to add a notes to explain/clarify the changes

**Relevant co-medication:** 
- [x] For information only, not a prescription

**Prophylaxis medications:** 
Move to: https://github.com/openmsupply/open-msupply/issues/948
- [ ] should also be a list of mSupply items (flagged as Prophylaxis Medication ?)
- [ ] enable the generation of a dispensing record (see ) with the ARV regimen
- [ ] should specify quantity of units prescribed

**Comment by richardmoizeau** [comment]
I was worried about case 2, but if you think about it, patient received pills for 30 days and he is coming for a refill after 60 days so meaning that patient was not able to take the pills during half the time since last encounter. The remaining 4% are most likely the 2 remaining pills.

**Comment by clemens-msupply** [comment]
@richardmoizeau  " should not populate ARV from last encounter" could you please clarify? do you mean the last encounter's regimen should not be displayed? Which fields should be taken over from last encounter

**Comment by richardmoizeau** [comment]
Initially I thought that it would be useful to see the ARV given to the client in the last encounter and make it the default value for the new encounter (assuming that patient will most of the time stay on the same regimen). However, maybe we can make it visible even if it is not a drop down, just for information ? Something like: "Last visit's regimen:"

**Comment by clemens-msupply** [comment]
"some of reasons should update the patient registration form(?) eg. "Patient has died""

nice to have but quite advanced to do. IMHO this can be done  manual process. Feel free to add it back
