### ISSUE TITLE
Unify visuals of multi select (EnumArrayComponent) and single Select components

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#860]
![Image](https://user-images.githubusercontent.com/88299195/203888375-1816319c-d21a-4dae-8bf8-cb456c429c05.png)

- [ ] use grey background "bubble" like for the single Select component
- [ ] remove underlined 

Probably needs some more tweaks to make it look nice...

**Comment by roxy-dao** [comment]
![2022-12-01 15 16 30](https://user-images.githubusercontent.com/61820074/204949855-b6b75db8-4ebc-4669-a92f-fbc83f19bd59.jpg)
Mock up from Anisha~
