### ISSUE TITLE
Highlight current Text box

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#861]
![Image](https://user-images.githubusercontent.com/88299195/203889186-3c23718f-8654-4b59-ab57-76d239dd287b.png)

The Select box has a red underline when selected, do the same for the Text box and other controls.

Note, this isn't currently done else where.

The colour might be changed from orange to grey though (orange is to close to red -> error)

**Comment by clemens-msupply** [comment]
@mark-prins Currently no Text component does this but if I understood you correctly this is what we want?

**Comment by mark-prins** [comment]
we deliberately disabled it.. and now I'm reconsidering.
Am warming to the idea - particularly for forms, it is helpful to see which field is highlighted.
Changing the `InputProps` on `BasicTextInput` would allow the underline, and set the color 🤷 

```
// disableUnderline: true,
        color: 'secondary',
```
