### ISSUE TITLE
Customize items in generic modals

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#867]
For example: Gender vs sex in patient creation dialog.

![Image](https://user-images.githubusercontent.com/88299195/204175766-468ccf42-9c99-4cee-a592-eb2a83aed9dd.png)

Make this customizable

Idea: use JSONForms for it using UI schemas stored in form_schema table. Problem here is that currently only one schema is associated with a single document type.

This could be solved by removing the schema id from the `document_registry` and creating a `document_schema_join` table.
This table would have another context column like: `"DEFAULT" | "GENERIC_PATIENT_CREATION"`.

**Comment by clemens-msupply** [comment]
@mark-prins is there an existing good place to store the mapping of json forms / ui forms to their usage?

**Comment by clemens-msupply** [comment]
After chat with @mark-prins: we can use the `form_schema` table `type` column to define types like "PROGRAMS_PATIENT_CREATION" to identify special UI forms.

**Comment by andreievg** [comment]
This is priority low, should it be in the sprint ?
