### ISSUE TITLE
Extract ValueBar component

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#873]
The `ValueBar` is now created in three places ( StockDistribution, RequestStoreStats, ResponseStoreStats ).
They might not be exactly the same, but are essentially copies of the first one. It would be good to lift these out to common to enable reuse.

**Comment by roxy-dao** [comment]
Maybe the MonthlyConsumption/MonthlyBar as well? (It's used in two places (StockDistribution and RequestStoreStats)... not sure if that warrants moving to common)

**Comment by mark-prins** [comment]
Additional request while working in this area: from #696 can you 

- [ ] Target Quantity should be spaced out more to fit all the numbers (Internal Orders)

![image](https://user-images.githubusercontent.com/9192912/212176879-1fbd48a8-a2b2-435e-a617-ff6f705ab07c.png)

**Comment by guatemartin** [comment]
Hi, just finding my way around this repo.
Is there any place better than another of where to extract ValueBar to?
I had thought common/src/ui/components/...   Not sure where this makes sense after that.

**Comment by mark-prins** [comment]
> I had thought common/src/ui/components/... 

@guatemartin Yes - somewhere in common would be my suggestion. I'd go with `/packages/common/src/ui/charts/ValueBar/` and create a file in there. You could add a storybook file as well ( there's examples of .stories files in other folders under the `ui` folder ) if you wanted to go crazy with it. Would be nice to have a storybook example of the value bar if possible.

**Comment by guatemartin** [comment]
@mark-prins Thanks for the suggestion.  I gave it a shot.  PR submitted.
