### ISSUE TITLE
Requisitions: Ok and next does not save the supply value

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#888]
https://demo-djibouti.msupply.org/distribution/customer-requisition/1?sort=itemName&dir=asc

Description: 
when entering a data in the modal and clicking on Ok & Next, the value is not saved. It works when clicking on OK though. 

https://user-images.githubusercontent.com/74992958/205176532-d9251516-190c-4602-b6fb-5b5384155916.mov

**Comment by roxy-dao** [comment]
Same thing with Internal Orders #785
