### ISSUE TITLE
Unable to create stocktake with items

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#889]
..when there are a lot of items.

Using the recent demo file from Richard, which has a lot of items in it, when I create a stocktake, and tick items - the stocktake is created but is empty 🤷 

Also, when I try to add items, I can only see the first n items ( up to `D` in this datafile )

**Comment by richardmoizeau** [comment]
I think this issue isn't limited to stocktakes, when creating an outbound shipment, the full list of items is not available
