### ISSUE TITLE
Internal order: leading 0 in input values

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#893]
![image](https://user-images.githubusercontent.com/7684221/205200221-c8ba543b-7fb2-49ce-bbc7-db65ff79ead7.png)

When you edit a line, it focuses "requested quantity" with the cursor after the 0. This adds further digits after the 0 so you have this leading zero which is slightly annoying. It remains after onblur, but when you save the line and reopen, the leading 0 is gone.

I think always highlight the full value when it the field is focused. Including when tabbing into it. That why when you type, it replaces the values.

**Comment by DhanyaHerath** [comment]
+1 to this! On android I can't delete the 0 either, which is a bit annoying...
