### ISSUE TITLE
Add full sync pull translation for the `report` table

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#906]
Missing:

- [x] sync report data blob

**Comment by Chris-Petty** [comment]
I don't think this is necessary - in the sync v5 API we've added a field `template` which is the plain text of the report (more specifically [UTF8 text without length](https://doc.4d.com/4Dv19R6/4D/19-R6/BLOB-to-text.301-5911146.en.html)). This was purely to make it more convenient for omSupply 😁 .

That said the blob fields do come through, they'll be BLOBs that are essentially UTF8 too but maybe with some hairy bits.

**Comment by clemens-msupply** [comment]
Perfect then we have everything in place already!
