### ISSUE TITLE
Postgres running out of memory

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#907]
When running in development with postgres DB I cannot initialise modest sized sites. In my tests I am initialising and integrating about 180K records, at about 10 mins into integration I get this error and integration stops:

```
2022-12-01 17:57:26.443497 WARN service::sync::translation_and_integration - DBError { msg: "UNKNOWN", extra: "\"\\\"out of shared memory\\\"\"" } "6C2C13CE7735AB4CA5E002AF1B533E61" "requisition_line"  service/src/sync/translation_and_integration.rs:125
```

Likely unrelated, but during initialisation I get many, many errors for unsupported records.

**Interestingly this is totally fine when running sqlite.**

Preliminary googling suggests this is likely due to having too many transactions within a transaction.

**Comment by andreievg** [comment]
Taking of the sprint, planned deployments sqlite only

**Comment by mark-prins** [comment]
not seeing the issue myself - have always been running postgres in dev, and we have pg on the various demo servers.

**Comment by Chris-Petty** [comment]
> not seeing the issue myself - have always been running postgres in dev, and we have pg on the various demo servers.

With big datafiles?

**Comment by mark-prins** [comment]
yup. TL with 3k+ items and syncing the hospital with the most transactions

**Comment by mark-prins** [comment]
@Chris-Petty is this still an issue for you?

**Comment by Chris-Petty** [comment]
Nah! Just tested with ~120K record initialisation, went fine. Took a wee while to integrate, still loads of FK violations for whatever reasons.

Unrelated but frontend exploded when I tried to login:
![image](https://user-images.githubusercontent.com/7684221/220010078-6f8d6328-1750-4abd-bcd6-8c1063a05873.png)
