### ISSUE TITLE
Cannot access tooltips on android

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#908]
When trying to login it seems to be impossible to get the tooltip with error info to show via touch input.

![image](https://user-images.githubusercontent.com/7684221/205785224-8b40c784-ebf5-420c-91ae-9589a812c81c.png)

I've had a similar experience on the initialisation page.

Or maybe my fat fingers?

**Comment by Chris-Petty** [comment]
This legit could just be my fat fingers. Note there is a little info icon next to the error message ℹ️ 
![Screenshot_20221206-160941](https://user-images.githubusercontent.com/7684221/205802919-b7926bdd-1391-41e1-8afe-90054aec08b8.png)

If I get it just right, I can see the further detail. Why can't I always see this, such as in the login image above?

**Comment by mark-prins** [comment]
There is no info icon shown on the login page, when the server has an error. 
Will add one in. Unsure about the initialisation screen, if you add details I'll look into it - for now.. will ignore 😉
