### ISSUE TITLE
[prog][control] Adherence Status

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#909]
Create an adherence status control that:
- auto calculates an adherence status
- able to manually overwrite the status (?)

There are is the following config:
```typescript
type Config = {
  /**
   * Field name for the dispense count is stored.
   * This field is loaded from the previous encounter.
   *
   * For example: `previousDispensedCountField: 'arvMedication.numberOfDaysDispensed'`
   */
  previousCountField: string;
  /**
   * Field name of the remaining count field.
   * For example: `remainingCountField: 'arvMedication.remainingPillCount'`
   */
  remainingCountField: string;
  /** Expected number of pills per day that a patient is suppose to take. */
  countPerDay: number;
};
```

The control:
- loads the `previousDispensedCount` from the previous encounter (using previousDispensedCountField)
- loads the `remainingCount` from the current encounter (using remainingCountField)
- calculates the `numberOfDays` from the current encounter to the previous encounter
- calculates adherence status: `adherenceStatus = (previousDispensedCount - remainingCount) / (countPerDay * numberOfDays)`

**Comment by CarlosNZ** [comment]
> * calculates adherence status: `adherenceStatus = (previousDispensedCount - remainingCount) / (countPerDay * numberOfDays)`

I don't quite understand. Why do we assume that an encounter will occur on the exact day that the patient finishes all their pills? (which is what would be required to get 100% adherence). Wouldn't people normally go to the doctor a few days before they need more medication?

**Comment by clemens-msupply** [comment]
Its `(amount of pills taken since last encounter) / (expected amount of till taken since last encounter)` Does this make sense?

So if you have taken more pills then expected you get adherence status > 100% and if you have taken less you get < 100%

**Comment by CarlosNZ** [comment]
> Its `(amount of pills taken since last encounter) / (expected amount of till taken since last encounter)` Does this make sense?

Ah okay, I see. You're calculating the expected amount based on the current encounter date. 👍

**Comment by CarlosNZ** [comment]
This is done, right @clemens-msupply ?
