### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#923]
Not sure what happened - the dj demo site was not running, with only this hint in the log

```
2022-12-08 13:04:22.414718 ERROR omsupply_service::omsupply_service - panic occurred PanicInfo { payload: Any { .. }, message: Some(invalid time), location: Location { file: "C:\\Users\\Administrator\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\chrono-0.4.19\\src\\naive\\time.rs", line: 412, col: 9 }, can_unwind: true }  windows\src/windows.rs:66
```

have uploaded the postgres db and the datafile to [data share](https://drive.google.com/drive/folders/1tzCrTy65oZ_dm8SB2kbZX1N9q7YPCTw1?usp=share_link)

have stopped mSupply on the demo server, so that the demo runs. otherwise, it crashes on start up.

**Comment by mark-prins** [comment]
So the issue is that `translate_sync_record` used naive_time to deserialise which panics if the time value supplied is invalid. This then takes the server down.

The problem record is an invoice, id `3cee66c2-359c-4d1f-9630-38f5136a7110` which shows an `entry_time` value of 2963575472 in the data in the sync_buffer. have edited the sync_buffer and set the value to 0 which has resolved the sync issue. 

Question is - how did that value get in there?

**Comment by craigdrown** [comment]
https://docs.rs/chrono/0.2.18/chrono/naive/time/struct.NaiveTime.html#method.from_hms_opt instead?
