### ISSUE TITLE
Practitioner input field

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#926]
Add a practitioner input field to the encounter view.

At a later stage this needs to be connected to users/practitioners stored in mSupply.

**Comment by richardmoizeau** [comment]
in the headers

**Comment by CarlosNZ** [comment]
> Add a practitioner input field to the encounter view.
> 
> At a later stage this needs to be connected to users/practitioners stored in mSupply.

Does that mean just a free-text input for now?

**Comment by clemens-msupply** [comment]
> > Add a practitioner input field to the encounter view.
> > At a later stage this needs to be connected to users/practitioners stored in mSupply.
> 
> Does that mean just a free-text input for now?

With the clinician API in place (in PR) we can just have a drop down with existing practitioners.

**Comment by CarlosNZ** [comment]
Think this is done.
