### ISSUE TITLE
Stocktake: Location is not saved when finalising the stocktake

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#937]
When adding a location through a stocktake, the location is not saved in the other module of the software (eg. view stock, issuing, etc...)

**Comment by CarlosNZ** [comment]
As far as I can see, you can't add a new location in Stocktakes, you can only select from the existing list? How were you doing this @richardmoizeau ?

**Comment by andreievg** [comment]
needs to be validated, if this is a bug should be pretty easy to fix, adding as normal priority to android stabilisation milestone.

**Comment by richardmoizeau** [comment]
Just to make sure I have described the issue properly, here is a video. 

In this video, I'm taking an item with 3 stock lines, each of them have no locations and one of them is missing the batch number. 

I create a stocktake for this item simply to add a location for each batch and a batch number + expiry for one of them. I finalise the stocktake. 

When I come back to the view stock, the information are still missing. If I create a new stocktake for the same item, the information are missing. 

https://user-images.githubusercontent.com/74992958/214217835-157e0571-90b7-4533-932d-80b9b5d4e730.mov
