### ISSUE TITLE
Would like to be able to create a stocktake filtered by location, masterlist, or whether items have stock

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#938]
- [ ] should be able to create a stocktake using a master list (from the initial modal and from the stocktake detailed view) - MEDIUM
- [ ] should be able to create a stocktake for items with stock (from the initial modal, similar to mSupply Mobile) - MEDIUM

**Comment by mark-prins** [comment]
Also, this from #696 

- [ ]  Can't update location/batch/sell or cost price of item (if does not exist)

**Comment by roxy-dao** [comment]
Sort order for snapshot no of packs is incorrect
![Screen Shot 2023-01-17 at 9 48 40 AM](https://user-images.githubusercontent.com/61820074/212763551-b006d755-f6c8-4ce1-b819-54d9d6300984.png)

**Comment by mark-prins** [comment]
Further to this - the discussion we've had is to:
- remove the current item list / selection modal
- replace with a modal which allows
  - selection of master list
  - selection by location

The other discussion is whether to implement a generic item filter and use that for selecting items

**Comment by roxy-dao** [comment]
> Also, this from #696
> 
> * [x]   Can't update location/batch/sell or cost price of item (if does not exist)

Should be fixed with https://github.com/openmsupply/open-msupply/pull/1102 (:

**Comment by mark-prins** [comment]
Also requested:
`When clicking on a past stocktake in mobile, there's a message at top corner saying : "finalised stocktake cannot be edited". Useful for the user but not in Open mSupply`
