### ISSUE TITLE
View stock: should be able to sort per available quantity (number of packs, number of units)

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#939]

**Comment by Chris-Petty** [comment]
@richardmoizeau could this be expanded to adding sorting by any column? For instance there is no way for me to sort by item `name` or `code`. This means that item batches can be scattered, such as "Acetylsalicylic Acid 100mg tabs" here on the demo server:

![image](https://user-images.githubusercontent.com/7684221/212582045-a74aff99-3ccd-4d4d-838e-8aa57a3ca418.png)

A drill down reusing parts shipments UI elements would be cool, but different issue: 
![image](https://user-images.githubusercontent.com/7684221/212581963-24e99640-75ed-45ff-801c-d3b6e2eee226.png)

**Comment by richardmoizeau** [comment]
Sure, free country mate.

**Comment by mark-prins** [comment]
have enabled column sorting in #1123
