### ISSUE TITLE
Country specific regional settings

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#951]
Currently the languages are defined at a language group level e.g. 'fr'

There is a request to have country specific localisation, which would allow overriding of terms while implementing the base language. A way to achieve this is to use a country specific language implementation, making use of the [fallback](https://www.i18next.com/principles/fallback) of translations.

e.g. If the locale is `fr_CI` then the following keys produce the following results:

| Key  | `fr_CI/app.json` | `fr/app.json` | `en/app.json` | translation |
| ------------- | ------------- |------------- |------------- |------------- |
| outbound-shipment  | Bon Command  | Livraison Sortante | Outbound Shipment | **Bon Command** |
| inbound-shipment  |   | Livraison Entrante | Inbound Shipment | **Livraison Entrante** |
| dispensing  |   |  | Dispensing | **Dispensing** |

We currently have regional settings tied to a language rather than a region and this also needs to be addressed. There are now multiple users with `fr` as the language who have different currency designations.

A related issue is that the 'es' translations added via weblate has the country designation (`es_CO` rather than `es`) - this needs investigating to check if handled correctly by the implementation of 118next.

**Comment by CarlosNZ** [comment]
![Screenshot 2023-04-26 at 11 56 11 AM](https://user-images.githubusercontent.com/5456533/234432614-9f9e7a21-cbba-4bba-b201-debfc7485881.png)

Is this actually "In PR"? I'm not seeing anything. :/

**Comment by mark-prins** [comment]
ah, no. closed with #1539
