### ISSUE TITLE
Can create order for the store that we're logged in from omSupply

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#968]
## Issue Description
In a sync setup with v700 cloud server and openMsupply(let's say StoreA), it looks like while we're logged in StoreA, we can create internal order for StoreA itself.

## Steps to Reproduce
1. Sync setup with v700 cloud and omsupply
2. Login StoreA in openmsuply
3. Opt to create a Internal Order
4. See error: in the list of stores to select, the logged-in store is showing as well.

**Comment by mark-prins** [comment]
Fixed with #1003
