### ISSUE TITLE
Should we handle the "pack to one" preference?

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#973]
mSupply has a store preference "Set pack to one for all visible items in the store". When a store with this preference turned on receives stock, the system automatically sets this stock to have pack sizes of one (and does the necessary conversions for packs, quantity, price, etc). 

This is primarily used for facilities that are either smaller, or dispense to patients, and therefore mainly work in pack sizes of 1. It
is widely used. 

The alternative to this functionality is being able to repack items manually to packs of 1 when received. The caution with this approach is that it may require some training and monitoring - staff who are used to always handling packs of one may accidentally issue out large amounts of larger packsizes. 

![image](https://user-images.githubusercontent.com/29744386/208538511-83742534-f729-4525-b454-5478bc12251e.png)

My questions are: 
- Around how long would this work take?
- Do we have a design for dealing with store prefs?
- Is it planned to deal with store prefs in omSupply at all? 
- Is it better to do the manual repack function?

**Comment by DhanyaHerath** [comment]
@andreievg @roxy-dao @mark-prins Info about the pack to one pref, as promised -

In practice, the "Set pack to one" pref will will turn on the `Allow pack to 1 conversion` and `Convert pack to 1 when receiving` checkboxes for all the item records in the store. This will mean that all stock received into the store will automatically be received in packs of 1. 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/29744386/212782019-9dd9829c-72f7-48f3-b17b-b52784cee226.png">

What this looks like in current mSupply is: 

- If I add a line to a supplier invoice, it will allow me to enter a packsize > 1, BUT when I click `OK`, it will convert the packsize to one and adjust the quantity accordingly. The Cost price, Volume per pack and Weight per pack will also be adjusted: 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/29744386/212781099-2a5ea009-12e1-40bb-81db-7df4d86cffe9.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/29744386/212781128-13d1d1a7-d086-40b6-a733-dd7f351352e7.png">

- If I receive a supplier invoice as a transfer, it will already have the lines converted to packsize one. 
- If I add a line to a stocktake, it will **not** convert the packsize to 1.

**Comment by andreievg** [comment]
I would suggest a store_preference table, with columns being the preferences, and store_id being primary key. I think this enforces the preferences format and is easy to query and update. 

@DhanyaHerath thank you for summary:

> If I add a line to a supplier invoice, it will allow me to enter a packsize > 1, BUT when I click OK, it will convert the packsize to one and adjust the quantity accordingly. The Cost price, Volume per pack and Weight per pack will also be adjusted:

Cools, @roxy-dao I think this should be done on back end when saving invoice_line. 

> If I receive a supplier invoice as a transfer, it will already have the lines converted to packsize one.

Oki, should be done in the transfer processor

> If I add a line to a stocktake, it will not convert the packsize to 1.

Have to make sure that trainers are aware of this. And at the very least we should set to default pack_size 1 if preference is turned on (which also means we need to communicate store preferences to front end).

**Comment by clemens-msupply** [comment]
> I would suggest a store_preference table, with columns being the preferences, and store_id being primary key. I think this enforces the preferences format and is easy to query and update.

As from a previous discussion about "contexts", my main argument against it would be the dev overhead to get new prefs in (all layers would need to be touched). However, how about a similar solution we had in this discussion, i.e. having a `preference` and a `store_preference_join` table? Adding a new pref would involve a migration to add a new `preference` row instead of altering a table. Additionally you could query all available preferences, e.g.  to build the preference ui...

**Comment by andreievg** [comment]
@clemens-msupply made a KDD for this https://github.com/openmsupply/open-msupply/pull/1088

>  Additionally you could query all available preferences, e.g. to build the preference ui...

But preferences are not just booleans, as per KDD.

> As from a previous discussion about "contexts", my main argument against it would be the dev overhead 

I am not convinced there is any significant dev overhead. I was going to do an example, but I think it would take too long. If you strong about dev overhead being significant, I can do an example (we also need to consider default values etc..)

**Comment by andreievg** [comment]
@DhanyaHerath 

I remember a discussion about the point you've raised, there are solutions to this use case but they are not trivial, unfortunately I don't think we have the time to deal with this right now, but I think we should do a KDD , [I made an issue](https://github.com/openmsupply/open-msupply/issues/1089)

**Comment by mark-prins** [comment]
> I am not convinced there is any significant dev overhead. I was going to do an example, but I think it would take too long

😆 

I know what you mean.. but on the face of it: 'it is quick to dev' and 'I would do an example but it would take too long' do sound like you are contradicting yourself!

**Comment by andreievg** [comment]
> I know what you mean.. but on the face of it: 'it is quick to dev' and 'I would do an example but it would take too long' do sound like you are contradicting yourself!

Haha, I should have phrased it differently, i mean significant difference in dev overhead for adding new preference between the two options
