### ISSUE TITLE
omsupply Desktop UI need some improvement

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#981]
## Issue Description
There are some places in omsupply Desktop app with some UI problems like:
1. The `Help` menu literally shows `(empty)` value. Doesn't look good.
![omsupply-ui-3](https://user-images.githubusercontent.com/59193490/208897078-7dc77ec3-c5a5-4bc9-bf31-f5d1e1937163.png)

2. The border lines of some Menus (`Edit` and `View`):
![omsupply-ui-1](https://user-images.githubusercontent.com/59193490/208897072-4f0a4d30-a3e3-40ef-8190-90a2906518cd.png)
![omsupply-ui-2](https://user-images.githubusercontent.com/59193490/208897073-29abf10d-78da-46cb-b212-96b3b45453e9.png)

3. In case when the omsupply server is not running, opening the omsupply Desktop app literally shows nothing: a blank screen. Do we want some message there instead?
![omsupply-ui-4](https://user-images.githubusercontent.com/59193490/208897062-3d874cef-1213-48e3-9184-484ff81066c3.png)

**Comment by mark-prins** [comment]
Fixed with #1685
