### ISSUE TITLE
Label problems in items details window in omsupply Desktop

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#987]
## Issue Description

Below is the screenshot if a item details in the **omsupply Desktop**. Notice the weird labels:
![Screen Shot 2022-12-29 at 10 55 24](https://user-images.githubusercontent.com/59193490/209907334-a2d48fde-93d2-4164-92dd-b3e0a1600dba.png)

It should show appropriate label titles like below in **browser** connected through omsupply Server:
![Screen Shot 2022-12-29 at 11 18 12](https://user-images.githubusercontent.com/59193490/209907590-7f53add2-5c80-40e2-9e11-fcaebfacca75.png)

I notice the similar problems in many others window as well:
1. Shipment details (Inbound & Outbound)
2. Requisition & Internal Orders
3. Stock line details
4. Location details
5. Stocktakes

**Comment by mark-prins** [comment]
Should be fixed with #952 
( for the curious, this commit I think: bb2cf8fb58e58066d8a39fa1694846cdcfeaed4f )
