### ISSUE TITLE
If there is previous transactions like CI/Prescriptions, then creating new CI/Outbound Shipment in openmsupply will override the previous transactions details. 

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#990]
## Issue Description
If there is previous transactions like CI/Prescriptions, then creating new CI/Outbound Shipment in openmsupply (with same previous numbered CI) will override the previous transactions details. 
For example, if we already have a CI with number 1 in our setup, now on omsupply, opt to create a new Outbound Shipment and it will override all the info of the previously existing transaction(CI/Prescription) numbered 1.

## Screenshots
[Link](https://drive.google.com/file/d/1TqO4q4A0OVkpyIeAB-0uIXIDP58AvZUJ/view?usp=share_link) here.

**Comment by Chris-Petty** [comment]
@andreievg Possibly related to the number sequence changes? Sounds sort of similar to https://github.com/openmsupply/open-msupply/issues/962

**Comment by andreievg** [comment]
@Chris-Petty yep that should have been fixed with number changes

@nisha-dangol what version were you using to test this ? Can you try to replicate this on latest develop please. 
I see this issue was opened last week, but the number changes that fix this behaviour would have been in develop already, I wonder if you were testing with an older version ?

**Comment by nisha-dangol** [comment]
> @Chris-Petty yep that should have been fixed with number changes
> 
> @nisha-dangol what version were you using to test this ? Can you try to replicate this on latest develop please. I see this issue was opened last week, but the number changes that fix this behaviour would have been in develop already, I wonder if you were testing with an older version ?

I definitely used the older version, the v1.04 most probably. Will test this on the latest (v1.1.1-test2 hopefully) !

**Comment by DhanyaHerath** [comment]
Any luck with re-testing @nisha-dangol?

**Comment by nisha-dangol** [comment]
> Any luck with re-testing @nisha-dangol?

I tested this with a new datafile in the latest oms v1.1.1. Creating a new CI/Outbound Shipment now creates a new CI no. thus there is no overriding of previous transactions. But I noticed that for every previously existing `cc`, the same number is still re-used. Is this the expected behaviour here?
Here's the screenshot of list of customer transactions (including both CI and CC) in the Cloud:
![Screen Shot 2023-01-24 at 12 59 38](https://user-images.githubusercontent.com/59193490/214238299-2ad64b7c-649f-4c51-a911-5e29e4b1f364.png)

**Comment by Chris-Petty** [comment]
@nisha-dangol ah great find! Pretty sure I understand what might be happening:

This is the code that determines the next biggest number:
https://github.com/openmsupply/open-msupply/blob/3bd37669303668ba6907f49c21eae4b7ad7970a0/server/service/src/number.rs#L24-L45

For inbound shipments, it needs to share the same number sequence as "customer credits". Currently it just looks at invoices of type "ci" essentially.

Here is the `invoice` sync translator:
https://github.com/openmsupply/open-msupply/blob/3bd37669303668ba6907f49c21eae4b7ad7970a0/server/service/src/sync/translations/invoice.rs#L48-L67

mSupply just doesn't integrate "cc", customer credits. So it currently not possible to respect the number sequences correctly when syncing data that was previously mobile or desktop. It would _happen to_ work correctly if the if the last invoice was a "ci", though.

@mark-prins you've indicated there might be a PR already related to this issue? If there isn't, I think cleanest track would be to close this issue and create a new one with what I describe above.

**Comment by andreievg** [comment]
Hi I just saw this as `in progress view` I don't think we need to do this.
* I would assume the same problem exists for og mobile
* Making existing sites data 100% accurate when migrating to omSupply would be a huge job if we test with all of the permutations of data records types that exist in mSupply and don't exists in omSupply (plus I don't think this is priority)

I think we may decide to have another number sequence type for cc

**Comment by Chris-Petty** [comment]
>I would assume the same problem exists for og mobile

Pessimistic me was assuming the same, [but checking assumptions it does appear it handles `cc`](https://github.com/openmsupply/mobile/blob/c90969eead61e9caef670e530adca233cc5f6bd4/src/database/utilities/numberSequence.js#L53-L62).

>I think we may decide to have another number sequence type for cc

@andreievg doing that doesn't fix the issue - that's essentially what is occurring now right?

What's the priority of ledger correctness in omSupply when migrating existing stores' data? If you made a correction on the remote server to adjust for the missing customer credits, then that'd break the ledger report on the central server.

**Comment by andreievg** [comment]
> Pessimistic me was assuming the same, [but on checking assumptions it does appear it handles cc](https://github.com/openmsupply/mobile/blob/c90969eead61e9caef670e530adca233cc5f6bd4/src/database/utilities/numberSequence.js#L53-L62).

thanks, oops, I didn't realise we handle customer credits in og mob

> @andreievg doing that doesn't fix the issue - that's essentially what is occurring now right?

I am not actually sure what the `issue` is, reported bug (invoices being overwritten) in this case doesn't apply (we don't integrate or show `cc` in omSupply). As for CC and CI needing to be in sequence, that would be good to validate, assuming (again) this is not a hard requirement. 

> What's the priority of ledger correctness in omSupply when migrating existing stores' data

I would assume once we start migrating those it would be pretty high priority, I think existing milestones don't require migrating existing store data (we would need to add repack transaction etc..)

**Comment by Chris-Petty** [comment]
(I'm in a number sequence rabbit whole, fixing some edge cases I did realise for older versions of mobile 🥲)

@andreievg in fairness it's messier already than I've let on earlier (because I remember now) - we've already made the decision for omSupply to have different sequences for `request` and `response` requisitions (mobile/desktop use one sequence for both). 

>thanks, oops, I didn't realise we handle customer credits in og mob

>I am not actually sure what the issue is, reported bug (invoices being overwritten) in this case doesn't apply (we don't integrate or show cc in omSupply). As for CC and CI needing to be in sequence, that would be good to validate, assuming (again) this is not a hard requirement.

In testing the solution, a new bug was reported - if you initialise on omSupply a store that has use of customer credits in the earlier apps, then when you start making outbound shipments omSupply will have no idea what serial numbers are already used as `ci` and `cc` share the same sequence. Then on central server, you'll be able to see duplicates of serial numbers when looking across all `ci` and `cc` for the store.

**Comment by andreievg** [comment]
> In testing the solution, a new bug was reported - if you initialise on omSupply a store that has use of customer credits in the earlier apps, then when you start making outbound shipments omSupply will have no idea what serial numbers are already used as ci and cc share the same sequence. Then on central server, you'll be able to see duplicates of serial numbers when looking across all ci and cc for the store.

Thanks @Chris-Petty new issue created, closing this one
https://github.com/openmsupply/open-msupply/issues/1145
