### ISSUE TITLE
Add name DB indexes

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#995]
To lookup patient we need indexes on the `name` table.

- [x] identify column needing an index, e.g. `first name`, `last name`, `code`, `code2`

**Comment by DhanyaHerath** [comment]
probably should be part of the field test milestone, right? @clemens-msupply

**Comment by CarlosNZ** [comment]
>     * [ ]  identify column needing an index, e.g. `first name`, `last name`, `code`, `code2`

How about:
- first name
- last name
- code (there is no `code2` as far as I can see)
- national_health_number

That enough for now?

**Comment by clemens-msupply** [comment]
Yes thats sounds good! national_health_number is used for code2...

**Comment by CarlosNZ** [comment]
Closed by #1602
