### ISSUE TITLE
External links to open in browser or allow back navigation

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#997]
epic: https://github.com/openmsupply/open-msupply/issues/996

Can navigate back from external links (or open external links in browser), this was changed with discovery work since can navigate to * in capacitor web view.

**Comment by mark-prins** [comment]
Don't understand what's required to be done sorry! Can you elaborate / detail what needs to happen? 🙏

**Comment by andreievg** [comment]
Currently external links will open in the same WebView as the app, and it seems the back button on the device doesn't navigate back to the app. 

Option 1 - (haven't checked but should be possible) - override navigation in capacitor and when navigating to somewhere other then currently connected server, open in browser vs app
Option 2 - make hardware back button work (it would navigate back to previous route)

**Comment by mark-prins** [comment]
thanks! hadn't even noticed. I've moved to 'to do' as I think we need to address this one
