### ISSUE TITLE
Hover over link in Android

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#998]
Epic: https://github.com/openmsupply/open-msupply/issues/996

Hover over doesn't work in mobile (like for sync error ui), would be good first issue for someone that's new to mobile/nativeAPI, or as an example of how to add new native functionality

**Comment by mark-prins** [comment]
I'm not sure what's required to be done with the issue sorry. Can you expand on the details?
Is it something like this?

- Identify all areas in the site which rely on a hover effect
- Determine if these are essential functionality or not
- If they are, replace hover with something else, e.g. long press

The only area identified so far is the info icon used in the sync error notification in the `ErrorWithDetails` component.

That said though - we are using material UI `Tooltip` and this, by default, supports long press as well as hover. I've just tested on android, and the sync error works fine - just press the info icon for a few seconds and the error tooltip shows.
So I don't think there's any work to be done here - can you correct if I've got that wrong?

**Comment by andreievg** [comment]
> So I don't think there's any work to be done here - can you correct if I've got that wrong?

Yep looks like we can close it, I wasn't aware that long press works.
